### ISSUE TITLE
help me, getUserMedia not working for huawei p10

### ISSUE THREAD

**Issue by yingkong87** [webrtc/samples#1006]
I used huawei p10 test https://webrtc.github.io/samples/src/content/getusermedia/gum/
but video play black screen， can you help me?
thanks in advance

**Comment by KaptenJansson** [comment]
Which browser and browser version are you using?

Have you tried https://appr.tc?

**Comment by yingkong87** [comment]
thank you for reply.  I used huawei Comes with browser，I will test https://appr.tc

**Comment by KaptenJansson** [comment]
You have to use a WebRTC enabled browser, please provide details about the browser, what is the name of it and the version?

**Comment by yingkong87** [comment]
![677c43827b3b5d645000f8910f5598e4](https://user-images.githubusercontent.com/18375391/35724029-46bec734-07f4-11e8-91a9-b67f74b4b420.jpg)

is this? the browser version?  I tried  https://appr.tc find the same problem.

**Comment by JenGL** [comment]
I have same problem on huawei P10 on chrome...
With simple constraint it works on Firefox but not on chrome.
(this is working on firefox https://webrtc.github.io/samples/src/content/getusermedia/gum/)
this is not working anywhere https://simpl.info/getusermedia/sources/

**Comment by yadomi** [comment]
Same problem here, I've tried on two Huawei P10 and it doesn't work in Chrome (64.0.3282.137) and Chrome Beta too (65.0.3325.38). However it's work in Firefox and even Microsoft Edge.

**Comment by JenGL** [comment]
#1013

**Comment by theraudmickael** [comment]
I've the same problem too:
Phone: huawei P10
Website to try: https://appr.tc
Work on: Chrome 63.0.3239.107
Work not on: Chrome 64.0.3282.137

**Comment by theraudmickael** [comment]
I created this bug on chromium bug tracker (https://bugs.chromium.org/p/chromium/issues/detail?id=812235)

**Comment by KaptenJansson** [comment]
Not an issue in the samples pages.
