### ISSUE TITLE
Hangup button gives Javascript TypeError (getStats) 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#1010]
**Browsers and versions affected**
M65.0.3325.56 Dev Build 

**Description**
Uncaught Type error at Hangup button, 100% Reproducible.

**Steps to reproduce**
Open the Javascript console in the browser
Go to https://webrtc.github.io/samples/src/content/peerconnection/pc1/
Tap on Start button
Tap on Call button 
Tap on Hang up button
Check the Javascript console

**Expected results**
No Javascript errors.

**Actual results**
In main.js:237 Uncaught TypeError: Cannot read property 'getStats' of null at HTMLButtonElement.hangup.

**Comment by rantonysamy** [comment]
Reproducible in all the Chromebooks.

**Comment by KaptenJansson** [comment]
Good catch, this is due to a recent change, will merge #1011 that will fix this.
