### ISSUE TITLE
getUserMedia on P10 not working

### ISSUE THREAD

**Issue by JenGL** [webrtc/samples#1013]
**Browsers and versions affected**
Chrome 64.0.32 - Huawei P10 with Android 7.0
even on Chrome beta 65.

**Description**
getUserMedia is not working. 
Page https://webrtc.github.io/samples/src/content/getusermedia/gum/ just give black screen. No error on console, the success handler function is called, but the video remains black.

**Steps to reproduce**
just open https://webrtc.github.io/samples/src/content/getusermedia/gum/ on an update Huawei P10

**Expected results**
camera should open

**Actual results**
camera remains black

**Comment by KaptenJansson** [comment]
Correction getUserMedia works but the camera is returning a black video stream. Issue in Browser or Phone.
