### ISSUE TITLE
iOS Mic Stops Working After Safari Loses Focus

### ISSUE THREAD

**Issue by mrwizzer** [webrtc/samples#1019]
**Browsers and versions affected**
Safari 11 on iOS devices  

**Description**
Not able to record audio in a webrtc browser-based audio recorder once the browser loses focus, (i.e. when returning to recorder after switching to another app or after reawakening after the device goes to sleep.)   Looks like a file is recorded, but there is no audio, making me think the mic has stopped working.

**Steps to reproduce**
Recording audio initially works fine.  Close Safari, wait ten seconds, open Safari back up to the same page.  Any new recorded audio is silent. (Audio recorded prior to closing Safari is still audible.)

**Expected results**
Playback of newly recorded audio.

**Actual results**
No new audio is recorded after returning from sleep or switching back to Safari from other apps.

Note: Refreshing the browser window does not help.  However, opening a new browser window does, as the microphone seems to be restored to working order upon the opening of a fresh browser window.

Using window.open(window.location.href, '_blank'); to open the same window in a new browser window does not restore the microphone to working order. 

Example:  https://recorder.scoe.net/test44.html

**Comment by KaptenJansson** [comment]
This is a browser issue.

**Comment by samueltuckey** [comment]
I am getting the same issue and have not been able to solve. Please let me know if you find anything.

**Comment by samueltuckey** [comment]
I tried submitting a bug report to https://www.apple.com/feedback/safari.html
