### ISSUE TITLE
Files required to run samples locally are 404 not found

### ISSUE THREAD

**Issue by brycepj** [webrtc/samples#1020]
If I run a simple http-server in any of the sample directories and open it in a browser, the page tries to load javascript and video files that aren't found. 

![screen shot 2018-02-23 at 10 29 11 am](https://user-images.githubusercontent.com/5140329/36602073-034e11ca-1885-11e8-91a1-42daf33f2987.png)

It seems that a build step is required, although I don't see anything like that in the Gruntfile. I'm not sure the way I'm trying to use this is intended or supported. Can anyone provide me some insight on this?

**Comment by KaptenJansson** [comment]
You start from the wrong folder. You have to run the HTTPS server (or use localhost for in order for GUM to succeed, not sure 127.0.0.1 will even though localhost redirects to it in the OS).

There is a provided server in the test folder, as stated in the [README.MD](https://github.com/webrtc/samples/tree/gh-pages/test#start-web-server-for-development):

Start web server for development
From the root of the checkout do cd test then run node server.js and finally navigate your browser to https://localhost:8080.
