### ISSUE TITLE
Audiocontext starts with suspended state

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#1028]
## Description

Audiocontext starts with suspended state, due to a policy ! So the I have to connect a headset / headphone to get the AudioContext state to be changed as "Running". In the test page there is no buttons, so I can't click on and show that the user Input had been available (as per the policy).

## Steps to reproduce

Go to https://webrtc.github.io/samples/src/content/getusermedia/volume/
Check the sample works.

## Actual Result:
Sample page not working

## Expected: 

It will be nice to have:

"Start AudioContext" "Check Status" (running or not running), "Suspend AudioContext" in this test page. 

## Browser affected
Chrome 66.0.3359.31

**Comment by rantonysamy** [comment]
@KaptenJansson Can you please take a look at this and drive it for a closure - at least 3 webrtc samples were failing due to this.

**Comment by vkkkumar** [comment]
This is is the root cause for other sample pages too. https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
https://webrtc.github.io/samples/src/content/getusermedia/volume/

Same javascript error is shown. 

Solution: After refreshing the page two or three times fixes this issue.

**Comment by vkkkumar** [comment]
Regarding the solution I mentioned above:
1. Open the sample pages mentioned above,
2. Kindly press **ctrl + shift + j** and then **Refresh** the page. 

P.S: Just refreshing the page will not resolve the issue.

**Comment by rantonysamy** [comment]
Checked that Its working in M66 beta / 66.0.3359.48, closing.

**Comment by vkkkumar** [comment]
Reproducible in 66.0.3359.46 /10452.19.0 Windows 7 (Thinkpad lenovo), Windows 10 (Asus UX430x)
(Beta)
We need to reopen again I guess.

**Comment by vkkkumar** [comment]
Reproducible in M66 Beta. 

Windows 7, windows 10 and one device from Gru family (Chromebook

66.0.3359.79 / 10452.42.0 
66.0.3359.87 Windows 7 & 10

**Comment by vkkkumar** [comment]
This issue is reproducible in M67 Dev 67.0.3383.0 / 10539.0.0  Leon, Link, Lars, Peach

**Comment by vkkkumar** [comment]
Reproducible in 67.0.3383.0 / 10539.0.0  Glimmer, Kip, Swanky, Snappy

**Comment by fippo** [comment]
@huibk this seems due to the autoplay policy changes. PTAL

**Comment by fippo** [comment]
filed https://bugs.chromium.org/p/chromium/issues/detail?id=835767

**Comment by fippo** [comment]
@rantonysamy do you typically test with a newly created profile (--user-data-dir=some-new-directory)?
I've seen this work on a normal profile and then break (in the same chrome version) with a fresh profile which might explain why this seemed to work for you [here](https://github.com/webrtc/samples/issues/1028#issuecomment-376501333).

I'd bet on the MEI making it look like everything was ok: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei
AFAICS if you used the same profile on another page of the samples that will change behaviour.

**Comment by rantonysamy** [comment]
Sometimes I used to switch to another profile, but It was happening in a fresh installed Chrome OS / Chrome at the Chromebooks. I will check the same issue in the latest build and see Its still reproducible.

**Comment by huibk** [comment]
Note that currently the autoplay policies are not enabled for all M66 users yet. Set chrome://flags/#autoplay-policy to manually for the new policy on.

**Comment by vkkkumar** [comment]
Thanks Huib! It is working fine when enabling the flag #autoplay-policy and set it to " User Gesture is required for cross-origin iframes. Tested in Quawks and Kip.

**Comment by ErikHellman** [comment]
Is this issue still relevant? I can't reproduce the problem when testing the different settings of autoplay policy.

**Comment by rantonysamy** [comment]
Its been fixed already. I am closing it.

**Comment by fippo** [comment]
mind you that this will probably come up again when autoplay tries to reland... :-|
