### ISSUE TITLE
DOMException is thrown when entering the alphabets in Tones text box

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1029]
## Browser affected
66.0.3359.31 /10452.11.0 M66 Dev 
also in M67 67.0.3362.0 Canary

## Devices
Guado, Caroline, Sentry, Macbook pro

## Description
Uncaught DOMException is thrown while entering alphabets as tones. 

## Steps to reproduce
1. Goto https://webrtc.github.io/samples/src/content/peerconnection/dtmf/ 
2. Press ctrl + shift + j to see javascript errors.
3. Click Call button,
4. Empty the text box after "Tones" and enter alphabets. 
5. Click Send Tones button

## Expected results
Do not throw any DOMException in the chrome console. 

## Actual results
Throws an exception as follows 
"Uncaught DOMException: Failed to execute 'insertDTMF' on 'RTCDTMFSender': Illegal characers in InsertDTMF tone argument
   at sendTones (https://webrtc.github.io/samples/src/content/peerconnection/dtmf/js/main.js:227:16)
   at HTMLButtonElement.handleSendTonesClick (https://webrtc.github.io/samples/src/content/peerconnection/dtmf/js/main.js:232:3)
sendTones @ main.js:227
handleSendTonesClick @ main.js:232"

## Reproducibility
100% reproducible. This issue is a regression not observed in M64 nor M65.
![screenshot 2018-03-21 at 2 17 14 pm](https://user-images.githubusercontent.com/34342420/37713270-a313b7f0-2d16-11e8-8fd3-4c27df6da2e0.png)

**Comment by KaptenJansson** [comment]
They are not legal DTMF tones, sure the page could validate the tones before inserting them but it's good to be able to test passing in illegal characters. This is working as intended.
