### ISSUE TITLE
Chromium on Raspbian failing to use captureStream and send video stream

### ISSUE THREAD

**Issue by agonza1** [webrtc/samples#1030]
**Description:**
Browser: Chromium 60.0.3112.89 (Developer Build) Built on Ubuntu 14.04, running on Raspbian 9.3 (32-bit)
can't send captured local video stream (`localVideo.captureStream()`) to Chrome or Firefox. 

**Steps to reproduce:**
I tried enabling experimental Web Platform features but all Stream capture demos here: https://webrtc.github.io/samples/ still fail.

I also tried https://www.webrtc-experiment.com/Pre-recorded-Media-Streaming without luck. All I get in the receiver peer is a black screen.  Audio works.

**Comment by KaptenJansson** [comment]
This is not a samples issues, please check your OS/Browser. Also please try with an up to date version of Chrome.
