### ISSUE TITLE
iOS 11 full hd issue.

### ISSUE THREAD

**Issue by RayLuxembourg** [webrtc/samples#1032]
I am trying to achieve 1080p with iOS 11+ devices but unfortunately all the things i tried result in 720p or less.
I am writing the code in typescript

```
  private getCameraSettings() {
    // working for android
    const android = { width: { exact: 1920 }, height: { exact: 1080 } };
    return {
      audio: false,
      video: { width: 1920, height: 1080 }
    };
  }
```

```
    navigator.mediaDevices
      .getUserMedia(this.getCameraSettings())
      .then(this.onSuccessulStream)
      .catch(this.onStreamError);
```

I have tried many variations and couldn't get to 1080p no matter what.
Has anyone else tried or found solution?

**Comment by KaptenJansson** [comment]
Have you checked with Apple which resolutions they support in Safari (might be different in MacOS and iOS as well)? GetUserMedia is browser specific.

**Comment by KaptenJansson** [comment]
And this is not a samples limitation hence why closing.
