### ISSUE TITLE
Change the input camera in the sources & outputs example on Safari (11) with M.Way camera

### ISSUE THREAD

**Issue by theraudmickael** [webrtc/samples#1033]
## Browser affected
Safari Version 11.0 (13604.5.6) (macOS)

## Description
The example "Select sources & outputs" is not switching the video input devices as expected. I have 2 camera connected and the example let's me select CAM 2, but i got an error on console about constraint used.

## Steps to reproduce
1. Plug 2 camera on Mac device
2. Go to https://webrtc.github.io/samples/src/content/devices/input-output/
3. Change video source to M.Way camera (see "Amazon camera references")

## Expected results
I expect to see the other camera stream

## Actual results
I got an error on console : 
> [Log] navigator.getUserMedia error:  – OverconstrainedError {message: "Invalid constraint", constraint: "deviceId"} (main.js, line 116) OverconstrainedError {message: "Invalid constraint", constraint: "deviceId"} OverconstrainedErrorconstraint: "deviceId"

## Amazon camera references
- Link of the article | https://www.amazon.fr/M-Way-Résolution-Microphone-ajustable-Compatible/dp/B073F6WQFJ
- Name of the article | Webcam HD 720P, M.Way USB Caméra à Haut Résolution avec Microphone Intégré et Trépied ajustable Caméra PC pour Skype/MSN/Facebook/Twitter Compatible avec Windows 7, Windows 8, Windows 10 Mac OS 10.6 Noir
- Number of the article | M.WAYLOLV12GRA101
- ASIN | B073F6WQFJ

**Comment by KaptenJansson** [comment]
I would guess Safari does not support deviceId and enumerateDevices?

**Comment by theraudmickael** [comment]
Nope, safari support "deviceId" and "enumerateDevices". The "deviceId" constraint works well on the first call. I get this error only when i change video source.

But .. I go try with another "CAM 2". This problem can come from camera device.

**Comment by theraudmickael** [comment]
Yep... this error come from the webcam. If i plug another webcam it works fine.

The camera is https://www.amazon.fr/M-Way-Résolution-Microphone-ajustable-Compatible/dp/B073F6WQFJ

What are we doing about this issue?

**Comment by ErikHellman** [comment]
I just tested this on Safari Version 11.1.1 (13605.2.8) and couldn't reproduce the error. Can you check again and see if you still get the same result with your camera?

I'm using a regular Logitech camera plugged.

**Comment by theraudmickael** [comment]
I just tested my camera (https://www.amazon.fr/M-Way-Résolution-Microphone-ajustable-Compatible/dp/B073F6WQFJ) on Safari Version 11.1.1 (13605.2.8) and i reproduce the error unfortunately.

I go to update my current description.

Thank you.

**Comment by ErikHellman** [comment]
I tried with another camera and still can't reproduce this. I'm assuming this is a bug in WebKit, so I suggest you file a bug there (https://bug.webkit.org/).

**Comment by theraudmickael** [comment]
Ok, i go to do this. Thank you for your help :)
