### ISSUE TITLE
ICE restart sample gets stuck if "ICE restart" button clicked too quickly

### ISSUE THREAD

**Issue by taylor-b** [webrtc/samples#1036]
## Browser affected

Chrome 65.0.3325.51

## Description

The [ICE restart sample](https://webrtc.github.io/samples/src/content/peerconnection/restart-ice/) has a "Restart ICE" button which is disabled when clicked, and re-enabled when there's a state transition to "connected".

If you click it fast enough, it will get stuck in a permanently disabled state, after which you need to "Hang up".

This is happening because Chrome transitions from "completed" to "connected" when the restart begins, then back to "completed" after connectivity checks for the new candidate pairs complete (which complies with the standard). But if the button is clicked fast enough, a restart will be initiated in the "connected" state. In which case there will be no transition back to "connected", only to "completed".

So, the sample page should use some other condition to enable the button. Like SRD(answer) completing?

**Comment by fippo** [comment]
@alvestrand since you said completed is "bogon"... what is a good solution here?

**Comment by fippo** [comment]
best i've figured out so far was to check for checking->connected in Firefox and connected->completed in Chrome/Safari...

**Comment by ErikHellman** [comment]
I consider this issue resolved for now. Please file a new issue in case it is still a problem.
