### ISSUE TITLE
Demo video chat at appr.tc does not work in Edge

### ISSUE THREAD

**Issue by nolimitdev** [webrtc/samples#1039]
Demo video chat app linked in this repo "AppRTC video chat client powered by Google App Engine" does not work in Edge. Originally I developed own video chat app which works well in Chrome, Firefox, IE11 (using adapter.js) but it does not work in Edge. WebRTC is supported in Edge since version 15. During debugging there is no problem, no error - each user see only own video but does not see opponent video. So I tried to find some WebRTC demos on the internet and no one works in Edge! I also tested Edge to Edge but no success.

1.) Demo of this repo: https://appr.tc/

2.) Another demo: https://simplewebrtc.com/demo.html

My app and demos do not report any problem in console. Everything seems to be fine but users do not see opponent video. Did you see working WebRCT in Edge? Can you try please linked demos in Edge to confirm it is not working?

Tested in two different Edges:
- Microsoft Edge 40.15063.674.0 (Microsoft EdgeHTML 15.15063)
- Microsoft Edge 40.16299.371.0 (Microsoft EdgeHTML 16.16299) 
Note:  "Let apps use my camera/microphone" is enabled in "Privacy Settings" ("Camera" and "Microphone" sub sections).

**Comment by ErikHellman** [comment]
Closing as this is filed on the wrong project. Try filing the same bug at https://github.com/webrtc/apprtc instead.
