### ISSUE TITLE
Is it possible to transfer video stream from a remote camera to Google Chrome?

### ISSUE THREAD

**Issue by ghost** [webrtc/samples#1040]
Hello, 
On my computer from where I connect to the WebRTC conference there is no webcam. I have a second laptop with a built-in camera.

Is it possible to emulate a fake media device in the first computer in Google Chrome that will receive a video stream from a remote webcam across the network from a second laptop to use this virtual media device as a webcam during a video conference?

I read that in the test mode, you can run Google Chrome with the keys that create virtual fake media devices, through which you can broadcast a local media file. For example, here https://github.com/webrtc/samples/issues/616:

"chrome.exe --use-file-for-fake-video-capture = "D:\Test\Video\y4m.y4m" --allow-file-access -use-fake-device-for-media-stream"

Is it possible to connect a remote webcam from one laptop to another laptop as a virtual camera?

**Comment by ErikHellman** [comment]
Closing this as it's not a feature request or a bug. For support on WebRTC, please refer to https://webrtc.org/ instead.
