### ISSUE TITLE
WebRTC samples Audio stream volume not working in chrome 66

### ISSUE THREAD

**Issue by Vijay-mRoads** [webrtc/samples#1041]
## Browser affected

**Browser name including version (e.g. Chrome 66.0.3359.117 )**

## Description
WebRTC samples Audio stream volume not working in chrome 66. Getting following error "The AudioContext was not allowed to start. It must be resume (or created) after a user gesture on the page"

## Steps to reproduce
1. Open this link in above mentioned browser https://webrtc.github.io/samples/src/content/getusermedia/volume/

2. Allow and speak something. 

## Expected results
Should display a progress when speaking

## Actual results
not displaying volume.

NOTE: 

If it works the first time then refresh the browser.

**Comment by fippo** [comment]
see #1028

**Comment by ErikHellman** [comment]
Closing this as it is currently working. We know what caused this and will open a new issue if it becomes a problem again.
