### ISSUE TITLE
Regression: Broken logo is displayed instead of the actual video's preview [Canvas]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1045]
## Browser affected
Chrome Version: 67.0.3388.0 (Dev)
OS: Chrome

## Steps to reproduce
What steps will reproduce the problem?
(1) Go to https://webrtc.github.io/samples/src/content/capture/canvas-record/
(2) Click on "Start recording"
(3) Click on "Stop recording" after a while 
(4) Observe the Canvas on the right

Note: Not available in M65.

## Expected results
Video Preview or blank canvas

## Actual results
Video Broken logo has been displayed 

Original Bug: https://bugs.chromium.org/p/chromium/issues/detail?id=837519&desc=2

**Comment by vkkkumar** [comment]
This issue is reproducible in M68 as well. @rantonysamy

**Comment by ErikHellman** [comment]
Setting the video.src attribute when we stop the recording solves this problem as well. See referenced PR.
