### ISSUE TITLE
Check for active screen sharing session

### ISSUE THREAD

**Issue by anuragvijayvergia** [webrtc/samples#1048]
Hi,

I am implementing webrtc in my electron project and I want to see is there any way where I can check if some app is already running a screen sharing session?

**Comment by joeygallegos** [comment]
Curious for the same, anybody have any ideas?

**Comment by ErikHellman** [comment]
I suggest you ask the question in the WebRTC discussion group.
See https://groups.google.com/forum/#!forum/discuss-webrtc
