### ISSUE TITLE
webrtc screen sharing + audio

### ISSUE THREAD

**Issue by bhavinshiroya1994** [webrtc/samples#1049]
any persion implement webrtc screen sharing with audio implement ?
please share your code,
my side not working webrtc screen sharing with audio

**Comment by ErikHellman** [comment]
I'm looking at writing a more complete sample for screen-sharing. Meanwhile, you can have a look at this sample that is not yet linked from the main page: https://github.com/webrtc/samples/tree/gh-pages/src/content/extensions/desktopcapture

**Comment by ErikHellman** [comment]
There is now a basic screensharing sample that works for Firefox. See https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

**Comment by anUniqueBoy** [comment]
const stream2 = await navigator.mediaDevices.getUserMedia({
        audio: {
          echoCancellation: {exact: true},
          noiseSuppression: {exact: true}
        }
      });
      stream.addTrack(stream2.getAudioTracks()[0]);
      stream :  getDisplayMedia() 

Add audio to the screen through addtrack
