### ISSUE TITLE
DOMException error comes can't start audio source when multiple tabs of same are opened.

### ISSUE THREAD

**Issue by rahulmehra1994** [webrtc/samples#1056]
## Description
The below code is working fine in getting stream and displaying it in the video element but when I open multiple tabs for the same page then a **DOMException error comes can't start audio source.**

## My Code
    var constraints = {
        audio: true,
        video: true
      };
          navigator.mediaDevices.getUserMedia(constraints)
          .then((stream) => {
              console.log("stream", stream);
             //refs are used to reference elements in React Js
              this.refs.calibrationVideo.srcObject = stream;
              this.refs.calibrationVideo.oncanplay = e => { this.refs.calibrationVideo.play() };
          })
          .catch((err) => {
              alert("Media error");
              console.error('media error', err);
          });

**Comment by ErikHellman** [comment]
Closing this issue as it is not related to any of the samples. Please see the guidelines if you want to report an issue on one of the WebRTC samples.
