### ISSUE TITLE
"Peer Connection: Adjust Bandwidth" sample not working on iPhone/Safari

### ISSUE THREAD

**Issue by tomorgan** [webrtc/samples#1057]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x ] I have provided steps to reproduce
- [ x] I have provided browser name and version
- [ x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Safari 11 on iOS 11.4 (iPhone X).   (other WebRTC samples checked and working OK)

## Description
"Peer connection: adjust bandwidth" sample not working on Safari 11.  No video shown, nothing shown in graphs.

## Steps to reproduce
Sample: https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/
Click Call.  Browser will prompt for device access, say Allow

## Expected results
Expect to see video in both panes, and plots in graph

## Actual results
Video panes are both black, graph is empty.

------------
Please can people verify that this is a problem affecting all devices, to rule out a device issue. I have verified that other samples work OK on my device but only have the one device for testing.

**Comment by ErikHellman** [comment]
Ping @alvestrand 

`RTCPeerConnection.getSenders()` doesn't seem to work on Safari. Do you know more? Suggestion for this issue?
