### ISSUE TITLE
Trickle-Ice in Safari gathers only host candidates

### ISSUE THREAD

**Issue by heyheyjc** [webrtc/samples#1068]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected
Safari 11.1.2 (11605.3.8.1)
OS X El Capitan 10.11.6

## Description
The ICE gathering immediately returns two 'host' candidates, IP4 and IP6, but no others, either STUN or TURN. There are no internet issues, websockets are working successfully, as is this page in other browsers, including Chrome on the same machine.

## Steps to reproduce
Navigate to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
Press "Gather candidates"

## Expected results
Various candidates, including STUN (srflx)

## Actual results
Host candidates only.

**Comment by fippo** [comment]
@youennf does this sound familiar?

@heyheyjc does this behaviour change if you call getUserMedia before gathering candidates?

**Comment by youennf** [comment]
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ is probably still using the legacy OfferToReceiveAudio/Video and should instead create a data channel to trigger ICE gathering for instance.
@heyheyjc, can you file a bug in bugs.webkit.org?

**Comment by heyheyjc** [comment]
@fippo The odd thing _here_* is that getUserMedia is supposedly compulsory before getting 'host' candidates - some concern about internal IP privacy, which in itself seems odd*.

@youennf Yep, that sample does use 'OfferToReceiveAudio: 1', but I thought that was shimmed out by adapter? I'll file a webkit bug once I've pinned down exactly what it's doing wrong.

I need to look at exactly when it starts gathering candidates, as I've seen some mention that opening a datachannel first, if ICE restrictions are disabled, allows gathering. Haven't worked out what that means yet, though. Behavior seems to vary when the channel is opened locally or remotely too*, and there's also the last comment to this [question](https://stackoverflow.com/questions/46605141/ios-safari-11-webrtc-does-not-gather-stun-turn-trickle-ice-candidates)*, which slightly tempts me to ignore Safari until it stabilizes.

*much about webrtc in Safari seems a little odd, to me at least.

**Comment by youennf** [comment]
> @youennf Yep, that sample does use 'OfferToReceiveAudio: 1', but I thought that was shimmed out by adapter? I'll file a webkit bug once I've pinned down exactly what it's doing wrong.

Oh I think you are right, a bugs.webkit.org ticket is cheap.

**Comment by heyheyjc** [comment]
@youennf Agreed, but they do take up someone's time, so I'd rather it was on point. I'm actively working on this, so it'll happen soon.

**Comment by ErikHellman** [comment]
I'm assuming the sample could use an update either way if we're using `OfferToReceiveAudio`? Anyone up for it?

**Comment by fippo** [comment]
offerToReceiveAudio is shimmed in adapter so that is fine.

**Comment by ErikHellman** [comment]
@fippo Sure, but the samples should reflect best practice. Would there be any problems with removing it from the sample?

**Comment by fippo** [comment]
Edge does not support data channels so that is not a viable option. offerToReceive* is still part of the spec

**Comment by ErikHellman** [comment]
I've started using the following function for the samples where we're not calling `getUserMedia()`. It seems to fix all the problems with Safari. How about I add this workaround for the trickle-ice sample (and others) as well?
```
if (adapter.browserDetails.browser === 'safari') {
  try {
    console.log('Call getUserMedia() to trigger media permission request.');
    const stream = await navigator.mediaDevices.getUserMedia({'audio': true, 'video': true});
    stream.getTracks().forEach(t => t.stop());
  } catch (e) {
    console.error('Error requesting permission:', e);
    return;
  }
}
```

**Comment by kenchris** [comment]
@anssik

**Comment by ErikHellman** [comment]
From the discussion in [https://github.com/webrtc/samples/pull/1110#discussion_r214661507] we won't add a workaround for this. 

Closing this issue for now.
