### ISSUE TITLE
css video cropping issues

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#1088]
it looks like the recent changes to use more of the page width lead to ugly black boxes (I think its called letterboxing?) around the video. Which was present before (see e.g. https://fippo.github.io/webrtc/src/content/peerconnection/pc1/) but much less visible. 

wdyt of removing the height attribute? That would let the fixed aspect ratio kick in.

**Comment by ErikHellman** [comment]
Agree.

**Comment by fippo** [comment]
ugh... this seems messier than I thought. This is defined in the main.css files of the individual samples. This somewhat makes sense as some samples have one video while others have two (or more).

No easy fix :-/

**Comment by ErikHellman** [comment]
I plan to revise that CSS file as well. Baby steps, things might break on the way, but we'll get there. :)

**Comment by fippo** [comment]
make sure @rantonysamy knows that things will break :-)

**Comment by ErikHellman** [comment]
☝️ Here you go! :)
