### ISSUE TITLE
You broke the code

### ISSUE THREAD

**Issue by smcardle** [webrtc/samples#1092]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ x] I have provided steps to reproduce
- [ x] I have provided browser name and version
- [ x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Chrome

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Version 68.0.3440.84 (Official Build) (64-bit)

## Description
The example at 
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
breaks after the latest release on Chrome

## Steps to reproduce
Add multiple STUN/TURN servers to the servers array and click gather candidates

## Expected results
Should get candidates

## Actual results
No candidates error in console 

main.js:133 Uncaught ReferenceError: i is not defined
    at HTMLButtonElement.start (main.js:133)

A change was made to the code at line 133 that does NOT declare 'let' for the variable 'i' in the for loop

**Comment by ErikHellman** [comment]
Thanks for noticing! The bug is fixed!
