### ISSUE TITLE
getUserMedia() error: NotFoundError

### ISSUE THREAD

**Issue by moozhub** [webrtc/samples#1097]
- [#] I have provided steps to reproduce
- [#] I have provided browser name and version
- [#] I have provided a link to the sample here or a modified version thereof

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Google Chrome Version 68.0.3440.75 (Official Build) (64-bit)
Firefox 60.1.0esr (64-bit)

## Description

Peer connection sample not working

## Steps to reproduce

Goto https://webrtc.github.io/samples/src/content/peerconnection/pc1/ and click start.

## Expected results

Not sure, haven't gotten it to work yet.

## Actual results

Chrome: getUserMedia() error: NotFoundError
Firefox: getUserMedia() error: InternalError

**Comment by ErikHellman** [comment]
From the error you describe it looks like your computer doesn't have a camera and/or microphone connected. Can you test this on a computer that has camera and microphone and see if it works?

**Comment by moozhub** [comment]
The problem stemmed from not having a microphone. When removing line 71 in main.js or changing it to false it loaded the stream. Thanks for the quick reply.
