### ISSUE TITLE
All Canvas tests fails. 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#1099]
## Browser affected
Chrome 70.0.3524.2

## Description
Canvas tests shows an empty screen 

## Steps to reproduce
Go to https://webrtc.github.io/samples/src/content/capture/canvas-record/
Check the Canvas

## Expected results
Canvas gets displayed 

## Actual results
Noting gets displayed 
<img width="1204" alt="screen shot 2018-08-24 at 11 50 15 am" src="https://user-images.githubusercontent.com/32895099/44578428-e3485680-a793-11e8-9fe3-61aef2f6273a.png">

**Comment by fippo** [comment]
regression from #1098 - @ErikHellman is on it

**Comment by rantonysamy** [comment]
Great, thanks for letting me know.

**Comment by rantonysamy** [comment]
Fixed !!!
