### ISSUE TITLE
Usability of the Abort button can be improved [Improvement]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1111]
## Description
Abort button is always available. This is not very good from usability perspective.  

## Steps to reproduce:
1. Goto https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Look at the Abort button
3. Abort button is always available and sometimes confusing why enabled always. 

## Browser affected
68.0.3440.106 and 69, 70. 

## Expected results
Disable the abort button at the initial stages. Enable after we attach a file. This gives more clear idea for the user to click on the button for abort the process. 

## Actual results
Abort button remain enabled always.

<img width="1105" alt="screen shot 2018-08-30 at 4 10 18 pm" src="https://user-images.githubusercontent.com/34342420/44857055-3ed08380-ac6f-11e8-91b4-402bcbedaa1a.png">

**Comment by ErikHellman** [comment]
Agree. It was a bit of a hasty change. I'll make a change asap.

**Comment by ErikHellman** [comment]
@vkkkumar Please check the updated sample and let me know if this is the improvement you requested.

**Comment by vkkkumar** [comment]
Looks good. Thanks a lot!
