### ISSUE TITLE
Camera In Use 

### ISSUE THREAD

**Issue by nehabhavikatti** [webrtc/samples#1113]
In my webRTC based application, how do I detect if the camera is already in use by other application which is also webRTC based.?

I want to block the user starting the video call if the camera is already in use.

Current Behaviour:

If I start video call on my webRTC based application when the camera is in use by other non-webRTC based application, it throws "NotReadableError" error
But if the camera is used by other webRTC based application, then there is no error nor any way to identify it.

Please suggest.
Thanks

**Comment by ErikHellman** [comment]
Please don't post questions about WebRTC API here. This is only for posting bugs and problems with the WebRTC samples. 

For questions about WebRTC, see https://groups.google.com/forum/#!forum/discuss-webrtc
