### ISSUE TITLE
Webrtc on ios getusermedia fail times to times

### ISSUE THREAD

**Issue by jyhuang-japan** [webrtc/samples#1118]
## Browser affected

**ios 11 safari**

## Description
The webrtc sometimes can not trigger the camera

## Steps to reproduce
1. open this link https://webrtc.github.io/samples/ and click the link "Basic getUserMedia demo"
2. open the camera
3. close the tab with camera on
4. open this link "Basic getUserMedia demo" again
5. open the camera

## Expected results
The camera should be opened

## Actual results
The camera not be opened

**Comment by ErikHellman** [comment]
There seems to be some problem with `getUserMedia()` on iOS. Please check https://webrtc.org/bugs and file a bug on Safari for iOS. Add a comment here with a link to that issue.

Thanks!
