### ISSUE TITLE
iframe Test page is not responsive - Javascript issue

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1119]
## Browser affected
 Kevin 70.0.3532.8 / 11005.1.0 

## Description
Test page is not responsive

## Steps to reproduce
Goto https://webrtc.github.io/test-pages/src/iframe-apprtc/
Click on Any buttons available on the test page. 

## Expected results
Able to join a test room and responsive.

## Actual results
Not able to click anything. It looks like a javascript error. 

##Regression
This test page works well in older version. Thus it is a regression.
![screenshot 2018-09-06 at 11 31 34 am](https://user-images.githubusercontent.com/34342420/45149176-3b864c00-b1c9-11e8-9ad5-b2a65fee59d5.png)

**Comment by ErikHellman** [comment]
Please report this issue on the correct repository: 

https://github.com/webrtc/test-pages/issues/new

**Comment by vkkkumar** [comment]
Thank you! I have opened the new ticket there. 
https://github.com/webrtc/test-pages/issues/29
