### ISSUE TITLE
Not able to connect two pc's 

### ISSUE THREAD

**Issue by meghq** [webrtc/samples#1120]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by meghq** [comment]
[](url)

https://raw.githubusercontent.com/webrtc/samples/gh-pages/src/content/peerconnection/pc1/js/main.js

**Comment by ErikHellman** [comment]
This is not a bug. All the samples are written to work in a single browser.

**Comment by meghq** [comment]
Hi Erik,

Thank you for the reply, As i am fresher to webRTC i was confused with the
topic so i have posted this query.
once again thanks for the reply.

Regards,
Megha G
