### ISSUE TITLE
macOS Safari problem with (getUserMedia) getting video stream from camera in angular 6 - NotReadableError: The I/O read operation failed

### ISSUE THREAD

**Issue by Serikpl** [webrtc/samples#1124]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

## Browser affected
Safari 11.1

## Description
Problem is appeared when I try get video stream from camera in mac on safari  (in angular).
For get stream I use function _navigator.mediaDevices.getUserMedia({video: true})_
On chrome it works nice, but in safari it sometimes throw error:

**NotReadableError: The I/O read operation failed.**

From documentation:
_NotReadableError_
Although the user granted permission to use the matching devices, a hardware error occurred at the operating system, browser, or Web page level which prevented access to the device.

![getusermedia_error](https://user-images.githubusercontent.com/18332577/45537814-9a6d4600-b805-11e8-8903-356f90dd8f9a.png)

The most strange that _**it's not stable, it error can appear and after sometime it will be work fine (without changing a code)**_...I checked it a lot of times on **3 different macs** and didn't find dependency why it or work or no, but error appeared on every mac.

Another one strange thing that **_error shows only in angular_**, so I thought that problem could be with _zone.js_ but I didn't find solution when trying take out call of function for getting stream from zone (for take out from _zone_ I used _runOutsideAngular_ and _run_).

I tried to use some npm libraries like **ngx-webcam**, **ack-angular-webcam** but that didn't help too, when error shows in my code it appears in plugins code too (I guess it cause they use same func to get stream).

So, my long research in internet didn't give appropriate result and I have to ask about advice, solution or at least idea.

## Steps to reproduce
- open some angular (v.6) project
- try to get stream using navigator.mediaDevices.getUserMedia({video: true})

## Expected results
The getUserMedia function have to return stream

## Actual results
The getUserMedia function returns error (sometimes)

**Comment by ErikHellman** [comment]
I will close this issue since this is not related to one of the WebRTC samples. If you need help with the WebRTC APIs, please see https://groups.google.com/forum/#!forum/discuss-webrtc or StackOverflow.
