### ISSUE TITLE
WebRTC - getUserMedia: select resolution example not working on IE11

### ISSUE THREAD

**Issue by stalari16** [webrtc/samples#1129]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Internet Explorer 11, Version: 11.1295.10586.0 on Windows 10

## Description
**WebRTC - getUserMedia: select resolution** sample not working in Internet Explorer 11. The page is rendering but button clicks are not working as expected.

I'm seeing a `Script error main.js (33, 24)` in the console while loading the page. because of this, the buttons click not working I think.

## Steps to reproduce
Just browse this url in IE 11 browser while dev tools open and you will notice the script error and try clicking on the buttons.
https://webrtc.github.io/samples/src/content/getusermedia/resolution/

## Expected results
The local webcam should turn on with different resolutions based on button clicks, just like what is on chrome.

## Actual results
Button clicks not working.

**Comment by fippo** [comment]
this is expected, IE never supported these APIs.
