### ISSUE TITLE
'Send messages with datachannel' broken on iOS 12

### ISSUE THREAD

**Issue by thehunmonkgroup** [webrtc/samples#1130]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected

iOS 12.0 Safari

## Description

As reported in #1123, the 'Send messages with datachannel' example is broken on iOS 12. See below for the error message. It fails during boot of the example, I don't think this is a WebRTC issue, but instead an issue in one of the support libraries used for the example.

## Steps to reproduce

1. Open https://webrtc.github.io/samples/src/content/datachannel/messaging/ in iOS 12 Safari

## Expected results

The example should load.

## Actual results

The example fails to load with the following error:

```
[Error] Unhandled Promise Rejection: Error: render() not implemented
	update (lit-element.js:18)
	_validate (updating-element.js:362)
	(anonymous function) (updating-element.js:344)
	asyncFunctionResume
	(anonymous function)
	promiseReactionJob
```

**Comment by lgrahl** [comment]
Also doesn't work in Firefox, so not limited to iOS.

**Comment by nkev** [comment]
It doesn't work on Chrome or Firefox on current Macbook either.
