### ISSUE TITLE
webRTC video calling- dial a call to second user

### ISSUE THREAD

**Issue by chhavikohli** [webrtc/samples#1133]
I am currently working on video calling app using webRTC. I have implemented it using

peer-to-peer
openTok
simplewebrtc
Componets that I was able to implement was:

creating room
two or more users can join this room
real time chat can be done
video can be disabled
video recording

calling is done :

call initiator is creating a room

participants are joining the room using room name
but I want a mechanism that initiator dial a call to participant.And participant should pick or reject a call.. How it can be done using simplewebRTC or openTok ? Or which other libraries supports the above feature.. Please help..

 code------------------------------------------------------------------------------
<script src="scripts/simplewebrtc/out/simplewebrtc-with-adapter.bundle.js"></script>

// We got access to local camera
webrtc.on('localStream', () => {
    console.log("hello");
    localVideo.show();
});
function action(data) {
    username = $('#username').val();
    const roomName = $('#roomName').val().toLowerCase();
    reject.hide();
    if (data === 'create-btn') {
        createRoom(roomName);
    }else if(data === 'reject'){
        console.log("reject");
    }
    else {
        joinRoom(roomName);
    }
    return false;
};

// Join existing Chat Room
const joinRoom = (roomName) => {
    console.log(`Joining Room: ${roomName}`);
    webrtc.joinRoom(roomName);
    showChatRoom(roomName);
    postMessage(`${username} joined chatroom`);
};

// Remote video was added
webrtc.on('videoAdded', function (video, peer) {
    console.log('video added', peer);
    let remotes = document.getElementById('remote-videos');
    if (remotes) {
        let d = document.createElement('div');
        d.className = 'videoContainer';
        d.id = 'container_' + webrtc.getDomId(peer);
        d.appendChild(video);
     
        remotes.appendChild(d);
    }
    
//VIDEO REMOVED
webrtc.on('videoRemoved', function (video, peer) {
        console.log('video removed ', peer);
        let remotes = document.getElementById('remote-videos');
        let el = document.getElementById('container_' + webrtc.getDomId(peer));
        if (remotes && el) {
            remotes.removeChild(el);
        }
    });
});

**Comment by ErikHellman** [comment]
Since this is not an issue with the WebRTC samples I will close this issue. Please see webrtc.org for how to get additional help regarding the use of the APIs
