### ISSUE TITLE
AppRTC video chat client does not work in hololens

### ISSUE THREAD

**Issue by CristianKica** [webrtc/samples#1145]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Microsoft Edge 42.17134.111.0 for Hololens

## Description
[AppRTC video chat client sample](https://appr.tc/)  that I found [here](https://webrtc.github.io/samples/), does not work on Hololens's Edge browser. I have a message
Create PeerConnection exception: TypeError:  Object does not support this action

## Steps to reproduce
1-Open Microsoft Edge on Hololens
2-Join a Room [here](https://appr.tc/) 
3-Click Join

## Expected results
The error should not appear. A video conference should be possible with another machine that has the room name.

## Actual results
Error appears and the communication is not possible

**Comment by agouaillard-cosmo** [comment]
Edge is not fully supported yet by appRTC, whatever the platform. Some efforts are ongoing to make it happens, with no ETA.

**Comment by ErikHellman** [comment]
Please file this on https://github.com/webrtc/apprtc. Issues here are for the WebRTC samples.
