### ISSUE TITLE
sdpSemantics is non-spec. Needs to be called out as such.

### ISSUE THREAD

**Issue by jan-ivar** [webrtc/samples#1147]
https://github.com/webrtc/samples/pull/1139 introduced the non-spec `sdpSemantics` from Chrome's [transition plan](https://webrtc.org/web-apis/chrome/unified-plan/) into the webrtc samples.

This may be ok to the extent it helps write spec samples that work in Chrome, but should be called out as such.

Unfortunately, the descriptive text added makes it sound like `plan-b` is an option in [WebRTC](https://w3c.github.io/webrtc-pc/) when it is not: *"An option to specify the [SDP semantics](https://webrtc.org/web-apis/chrome/unified-plan/) for the connection is also available (unified-plan, plan-b or default)."*

Instead, I think something like the following would be more appropriate: *"This is needed at the moment for webrtc samples using `RTCRtpTransceiver` to run in Chrome-based browsers, as part of Chrome's [transition plan](https://webrtc.org/web-apis/chrome/unified-plan/)"*.

cc @ErikHellman @alvestrand

**Comment by fippo** [comment]
removing in #1400

**Comment by fippo** [comment]
it is gone (well, almost)
