### ISSUE TITLE
Select Multiple Cameras By Label

### ISSUE THREAD

**Issue by benlemond** [webrtc/samples#1151]
This is probably more of a question than an issue.  I am trying to open multiple cameras, if they exist,on an embedded linux box.  I can get an open all of the cameras by Id.  The problem is that I need to use the label to identify what that camera is on my hardware.  Currently, no matter what I do, the deviceInfo.label is always blank, even after I have granted permisson.  Can someone please provide me a short example of how to get the labels and load the streams based on the hardware label?

**Comment by ErikHellman** [comment]
I'm closing this as it isn't an issue related to the samples. Please direct your questions about the WebRTC APIs to the discuss-webrtc Google Group: https://groups.google.com/forum/#!topic/discuss-webrtc
