### ISSUE TITLE
Get non-standard stuff out of the WebRTC Samples

### ISSUE THREAD

**Issue by jan-ivar** [webrtc/samples#1152]
https://github.com/webrtc/samples/pull/1144 booted adapter.js for custom non-standard cruft to get `getDisplayMedia`-equivalent behavior in Firefox. We at Mozilla believe in promoting the spec, and do not want people copying this.

This is antithetical to what the purpose of webrtc samples has been up until now, which is to promote samples that we feel good about people copying.

Keeping non-standard stuff out of the webrtc samples was the original purpose of adapter.js. What's changed?

cc @alvestrand @ErikHellman

**Comment by ErikHellman** [comment]
I'm working on this one but have limited time to do finish it this week. The plan is to revert the change so we can discuss some more on how the samples should be structured..
