### ISSUE TITLE
Consider adopting MDN example guidelines

### ISSUE THREAD

**Issue by jan-ivar** [webrtc/samples#1155]
MDN examples follow the [following guidelines](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Guidelines/Code_guidelines).

Some callouts:

* "Only include code that is essential for the example. A large amount of non-relevant code can easily distract or confuse the audience."

* "Don't include unnecessary server-side code, libraries, frameworks, preprocessors, and other such dependencies — they make the code less portable, and harder to run and understand. Use vanilla code where possible."

If not these particular guidelines, then some common guidelines might be helpful.

**Comment by fippo** [comment]
i think we are back to a relatively normal state now
