### ISSUE TITLE
datachannel/messaging: the first message is prepended with 'undefined'

### ISSUE THREAD

**Issue by peat-psuwit** [webrtc/samples#1156]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chromium 70.0.3538.77 on Xubuntu 18.04 (snap version 70.0.3538.77, revision 509)

## Description
The first message in the session seems to always be prepended with 'undefined'. The subsequent messages seem to be normal.

## Steps to reproduce
1. Go to https://webrtc.github.io/samples/src/content/datachannel/messaging/ and click 'Connect'
2. Send 2 messages from the local side.
3. Send 2 messages from the remote side.

## Expected results
All messages appear correctly in the corresponding boxes.

## Actual results
The first message of either side is prepended with word 'undefined' without space. The second message appears correctly.

**Comment by fippo** [comment]
this was fixed in #1175
