### ISSUE TITLE
Ability to pass invalid parameters in getDisplaymedia()

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1158]
# Browser affected
Chrome with experimental features turned on. (after 72.0.3608.4)

## Description
Adding a new checkbox

## Steps to reproduce
Step 1: Go to https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
Step 2: Add a Check box for "Pass Invalid resolution"
Step 3: Click Screen capture and select the option in the pop-up

## Expected results
User gets indicated either in the log or in the UI that the resolution is invalid

## Actual results
Not applicable as this is a new feature request.

**Comment by vkkkumar** [comment]
@ErikHellman Please have a look. Feel free to ask me if you need more information. Thanks!

**Comment by fippo** [comment]
Unlikely to happen in a reasonable timeframe
