### ISSUE TITLE
Stop screen capture button should be disabled, when the screen capture is closed

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1159]
## Browser affected
Chrome with experimental features turned on. (after 72.0.3608.4)

## Description
Stop screen capture button should be disabled, when the screen capture is closed

## Steps to reproduce
1. Click on Start screen capture, in the window picker, close it using X button
2. Check the "Stop screen capture" button

## Expected results
The Stop screen capture button should not be enabled, since the operation has already been cancelled

## Actual results
Uncaught exception in the logs
note : the download button should also be disabled

![2](https://user-images.githubusercontent.com/34342420/49806778-d9555e00-fd58-11e8-97f8-4f2d37b995d3.png)
![1](https://user-images.githubusercontent.com/34342420/49806779-d9555e00-fd58-11e8-8185-30ea5caa1266.png)
![getusermedia](https://user-images.githubusercontent.com/34342420/49806780-d9edf480-fd58-11e8-881a-74c60cf22553.png)

**Comment by fippo** [comment]
the old code handles this better so this is obsolete
