### ISSUE TITLE
No Preview while screen capture ongoing

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1160]
## Browser affected
Chrome with experimental features turned on. (after 72.0.3608.4)

## Description
Enable experimental web platform features, Validate that the preview available while screen sharing

## Steps to reproduce
Step 1: Go to https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
Step 2: Click on "Start screen capture"
Step 3: Select the applicaton window and press "Share"

## Expected results
The screensharing preview is on display.

## Actual results
There is no preview for the screen sharing, but once you click on "stop screen capture", the video gets played.

**Comment by KaptenJansson** [comment]
I think the web page was not designed for this as it's only showing what has been recorded in the video tag. I.e. this is more of a feature request.

**Comment by fippo** [comment]
obsolete since the old code behaves that way
