### ISSUE TITLE
Multiple getDisplayMedia() requests from a test page

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1161]
## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Description
create a test page that has the possibility to request multiple getDisplaymedia() at the same time. The requests must be queued and It should not overlap / overrun to each other.

## Steps to reproduce
This is a new feature request. Thus this section is not applicable

## Expected results
create a test page that has the possibility to request multiple getDisplaymedia() at the same time. The requests must be queued and It should not overlap / overrun to each other.

#
## Actual results
This is a new feature request. Thus this section is not applicable

**Comment by fippo** [comment]
Unlikely to happen in a reasonable timeframe
