### ISSUE TITLE
getDisplayMedia() request from a IFRAME

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1162]
## Browser affected
Chrome with experimental features turned on. (after 72.0.3608.4)

## Description
Create a test page that has the possibility to fire the getDisplaymedia() from an IFRAME

## Steps to reproduce
This is a new feature request. Thus this section is not applicable

## Expected results
Create a test page that has the possibility to fire the getDisplaymedia() from an IFRAME

## Actual results
This is a new feature request. Thus this section is not applicable

**Comment by KaptenJansson** [comment]
Please try to embed the existing test page into a page with an iframe. Should be trivial.

**Comment by rantonysamy** [comment]
Yes that will be really good.

**Comment by KaptenJansson** [comment]
@rantonysamy could you give it a go?

**Comment by rantonysamy** [comment]
Sure will do.

**Comment by guest271314** [comment]
@vkkkumar cc @rantonysamy See https://jsfiddle.net/jib1/thaqyt42/

**Comment by fippo** [comment]
Unlikely to happen in a reasonable timeframe
