### ISSUE TITLE
New Test page which has the notification of Screenshare which cannot be spoofed by website

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1163]
## Browser affected
This is a new feature request. Thus this section is not applicable

## Description
The notification of screen sharing is shown and cannot be spoofed by the website or drawn over

1. The notification of screen sharing windows should not be allowed to drawn over by other apps"
2. The Screen sharing notification window should not be allowed to be spoofed by other apps

## Steps to reproduce
This is a new feature request. Thus this section is not applicable

## Actual results
This is a new feature request. Thus this section is not applicable

**Comment by dagingaa** [comment]
This is already handled by browsers though? If not the appropriate place to file a bug is with the browser vendor in question.

**Comment by KaptenJansson** [comment]
I do not understand the issue, ofc a browser window (which the sharing window is rendered in) has the ability to be drawn over other apps. It's not part of the web page itself.

**Comment by KaptenJansson** [comment]
@rantonysamy could you chime in here if I'm missing something as I do not understand.

**Comment by fippo** [comment]
The browser UI can't be overridden or controlled by the web page (for good reasons!)
