### ISSUE TITLE
CaptureStream is not working in safari 

### ISSUE THREAD

**Issue by RamyaAshika** [webrtc/samples#1164]
# Browser affected

Latest version Safari

## Description
The stream is not at all working in safari.

## Steps to reproduce
Just open this example also

https://webrtc.github.io/samples/src/content/capture/canvas-pc/

nothing is working

## Expected results
It's should work

## Actual results
But it's not at working

**Comment by dagingaa** [comment]
Is this a bug in Safari or the code itself? If it's a bug in Safari a more appropriate place to file the bug might be the Webkit bug tracker here: https://bugs.webkit.org/buglist.cgi?bug_status=__open__&component=WebRTC&list_id=4324407&product=WebKit

**Comment by RamyaAshika** [comment]
iOS calling getUserMedia() again kills video display of first getUserMedia(). Do you have any solution for this? @dagingaa

**Comment by dagingaa** [comment]
Unfortunately not, this is a limitation in Safari. Please refer to the bug on the webkit bug tracker for this issue: https://bugs.webkit.org/show_bug.cgi?id=179363

**Comment by RamyaAshika** [comment]
Oops, actually I commented there but still no response from the bug tracker. @dagingaa

**Comment by RamyaAshika** [comment]
Fixed.
