### ISSUE TITLE
Handle chrome autoplay policy

### ISSUE THREAD

**Issue by akilude** [webrtc/samples#1167]
- [X] I have provided steps to reproduce
- [X] I have provided browser name and version
- [X] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Chrome

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome 71+

## Description
https://webrtc.github.io/samples/src/content/capture/canvas-pc/ demo doesn't work due to changes in the [chrome autoplay policy](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes)  from chrome 71 and above.

## Steps to reproduce
Open sample in chrome 71 or later, move only the canvas teapot without clicking on anything else. On desktop chrome the issue presents itself if the [MEI](https://developers.google.com/web/updates/2017/09/autoplay-policy-changes#mei) of the site s below the threshold, on android the issue always occurs.

## Expected results
Canvas stream is streamed to the video element, video element shows the canvas stream

## Actual results
video element blocks autoplay due to no user interaction. video element does not show the canvas stream.

Simplest fix is just to add the muted attribute to the video element since chrome has no autoplay restrictions on autoplaying muted video.

**Comment by fippo** [comment]
autoplay detection has been added to this in the meantime
