### ISSUE TITLE
Fix the getDisplayMedia sample for functionality issue

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#1171]
## Browser affected
Chrome M72 / M73

## Description
Video stream preview is not being displayed after the screenshare had been started. [Displays only empty screen]. But after the recording had been ended, its possible to see the preview. 

## Steps to reproduce
Go to the test page https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/
Click on "Start screen capture"
Click on "Stop screen capture"

## Expected results
Screen capture preview should be displayed in the video element.

## Actual results
No preview of the screen capture in the video element [and its been blacked out]

**Comment by rantonysamy** [comment]
@ErikHellman @KaptenJansson

**Comment by fippo** [comment]
old code behaves a bit better here
