### ISSUE TITLE
Access camera or webcam without webRTC

### ISSUE THREAD

**Issue by alvintheodora** [webrtc/samples#1174]
In my website, it needs to access camera or webcam. But webRTC is not supported yet on ios webview based on https://forums.developer.apple.com/thread/88052 (please cmiiw). So, I'm trying to find a way to access it without webRTC. Is there any?

1. And is this following code, a part of utilizing webRTC? Because the console.log shows up on ios webview

`function hasGetUserMedia() {
  return !!(navigator.getUserMedia || navigator.webkitGetUserMedia || 
    navigator.mozGetUserMedia || navigator.msGetUserMedia);
}`

`if (!hasGetUserMedia()) {           
  console.log( "webRTC is not supported in your browser" );//it shows on ios webview             
}`

`navigator.mediaDevices.getUserMedia({
 audio: false, //no audio
 video: {deviceId: {exact: videoSource.camera_id} }
})
`

2. If yes, so what's the workaround which not using webRTC, and can be run on android webview, ios webview, and web browsers?

**Comment by dagingaa** [comment]
There is no way to do what you are trying to achieve on iOS. If you need access to the camera on iOS in a native app, you need to access it from the native context. Try looking into React Native and WebRTC if you wish to develop using JavaScript.

**Comment by alvintheodora** [comment]
@dagingaa Thanks for responding. 
So, are you saying that in **ios webview**, there is absolutely no way to access camera devices?

**Comment by dagingaa** [comment]
Yes, getUserMedia is not supported there yet, and the security model of the webview won’t allow accessing it.

**Comment by sravanshty** [comment]
Hello,

In my sample application i am using doing basic video capturing with getUserMedia-( as it uses MediaRecorder API) able to capture in Chrome, **but it is not supporting is Safari browser**. Do we have an option to capture video in Safari browser with this?

**Comment by dagingaa** [comment]
Can you provide a minimal test case? (Also I think this warrants a new issue, this one can be closed)

**Comment by sravanshty** [comment]
for video recording 
For Starting video capture using below snippet
let mediaRecorder = new MediaRecorder(stream,{mimeType:'video/webm'});
mediaRecorder.ondataavailable = this.handleData;
mediaRecorder.start(1000);

for Stopping video recording using below snippet
mediaRecorder.stop();

this sample is working fine in chrome. But in safari when i click on start it is Error : can't find variable: MediaRecorder.

My question is like does  safari browser supports getUserMedia() for video capturing or not? Please help me out with your solution

**Comment by dagingaa** [comment]
A quick Google search reveals the answer to your question: https://bugs.webkit.org/show_bug.cgi?id=85851

If MediaRecorder is not defined it won't work, and has nothing to do with getUserMedia inherently. getUserMedia IS supported in some variants of Safari, but MediaRecorder is not.

This is a separate issue from the one asked here

**Comment by sravanshty** [comment]
Thanks @dagingaa  for your response. But https://www.webrtc-experiment.com/msr/video-recorder.html which is used for capturing video which works in Chrome but it is not supporting in Safari right?

**Comment by dagingaa** [comment]
Does it use MediaRecorder (think it was called MediaStreamRecorder before)? If so yes, since Safari doesn't support MediaRecorder it's no wonder it doesn't work in Safari?

**Comment by davidbongcc** [comment]
I'm using WKWEbview to access a React app with camera. Any solutions so far?

**Comment by philfung** [comment]
https://github.com/fathyb/JSCameraKit

**Comment by M4THYOU** [comment]
@philfung I've been looking at that repo for a while, any idea if there are any docs or examples that could help me figure out how to implement JSCameraKit?

**Comment by fippo** [comment]
closing as it is not related to the samples but should have been discussed on [discuss-webrtc](https://groups.google.com/g/discuss-webrtc)
