### ISSUE TITLE
Peer connection fails in chromebooks

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1176]
## Browser affected

72.0.3626.85 Chromebooks and Mac 72.0.3626.81.
P.S:  It could be the same in other platforms too. .

## Description
Remote video is blacked out.

## Steps to reproduce
Go to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
Click Call and then click Accept button.

## Expected results
Remote video feed should not be black and it should have the video content.

## Actual results

Remote video feed is blacked out. It does seems like the sample page issue not it does not effect any other live webrtc apps. 

[webrtc.github.io-1549274618803.log](https://github.com/webrtc/samples/files/2827796/webrtc.github.io-1549274618803.log)
[webrtc_internals_dump.txt](https://github.com/webrtc/samples/files/2827797/webrtc_internals_dump.txt)

**Comment by KaptenJansson** [comment]
Could you include logs from the page?

**Comment by vkkkumar** [comment]
Do you mean Javascript Logs from the sample page? if yes Here it is from M74 on Minnie. 
[webrtc.github.io-1551865860719.log](https://github.com/webrtc/samples/files/2935548/webrtc.github.io-1551865860719.log)

**Comment by vkkkumar** [comment]
This issue is still available in Buddy Buddy 74.0.3729.0 / 11895.4.0

**Comment by subhashreesahoo86** [comment]
Similar issue is observed in Chrome M83.0.4094.0 builds for Mac, Windows, Linux and Pixel Book.

Chrome Version: M83.0.4094.0(Official Build) (64-bit)
Chrome OS Version:
Chrome OS Platform: Linux, Mac, Windows, PixelBook
Description
pr-answer functionality is not working as expected

Steps To Reproduce:
0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Check if the local video is seen in the left pane
3. Press "Call"
4. Press "Accept"
5. Press "Hang up

Expected Result:
Step 3: After accepting the call, the remote video in the right pane should be seen
Step 5: After hanging up, the remote video in the right pane should be seen black

Actual Result:
After accepting the call, the remote video in the right pane is blacked out.

Error received in console:
GET https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/css/main.css net::ERR_ABORTED 404

**Comment by subhashreesahoo86** [comment]
Similar issue is observed in Chrome M83.0.4094.0 builds for Mac, Windows, Linux and Pixel Book.

Chrome Version: M84.0.4114.0(Official Build) (64-bit)
Chrome OS Version:
Chrome OS Platform: Linux, Mac, Windows, PixelBook
Description
pr-answer functionality is not working as expected

Steps To Reproduce:
0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/

Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
Check if the local video is seen in the left pane
Press "Call"
Press "Accept"
Press "Hang up
Expected Result:
Step 3: After accepting the call, the remote video in the right pane should be seen
Step 5: After hanging up, the remote video in the right pane should be seen black

Actual Result:
After accepting the call, the remote video in the right pane is blacked out.

Error received in console:
Failed to load resource: the server responded with a status of 404 ()

**Comment by fippo** [comment]
M72 is pretty old and this hasn't been a big problem since
