### ISSUE TITLE
Audio context was not allowed to start in the sample page

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#1179]
## Browser affected
Macbook Air 72.0.3626.119 and later versions. It seems like an old issue (Regression)

## Description
Test page is not working on Mac devices. 

## Steps to reproduce
Goto https://webrtc.github.io/samples/src/content/getusermedia/volume/
Speak something.

## Expected results
Based on the input noise the graphs should reflect. 

## Actual results
Unfortunately the graphs are stuck. 

In java script it shows,
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

## Does this happen in other platforms? 
No in Windows 10 it is not reproducible. Thus it is Mac Os specific issue.

**Comment by fippo** [comment]
That is the good old autoplay issue which got re-enabled in Chrome 71. Not part of the webrtc release notes sadly. See https://bugs.chromium.org/p/chromium/issues/detail?id=835767

**Comment by vkkkumar** [comment]
This is not reproducible in Windows is it specific to MacOS?

**Comment by fippo** [comment]
the confusing (and almost un-QA-able) thing about autoplay is the MEI which does things invisibly in the background :-|

See https://webrtchacks.com/autoplay-restrictions-and-webrtc/

**Comment by wotamann** [comment]
**Browser depending not working in Win10-64**

Goto [https://webrtc.github.io/samples/src/content/getusermedia/volume/](https://webrtc.github.io/samples/src/content/getusermedia/volume/)
Speak something.

FF 66 -> works as expected

Chrome 72 -> navigator.MediaDevices.getUserMedia error:  Could not start audio source NotReadableError

Microsoft EdgeHTML 17.17134 -> navigator.MediaDevices.getUserMedia error: null NotFoundError

Despite using HTTPS and calling `navigator.MediaDevices.getUserMedia( {audio:true} )` after  a user gesture Chrome/Edge will throws an error 

Do you have any idea?
