### ISSUE TITLE
Cannot automatically output audio to loudspeaker for Safari in iOS 12.2 

### ISSUE THREAD

**Issue by phsultan** [webrtc/samples#1186]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected
**Safari 12.2, iPhone 7**
**Safari 12.0, iPhone 5S**

## Description
An audio stream that results of an established PeerConnection seems to always be played back by the internal speaker in Safari 12.2 on my iPhone 7, and can be later switched to the phone's loudspeaker by pausing the local audio or muting then unmuting the microphone. I know that `setSinkId()` isn't implemented but I'm wondering how Safari on iOS selects the output device that plays audio, if it ever makes a choice.

It might be that this bug report is actually a general WebRTC question, a bug in Safari, or me missing something obvious, but I need to get some advices to understand :).

I have tested this page : https://webrtc.github.io/samples/src/content/peerconnection/audio

## Steps to reproduce
- access https://webrtc.github.io/samples/src/content/peerconnection/audio/, click the `Call` button, authorize access to your microphone
- you should see the red microphone icon being displayed on the upper left, statistics charts flowing, and hear your own audio input being played back in the internal phone speaker
- now pause you local audio stream (by clicking the corresponding `<audio />` tag, or mute/unmute yourself by clicking the red microphone icon, and the remote audio will be played back in the loudspeaker.

## Expected results
Audio should be played back in the loudspeaker (or should stay in the internal phone speaker).

## Actual results
Audio is played back in the internal phone speaker, and can be later played in the loudspeaker by pausing your local audio, or muting/unmuting your microphone.

Thanks a lot!

**Comment by youennf** [comment]
@phsultan, thanks for the report. This seems like a bug in WebKit so a bug report in bugs.webkit.org seems like the best thing to do.

**Comment by youennf** [comment]
I filed https://bugs.webkit.org/show_bug.cgi?id=196539

**Comment by phsultan** [comment]
Thanks for your feedback @youennf ! Closing this one then.

**Comment by yvesgurcan** [comment]
Hello! I'm stumbling on this issue report as I encounter the same bug. Do we know if there's been any progress, information, or a workaround found? @youennf, if you have something, I'm all ears!

My application streams the audio from the user's microphone to other users and plays audio files to the users at the same time. I noticed the bug on iOS+Safari on an iPad using iOS 13.7 and an iPhone using iOS 14. The audio files seem to be played by the internal speaker instead of the loudspeaker. However, this behavior is inconsistent and sometimes audio files are played by the loudspeaker. Even worse, sometimes audio files are played by the internal speaker first and then switched to the loudspeaker without a visible reason. Another issue I noticed when the microphone is active is the stuttering in the playback of the audio files.

**Comment by karltaylor** [comment]
Just to add some more to this issue, I understand that it's not Safari / iOS so apologies

But is there any way to change this on Chrome in Android as well? Audio is treated as a phone call and not sure if it's possible to make audio come out of the loudspeaker and not as a phone call?

**Comment by qiulang** [comment]
@phsultan 

Hi I come across this issue but what I don't understand is why should iOS **automatically** output audio to loudspeaker ? 

As a matter of fact, some of my client tells me that their iOS app, which uses WebRTC, automatically outputs audio to loudspeaker and they do not want that.

**Comment by youennf** [comment]
@qiulang, default is to output to loudspeaker.
A web app can override this default behaviour by using https://w3c.github.io/mediacapture-output/#dom-htmlmediaelement-setsinkid.

**Comment by qiulang** [comment]
@youennf Thanks for the reply!

But I also find this https://stackoverflow.com/questions/79401143/ios-safari-switches-audio-output-to-speakers-when-starting-microphone-recording

He complained (just like my client) why output speaker ?

Besides I read the w3c document you said I can't find where it says "default is to output to loudspeaker"
