### ISSUE TITLE
When it becomes 3d touch(iPhone), it becomes disable

### ISSUE THREAD

**Issue by whilemouse** [webrtc/samples#1188]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [v] I have provided steps to reproduce
- [v] I have provided browser name and version
- [v] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
safari 12
ios 12.2
iPhone6s(include 3d touch)

## Description
[step link](https://youtu.be/3w-Lc9PIySw)
When it becomes 3d touch(iPhone), it becomes camera off. 

## Steps to reproduce
1. go [link](https://webrtc.github.io/samples/src/content/getusermedia/gum/)
2. click [Open camera]
3. click(force touch) [WebRTC samples]
4. Camera is disable

## Expected results
Camera is not disable

## Actual results
Camera is disable

**Comment by fippo** [comment]
File a safari bug if this remains an issue
