### ISSUE TITLE
getDisplayMedia Crashes on Android Chrome 73 

### ISSUE THREAD

**Issue by akilude** [webrtc/samples#1189]
- [ X] I have provided steps to reproduce
- [ X] I have provided browser name and version
- [ X] I have provided a link to the sample here or a modified version thereof

## Browser affected

Android Chrome 73.*, Maybe with earlier versions as well

## Description
The chrome android browser app crashes when attempting to use the getDisplayMedia demo

## Steps to reproduce
1)Open https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/ on chrome android
2)Click Start screen capturing, accept the permission when prompted.
3) Chrome android app crashes

## Expected results
Demo works

## Actual results
Chrome crashes and presents a popup asking to be opened again.

**Comment by ben-turner** [comment]
Happens for me with Chrome on Linux, but I don't get a popup asking me to restart it.

`chrome://version`

Google Chrome | 83.0.4103.97 (Official Build) (64-bit)
-- | --
Revision | 326d148b9655369b86498d9ecca39f63dd2bdd2d-refs/branch-heads/4103@{#657}
OS | Linux
JavaScript | V8 8.3.110.9
Flash | 32.0.0.387 /home/ben/.config/google-chrome/PepperFlash/32.0.0.387/libpepflashplayer.so
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36
Command Line | /opt/google/chrome/google-chrome --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service

**Comment by fippo** [comment]
file a chrome bug if this still happens
