### ISSUE TITLE
Offer size increase infinitely upon add/remove track

### ISSUE THREAD

**Issue by Mfron-42** [webrtc/samples#1190]
I noticed that the signals keep on growing as I add new streams. Seems like removed stream are still referenced in futur signals. After a few cycles of adding and removing a stream the signal grows to more than 100ko.

I joined the offer produced after adding then removing the same track ~10 times.

Reproduce :

1. Download the project here : https://webrtc.github.io/samples/src/content/peerconnection/upgrade/

2. Change the function upgrade in main.js by =>
`function upgrade() {
  upgradeButton.disabled = true;
  return navigator.mediaDevices
    .getUserMedia({video: true})
    .then(stream => {
      const videoTracks = stream.getVideoTracks();
      if (videoTracks.length > 0) {
        console.log(`Using video device: ${videoTracks[0].label}`);
      }
      localStream.addTrack(videoTracks[0]);
      localVideo.srcObject = null;
      localVideo.srcObject = localStream;
      pc1.sender = pc1.addTrack(videoTracks[0], localStream);
      return pc1.createOffer();
    })
    .then(offer => {
      pc1.setLocalDescription(offer);
      console.warn("Offer lenght upgrade : " + JSON.stringify(offer).length);
      console.warn(offer);
      return offer;
    })
    .then((offer) => pc2.setRemoteDescription(offer))
    .then(() => pc2.createAnswer())
    .then(answer => {
      pc2.setLocalDescription(answer);
      return answer;
    })
    .then((answer) => pc1.setRemoteDescription(answer))
    .then(() => downgrade());
}`

3. Add the function downgrade on main.js by =>
`function downgrade() {
  upgradeButton.disabled = true;
  return navigator.mediaDevices
    .getUserMedia({video: true})
    .then(stream => {
      const videoTracks = stream.getVideoTracks();
      if (videoTracks.length > 0) {
        console.log(`Using video device: ${videoTracks[0].label}`);
      }
      localStream.addTrack(videoTracks[0]);
      localVideo.srcObject = null;
      localVideo.srcObject = localStream;
      
      pc1.removeTrack(pc1.sender);
      return pc1.createOffer();
    })
    .then(offer => {
      pc1.setLocalDescription(offer);
      console.warn("Offer lenght downgrade: " + JSON.stringify(offer).length);
      console.warn(offer);
      return offer;
    })
    .then((offer) => pc2.setRemoteDescription(offer))
    .then(() => pc2.createAnswer())
    .then(answer => {
      pc2.setLocalDescription(answer);
      return answer;
    })
    .then((answer) => pc1.setRemoteDescription(answer))
    .then(() => upgrade());
}`

**Comment by fippo** [comment]
This is an expected consequence of unified-plan.
