### ISSUE TITLE
getUserMedia fails in Chrome

### ISSUE THREAD

**Issue by claytron5000** [webrtc/samples#1191]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Chrome Version 73.0.3683.103 (Official Build) (64-bit)

## Description

`getUserMedia` fails with the error message "Permission denied by system", name: "NotAllowedError"

## Steps to reproduce
1. In Chrome, go to https://webrtc.github.io/samples/src/content/getusermedia/audio/
2. Nothing happens
3. Open console, observe the error message `navigator.MediaDevices.getUserMedia error:  Permission denied by system NotAllowedError`

## Expected results

Expected behavior: asking permission, then hearing the audio input

## Actual results

Nothing happens

**Comment by claytron5000** [comment]
Some troubleshooting:
- the permission pop-up never showed
- My microphone is set to "Ask before accessing", with no blocked sites.
- It does work in other browsers on the same machine (Firefox, Safari)

**Comment by claytron5000** [comment]
And there's a Chrome bug report from Linux land as well https://bugs.chromium.org/p/chromium/issues/detail?id=957572&q=component%3ABlink%3EGetUserMedia%20&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

I've added a bug in the Mac OS channel
https://bugs.chromium.org/p/chromium/issues/detail?id=958496&can=2&q=component%3ABlink%3EGetUserMedia%20%20os%3DMac%20%20m%3D74&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified

**Comment by claytron5000** [comment]
So the issue is not in Chrome, but a System Setting in MacOS. I think this issue can encompass making the page display a more informative error to the user.

**Comment by dagingaa** [comment]
I don't believe the sample pages should handle those issues. What it does now is correct, it shows you the error. The UX for handling this can vary widely between implementations. IMO samples should show you when an error happens and the specifics of that error, but solving it should be left to the implementor in their own product.

For what it's worth the error is better than I've seen before with "Permission denied by system" being quite descriptive of what's going on without being verbose.

**Comment by claytron5000** [comment]
The error is good, but on page https://webrtc.github.io/samples/src/content/getusermedia/record/ the error is actually printed to the page. It's a small improvement, but might help reduce confusion.

**Comment by dagingaa** [comment]
Ah right, in that case I agree, that would be very helpful! I just kinda figured this page also did it since so many others already have that functionality (as the record one you mentioned). So I assumed you meant something else. Sorry about that!

**Comment by claytron5000** [comment]
I opened a PR to print the error on the page: https://github.com/webrtc/samples/pull/1193
Closing this issue.

**Comment by ankitarora05** [comment]
Hi Guys,
I am trying to make an web app which captures images both from front and back camera. When i try it in all browsers say Opera, Firefox, UC on mobile i am able to switch between front and back camera but on Chrome mobile i am not able to do that. I can't figure out what did miss.

You can check it on https://webpd.gamecom.app/ you would have to sign in through google or facebook as it is a production app.
Once you have signed in you can click on Reply button (in red) which triggers the camera. But not able to switch cameras in chrome.
Let me know if you need more input on this.

Thanks

**Comment by ankitarora05** [comment]
Forgot to mention the reply button is only there on mobile. Web there was only one camera so it was working fine.
https://webpd.gamecom.app/
