### ISSUE TITLE
Can i change playout delay?

### ISSUE THREAD

**Issue by jimmywarting** [webrtc/samples#1198]
## Browser affected

**Browser** Google Chrome 74.0.3729.169

## Description
I want to use the camera and rewatch the live feed 10-20 seconds later on another device (mostly for sports where you can see what you did wrong after you did something)

Now, I have tried using MediaRecorder on the receivers RTC stream and it didn't go so well. 

## Steps to reproduce

https://jsfiddle.net/ofy8w1jn/5

## Expected results
To play the WebRTC track with an added 10-20 sec delay

## Actual results

It looks like it's able to record the stream and spit out some actual data from the stream, but it's unable to play it back with MSE. Using it on the local stream works fine...

The video where mostly black and i would eventually get one frame and nothing more after a long delay.

---

I posted this on [stackoverflow](https://stackoverflow.com/questions/56510151/delayed-recorded-webrtc-video-stream) also, will hand out a bounty reward for whoever can give me a good answer

**Comment by fippo** [comment]
looks like stackoverflow yielded an answer

**Comment by jimmywarting** [comment]
yup, indeed :)
