### ISSUE TITLE
GETTING ISSUES ON "https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/"

### ISSUE THREAD

**Issue by Dhrubo700110** [webrtc/samples#1200]
Hi, after clicking on the point "Screensharing with getDisplayMedia" of the link "https://webrtc.github.io/samples/" I am getting page like 1.jpg which is working fluently, but when I'm downloading the code from "View source on GitHub" and trying to run it it's opening like 2.jpg & there is no "Start screen capture  - Stop screen capture - Download recording" button and no display window at all.

**n.b. 1.jpg & 2.jpg are duly attached.**

Maybe some lines of code are missing in index.html
![1](https://user-images.githubusercontent.com/52395859/60412294-2f52fb80-9bee-11e9-9106-e4b7f16bb133.jpg)
![2](https://user-images.githubusercontent.com/52395859/60412295-2f52fb80-9bee-11e9-8828-f98290e0794b.jpg)

**Comment by fippo** [comment]
should no longer happen with the old code that came back
