### ISSUE TITLE
there is an easy guide about how to launch these code sample locally in my computer?

### ISSUE THREAD

**Issue by EliosSs** [webrtc/samples#1204]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ x] I have provided steps to reproduce
- [x ] I have provided browser name and version
- [ x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Version 75.0.3770.100

## Description

Hi guys, how are you? I am very very new guy on this and I have "zero" experience on this. I just want to know if there is an easy guide or tutorial to launch and test these code samples locally (on my own PC or local network). However i will follow all the standards of the forum because I don't want my post to be deleted and I would like to have an easy and concrete answer.

I am already using the repository code and installing the nightwatch and webdrivers inside it.

## Steps to reproduce

I do all the steps that nightwatch recommends in their getting started webpage 
https://nightwatchjs.org/gettingstarted/

after the installation of the nightwatch, selenium, and webdrivers that I need for the project (basically the folder "node_modules" right?), the configuration step comes, and I don't do nothing in this step because all the conf.js and .json file are ready, right?

after this I just run ./node_modules/.bin/nightwatch and then I obtain an error connection message.
Can anyone help me? I don't want to waste much time of the people, just refer me to a guide or tutorial that I can read to launch the code samples locally on my pc or something. Is that possible?

## Expected results

I don't know which is the expected result, is it possible for me to launch the code samples locally and to obtain something like the live tests? https://webrtc.github.io/samples/
but locally on my pc and accessible from my local network?

## Actual results
the error that I get is "connect ECONNREFUSED 127.0.0.1:4444", It means that my server is not online right? but I don't know how to launh it. can you tell me how? I should use te selenium server? Sorry but in any place tells me how to use it?
I apologize is my questins are so stupid or something, as I said I am an extreme beginner on this.
I would really apreciate your help.

**Comment by fippo** [comment]
nightwatch is gone. `npm start` starts a http server.
