### ISSUE TITLE
No option for controlling speed in video to peer connection sample

### ISSUE THREAD

**Issue by rdxmiles** [webrtc/samples#1213]
I was looking around the WebRTC sample and I found that in video to peer connection sample in steam capture there was no option for controlling speed of the video that has been shared to peer connection.
My suggestion is of adding slider to control video speed.
https://webrtc.github.io/samples/src/content/capture/video-pc/

**Comment by fippo** [comment]
the [bandwidth sample](https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/) covers this
