### ISSUE TITLE
Could not record video data from iphone to mac chrome.

### ISSUE THREAD

**Issue by nagamunireddy** [webrtc/samples#1217]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by nagamunireddy** [comment]
Hi guys,

I am currently using google chrome version 77.0.3865.35. and I have an app build on top of webRTC which I have downloaded the framework dec,18.

When I call from chrome to my mobile application, recording API is not working. Strangely the blob data is of 0 Mb. Weird thing is, the same scenario works in a windows chrome version. I can record the data when I call from a windows chrome to my mobile application.

Any help on this?

**Comment by thomas-cruz** [comment]
I am running the  MediaRecorder sample locally and I get the same error as @nagamunireddy where the blob data is 0mb. I am running mozilla firefox 87.0 (64-bit) on macOS catalina 10.15.7

**Comment by fippo** [comment]
Not clear how this affects the samples in this repository
