### ISSUE TITLE
How to resolve Safari 13 getUserMedia “Invalid constraint” issue

### ISSUE THREAD

**Issue by Aleksei-Suprun-Mera** [webrtc/samples#1218]
Safari Version 13.0 (14608.1.48)
MacOS Mojave 10.14.6

## Description
getUserMedia “Invalid constraint”

## Actual results
Unable to acquire screen capture: Invalid constraint

Works fine on both Edge and Chrome.
I've tried every combination
example doesn't work https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/

**Comment by AdrienV** [comment]
I don't know if it can help, but I had the same problem with Safari (in the demo as well), but for this example : https://webrtc.github.io/samples/src/content/getusermedia/record/

I deleted the `echoCancellation` constraints and it solve this error  : 
`````
const constraints = {
    audio: {
      //echoCancellation: {exact: hasEchoCancellation}
    },
    video: {
      width: 1280, height: 720
    }
  };```

**Comment by alvestrand** [comment]
This is a Safari bug, I believe. Echo cancellation is supposed to be supported as a constraint.
Note: if Safari doesn't show echoCancellation in getCapabilities, Safari is at least consistent.
