### ISSUE TITLE
Using  getDisplayMedia PowerPoint program maximize ppt not change

### ISSUE THREAD

**Issue by tym3515** [webrtc/samples#1220]
navigator.mediaDevices.getDisplayMedia({
				video: {
					cursor: "always" // 始终显示鼠标信息
				},
				// audio 配置信息是可选的
				audio: {
					echoCancellation: true,
					noiseSuppression: true,
					sampleRate: 44100
				},
			})

**Comment by fippo** [comment]
not clear how this is an issue with the samples
