### ISSUE TITLE
getusermedia() is not working in android webview.

### ISSUE THREAD

**Issue by sameermk97** [webrtc/samples#1222]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

works perfectly on chrome and can also access the webcam but it fails to load front camera when i try it in webview(android studio)

## Description
I have a webpage which uses webcam with the help of getusermedia(). The webpage works fine. But, when I try it on android studio using webview, the webpage loads fine but the front camera of the phone is blank. I have given all the required permissions in manifest.xml.

Is there any way to access front camera in webview (originally javascript page).

**Comment by fippo** [comment]
not an issue with the samples. Please file a chrome bug if this is still an issue
