### ISSUE TITLE
701 error

### ISSUE THREAD

**Issue by Archer-Thane** [webrtc/samples#1232]
- [X] I have provided steps to reproduce
- [X] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

The issue is not browser specific. Tested with: Chrome Version 78.0.3904.70 (Official Build) (64-bit)
and Firefox 69.0.1
## Description
I've used pion turn server. the instructions are found inside [github page](https://github.com/pion/turn) 
After a simple setup using test as username and password, I see a 701 error code from trickle Ice page.
Worth to mention that the pion program started correctly at port 3478 on UDP. this is verified using fuser 3478/tcp command from server's terminal.
First of all, what means this error and where can I find description about error codes, and second is how to fix this?
## Steps to reproduce
1- open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2- STUN or TURN URI: turn:aalimoshaver.com:3478
3- TURN username: test
4- TURN password: test
## Expected results
This should show a success test, which indicates done. 
## Actual results
I got these as error text:
The server stun:aalimoshaver.com:3478 returned an error with code=701:
STUN allocate request timed out.
The server turn:aalimoshaver.com:3478?transport=udp returned an error with code=701:
TURN allocate request timed out.

**Comment by Archer-Thane** [comment]
possible #1215

**Comment by ForGuru** [comment]
Issue is appearing only on Chrome browser also appearing on  

> stun:stun1.l.google.com:19302

 while testing on Chrome

**Comment by Archer-Thane** [comment]
On firefox and my server, I see a 'not reachable' after about ten seconds status. 
But for google stun server, I can see both is working fine.

**Comment by Archer-Thane** [comment]
The problem was from infrastructure. Since there were close ports (49152–65535) I saw connection timeouts.
I really suggests to add those to documentation, even on first github page (adding a requirements part).
Also I would like to share this page to you. https://docs.pexip.com/rp_turn/rpturn_ports.htm
That's a gem I found explaining all necessary ports for this.

**Comment by rah-0** [comment]
Seems to be more like a chrome related bug, I opened that port range too but I still get errors in chrome. Firefox did not give any error with either ports open or closed. 

Related to https://github.com/webrtc/samples/issues/1227

**Comment by ghost** [comment]
I have too on Edge and chrome. this must be a bug. any way its work,.. mayby its because its not set for IPv6 ?

**Comment by Sigma721** [comment]
Not sure if you still struggling, but I had my Coturn server setup and it worked with Firefox, but not with Chrome(with and without plugins like AdBlockers). I followed this(https://ourcodeworld.com/articles/read/1175/how-to-create-and-configure-your-own-stun-turn-server-with-coturn-in-ubuntu-18-04) guide, and it's working with Chrome now

**Comment by kyteague** [comment]
@nass1988 exactly

Make sure the STUN/TURN servers are binded to both IPv4 and IPv6 addresses otherwise this timeout will occur.

**Comment by regnaio** [comment]
Google Chrome has the error:

The server stun:stun.l.google.com:19302 returned an error with code=701

Firefox works great though

https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by alvestrand** [comment]
Stun code 701 is SERVER NOT REACHABLE.
If you have logs from the server showing that a packet reached it and a reply was returned, this is most likely a firewall problem, and needs to be solved on your local network.

This bug is closed because it is not a bug in the samples. Please don't pile on.

**Comment by kekkokk** [comment]
Seems happening only when I have a VPN connected in my OSX pc. 
No matter what or where the VPN is connected but seems that whenever chrome engine "see" another connected link, tries to do thing with it.
If i disable VPN no more 701 occurs. Tried with OpenVPN connect and WireGuard.

Tried different config as suggested and also setting an AAAA record for the ipv6, still the same error. 
Only thing make it works is to disable VPN client
