### ISSUE TITLE
why is not possible to control both media (video/audio) using the code provided?

### ISSUE THREAD

**Issue by EliosSs** [webrtc/samples#1235]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x ] I have provided steps to reproduce
- [ x] I have provided browser name and version
- [ x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Version 78.0.3904.87 (Official Build) (64-bit)

## Description
I am trying to control the bandwidth of the video but with both medias, Audio and video enabled, when I try to control the bandwidth it gets an strange behavior and the control is not effective.
Another thing is even with just video as the only medio it is imposible to control for high bandwidth values? why is that?

## Steps to reproduce
enabling audio as the getUsermedia constraints
`const constraints = {
  audio: true,
  video: true
}`

## Expected results
The effective control of the Video bandwidth

## Actual results
Nothing about the control

**Comment by alissonwerner** [comment]
I also have this problem. 

When audio is enabled and the `updateBandwidthRestriction` method insert a 'b=AS' line inside SDP answer, it seems the pc1 bandwidth control has not effect.

**Steps to reproduce**

`const offerOptions = {
  offerToReceiveAudio: 1,
  offerToReceiveVideo: 0
};`

`getUserMedia({audio: true})`

`let maxBandwidth = 15;`

**Expected results**
pc1 sending audio with 15 kbps at most. 

**Actual results**
pc1 sending audio over 20/30 kbps.

**Comment by fippo** [comment]
The sample only supports a single m-line. If you need both audio and video you'll have to modify it (preferably for the more modern getSenders approach)
