### ISSUE TITLE
Webcam Error NotReadableError: 'Could notstart video source' on my Galaxy S10

### ISSUE THREAD

**Issue by EugeneFitzher** [webrtc/samples#1248]
Hello, I'm using Samsung Galaxy S10 ( G977, QP1A.190711.020 ) version Android 10 and chrome version 79.0.3945.93.

I'm new to webAR, and I'm trying to learn AR.js, but there are errors when I open the every AR websites, 'Webcam Error Name: NotReadableError, Message: Could not start video source'.
I found the way that changing camera can solve this problem some cases, but for me, just white site is showing.
( I used these links to try:
1. https://codepen.io/nicolocarpignoli/full/KKwzRdJ => just white sites, CHANGE CAMERA works nothing.
2. https://nicolo-carpignoli-herokuapp.com/select-camera => WebcamError shown first, and when I click 'Switch camera' button, chrome said on status bar: Accessing video input. Touch to return to https:// ~ .' But also white site no contents just 'Switch Camera' and VR button. )

I'm trying to solve this problem, but I can't.

How can I solve it?

Thanks.

**Comment by narmeenm94** [comment]
I am facing the same issue... no updates?

**Comment by hgoona** [comment]
> I am facing the same issue... no updates?

Hi guys, same issue here. Is this a new issue? Anyone found a solution? :/

**Comment by fippo** [comment]
file a chrome bug if this persists
