### ISSUE TITLE
Audio context was not allowed to start in the sample page

### ISSUE THREAD

**Issue by subhashreesahoo86** [webrtc/samples#1250]
Browser affected
Chrome Browser 81.0.4013.0.  

Description
Test page is not working on Linux devices.

Steps to reproduce
Goto https://webrtc.github.io/samples/src/content/getusermedia/volume/
Speak something.

Expected results
Based on the input noise the graphs should reflect.

Actual results
Unfortunately the graphs are stuck.

In java script it shows,
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

Does this happen in other platforms?
Not yet checked. The other devices testing is in progress.

**Comment by leelaharitha** [comment]
Same issue is reproducible in Windows devices - Chrome version 81.0.4016.0

**Comment by KaptenJansson** [comment]
This is now fixed, right?

**Comment by subhashreesahoo86** [comment]
Yes, this is fixed, Working as expected in M86.
Thanks
