### ISSUE TITLE
Getting Timeout and Error with code 701 on clicking Gather Candidates for ICE Server

### ISSUE THREAD

**Issue by chiangky** [webrtc/samples#1251]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ v] I have provided steps to reproduce
- [ v] I have provided browser name and version
- [ v] I have provided a link to the sample here or a modified version thereof

## Browser affected
Google Chrome Version 79.0.3945.88 (Official Build) (64-bit)
Firefox v71.0 (32bit)

## Description
In my same PC and same networking environment, both Chrome & Firefox browser has different testing result. Firefox works fine but Chrome is not working.

## Steps to reproduce
0. Connect the PC to the router (My Public IP: 112.118.183.xxx ; LAN local IP: 192.168.8.228)
1. Launch https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Click "Reset to defaults" button
3. Input STUN URI: "stun:stun1.l.google.com:19302" and click "Add Server" button
4. Input STUN URI: "stun:stun2.l.google.com:19302" and click "Add Server" button
5. Input STUN URI: "stun:stun3.l.google.com:19302" and click "Add Server" button
6. Input STUN URI: "stun:stun4.l.google.com:19302" and click "Add Server" button
7. ICE options "IceTransports value:" set to "all" (default)
8. ICE options "ICE Candidate Pool:" set to "0" (default)
9. Click on "Gather Candidates" button

## Expected results
It should display all the candidates of Type 'Host' or 'srflx', and no errors show at the bottom.

## Actual results
Error code 701 shows at the bottom of "Gather Candidates" button.
The server stun:stun1.l.google.com:19302 returned an error with code=701:
STUN allocate request timed out.
The server stun:stun2.l.google.com:19302 returned an error with code=701:
STUN allocate request timed out.
The server stun:stun3.l.google.com:19302 returned an error with code=701:
STUN allocate request timed out.
The server stun:stun.l.google.com:19302 returned an error with code=701:
STUN allocate request timed out.
The server stun:stun4.l.google.com:19302 returned an error with code=701:
STUN allocate request timed out.

Screenshot of Chrome test result:
![Chrome](https://user-images.githubusercontent.com/37294789/71804068-63c3da80-309d-11ea-865a-747228b3c95d.png)

Screenshot of Firefox test result:
![firefox](https://user-images.githubusercontent.com/37294789/71804066-63c3da80-309d-11ea-975c-8d074ddc4325.png)

**Comment by Archer-Thane** [comment]
We need some documentation on error codes and their meanings. What is 701? why this is not working? what is to be solve?

**Comment by verycosy** [comment]
I have a same experience now, and agree to this guy @Archer-Thane 
Even in MDN, Error codes between 700 and 799 are not specified yet. 
https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidateerror

In my case, Media Communication works well.
But In RTCDataChannel, I got same error when icecandidate event is fired.
![스크린샷 2020-01-28 오후 11 41 06](https://user-images.githubusercontent.com/45239217/73273647-b79e8b00-4227-11ea-8632-962a1e61f85d.png)

**Comment by foresto** [comment]
Confirming: While attempting a [Trickle ICE test](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/)...

Chromium 83.0.4103.116 shows two host results with <uuid>.local addresses (a format I don't recognize) along with this error message:
`The server stun:157.131.249.252:57500 returned an error with code=701:
STUN server address is incompatible.`

Meanwhile, Firefox 83.0 shows two srflx and two relay results with recognizable IP addresses, and no error messages.

Both browsers are running on the same client machine, which runs linux.

A single turn: URL (with username and password) is entered in the test app.

The TURN server is a fresh coTURN installation behind a NAT router, with ports forwarded.

**Comment by fippo** [comment]
at least for the samples this has been addressed by the "Note: errors from onicecandidateerror above are not neccessarily fatal. For example an IPv6 DNS lookup may fail but relay candidates can still be gathered via IPv4" note.

**Comment by murugancmi** [comment]
@fippo we are facing srflx issue from STUN, ICE Gathering fail on chrome 100.0.4896.127 (MAc)


![Screenshot 2022-04-26 at 2 19 44 PM](https://user-images.githubusercontent.com/25261553/165261422-7ffef933-d6ee-4c1e-9446-008d7332ff1f.png)

**Comment by davidcsi** [comment]
FYI:

The error object's errorCode property is one of the numeric STUN error codes. There is one additional, WebRTC-specific, error which lies outside the valid STUN error code range: 701. Error 701 indicates that none of the ICE candidates were able to successfully make contact with the STUN or TURN server.

**Comment by fippo** [comment]
701 will also be emitted if *some* candidates could not reach the STUN server as shown in the first screenshot.
So it is only an additional signal if you fail to collect candidates.
