### ISSUE TITLE
Feature request - captured video size

### ISSUE THREAD

**Issue by aeu** [webrtc/samples#1254]
Hello,

First of all, thank you for posting this sample, it's very helpful.  

I was wondering if it would be possible to expand the sample a little showing how to make the captured video have a a larger width and height?

Thank you.

**Comment by fippo** [comment]
have you seen https://webrtc.github.io/samples/src/content/getusermedia/resolution/ ?

**Comment by aeu** [comment]
Hi @fippo ,

Thank you for the link, I'll take a look.
