### ISSUE TITLE
Error in sendChannel

### ISSUE THREAD

**Issue by smitaparna** [webrtc/samples#1261]
- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
 Chrome
##Tested on 82.0.4056.0(64 bit).
## Description
While sending the file,in java console getting error like 'Error in sendChannel'.Its coming for any file size as well as 0KB file.
Error coming for MAC,Windows,Linux

## Steps to reproduce
0. Browse to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Click the "Choose File" button
3. Select a file of any size
4. Verify that the Average Bitrate is > 0
5. Click the "Click to download $filename" link
6. Download the file, verify that it has the same size as the originally uploaded file.
7. Click the "Choose File" button
8. Select a file of size 0 bytes
9. Verify that the message "File is empty, please select a non-empty file" appears

## Expected results
File should sent successfully without any javascript  console error.

## Actual results
Error showing in javascript console
![test case 9 error](https://user-images.githubusercontent.com/61240703/75020524-38514f80-5493-11ea-8c1f-8ef0da008ae1.PNG)
![test case 9](https://user-images.githubusercontent.com/61240703/75020528-38e9e600-5493-11ea-86d1-ed585c91d2cc.PNG)

**Comment by fippo** [comment]
@alvestrand you changed that in Chrome, is this behaviour intended? Also cc @lgrahl

**Comment by smitaparna** [comment]
Same observation for Windows and MAC
Chrome
##Tested on 83.0.4094.0(64 bit).

**Comment by subhashreesahoo86** [comment]
Attaching the screenshots for tests conducted on version 83.0.4094.0 
<img width="1225" alt="Screen Shot 2020-03-31 at 4 12 46 PM" src="https://user-images.githubusercontent.com/59478163/78036476-a1699400-736a-11ea-962a-6304e5ce43d4.png">

**Comment by smitaparna** [comment]
Same observation for Windows and MAC
![image](https://user-images.githubusercontent.com/61240703/79874925-394a2300-83e9-11ea-8d22-2f260cfe974a.png)
![image (1)](https://user-images.githubusercontent.com/61240703/79874941-3ea76d80-83e9-11ea-8a16-b963f78ac0c7.png)


Chrome
##Tested on 84.0.4114.0(64 bit).

**Comment by smitaparna** [comment]
Same observation for Linux also.
##Tested on 84.0.4114.0(64 bit).
![linux-error](https://user-images.githubusercontent.com/61240703/80092121-869dd000-8562-11ea-8ae2-69d4cb83d99b.PNG)
