### ISSUE TITLE
Selenium Server version mismatch causing Nigthwatch failing to start

### ISSUE THREAD

**Issue by csikosjanos** [webrtc/samples#1264]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

The browser is not relevant, the issue relates to the tooling.

## Description

The Nightwatch configuration file points to the `./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.14.0.jar` which is not exists since the package has been updated to `"selenium-server": "^3.141.59",`.

Please note, that the problem already mentioned in the #1196 issue (not as detailed as here).

## Steps to reproduce
1. Check out the repository into an empty folder
1. Install the dependencies with `npm install`
1. Run the tests with `npm run test`

## Expected results
I expect that the tests are running and passing successfully.

## Actual results
The tests never start and failing with the following errors:
```
[14:36:55] Starting nightwatch...
   Error: Selenium Server process exited with code: 1
   Error: Unable to access jarfile ./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.14.0.jar
  
       at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
 Error: Unable to access jarfile ./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.14.0.jar
 
[14:36:56] Error: Selenium Server process exited with code: 1
    at SeleniumServer.createError (/Users/janoscsikos/Projects/sandbox/WebRTC-samples/node_modules/nightwatch/lib/runner/wd-instances/base-wd-server.js:299:15)
    at SeleniumServer.onExit (/Users/janoscsikos/Projects/sandbox/WebRTC-samples/node_modules/nightwatch/lib/runner/wd-instances/base-wd-server.js:261:22)
    at ChildProcess.emit (events.js:321:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12) {
  code: 1,
  errorOut: 'Error: Unable to access jarfile ./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.14.0.jar\n' +
    ' ',
  detailedErr: 'Error: Unable to access jarfile ./node_modules/selenium-server/lib/runner/selenium-server-standalone-3.14.0.jar\n'
}
```

**Comment by milochen0418** [comment]
I have the same issue on my mac os x. 
<img width="1048" alt="Screen Shot 2020-10-22 at 11 50 51 AM" src="https://user-images.githubusercontent.com/12568287/96822519-dbac9700-145c-11eb-906d-1e5179331c36.png">

**Comment by milochen0418** [comment]
$ rm package-lock.json
$ rm node-modules
Edit the file -- package.json 
-    "selenium-server": "^3.141.59",
+    "selenium-server": "3.14.0",

Then we can install and run it.

$ npm install 
$ npm run test

<img width="1191" alt="Screen Shot 2020-10-22 at 12 21 53 PM" src="https://user-images.githubusercontent.com/12568287/96824374-347e2e80-1461-11eb-80ff-d39c8947db30.png">

**Comment by fippo** [comment]
nightwatch is gone
