### ISSUE TITLE
Include "Perfect Negotiation" example

### ISSUE THREAD

**Issue by NasskalteJuni** [webrtc/samples#1271]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

none, the issue is about adding a sample to the existing webrtc examples

## Description

The WebRTC examples should contain a sample for a call that uses "Perfect Negotiation". 

The latest draft of WebRTC (published at December 13, 2019, see https://www.w3.org/TR/2019/CR-webrtc-20191213/ ) contains a pattern called "Perfect Negotiation" (see paragraph 10.7). 
The draft recommends usage of said pattern, the necessary methods (mostly `setLocalDescription({type: "rollback"})`) are already implemented in the current releases of the standard versions of Chrome and Firefox.
They might be still racy (see https://crbug.com/1060083 and https://crbug.com/1028969 ), but it is foreseeable that these races will be fixed in later versions in the near future.
Therefore, the WebRTC examples directory should include an example for a call that uses the Perfect Negotiation pattern. The issue has been mentioned in the discuss-webrtc google group, support to include an example regarding this topic exists.

## Steps to reproduce

Search for an example regarding perfect negotiation (there is no such example).

## Expected results

Having an example implementation for "Perfect Negotiation" which demonstrates the recommended pattern as part of the WebRTC Samples
(at least after the race conditions related to https://crbug.com/1060083 and https://crbug.com/1028969 are fixed)

## Actual results

There is no such example

**Comment by paq85** [comment]
There is an example for the "Perfect Negotiation" https://webrtc.github.io/samples/src/content/peerconnection/perfect-negotiation/ -> https://github.com/webrtc/samples/tree/9f7e3b73c6ef69232c2e14b453f7c0c528ee61a1/src/content/peerconnection/perfect-negotiation

But I have an issue with it as it's calling `pc.setLocalDescription()` without any parameter.
According to the doc this method expects `setLocalDescription(description: RTCSessionDescriptionInit): Promise<void>`.

**Comment by fippo** [comment]
there is a sample now: https://webrtc.github.io/samples/src/content/peerconnection/perfect-negotiation/
