### ISSUE TITLE
Links on the samples website are too light and hard to see

### ISSUE THREAD

**Issue by tiansh** [webrtc/samples#1297]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Firefox 75.0

## Description

Links on https://webrtc.github.io/samples/ are too light. Texts with contrast 2.53 is not such friendly. I had to select them to read.

## Steps to reproduce

Open https://webrtc.github.io/samples/ in your browser.

## Expected results

Text with higher contrast.

## Actual results

Links with color #6fa8dc

**Comment by fippo** [comment]
feel free to provide a PR. I don't think any nonstandard css is used for links
