### ISSUE TITLE
How I compile and used in my current IOS project?

### ISSUE THREAD

**Issue by AshishYadav01** [webrtc/samples#1298]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by rodmytro** [comment]
You can use Cocoapods - https://cocoapods.org/pods/GoogleWebRTC there is no need to build
