### ISSUE TITLE
Change console.log to console.error for errors

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#130]
As per #73 discussion.

**Comment by KaptenJansson** [comment]
This requires a change to adapter.js right as we use trace() from it? Should we add trace.error() and trace.log() methods?

**Comment by KaptenJansson** [comment]
or trace.info()

**Comment by samdutton** [comment]
Yes: trace() can match Console
<https://developer.chrome.com/devtools/docs/console-api> (though the
behaviour of console.info() is the same as console.log()).

**Comment by KaptenJansson** [comment]
How do you propose we do this as there are quite a lot of pages using trace().

I was thinking of adding a Trace() constructor with info() and error() methods then create a "trace" object like : "var trace = new Trace()" in adapter.js so all pages can just call on trace.info/error() directly. 
But this means we have to update all pages using currently trace(). And that means we can only fix the problem for the repos we have control over (all under webrtc/).

I guess we could leave the old trace() function and name the aforementioned constructor something else and update our pages. Then after a while we can remove trace() and rename the new one (if we want the same name).

**Comment by samdutton** [comment]
> I was thinking of adding a Trace() constructor with info() and error() methods then create a "trace" object like : "var trace = new Trace()" in adapter.js so all pages can just call on trace.info/error() directly. 



Tricky.

I think trace.info/error() is a bit messy.

What about this (see [jsbin.com/yoyejaliri/3/edit](http://jsbin.com/yoyejaliri/3/edit)):

    var Trace = function(message) {

      if (message) {

        console.log('Trace: ' + message);

      }

    };


    Trace.error = function(message) {

      console.error('Trace error: ' + message);

    };


    Trace.info = function(message) {

      console.info('Trace info: ' + message);

    };


    var trace = Trace;

    trace('plain old trace()');
    trace.error('trace.error()');
    trace.info('trace.info()');

**Comment by KaptenJansson** [comment]
Actually, there has been discussions about keeping adapter clean of utility functions not related to shimming spec difference. I suggest logging should be taken care of in each sample or create a util.js file that handles this.

**Comment by KaptenJansson** [comment]
Closing this in favor of doing a general log cleanup later if needed.
