### ISSUE TITLE
WebRTC Connection on ChromeOS disables Verizon MiFi 8800L Data Connection

### ISSUE THREAD

**Issue by SLCSTechnology** [webrtc/samples#1302]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [X] I have provided steps to reproduce
- [X] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Google ChromeOS 83.0.4103.42 (Official Build) beta (64-bit) - HP Chromebook x360 11 G1 EE

This is the device/build I personally tested with but I have had reports from staff that it affects same Chromebook model on latest ChromeOS stable build (ChromeOS 80.0.3987.162).

## Description

When starting a Google Meet or Microsoft Teams (WebRTC peer connection) video meeting the Verizon MiFi 8800L loses data connection.

## Steps to reproduce

1. Connect Chromebook to a Verizon 8800L MiFi hotspot.
2. Start a Google Meet/Microsoft Teams video meeting from Chromebook.
3. During the phase of joining the meeting, the hotspot will lose data connection.

## Expected results

Able to start a video meeting and chat and see video as usual with meeting participants.

## Actual results

Data connection on the hotspot is disconnected and you are unable to join a video meeting or browse the internet until the connection comes back up. Subsequent meeting joins also disconnect the data connection on the MiFi hotspot.

**Comment by VZdub** [comment]
They just released a patch to the dev channel for chrome OS today. https://bugs.chromium.org/p/chromium/issues/detail?id=898210

**Comment by fippo** [comment]
looks like this was fixed by the cros bugfix, please holler if that is not the case
