### ISSUE TITLE
Canvas to peer connection broken on mac

### ISSUE THREAD

**Issue by JeffCyr** [webrtc/samples#1308]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Version 81.0.4044.138 (Official Build) (64-bit)

## Description
The [Canvas to peer connection](https://webrtc.github.io/samples/src/content/capture/canvas-pc/) sample does not work on macOS Catalina Version 10.15.4

## Steps to reproduce
- Navigate to https://webrtc.github.io/samples/src/content/capture/canvas-pc/
- Move the teapot in the left tile

## Expected results
The teapot is displayed on the right tile

## Actual results
The right tile stays black

## Note
The same sample works on Windows 10 with the same Chrome version

**Comment by JeffCyr** [comment]
I just noticed that it works when navigating to the "Canvas to peer connection" from the [WebRTC samples](https://webrtc.github.io/samples/) page.

But it doesn't work if it's opened from [Google Search](https://www.google.com/search?q=canvas+to+peer+connection)

**Comment by leaysgur** [comment]
Using `Incognito` mode also reproduce this.

I submitted a PR to solve this by adding `muted` attribute to `video` element.
