### ISSUE TITLE
No ReadMe with proper steps to run the Sample Application

### ISSUE THREAD

**Issue by rugved-mahamune** [webrtc/samples#1311]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Expected results
There must be a updated ReadMe file which provides steps to run the project

## Actual results
No Instrutions found

**Comment by alvestrand** [comment]
What do you mean by "run the project"?

**Comment by rugved-mahamune** [comment]
By running the Project I mean steps to run the sample project. There are many places where I was blocked when trying to run the Sample project.

**Comment by turivishal** [comment]
Requires steps to run project in my local machine, 
what will be the commands i have to run after setup in folder
for example first would be "npm install" second will be "node  web_server/server.js", its started running in cmd but i opened in browser its not showing anything.
same requests:
https://github.com/webrtc/samples/issues/1339
https://github.com/webrtc/samples/issues/1239
https://github.com/webrtc/samples/issues/1204
