### ISSUE TITLE
getdisplaymedia is not recording audio in Google Chrome browser.

### ISSUE THREAD

**Issue by swayaminfotech** [webrtc/samples#1315]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Google Chrome (Any version)

## Description
I am trying to capture screens along with recording audio using code as in `getdisplaymedia` sample, I have updated code to record audio along with screen capturing but is not recording audio.

Here is a code snippet that I have update:

static _startScreenCapture() {
    if (navigator.getDisplayMedia) {
      return navigator.getDisplayMedia({video: true,audio:true});
    } else if (navigator.mediaDevices.getDisplayMedia) {
      return navigator.mediaDevices.getDisplayMedia({ 
      video: {
        cursor: "always"
      },
      audio: {
        echoCancellation: true,
        noiseSuppression: true,
        sampleRate: 44100
      }
    });
    } else {
      return navigator.mediaDevices.getUserMedia({video: {mediaSource: 'screen'},audio:true});
    }
  }

## Steps to reproduce
1. Goto: https://dev.ceranote.com/media/
2. Click on Start Capturing.
3. Select any screen.

## Expected results
It should record audio along with the captured screen.

## Actual results
It is not recording audio with the captured screen.

**Comment by guest271314** [comment]
Media Capture Screen Capture specification does not mandate implementation of audio capture https://github.com/w3c/mediacapture-screen-share/issues/140.

**Comment by fippo** [comment]
Not an issue with the samples and there have been some improvements since, closing
