### ISSUE TITLE
"https://webrtc.github.io/samples/src/content/getusermedia/volume" page is not working as intended

### ISSUE THREAD

**Issue by subhashreesahoo86** [webrtc/samples#1317]
## Browser affected
Google Chrome | 85.0.4170.0 (Official Build) (64-bit)
-- | --
Revision | c4613390bc059d8aab9d57828847f77fd0c0ef47-refs/branch-heads/4170@{#1}
OS | macOS Version 10.15.4 (Build 19E287)

## Description
https://webrtc.github.io/samples/src/content/getusermedia/volume Page is not working as intended.

## Steps to reproduce
1. Launch https://webrtc.github.io/samples/src/content/getusermedia/volume on Chrome Browser.
2. Warning message observed in the console  "main.js:23 The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu"

## Expected results
When user speaks, the volume of the local media streams should fluctuate.

## Actual results
When user speaks, the volume of the local media streams do not fluctuate

**Comment by smitaparna** [comment]
Same observation for Linux.
* Build ver.- 85.0.4170.0

**Comment by smitaparna** [comment]
Same observation for Chrome Book.
Build ver- 85.0.4176.0
