### ISSUE TITLE
Misplaced HTML tag in "Getting started with media devices" guide? 

### ISSUE THREAD

**Issue by kimberleehowley** [webrtc/samples#1319]
# Checklist
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected
Chrome 83.0.4103.106 

## Description
In the last code snippet on the "Getting started with media devices" guide, a `<title>` tag closes with a </video> tag instead of a `</title>` tag. 

I tested the code snippet out in a repl.it to see if it still worked despite the tags, but it did not work until I changed the tag to be a corresponding `</title>`. 

## Steps to reproduce
1. In your browser, head to: https://webrtc.org/getting-started/media-devices
2. Scroll to the bottom of the page. 
3. Spot the mismatched closing tag in line two: 
![Screen Shot 2020-06-24 at 3 58 01 PM](https://user-images.githubusercontent.com/28582074/85635779-9b1a4980-b633-11ea-826e-72077e311e63.png)
4. Head to this repl.it: https://repl.it/@kimberlee/KindFirmAutocad#index.html 
5. Notice nothing is on the page. 
6. Change line 5 to close with `</title>` instead of `</video>`. 
7. An element with a potential video stream now populates the page. 

## Expected results
I expected the sample code would've worked automatically when I copy/pasted it. 

## Actual results
But, the mismatched closing tag prevented that from happening. 

## Question about contributing
I tried to head over to find a repo to contribute to these docs and guides, but all I could find was the deprecated, Jekyll powered WebRTC.org repo. 

Is there a better place where I could contribute to documentation? I would've been happy to push a fix for this typo, if I could've more quickly found where to do so. I tried getting the native code up and running but quickly realized that was the wrong place. 

Thank you!

**Comment by fippo** [comment]
assigning to henbos who sometimes finds the magic edit button

**Comment by fippo** [comment]
Harald, while your memory of how to fix things is fresh... ;-)

**Comment by alvestrand** [comment]
CL sent for review.

**Comment by alvestrand** [comment]
Fixed. (I haven't checked that copy/paste/run on the code works, though)
