### ISSUE TITLE
travis no longer reports back

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#1330]
travis doesn't report back, probably due to the removal of the old stuff described in 
  https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154

@samdutton since @alvestrand is not an owner but you added the .travis.yml...  can you please
1) login to travis, disable it for this repository and re-enable it
2) check the protected branches

If you can also figure out how to make Harald and/or @MirkoBonadei travis admins that would be even better, then we don't need to bug you all the time

**Comment by samdutton** [comment]
Is this still malfunctioning? I've tried a few things: updating the WebHook, etc. 

MirkoBonadei and Harald are already repo owners, so I think they should be able to tweak the Travis settings (but I may be wrong).

**Comment by fippo** [comment]
i *think* (but things are a bit unclear) the repo needs to be migrated to travis-ci.com as described here:
  https://docs.travis-ci.com/user/migrate/open-source-repository-migration
That would explain why things don't show up...

**Comment by fippo** [comment]
Looks like hitting the reset button worked! [This PR](https://github.com/webrtc/samples/pull/1333) passed so I think we're good. Will push old PRs and confirm...

**Comment by fippo** [comment]
Fixed by "reboot". Yay!
