### ISSUE TITLE
Frame loss when recording in mobile browser ..

### ISSUE THREAD

**Issue by sr1dh4r** [webrtc/samples#1331]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Chrome 83.0.4103.106

## Description

Frames are lost in the recording.

## Steps to reproduce

Testing:

Open https://webrtc.github.io/samples/src/content/getusermedia/record/ link in mobile chrome browser on android.

## Expected results

Recording should be available without any frame drop.

## Actual results

Recording has a lot of frame loss.

**Comment by fippo** [comment]
this is a browser issue, not a issue with the samples
