### ISSUE TITLE
Want to discuss if mobile devices switch from wifi to 4G, is there a better solution than renegotiation?

### ISSUE THREAD

**Issue by zeijibashuai** [webrtc/samples#1340]
- Want to discuss if mobile devices switch from wifi to 4G, is there a better solution than renegotiation?

**Comment by fippo** [comment]
Please use the discuss-webrtc mailing list indicated in the template you deleted for discussions.

**Comment by hthetiot** [comment]
@zeijibashuai you asked the same question here https://github.com/muaz-khan/WebRTC-Experiment/issues/686#issuecomment-672841143

You are a bot or what?
