### ISSUE TITLE
Provide a unified stats interface in adapter.js

### ISSUE THREAD

**Issue by bemasc** [webrtc/samples#135]
Currently, adapter.js makes no attempt to unify the getStats behavior between different browsers.   Now that the standard seems to be settling on a stats format, adapter.js should attempt to provide it.

This work item does not include munging the names of any stats keys.  The goal is only to provide a unified, browser-independent access method.

**Comment by juberti** [comment]
Now tracked in https://github.com/webrtc/adapter/issues/5
