### ISSUE TITLE
Active maintainers for this project

### ISSUE THREAD

**Issue by lgrahl** [webrtc/samples#1350]
WebRTC examples are important for WebRTC. As we can see from the amount of issues and PRs piling up, there clearly is an issue with maintenance, even if it's just closing issues and marking them as *this doesn't concern the examples, it concerns WebRTC itself*.

There are a bunch of WebRTC devs out there that have the experience to maintain these examples. I think we just need to call them out and find some of them that would be willing to help. If they have the time (don't be afraid to say "no"), all you need to do is add them as maintainers. I'll start calling out a couple of folks that just occurred to me and those mentioned may /cc more:

@fippo @sean-der @nils-ohlmeier @jlaine @jan-ivar 

Speaking for myself: I'm willing to spend a little bit of time to maintain at least the data channel examples of this repo and resolving piled up issues.

**Comment by fippo** [comment]
tagging @alvestrand @KaptenJansson (welcome back!)

After the drama in #1096 (two years ago) or the website (https://github.com/webrtc/webrtc-org/issues/246) I am not available unless there is project governance  that prevents such unilateral actions.

**Comment by lgrahl** [comment]
No interest in resolving this?

**Comment by Sean-Der** [comment]
Thanks for starting this @lgrahl. I would love to take this on. I could also drag some more devs into this. Before I get involved I would really like to see the following though.

### Project Governance
WebRTC is a protocol, and belongs to the internet. We should have representation from lots of individuals and projects. I would love for everyone to have an equal voice. [The Internet is for End Users](https://tools.ietf.org/html/draft-nottingham-for-the-users-09)

### More respect for user, educate not just talk about APIs
http://webrtc.org only talks about Javascript APIs. I want to re-work this to help people learn about everything else that exists. We don't have to talk about anything specific. I am trying to do this with [WebRTC for the Curious](https://webrtcforthecurious.com). I would even be fine with transferring this to the webrtc GitHub if we can help others.

I build stuff with WebRTC all day, and never use a browser. Mostly IoT/Protocol Bridging and CDN Ingestion. I want to make this more accessible and have these use cases represented.

---- 

To be blunt I am afraid that I am going to maintain this repo, and only be used to further other peoples goals. I would love to be a greater part of Google's WebRTC project here though.

**Comment by KaptenJansson** [comment]
FYI native webrtc documentation can be found near the code since a while back (also linked from https://webrtc.org/support/overview via the Native documentation link, yeah not easy to find but it's there) at https://webrtc.googlesource.com/src/+/refs/heads/master/docs/native-code/index.md.

It is obviously only focused on getting the code and building it but with weaker samples/demos compared to the web.

**Comment by fippo** [comment]
we're in a much better state now and have an escalation path in case of vandalism
