### ISSUE TITLE
Soundmeter.js uses deprecated createScriptProcessor

### ISSUE THREAD

**Issue by tommedema** [webrtc/samples#1353]
At https://github.com/webrtc/samples/blob/5033b81d0e3984179cfeb03b5089f2eb705202db/src/content/getusermedia/volume/js/soundmeter.js#L21 createScriptProcessor is used which was [deprecated](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/createScriptProcessor) back in 2014

**Comment by scarrington76** [comment]
Having the same issue

**Comment by fippo** [comment]
duping into #1509
