### ISSUE TITLE
 Stream from a video to a peer connection - doesn't work

### ISSUE THREAD

**Issue by xunhuang** [webrtc/samples#1355]
tested on Chrome 85.0.4183.102 (Official Build) (64-bit) on Mac OS. 

- [ x] I have provided steps to reproduce
- [ x] I have provided browser name and version
- [ x] I have provided a link to the sample here or a modified version thereof

## Browser affected

 Chrome 85.0.4183.102 (Official Build) (64-bit) on Mac OS. 

## Description
the mirroring video pane is black and not updated. 

## Steps to reproduce

https://webrtc.github.io/samples/src/content/capture/video-pc/ 

## Expected results

expect video window on the right to load. 

## Actual results

![image](https://user-images.githubusercontent.com/729879/93129571-149b6400-f686-11ea-84cc-b2be9435f4bd.png)

**Comment by fippo** [comment]
looks like an autoplay issue...

**Comment by xunhuang** [comment]
actually it's my own issue. One of my Chrome extensions interfered. I deleted all my extension and it started to work. that said, I didn't keep track of which one exactly was causing the problem. Closing.
