### ISSUE TITLE
Stream from a video to a peer connection does not work on localhost

### ISSUE THREAD

**Issue by bugb** [webrtc/samples#1358]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Version 80.0.3987.132 (Official Build) (64-bit)** on Windows OS with **Experimental Web Platform features** enabled

## Description
Can not make demo **Stream from a video to a peer connection** works on localhost

The source code is located at:
```
https://webrtc.github.io/samples/src/content/capture/video-pc/
```
## Steps to reproduce
1. Get the source code from here: https://webrtc.github.io/samples/src/content/capture/video-pc/

2. Setup Chrome with **Experimental Web Platform features** enabled

3. Click on `index.html` file and open with Chrome
## Expected results
The demo should work as expected here: https://webrtc.github.io/samples/src/content/capture/video-pc/

## Actual results
Got the error:

```
main.js:30 Uncaught DOMException: Failed to execute 'captureStream' on 'HTMLMediaElement': Cannot capture from element with cross-origin data
    at HTMLVideoElement.maybeCreateStream 
```

![image](https://user-images.githubusercontent.com/9280412/94044321-2dc7b180-fdf8-11ea-9dc4-b9e21b34b8b1.png)

**Comment by fippo** [comment]
This should work when you use a http server (e.g. `python -m SimpleHTTPServer`) to serve the samples. `file://` is special.

**Comment by bugb** [comment]
thank let me try it @fippo

**Comment by guest271314** [comment]
This will work at `file:` protocol at Chromium by downloading chrome.webm and chrome.mp4 to the same directory as index.html videos and launching with `--allow-file-access-from-files` flag. However, at Nightly 83 the remote video is only rendering "black frames".

**Comment by guest271314** [comment]
`this` within

```
rightVideo.onloadedmetadata = () => {
  console.log(`Remote video videoWidth: ${this.videoWidth}px,  videoHeight: ${this.videoHeight}px`);
};
```

is `window`, not the `HTMLVideoElement`, due to arrow function, should be

```
rightVideo.onloadedmetadata = () => {
  console.log(`Remote video videoWidth: ${rightVideo.videoWidth}px,  videoHeight: ${rightVideo.videoHeight}px`);
};
```
