### ISSUE TITLE
End To End Encryption example throws error in Chrome Canary

### ISSUE THREAD

**Issue by swasunb** [webrtc/samples#1359]
Running https://webrtc.github.io/samples/src/content/peerconnection/endtoend-encryption/ sample in Chrome Canary fails with the following error

Uncaught TypeError: Failed to execute 'postMessage' on 'Worker': Value at index 0 does not have a transferable type.
    at setupSenderTransform (main.js:110)
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.call (main.js:145)

**Comment by fippo** [comment]
Canary and M86 don't support transferable streams yet.

**Comment by swasunb** [comment]
Is it behind some flag now?
