### ISSUE TITLE
WebRTC camera stream is crashing if embedded with YouTube video on the same page

### ISSUE THREAD

**Issue by Smithangshu** [webrtc/samples#1367]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Android 86.0.4240.99(Latest)
Mozilla/5.0 (Linux; Android 9; Redmi Note 5 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.99 Mobile Safari/537.36 via https://thismachine.info

## Description
WebRTC camera feed is crashing and video element turn black after few seconds of playing embedded YouTube video on the same page.

## Steps to reproduce
1.First start the WebRTC camera stream feed
2.Then start embedded YouTube video
3.Video element showing WebRTC feed will turn black and on console it can be seen stream status turned inactive

## Expected results
It should play both the video like every other browser like Firefox Android, Opera etc.

## Actual results
WebRTC camera feed is crashing and video element turn black after few seconds of playing embedded YouTube video on the same page. After that on console I can see stream status is inactive.

***Note: Please try with this page https://codepen.io/smithangshu/pen/abZmZrR on Chrome Android 86.0.4240.99(Latest) and follow above steps you can reproduce the issue and if you start the YouTube video first and then the WebRTC feed then it will work perfectly but otherwise it wont. Moreover, I checked with Chrome Android 80.0.3987.99 and it works there correctly.

**Comment by guidou** [comment]
Tracked in https://crbug.com/1140477
