### ISSUE TITLE
End to End encryption example throws error in Chrome beta(87) and chrome canary(v88)

### ISSUE THREAD

**Issue by swasunb** [webrtc/samples#1369]
Uncaught (in promise) DOMException: RTCEncodedVideoFrame object could not be cloned.
Uncaught (in promise) DOMException: RTCEncodedAudioFrame object could not be cloned.
Uncaught (in promise) DOMException: RTCEncodedVideoFrame object could not be cloned.

**Comment by swasunb** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1142519

**Comment by guidou** [comment]
Thanks for reporting!
Closing since this is a bug in Chromium, not the sample.
