### ISSUE TITLE
Pr-answer page throws 404() error on load

### ISSUE THREAD

**Issue by smitaparna** [webrtc/samples#1370]
##Browser affected
Chrome(88.0.4302.0) MAC and Windows
**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome(88.0.4302.0)

## Description
Pr-answer throws error on load, 
showing error in the console. Getting the below error msg.
Failed to load resource: the server responded with a status of 404()  

## Steps to reproduce
Objective: Ensure remote video is seen

0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Check if the local video is seen in the left pane
3. Press "Call"
4. Press "Accept"
5. Press "Hang up"

## Expected results
Expected result:
Step 3: After accepting the call, the remote video in the right pane should be seen
Step 5: After hanging up, the remote video in the right pane should be seen black

## Actual results
We can see remote video. But on load of the page, we are getting the 404() error in the console.
![pr-answer](https://user-images.githubusercontent.com/61240703/97999968-3eeae180-1dec-11eb-8d0f-8a6d36a7c5f9.PNG)

![pr-answer1](https://user-images.githubusercontent.com/61240703/98001898-f16f7400-1ded-11eb-9162-bd2341e64083.PNG)

**Comment by smitaparna** [comment]
same observation in Linux too.(Chrome build - 88.0.4300.0)

**Comment by subhashreesahoo86** [comment]
Similar error observed for 
Google Chrome	88.0.4305.0 (Official Build) dev (64-bit)
Revision	220a8ec906c0a0787582039399e6674344446932-refs/branch-heads/4305@{#1}
Platform	13560.0.0 (Official Build) dev-channel eve

**Comment by smitaparna** [comment]
same observation in Chromebook-drallion too.(Chrome build - 88.0.4314.0)

**Comment by smitaparna** [comment]
Similar observation for Windows and Linux(Chrome ver-89.0.4356.6)

**Comment by subhashreesahoo86** [comment]
Similar observation for 

Google Chrome | 90.0.4412.3 (Official Build) (x86_64) 

OS | macOS Version 11.2.1 (Build 20D74)

**Comment by smitaparna** [comment]
Same observation in 91.0.4455.2 build in windows and Linux

**Comment by subhashreesahoo86** [comment]
Same observation in 91.0.4455.2 build in Mac OS(X86_64)

**Comment by smitaparna** [comment]
Same observation in 91.0.4459.0 in chrome book ezkinil

**Comment by smitaparna** [comment]
Same observation in 91.0.4456.0 in chrome book drallion

**Comment by smitaparna** [comment]
Same observation in 92.0.4496.3 in windows.

**Comment by smitaparna** [comment]
Same observation in 92.0.4496.3 in linux

**Comment by smitaparna** [comment]
Same observation in chromebook drallion too.
Chrome ver(92.0.4502.0)

**Comment by smitaparna** [comment]
Same observation in 93.0.4549.3 in windows.

**Comment by smitaparna** [comment]
Same observation in 94.0.4590.0 in windows, Mac

**Comment by smitaparna** [comment]
Same observation in chromebook drallion too.
Chrome ver(94.0.4588.0)

**Comment by smitaparna** [comment]
Same observation in linux- chrome-94.0.4595.0

**Comment by smitaparna** [comment]
Same observation in 95.0.4621.4 in windows,linux.

**Comment by smitaparna** [comment]
Same observation in 95.0.4631.0 in Chrome book Ezkinil

**Comment by hthetiot** [comment]
A 404 will not be fixed by browser update, here it's simply a missing stylesheet main.css and until it is fixed it will not change even if browser is updated.

**Comment by hthetiot** [comment]
The missing main.css is linked here: https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/pr-answer/index.html#L27

Making a PR to remove this line would fix the issue and would be more productive than reporting the issue with each chrome version in my point of view.

**Comment by smitaparna** [comment]
Still getting 404 error in console. Harold Thétiot is that changes have pushed ?

**Comment by fippo** [comment]
already reported in #1165. It is amazing to see so many comments on something that is trivial to fix.
