### ISSUE TITLE
Multiple javascript console errors are found while loading "iframe-apprtc" Page.

### ISSUE THREAD

**Issue by subhashreesahoo86** [webrtc/samples#1371]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Google Chrome | 88.0.4302.0 (Official Build) (x86_64)
-- | --
Revision | 7ad99dde6ddb11ea20090a50f6b7963e53bc172d-refs/branch-heads/4302@{#1}
OS | macOS Version 10.15.7 (Build 19H2)

## Description
'https://webrtc.github.io/test-pages/src/iframe-apprtc/' page gives 404 error while loading the page

## Steps to reproduce

0. Browse to https://webrtc.github.io/test-pages/src/iframe-apprtc/ on one machine and https://appr.tc/ in another.
1. Enter the room name from the first machine on the 2nd machine.
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
-- | --

## Expected results
No Javascript console error should be present.

## Actual results
Getting below error in Javascript console 
"Failed to load resource: the server responded with a status of 404 [()"]
"Blocked autofocusing on a <input> element in a cross-origin subframe."

<img width="1440" alt="Screen Shot 2020-11-04 at 2 34 32 PM" src="https://user-images.githubusercontent.com/59478163/98119763-5938c400-1ead-11eb-9a03-eddeb8e5aa00.png">

**Comment by subhashreesahoo86** [comment]
![Uploading Screen Shot 2020-11-04 at 2.34.32 PM.png…]()

**Comment by smitaparna** [comment]
getting the same error for windows (chrome build-88.0.4302.0) and linux( chrome build- 88.0.4300.0)

**Comment by subhashreesahoo86** [comment]
Similar error is observed for 
Google Chrome	88.0.4305.0 (Official Build) dev (64-bit)
Revision	220a8ec906c0a0787582039399e6674344446932-refs/branch-heads/4305@{#1}
Platform	13560.0.0 (Official Build) dev-channel eve

**Comment by smitaparna** [comment]
Similar observation for chromebook drallion(Chrome ver-88.0.4314.0)

**Comment by smitaparna** [comment]
Similar observation for Windows and Linux(Chrome ver-89.0.4356.6)

**Comment by smitaparna** [comment]
Same observation in 91.0.4455.2 build in windows and Linux

**Comment by smitaparna** [comment]
Once the other participant joining the meeting, getting 404 error in the console. Please find the attached screenshot.

![Screenshot from 2021-03-30 15-38-22](https://user-images.githubusercontent.com/61240703/112998562-70cf5c80-916e-11eb-939c-c4b6fde1a161.png)

**Comment by smitaparna** [comment]
Same observation in 91.0.4459.0 in chrome book ezkinil

**Comment by smitaparna** [comment]
Same observation in 91.0.4456.0 in chrome book drallion

**Comment by smitaparna** [comment]
Same observation in 92.0.4496.3 in windows.

**Comment by subhashreesahoo86** [comment]
Same observation for 
Google Chrome | 92.0.4496.0 (Official Build) (x86_64)
Revision | 86a34de5547cdf78c183dca7bd23bdd9cbe89513-refs/branch-heads/4496@{#1}
OS | macOS Version 11.2.3 (Build 20D91)

**Comment by smitaparna** [comment]
Same observation in 92.0.4496.3 in Linux.

**Comment by smitaparna** [comment]
Same observation in chromebook drallion too.
Chrome ver(92.0.4502.0)

**Comment by smitaparna** [comment]
Same observation in 93.0.4549.3 in windows.

**Comment by smitaparna** [comment]
Same observation in linux- chrome-93.0.4557.4

**Comment by smitaparna** [comment]
Same observation in 94.0.4590.0 in windows.

**Comment by smitaparna** [comment]
Same observation in chromebook drallion too.
Chrome ver(94.0.4588.0)

**Comment by smitaparna** [comment]
Same observation in linux- chrome-94.0.4595.0

**Comment by smitaparna** [comment]
Same observation in 95.0.4621.4 in windows and linux

**Comment by smitaparna** [comment]
Same observation in 95.0.4631.0 in Chrome book Ezkinil

**Comment by hthetiot** [comment]
@smitaparna are you a bot ?
This kind of error will not desappear with browser update, for example autofocus in subframe is normal error due the sample environment and should not be considered as a bug since it's simply triggered as a security measure to prevent click jacking.

**Comment by smitaparna** [comment]
Thanks for your clarification. Will you please update the status of the bug as Won't fix or WAI .

**Comment by hthetiot** [comment]
> Will you please update the status of the bug as Won't fix or WAI

I'm not the owner or maintainer of this project, I simply subscribed to this repository notifications and I was getting annoyed by received noise.
