### ISSUE TITLE
new sample: video processing with insertable streams

### ISSUE THREAD

**Issue by dogben** [webrtc/samples#1377]
Per https://github.com/webrtc/samples/blob/gh-pages/CONTRIBUTING.md, I'm filing an issue to discuss a new sample that I would like to add.

I'm working on a sample using the new API described in https://github.com/w3c/mediacapture-insertable-streams for video.

Eventually I'd like to import the new sample as a Chrome perf test, similar to several others mentioned in this file: https://source.chromium.org/chromium/chromium/src/+/master:tools/perf/page_sets/update_webrtc_cases

The general idea for the sample is to allow applying various transforms to a video track. To cover common use cases, the source of the video track could be getUserMedia, a video element, canvas capture, or a peer connection, the transform could use canvas 2D, WebGL, or stream controls, and the destination could be a video element, peer connection, or canvas via 2D or WebGL APIs.

**Comment by dogben** [comment]
Initial draft in #1378. I wasn't able to figure out how to run the Nightwatch tests, so there's no unit test there.

**Comment by guidou** [comment]
The sample landed. Closing this issue.
