### ISSUE TITLE
FIREFOX TIAS problem. Not respecting the setted bitrate

### ISSUE THREAD

**Issue by Scoserix** [webrtc/samples#1389]
Following the example https://webrtc.github.io/samples/src/content/peerconnection/bandwidth/ .

Chrome, Opera, Edge are fine.

Mozilla seems instead to don't care about the restriction sending at way higher bitrates.

**Comment by fippo** [comment]
it seems to be a bit finicky but seems to work in general:
![image](https://user-images.githubusercontent.com/289731/101648421-15038b00-3a3a-11eb-976e-f90f8c42fba0.png)
Note that setParameters should be used, not TIAS.

cc @jan-ivar

**Comment by jan-ivar** [comment]
Oh my, that samples code looks like it needs a serious overhaul. We shouldn't be promoting feature-detection and SDP-munging in 2020 IMHO.

`maxBitrate` in Firefox appears to work in https://blog.mozilla.org/webrtc/fiddle-week-downscale-video-peerconnection/ (with some help from adapter on `setParameters` compliance)

**Comment by fippo** [comment]
The sample does *not* prefer sdp munging. When it does fall back to it, it does so in ways which are perfectly spec-compliant.
Detecting browsers and browser versions remains the daily bread of webrtc development even in 2020.

**Comment by Scoserix** [comment]
First of all, thank you for your answers.

The sample does look to work, but in my real situation something is off.

My video ideal constraints are 320x240 with framerate min 1, max 15.

I give 250kb for the video and 100kb for the audio modifying the sdp. (AS for every browser except Mozilla, where I do use TIAS).

Fun fact, Mozilla doesn't like the resolution (https://webrtchacks.github.io/WebRTC-Camera-Resolution/) .. 

Mozilla is sending on the 62 version at 700kb, on the latest version at 2.5mb

I just saw that the latest version is sending a 1280x720.

I guess that could be the problem. I just can't set the resolution that I want on mozilla, hes probably forced to send that high resolution video.

(Btw I'm not ignoring the fact that you sayd me to use the setParameters)

**Comment by jan-ivar** [comment]
> Detecting browsers and browser versions remains the daily bread of webrtc development even in 2020.

That belongs in [adapter](https://github.com/webrtcHacks/adapter), not samples IMHO. Where are people supposed to turn for simple WebRTC examples?

Stuff like this is a barrier to entry,  and why WebRTC is considered overly complicated.

**Comment by jan-ivar** [comment]
> Fun fact, Mozilla doesn't like the resolution

See the blog post. This is [bug 1286945](https://bugzilla.mozilla.org/show_bug.cgi?id=1286945).
