### ISSUE TITLE
Is it possible to connect IP camera and capture image

### ISSUE THREAD

**Issue by bhushan90** [webrtc/samples#1392]
I am working on a project where I have to detect a camera which is conncted by IP address.

Is there any way to handle that?

**Comment by guest271314** [comment]
Can you provide more details?

**Comment by bhushan90** [comment]
I have two cameras one is a webcam and another is an IP camera.
A web camera is detected by this project but the IP camera is not detecting
Is there any way to solve this problem.

**Comment by guest271314** [comment]
I am still not sure what an "IP camera" is?

**Comment by bhushan90** [comment]
The external camera which we can connect to machine using IP address.

**Comment by guest271314** [comment]
How do you currently view the camera?

**Comment by bhushan90** [comment]
Sorry @guest271314  I did not understand your question

**Comment by guest271314** [comment]
How do you currently render the remote camera locally?

**Comment by guest271314** [comment]
Two possible options include

- Creating a virtual camera, writing to the device, capturing the device after writing starts using `navigator.mediaDevices.getUserMedia({video: true})`, then selecting the virtual camera `deviceId`, stopping the default stream, setting `exact` `deviceId` and capturing the virtual device.

- Using `ffplay`, `vlc`, or `mpv`, or the means you are currently using, to stream the camera using the IP address that you have, then capturing the application window using `navigator.mediaDevices.getDisplayMedia()`.

**Comment by hthetiot** [comment]
Other solution:

- Generate an RTMP stream from IP camera, push the RTMP stream into a SIP call and have the WebRTC peer connect to SIP server to join the call that broadcast the RTMP.

This can be done easily using JsSip and Freeswitch.

**Comment by guest271314** [comment]
See https://flashphoner.com/browser-based-webrtc-stream-from-rtsp-ip-camera-with-low-latency/

**Comment by joinwen** [comment]
capture virtual camera stream by web, I also have the problem

**Comment by fippo** [comment]
closing as this is not an issue with the samples
