### ISSUE TITLE
input-output sample failing when changing video source

### ISSUE THREAD

**Issue by SergioFaustino** [webrtc/samples#1397]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Chrome 87.0.4280.101

## Description
The issue is within the sample: https://webrtc.github.io/samples/src/content/devices/input-output/ 
Open the link in my mobile (S20) with android 11 and I can see the available cameras (4) in the "video source" list.
When changing/selecting a different camera the application blocks.

I have used incognito mode and given permission to access camera.

## Steps to reproduce
Open: https://webrtc.github.io/samples/src/content/devices/input-output/
Select "video source"
Change source and the browser freezes.

## Expected results
Select all available cameras without blocking

## Actual results
Browser gets frozen when changing video source.

**Comment by fippo** [comment]
known issue, see https://bugs.chromium.org/p/chromium/issues/detail?id=1138823#c8
Should be fixed in Chrome 88
