### ISSUE TITLE
munge-sdp ok with Firefox but now with Chrome!

### ISSUE THREAD

**Issue by DanieleRatti** [webrtc/samples#14]
I noticed that after a lot of attempts this demo still not working on chrome but it's working fine with firefox, and don't understand why!
In chrome i just see a black screen.
(Tried both in local and in remote official demo)

**Comment by juberti** [comment]
Is this still a problem?

**Comment by KaptenJansson** [comment]
Closing this for now as it works for me. Please let me know if it's still an issue + attach logs.
