### ISSUE TITLE
When main thread is blocked, then audio/video is paused in end to end encryption example

### ISSUE THREAD

**Issue by swasunb** [webrtc/samples#1409]
# Please read first!
Link to discussion in [discuss-webrtc](https://groups.google.com/g/discuss-webrtc/c/XSpU6ghoFYY).

- [ x ] I have provided steps to reproduce
- [ x ] I have provided browser name and version
- [ x ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Chrome: 87.0.4280.141 

## Description

When the main thread is clogged with some operation, then audio/video is paused for a while in the end to end encryption example.
 Could it be to do with Transferable streams ? Is there any best practices around that?

## Steps to reproduce
1. Use forked https://github.com/swasunb/samples/tree/gh-pages/src/content/insertable-streams/endtoend-encryption
2. Start a call
3. Open dev tools
4. Click on start clogging

## Expected results
Clogging main thread, should not stop the media flow.

## Actual results
Clogging main thread, freezes video/audio

**Comment by alvestrand** [comment]
This is expected behavior as long as you keep processing on the main thread.
The way to work around it is to move processing to a worker, and transfer the streams to the worker.
@guidou @dogben - we need to provide a sample that uses a worker. Do we have one?

**Comment by swasunb** [comment]
@alvestrand thank you for the reply.

I can see that the above example uses worker, and transfers the streams to a worker.
https://github.com/swasunb/samples/blob/gh-pages/src/content/insertable-streams/endtoend-encryption/js/main.js#L114

**Comment by guidou** [comment]
Even using a worker, Chromium uses the main thread is still used to transfer frames to the worker, which is probably what is happening if you're already using a worker and your main thread is very busy.
We're working on an optimization to avoid using the main thread at all when a worker is used. 
crbug.com/1103280 is tracking this on the Chromium side.

**Comment by swasunb** [comment]
Any idea when will this fix make to Chrome stable?

**Comment by swasunb** [comment]
@guidou  any idea if this is fixed?

https://bugs.chromium.org/p/chromium/issues/detail?id=1103280 seems to be blocked by  https://bugs.chromium.org/p/chromium/issues/detail?id=114639

But the latter has been fixed.

**Comment by guidou** [comment]
Yes, we are planning to fix this soon.

**Comment by swasunb** [comment]
Do you have a version, in which it would be available by any chance?

**Comment by fippo** [comment]
please use the chrome bug for discussion (and no, this is still not fixed for video)
