### ISSUE TITLE
ambiguous word "best"

### ISSUE THREAD

**Issue by ricksentam** [webrtc/samples#1417]
```for the word "best", it doesn't have any indication to define "best" media experience. is it a too subjective word? may i suggest to delete it or define it ?```

https://github.com/webrtc/samples/blob/59a335a23c5c5d9a55edc5dfae70f2ade8975ea8/src/content/extensions/multipleroutes/src/_locales/en/messages.json#L3

**Comment by guest271314** [comment]
What substitute language do you suggest? 

"most performant" is used in the same message, though could also be construed as ambiguous without clear criteria as to what "performant" means.

**Comment by juberti** [comment]
"most likely to have the minimum RTT" is what is meant by "best"
