### ISSUE TITLE
WebRTC(iOS): local video is not getting stream on remote side

### ISSUE THREAD

**Issue by JumpJumpSparrow** [webrtc/samples#1422]
![截屏2021-02-09 上午11 06 21](https://user-images.githubusercontent.com/11475386/107311262-f9b00d00-6ac8-11eb-9667-639a0992e744.png)

  RTC_OBJC_TYPE(RTCVideoSource) *source = [_factory videoSource];
in Google Official Demo, the 'RTCVideoSource' instance gonna be release when 'createLocalVideoTrack' executed,
just retain the instance and the rest things are OK

**Comment by fippo** [comment]
wrong repository, if this still persists file an issue over at https://bugs.chromium.org/p/webrtc/issues/list
