### ISSUE TITLE
Unable to 'npm install' on Apple Silicon MacBook

### ISSUE THREAD

**Issue by izzyzizou** [webrtc/samples#1431]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**
## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Safari 14.0.3 (16610.4.3.1.7)

## Description

When trying to install packages I am running into "Only Mac 64 bits supported" error message. See image below.

## Steps to reproduce

Clone Samples repo to local and do 'npm install' to install packages specified in package.json.

## Expected results

Should be able to install node_modules successfully.

## Actual results

Running into "Only Mac 64 bits supported" error message.

<img width="327" alt="Screen Shot 2021-03-30 at 3 16 23 PM" src="https://user-images.githubusercontent.com/9014499/113044971-45e40900-916c-11eb-9bc8-6450b046dec3.png">

**Comment by olkotz** [comment]
Hello @izzyzizou, i have the same problem with my Mac, you ware able to solve this problem?

Thank you so Much!!!

**Comment by AlexRetortJS** [comment]
I also have this problem 😢  it seems to be node_modules/chromedriver that is causing the issue on my Mac. Has anyone been able to fix this?

**Comment by Joeychen80627** [comment]
same problem...

**Comment by stunninglaw** [comment]
Guys, if you go in package.json you can edit the version of Chrome you want to install. I had an old version in the previous file, changed it manually and now it works. 
change `"chromedriver": "^80.0.0"`,  to `"chromedriver": "^98.0.0" `
Hope it helps.
