### ISSUE TITLE
works only when both devices are connected to the same network (ie: same wifi)

### ISSUE THREAD

**Issue by sbendahan** [webrtc/samples#1446]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Description
connect your phone to 4G data service. Connect Linux PC to WIFI

**Comment by alvestrand** [comment]
What is it that works only when both devices are on the same network?

**Comment by alvestrand** [comment]
Closing due to no followup from poster.
