### ISSUE TITLE
In end to end encryption demo, how to make receiver decode successfully without using crypto offset?

### ISSUE THREAD

**Issue by HAHAHA44** [webrtc/samples#1448]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ x ] I have provided steps to reproduce
- [ x ] I have provided browser name and version
- [ x ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

Chrome 90.0.4430.212 (x86_64)

## Description

could not successfully decode the full encrypted data with insertable stream.

## Steps to reproduce

Open end to end encryption demo.
select "Encrypt first bytes" checkbox, and start call.

## Expected results

show the same video image the same as the video in sender box in receiver box.

## Actual results

Receiver box`s image is a black view. the RTCEncodedFrame `s additionalData and frameType properties of  receiver insertable stream  are incorrect .

**Comment by fippo** [comment]
you're using H264? That is a known issue, see https://bugs.chromium.org/p/webrtc/issues/detail?id=11886&
