### ISSUE TITLE
https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/ is broken

### ISSUE THREAD

**Issue by alvestrand** [webrtc/samples#1454]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [X] I have provided steps to reproduce
- [X] I have provided browser name and version
- [X] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome Version 91.0.4472.106 (Official Build) (64-bit)

## Description
https://webrtc.github.io/samples/src/content/peerconnection/munge-sdp/ is broken

## Steps to reproduce

Hit "Get media", "Create Peerconnection", and "Create offer".

## Expected results

An offer.

## Actual results

Console error: "Failed to create session description: TypeError: Cannot read property 'createOffer' of undefined"

**Comment by fippo** [comment]
This used to enable the buttons only when they were usable (or rather set disabled=false). This broke as part of the big vandalism^Wrewrite.

Workaround: do not click so fast
