### ISSUE TITLE
Is it necessary to create offer and setLocaldescription after pc.addTrack(track)

### ISSUE THREAD

**Issue by Karthikdb** [webrtc/samples#1458]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce
- [x] I have provided a link to the sample here or a modified version thereof
- [x] I have provided browser name and version

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Chrome 
Safari
**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Description
I am using RTCpeerconnection in chrome and `pc.addStream(stream) `to add stream which is not working in Safari. Finally I found that there is `pc.addTrack(track)` and `ontrack` to add and receive track.

## Steps to reproduce
When I am using `pc.addStream(stream)` I have `createOffer` and `setLocalDescription` every time when I add stream 

My question is it necessary to `createoffer` and `setLocalDescription` on every time I do `pc.addTrack(track)`

## Actual results
If I `createoffer` and `setLocalDescription` while using `pc.addTrack` I am getting this error `PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer`

[https://github.com/Karthikdb/Video-Meeting/blob/ff17877ceeac3a36cb99047bf465082d51fedab9/src/Video.js](url)

Here is my complete code

**Comment by alvestrand** [comment]
Not only createOffer, but transmit the offer to the other side and do a setRemoteDescription on the other end, doing a createAnswer there, doing a setLocalDescription there, transmit the answer back, and do setRemoteDescription with the answer on the first end.

Otherwise, the other end will not know about your added track.

A good introduction to WebRTC should give you this information.
