### ISSUE TITLE
One to Many broadcast

### ISSUE THREAD

**Issue by codydev-git** [webrtc/samples#1459]
How are you?
I want to build a live streaming website with WebRTC.
Is it possible?
if yes, Please give me a simple source code.
Thank you.

**Comment by rpbsi** [comment]
How are you? I am using your webRTC unity asset in my Unity build 2020.03.14 I am looking for One too many broadcasts with a group of users into one session (One Sender and many receivers). Having each session with few unique users. Can I implement the signaling process within the Unity asset?
