### ISSUE TITLE
getDisplayMedia， Screen nesting

### ISSUE THREAD

**Issue by anUniqueBoy** [webrtc/samples#1460]
## Description
Using the official screen to share the demo has multiple nesting problems on the browser
## Steps to reproduce
first, open [demo](https://webrtc.github.io/samples/src/content/getusermedia/getdisplaymedia/)
next，choose the whole screen
Google Chrome:  91.0.4472.124
firefox: 89.0.2 
## Expected results
one screen
## Actual results
Screen nested multiple levels

**Comment by fippo** [comment]
see https://webrtchacks.com/capture-handle/ for a discussion of the hall-of-mirrors effect and some suggestions to avoid it
