### ISSUE TITLE
end-to-end encryptions should be part of the standard

### ISSUE THREAD

**Issue by Zibri** [webrtc/samples#1464]
Just a though:
while this seems very interesting ( https://github.com/webrtc/samples/tree/gh-pages/src/content/insertable-streams/endtoend-encryption )

I think that end to end encryptions should be just a parameterin the webrtc standard.

Something like: end2end: true encryptionType encriptionKey

**Comment by alvestrand** [comment]
Please take that to the webrtc WG - a proposal has been made for a builtin "sframe transform" as part of the webrtc-encoded-transform spec.
