### ISSUE TITLE
Audio only & record samples do not work on Chrome browser on iOS

### ISSUE THREAD

**Issue by naveennazimudeen** [webrtc/samples#1485]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [X] I have provided steps to reproduce
- [X] I have provided browser name and version
- [X] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Chrome Browser 94.0.4606.52 on iOS 14.8

## Description

Audio sample:  https://webrtc.github.io/samples/src/content/getusermedia/audio/ does not work. On loading the page, there is no prompt shown asking the user for permission. 

On page load the following error is shown: 

```navigator.MediaDevices.getUserMedia error: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission. NotAllowedError```

<img src="https://user-images.githubusercontent.com/20735539/135552017-9ce2370d-1418-4802-9ce8-ecc7f5d3bf0c.PNG" alt="Audio Sample on Chrome on iOS error" width="250"/>

The record sample does not work as well: https://webrtc.github.io/samples/src/content/getusermedia/record . On clicking the `Start Camera` button the error `navigator.getUserMedia error:OverconstrainedError: Invalid constraint` shows

## Steps to reproduce
1. On chrome on iOS  go to  audio sample page: https://webrtc.github.io/samples/src/content/getusermedia/audio/. The error shows on page
2. On chrome browser on iOS go to record sample page: https://webrtc.github.io/samples/src/content/getusermedia/record. Then click on `Start Camera` button. The error shows.

## Expected results

The Audio Sample page is loaded on chrome browser on iOS, the user permission to access microphone is asked and the page is loaded without error.

For the Record sample page, on clicking the Start Camera button, the user permission is asked and that there is no error.

**Comment by fippo** [comment]
can't reproduce - this error typically suggests the user denied access.
