### ISSUE TITLE
getUserMedia() returns error in iOS 15

### ISSUE THREAD

**Issue by amerfathullah** [webrtc/samples#1487]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

Chrome version 94.0.4606.76

## Description
only happens in iOS 15 (iPhone SE). iOS 14.3 (tested on iPhone 11) works fine.

Device: iPhone SE 1st Gen (iOS 15.0.2)

## Steps to reproduce
1. Go here: https://webrtc.github.io/samples/src/content/getusermedia/gum/ on iPhone SE.
2. Click "Open Camera" button.
3. Error shown.

## Expected results
Camera view will be shown on the page.

## Actual results
![image (1)](https://user-images.githubusercontent.com/36897396/137426345-189a360f-96e1-4301-802a-cbbdb4fa4031.png)

**Comment by mcdade** [comment]
I have seen the same issue on iPhone SE2 running 14.8.1.

**Comment by fippo** [comment]
please file a webkit issue if this persists
