### ISSUE TITLE
it should be, Offer from pc2.

### ISSUE THREAD

**Issue by mqasim423** [webrtc/samples#1495]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [X ] I have provided steps to reproduce
- [X ] I have provided browser name and version
- [X ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
   Version 96.0.4664.45 (Official Build) (64-bit)

## Description

/src/content/peerconnection/webaudio-input/js/main.js

change require in line 98. Maybe it will helpful for leaner.
console.log(`Offer from pc1\n${desc.sdp}`);
to
console.log(`Offer from pc2\n${desc.sdp}`);

![image](https://user-images.githubusercontent.com/92620819/144047343-a03b47e5-7261-4d91-83a3-2ef936d5aaba.png)

## Steps to reproduce

/src/content/peerconnection/webaudio-input/js/main.js

## Expected results

Offer from pc1
v=0
o=- 802837418911162144 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed

Offer from pc2
v=0
o=- 80283997418911162144 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed

## Actual results

Offer from pc1
v=0
o=- 802837418911162144 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed

Offer from pc1
v=0
o=- 80283997418911162144 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0
a=extmap-allow-mixed

**Comment by fippo** [comment]
the offer is from the pc1 object so this is correct. However, the logging is too verbose and one of those logs should be removed
