### ISSUE TITLE
Trickle ICE should catch Exceptions in start function for better error handling

### ISSUE THREAD

**Issue by in-fke** [webrtc/samples#1499]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected

Windows Chrome Version 96.0.4664.45 (Offizieller Build) (64-Bit)

## Description

Entering an invalid (?) TURN Url will lead to silent JS exception (not properly logged in browser console).

## Steps to reproduce

1. Using a browser with Chrome Engine, go to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Enter as TURN URI: `turn:turn.my-domain.com:443?transport=tcp` (leave username and password blank)
2. Hit "Add Server"
3. Hit the "Gather Candidates"

## Expected results

Expected some error message (in the UI), or a more detailed exception log.
e.g. by adding a try/catch block in the start function.

## Actual results

Top level (unhandled) exception in the DOM:

```
Uncaught (in promise) DOMException: Failed to construct 'RTCPeerConnection': ICE server parse failed
    at HTMLButtonElement.start (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/js/main.js:159:8)
start @ main.js:159
```
The Chromium Code (where the original error is from) is from here: https://chromium.googlesource.com/external/webrtc/+/master/pc/peer_connection.cc

**Comment by fippo** [comment]
actually fixed as part of #1535
