### ISSUE TITLE
When nearly all outbound tcp and udp traffic blocked, data channel test hangs

### ISSUE THREAD

**Issue by tednakamura** [webrtc/samples#150]
OS: Ubuntu 14.04.1 LTS
Setup: use iptables to block nearly all outbound tcp (except 80 and 443) and udp (except dns and dhcp).

Repro steps:
1) Open https://test-rtc.appspot.com/
2) Press Start

Issue:
Test seems to hang at the "Data channel throughput" test. Perhaps it's missing a timeout?

Full test output below:
[ RUN    ] MicrophoneTest
[     OK ] getUserMedia succeeded.
[     OK ] Audio track exists with label=Default
[     OK ] Audio num channels=1
[     OK ] Audio sample rate=44100
[     OK ] Audio power=-36.1199102794985
[ ------ ] 
[ RUN    ] UdpConnectivityTest
[ FAILED ] Failed to gather specified candidates
[ ------ ] 
[ RUN    ] TcpConnectivityTest
[ FAILED ] Failed to gather specified candidates
[ ------ ] 
[ RUN    ] HasIpv6Test
[     OK ] Gathered candidate with type: host address: 2620:0:1000:1600:a2e:5fff:fe0d:28c0
[ ------ ] 
[ RUN    ] CamResolutionsTest
[   INFO ] Supported resolution: (160x120)
[   INFO ] Supported resolution: (320x180)
[   INFO ] Supported resolution: (320x240)
[   INFO ] Supported resolution: (640x360)
[   INFO ] Supported resolution: (640x480)
[   INFO ] Resolution NOT supported: (768x576)
[   INFO ] Resolution NOT supported: (1024x576)
[ FAILED ] Camera does not support a mandatory resolution, (1280x720)
[   INFO ] Resolution NOT supported: (1280x768)
[   INFO ] Resolution NOT supported: (1280x800)
[   INFO ] Resolution NOT supported: (1920x1080)
[   INFO ] Resolution NOT supported: (1920x1200)
[   INFO ] Resolution NOT supported: (3840x2160)
[   INFO ] Resolution NOT supported: (4096x2160)
[ ------ ] 
[ RUN    ] CamCaptureTest
[     OK ] getUserMedia succeeded.
[     OK ] Video track exists with label = Microsoft® LifeCam VX-2000 (045e:0761)
[   INFO ] Checking if your camera is delivering frames for five seconds...
[     OK ] Expected: 640 === 640: Width OK
[     OK ] Expected: 480 === 480: Height OK
[     OK ] Expected: false === false: Camera is delivering frames
[     OK ] Expected: 0 === 0: Camera is sending non-black frames.
[ ------ ] 
[ RUN    ] Data channel throughput

**Comment by juberti** [comment]
Please migrate this to testrtc tracker

**Comment by KaptenJansson** [comment]
Migrated: https://github.com/webrtc/testrtc/issues/25

**Comment by dschwarz2011** [comment]
What was the resolution here? It's still failing these tests for me. However, I am running a paping using port 443 and port 80 to test.webrtc.org and it replies fine. Is this just a glitch ?

**Comment by KaptenJansson** [comment]
The issue was moved to the correct tracker,  https://github.com/webrtc/testrtc/issues/25. It has not been resolved yet.
