### ISSUE TITLE
Trickle ICE seems to report wrong error

### ISSUE THREAD

**Issue by stiv-yakovenko** [webrtc/samples#1501]
Try Trickle ICE (https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) with stun:stun.l.google.com:19302:

![image](https://user-images.githubusercontent.com/4163254/145716673-9c16ca45-73c5-4d96-a944-85c4a6c2400b.png)
I get:
```
The server stun:stun.l.google.com:19302 returned an error with code=701:
STUN host lookup received error.

```
I get same error with my own correctly working TURN server and other people reporting the same. May it be a bug in Trickle ICE?

**Comment by sondcdev** [comment]
Same, Can anyone suggest me an alternative to test whether my STUN/TURN server work? Thanks

**Comment by fippo** [comment]
as pointed out by the note which says
```
Note: errors from onicecandidateerror above are not neccessarily fatal.
For example an IPv6 DNS lookup may fail but relay candidates can still be gathered via IPv4.
 ```
this is expected behavior
