### ISSUE TITLE
VideoCall not working

### ISSUE THREAD

**Issue by chetanmaniya** [webrtc/samples#1504]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

## Actual results
![image](https://user-images.githubusercontent.com/50447200/146641249-aa30a831-a084-4247-b495-6bf17344a45c.png)

**Comment by fippo** [comment]
apprtc was turned off, see https://groups.google.com/g/discuss-webrtc/c/H7XuZfgkGH0/m/Q0BKTWZICgAJ

**Comment by hthetiot** [comment]
As part of couple of WebRTC open source projects that I maintain, I do receive donations via GitHub Sponsor, I'm willing to invest part of this donations into an apprtc hosting (EC2 instance with Turn)  and a DNS domain (apprtc.dev) to assit the WebRTC community to transition away from old apprtc. Let me know what you think @fippo

**Comment by fippo** [comment]
@hthetiot I don't work or speak for Google but it is rather unlikely that lack of resources were the problem given it was running on appengine.

Externalizing apprtc is not going to help since its value in the last five years was that it was accepted as *their* reference app and there was no discussion or confusion about whether the code is correct or not.

**Comment by alvestrand** [comment]
Not a samples issue, so closing - further discussion should happen on the apprtc repo - https://github.com/webrtc/apprtc
