### ISSUE TITLE
Sample for canvas-video video not working.

### ISSUE THREAD

**Issue by JamesDrummond** [webrtc/samples#1510]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 97.0.4692.99)**

## Description
Sample for canvas-video video not working. I got it working by changing the following.
![image](https://user-images.githubusercontent.com/20580888/150693130-a6ff3020-8463-4cd3-bddb-305ee247110a.png)

## Steps to reproduce
Go to http://localhost:8080/src/content/capture/canvas-video/ and canvas on left is blank.

## Expected results
Show image. Below is after change I mentioned above.
![image](https://user-images.githubusercontent.com/20580888/150693247-bf4c2aad-5120-4f76-bc2b-3364ba03b694.png)

## Actual results
No image
![image](https://user-images.githubusercontent.com/20580888/150693201-dc99002d-e829-472d-bdfc-c8a9e98bbdcf.png)

**Comment by meesrutten** [comment]
bump!
