### ISSUE TITLE
WebRTC getUserMedia does not work with audio just in in-app iOS browser (>=15.1, previous versions worked)

### ISSUE THREAD

**Issue by skiiiks** [webrtc/samples#1512]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected

Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [LinkedInApp]

## Description

Let's take this example: https://webrtc.github.io/samples/src/content/devices/input-output/

If you load that page with Desktop Chrome, Desktop Safari, Chrome from Android, Chrome from iPhone, Safari from iPhone, ... anywhere ... it works perfectly.

But, if you send that URL through a personal message in LinkedIn (I tested with this app, but I guess it will happen in all in-app browsers in iOS), and you open the link within the iPhone LinkedIn app (this is the user_agent: "Mozilla/5.0 (iPhone; CPU iPhone OS 15_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 [LinkedInApp]"), it does not work.

After investigating, I've checked that the problem is the "audio" in constraints.

If I put the constraints with { video:true, audio: false } it works. For example, here is an example working (again, from iPhone LinkedIn app): https://webrtc.github.io/samples/src/content/getusermedia/gum/ (because it does not use "audio")

But if you add "audio: true" to this last example, it does not work, it goes to the handleError function with a message: "The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission."

What is happening with this browser and WebRTC?

I see no clues or info in Internet, and I think it's happening since the iOS 15.1, because it was working perfectly in 14_5_1, 14_7_1, 14_8, 15_0_1

**Comment by alvestrand** [comment]
Do you know if any app that uses GetUserMedia with audio works in the LinkedIn app?

It would be consistent with the symptoms reported if the LinkedIn app does not have microphone permission.

**Comment by skiiiks** [comment]
Maybe LinkedIn app has been "updated", I don't know.

But I can tell FOR SURE, that with iOS 14.5, 14.7, 14.8, and even 15.0.1, it was working.
I had a tech working, but since iOS 15.1 stopped to work this feature.

I don't think it's something about LinkedIn app itself, but the WebView component of iOS later versions

**Comment by alvestrand** [comment]
Seems to be either an IOS error or a LinkedIn error (not getting microphone permission).
Closing bug, as there seems like nothing we can do on the samples side; feel free to refer to this issue when reporting the issue to Apple and/or LinkedIn.

**Comment by alvestrand** [comment]
tagging @youennf for interest.

**Comment by youennf** [comment]
I just tried LinkedIn app in latest iOS 15.4 beta and it works for me.
I would hope it would work as well before then.
@skiiiks, can you check whether microphone access is allowed in System settings for LinkedIn?
If that is the case, you can file a bug in bugs.webkit.org, or send me privately a sysdiagnose (youenn@apple.com) to look at the issue.

**Comment by youennf** [comment]
I just tried LinkedIn app in latest iOS 15.4 beta and it works for me.
I would hope it would work as well before then.
@skiiiks, can you check whether microphone access is allowed in System settings for LinkedIn?
If that is the case, you can file a bug in bugs.webkit.org, or send me privately a sysdiagnose (youenn@apple.com) to look at the issue.
