### ISSUE TITLE
Safari w/ Headphones capture failure in sample due to AudioContext not releasing resources

### ISSUE THREAD

**Issue by maikthomas** [webrtc/samples#1514]
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected

Safari Version 15.0 (16612.1.29.41.4, 16612) on Mac

## Description
When running the Audio stream volume example: https://webrtc.github.io/samples/src/content/getusermedia/volume/
On Safari with Bluetooth headphones, if you stop and start the audio track is not recaptured and you will see the error:
`A MediaStreamTrack ended due to a capture failure`

I believe this is due to [`AudioContext.close()`](https://developer.mozilla.org/en-US/docs/Web/API/AudioContext) not being called.
This doc for method says:
>Closes the audio context, releasing any system audio resources that it uses.

So it seems the bluetooth resource is not being released.

I have added a call to `audioContext.close()` and the issue appears to be fixed.
Note that since this only happens on Safari and with bluetooth devices, we have also opened a ticket to WebKit:
https://bugs.webkit.org/show_bug.cgi?id=236350

## Steps to reproduce
- On a Mac (haven't tested on windows)
- Connect bluetooth headphones as default audio device
- Open in safari: https://webrtc.github.io/samples/src/content/getusermedia/volume/
- Click Start, Stop, and Start again
- Observe in console: `A MediaStreamTrack ended due to a capture failure`

## Expected results
- Stream and be started and stopped freely with audioMeter working

## Actual results
- Stream and audioMeter only work first time before become permanently broken with audio track unavailable

**Comment by fippo** [comment]
fixed!
