### ISSUE TITLE
Full featured WebRTC application sample not available

### ISSUE THREAD

**Issue by Level60Warlock** [webrtc/samples#1520]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.

- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
All browsers

## Description
Sample Full featured WebRTC application not available.

## Steps to reproduce
Navigate to https://apprtc.appspot.com/

## Expected results
Sample app available

## Actual results
```
Error: Page not found
The requested URL was not found on this server.
```

**Comment by alvestrand** [comment]
This service has been shut down. Instructions for running your own instance are at https://github.com/webrtc/apprtc

**Comment by Level60Warlock** [comment]
@alvestrand  - That's great... but the samples page should be updated to reflect this, no?
https://github.com/webrtc/samples/blob/gh-pages/index.html

**Comment by alvestrand** [comment]
Right you are. Fixed.

**Comment by alvestrand** [comment]
And thanks for pointing it out after I missed it!
