### ISSUE TITLE
https://drive.google.com/file/d/1AF_bGLXOEuW7oEikde1M35du8T7HyrCl/view?usp=drivesdk


### ISSUE THREAD

**Issue by RemedialGenius** [webrtc/samples#1525]
Intelligence

**Comment by RemedialGenius** [comment]
Watch thid

**Comment by RemedialGenius** [comment]
> Intelligence
> 

https://drive.google.com/file/d/1AF_bGLXOEuW7oEikde1M35du8T7HyrCl/view?usp=drives do

**Comment by alvestrand** [comment]
Please don't post irrelevant material.
