### ISSUE TITLE
Add developer's guide

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#153]
Create a short guide for developers working on this repo.

- Use of GitHub: branches and forks.
- Use of JSHint: validation, use of .jshintrc, etc.
- HTML, CSS and JavaScript coding style (based on https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml).

Anything else?

**Comment by juberti** [comment]
Anything remaining here?

**Comment by samdutton** [comment]
Not that I'm aware of (here
<https://docs.google.com/document/d/1tn1t6LW2ffzGuYTK3366w1fhTkkzsSvHsBnOHoDfRzY/edit>).
I've updated for JCSC validation.
