### ISSUE TITLE
Trickle ICE Failed

### ISSUE THREAD

**Issue by murugancmi** [webrtc/samples#1556]
- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Chrome 102.0.5005.61 (Official Build) (x86_64)**

## Description
when we try to test Trickle ICE in Chrome 102.0.5005.61 (Official Build) (x86_64) Mac ICE gathering failed, If I test the same sample it works fine in firefox.

Tested On Chrome

![Screenshot 2022-05-27 at 5 03 10 PM](https://user-images.githubusercontent.com/25261553/170692928-c9b3a578-aba5-48cc-9fc1-a2cbab6c7296.png)

Tested on firefox

![Screenshot 2022-05-27 at 5 03 50 PM](https://user-images.githubusercontent.com/25261553/170693038-84abd57a-d310-4aeb-b914-5aa02eed0675.png)

## Steps to reproduce

Add stun server URL and click Gather candidates https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

## Expected results

gather a candidate with type "srflx" from the stun server

## Actual results

No candidate from STUN server

**Comment by rajneeshksoni** [comment]
Can you check first running the [getUserMedia sample](https://webrtc.github.io/samples/src/content/getusermedia/gum/)
allow camera and then run the trickle ice sample i think it should work.

i think it is related to [this](https://bloggeek.me/psa-mdns-and-local-ice-candidates-are-coming/).

**Comment by murugancmi** [comment]
No still the same issue please have a look 


![Screenshot 2022-05-28 at 4 28 25 PM](https://user-images.githubusercontent.com/25261553/170822546-a4482ec5-deae-4381-94e0-fe937e3a6db8.png)

**Comment by fippo** [comment]
are you using any "privacy" extensions which might tamper with how WebRTC behaves? Not gathering any candidates is quite unusual
