### ISSUE TITLE
How to activate front and back camera in android and ios using Webrtc

### ISSUE THREAD

**Issue by mahadevan-muthirakumaran** [webrtc/samples#1559]
Hi ,
   I am new for webrtc world. Myself created one new video call application using webrtc. By changing the camera front and back (FLIP option).

MediaConfig mediaConfig = new MediaConfig();
ICall mCall=UnityCallFactory.Instance.Create(NetConfig);
mCall.CallEvent += Call_CallEvent;
mMediaConfig.VideoDeviceName = "1";
mMediaConfig.Video = true;
mCall.Configure(mMediaConfig);

Above code is initiated for a call. After start the call(streaming) I am trying to change the device number -'mMediaConfig.VideoDeviceName = "0";' but its not reflected on current streaming. Please could you suggest me a correct way.

Thank you..

**Comment by fippo** [comment]
You'll have to find another place for support wrt Unity, as pointed out in the template that you deleted, issues in this repository should be about the JS/web samples it contains
