### ISSUE TITLE
Camera feed is not drawn via WeChat WebView

### ISSUE THREAD

**Issue by evanmcarlson** [webrtc/samples#1565]
- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected
WeChat WebView on iOS 13+ (Version 8.0.25)

## Description
None of the getUserMedia demos are working within WeChat, but we have seen many other applications that use getUserMedia successfully work within WeChat. Open [https://shrek.imdevsh.com/demo/camera/](https://shrek.imdevsh.com/demo/camera/) within WeChat to see a webpage using getUserMedia that successfully draws the camera feed. Open any of the official getUserMedia demos within WeChat to see a webpages that do not successfully draw the camera feed. Any insight to this issue would be much appreciated!

## Steps to reproduce
Open the [basic get user media demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/) within WeChat.

## Expected results
When the _Open camera_ button is tapped, it should prompt for camera access and draw the camera feed. 

## Actual results
When the _Open camera_ button is tapped, it prompts for camera access but does not draw the camera feed.

**Comment by evanmcarlson** [comment]
We've found that calling `play` on the video in `handleSuccess` resolves the issue.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/35385537/179834018-d89b73fa-9bd3-4cdb-a4e8-693fc4ed8b49.png">

**Comment by evanmcarlson** [comment]
[official demo](https://webrtc.github.io/samples/src/content/getusermedia/gum/) (not working via WeChat) / [custom demo](https://shrek.imdevsh.com/demo/webrtc/basic/) (working via WeChat)

**Comment by fippo** [comment]
That sounds like WeChat WebView has a broken implementation of autoplay for MediaStreams.
Not something we can solve
