### ISSUE TITLE
Question: Recording remote (incoming) audio in a peer connection

### ISSUE THREAD

**Issue by santo4ul** [webrtc/samples#1567]
- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

Browser Version: Chrome Version 102.0.5005.61 (Official Build) (64-bit)

Hi, 

Thanks for putting together such a nice example. 

I'm new to WebRTC and these examples are helping me a lot. 

Is is possible to record the remote (incoming) audio of a peer connection to a file? I'd like to save the raw audio (PCMU/PCMA) to a WAV file. Do we have any example to demonstrate this? 

Or any pointers to the relevant WebRTC APIs that'd help me with my audio recording experiment, would be really great.

Thank you.

**Comment by alvestrand** [comment]
For usage advice, it is better to send a message to discuss-webrtc@googlegroups.com (after joining).

For recording incoming media, take a look at the MediaRecorder API. I'm not sure what formats it supports, but that's probably the simplest approach.
If you want access to the samples while they are coming in, either WebAudio or the Breakout Box API (MediaStreamTrackProcessor) can be used.

Closing this issue.
