### ISSUE TITLE
End-to-end encryption sample crashes in Safari

### ISSUE THREAD

**Issue by vitaly-castLabs** [webrtc/samples#1574]
## Browser affected

Both regular Safari 16.0 and Safari Technology Preview, Release 154 (Safari 16.0, WebKit 17615.1.6.2) on macOS 12.6, MacBookAir (M1, 2020).
From npm logs (when I run it locally): "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15"

## Description
https://webrtc.github.io/samples/src/content/insertable-streams/endtoend-encryption/ causes Safari to throw "This page was reloaded because a problem occurred"

## Steps to reproduce
Open the sample page, type in some Crypto key in the box, press Start and then Call

## Expected results
Garbled video in Middlebox

## Actual results
The page apparently crashes and Safari reloads the page.

I see about a dozen "send" and "recv" records in the JS console with both audio and video (key & delta) present, i.e. it works for a little while before crashing.

When there's no crypto key specified it works flawlessly. Works fine with Chrome, both crypto/no-crypto scenarios

**Comment by alvestrand** [comment]
@youennf should this be reclassified as a Safari bug?

**Comment by saghul** [comment]
Looks like a Safari bug indeed. It works for me on Safari TP 153:

<img width="1939" alt="Screenshot 2022-09-30 at 10 26 48" src="https://user-images.githubusercontent.com/317464/193227187-3ec9017a-5b0c-4553-bf0c-73a928ec4eb6.png">

**Comment by youennf** [comment]
Yes, @vitaly-castLabs, can you file a bug in bugs.webkit.org?
I'll file one otherwise.

**Comment by vitaly-castLabs** [comment]
@youennf Done: https://bugs.webkit.org/show_bug.cgi?id=245870

**Comment by vitaly-castLabs** [comment]
@saghul it works for me on my old MBP (macOS 10.15.7, Safari 15.6.1) too, it's just unbelievably slow (I guess this is the issue: https://bugs.webkit.org/show_bug.cgi?id=229190) when encryption is on

**Comment by youennf** [comment]
Thanks for the reminder on bug 229190, I'll fix it.

**Comment by fippo** [comment]
acted upon in the respective bugtracker 👍
