### ISSUE TITLE
Helpppp！Callback does not be called when I call SetLocalDescription

### ISSUE THREAD

**Issue by zdh3303** [webrtc/samples#1578]
using webrtc native api  C++, system: window 10 

## Description
I call SetLocalDescription in the OnSuccess(webrtc::SessionDescriptionInterface* desc) after CreateAnswer, but the callback does not be called

## Steps to reproduce
receive the peer offer ,SetRemoteDescription ,createanswer,call SetLocalDescription in the OnSuccess(webrtc::SessionDescriptionInterface* desc) after CreateAnswer,

## Expected results
SetLocalDescription(Observer, desc),Observer::OnSuccess or OnFailure  should be called

## Actual results

SetLocalDescription(Observer, desc),Observer::OnSuccess or OnFailure  does not be called

**Comment by fippo** [comment]
As the template you deleted says, this repository is about JS samples, not C++
