### ISSUE TITLE
Regular audio cuts in all RTCPeerConnection samples

### ISSUE THREAD

**Issue by CorentinJ** [webrtc/samples#1585]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Tested on **Chrome 107.0.5304.107 (Official Build) (64-bit)** and **Firefox 107.0 (64-bit)**

## Description
All examples under the RTCPeerConnection category output audio that is intermittently cut. 

## Steps to reproduce

I have been able to reproduce this issue with different browsers (chrome & firefox as above) and on different hardware, including a recent Ubuntu install and win64.

Any of the following samples will reproduce this issue:
[Basic peer connection demo in a single tab](https://webrtc.github.io/samples/src/content/peerconnection/pc1/)
[Basic peer connection demo between two tabs](https://webrtc.github.io/samples/src/content/peerconnection/channel/)
[Audio-only peer connection demo](https://webrtc.github.io/samples/src/content/peerconnection/audio/)

The samples in the first category do **not** present this same issue
[Record stream](https://webrtc.github.io/samples/src/content/getusermedia/record/)
[Audio-only getUserMedia() output to local audio element](https://webrtc.github.io/samples/src/content/getusermedia/audio/)

## Expected results
A smooth audio output 

## Actual results
This video where both input and output audio is recorded illustrates the problem:

https://user-images.githubusercontent.com/12038136/203829510-f1a5758c-e9a8-44b8-b76e-d158ca653dee.mp4

**Comment by fippo** [comment]
I think you're hitting AEC and "double talk". https://groups.google.com/g/discuss-webrtc/c/ddS08EgXfSU/m/Sq9OIsVXCwAJ has some hints

**Comment by CorentinJ** [comment]
Indeed! Adding the audio constraint `{echoCancellation: false}` does fix the issue! Thanks
