### ISSUE TITLE
When I use Android phone to publish stream, I get this problem in my chrome browser: "Uncaught TypeError: Cannot read property 'find' of undefined."

### ISSUE THREAD

**Issue by chenxuan670693438** [webrtc/samples#1589]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [ ] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by hthetiot** [comment]
@chenxuan670693438 

This is most likely an issue in your code, unless you provide a way to reproduce the issue via a sample like requested when you created the issue it's unlikely anyone can help you.

'find' is an array method, you most likely using find on an array variable that is undefined. With the error you have a trace of the line and where the error is located.
