### ISSUE TITLE
Invite is being truncated

### ISSUE THREAD

**Issue by bp2468** [webrtc/samples#1590]
How to resolve sip_inv.c .Error parsing/validating SDP body: Missing SDP rtpmap for dynamic payload type (PJMEDIA_SDP_EMISSINGRTPMAP) this error?

Starting Video Call... and the above error is displayed in the browser.

v=0
o=- 1381334577221906819 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=extmap-allow-mixed
a=msid-semantic: WMS f0cb88d3-b5f6-45ad-bf5e-2fc384cd5007
m=audio 63384 UDP/TLS/RTP/SAVPF 111 63 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 14.139.183.221
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2307628153 1 udp 2122260223 192.168.56.1 63383 typ host generation 0 network-id 1
a=candidate:1168475650 1 udp 2122194687 10.176.17.207 63384 typ host generation 0 network-id 2
a=candidate:1000382465 1 udp 2122129151 10.200.0.78 63385 typ host generation 0 network-id 3
a=candidate:2942053582 1 udp 2122063615 10.201.0.83 63386 typ host generation 0 network-id 4
a=candidate:2910989289 1 udp 2121998079 10.202.0.83 63387 typ host generation 0 network-id 5
a=candidate:2889340660 1 udp 2121932543 10.203.0.83 63388 typ host generation 0 network-id 6
a=candidate:2739288379 1 udp 2121867007 10.208.0.83 63389 typ host generation 0 network-id 7
a=candidate:1151726628 1 udp 1685987071 14.139.183.221 63384 typ srflx raddr 10.176.17.207 rport 63384 generation 0 network-id 2
a=candidate:4148461281 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 network-id 1
a=candidate:996828314 1 tcp 1518214911 10.176.17.207 9 typ host tcptype active generation 0 network-id 2
a=candidate:1164919449 1 tcp 1518149375 10.200.0.78 9 typ host tcptype active generation 0 network-id 3
a=candidate:3516124758 1 tcp 1518083839 10.201.0.83 9 typ host tcptype active generation 0 network-id 4
a=candidate:3545090417 1 tcp 1518018303 10.202.0.83 9 typ host tcptype active generation 0 network-id 5
a=candidate:3539481708 1 tcp 1517952767 10.203.0.83 9 typ host tcptype active generation 0 network-id 6
a=candidate:3716799395 1 tcp 1517887231 10.208.0.83 9 typ host tcptype active generation 0 network-id 7
a=ice-ufrag:58ia
a=ice-pwd:JOJwFcXOQgB/BjvWBYeoVf+o
a=ice-options:trickle
a=fingerprint:sha-256 26:61:B0:1D:FF:98:02:A7:80:5D:E9:93:2F:9A:3D:81:9D:5F:4F:53:F9:11:2E:07:55:56:E8:A8:3B:88:9E:C2
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 [docs/native-code/rtp-hdrext/abs-send-time - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time)
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=sendrecv
a=msid:f0cb88d3-b5f6-45ad-bf5e-2fc384cd5007 7f4eb73f-b76b-44ee-97d3-896beca8bc44
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:63 red/48000/2
a=fmtp:63 111/111
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:1375327883 cname:d6fR/l3DJldZt5eD
a=ssrc:1375327883 msid:f0cb88d3-b5f6-45ad-bf5e-2fc384cd5007 7f4eb73f-b76b-44ee-97d3-896beca8bc44
m=video 63391 UDP/TLS/RTP/SAVPF 96 97 102 122 127 121 125 107 108 109 124 120 39 40 45 46 98 99 100 101 123 119 114 115 116
c=IN IP4 14.139.183.221
a=rtcp:9 IN IP4 0.0.0.0
a=candidate:2307628153 1 udp 2122260223 192.168.56.1 63390 typ host generation 0 network-id 1
a=candidate:1168475650 1 udp 2122194687 10.176.17.207 63391 typ host generation 0 network-id 2
a=candidate:1000382465 1 udp 2122129151 10.200.0.78 63392 typ host generation 0 network-id 3
a=candidate:2942053582 1 udp 2122063615 10.201.0.83 63393 typ host generation 0 network-id 4
a=candidate:2910989289 1 udp 2121998079 10.202.0.83 63394 typ host generation 0 network-id 5
a=candidate:2889340660 1 udp 2121932543 10.203.0.83 63395 typ host generation 0 network-id 6
a=candidate:2739288379 1 udp 2121867007 10.208.0.83 63396 typ host generation 0 network-id 7
a=candidate:1151726628 1 udp 1685987071 14.139.183.221 63391 typ srflx raddr 10.176.17.207 rport 63391 generation 0 network-id 2
a=candidate:4148461281 1 tcp 1518280447 192.168.56.1 9 typ host tcptype active generation 0 network-id 1
a=candidate:996828314 1 tcp 1518214911 10.176.17.207 9 typ host tcptype active generation 0 network-id 2
a=candidate:1164919449 1 tcp 1518149375 10.200.0.78 9 typ host tcptype active generation 0 network-id 3
a=candidate:3516124758 1 tcp 1518083839 10.201.0.83 9 typ host tcptype active generation 0 network-id 4
a=candidate:3545090417 1 tcp 1518018303 10.202.0.83 9 typ host tcptype active generation 0 network-id 5
a=candidate:3539481708 1 tcp 1517952767 10.203.0.83 9 typ host tcptype active generation 0 network-id 6
a=candidate:3716799395 1 tcp 1517887231 10.208.0.83 9 typ host tcptype active generation 0 network-id 7
a=ice-ufrag:58ia
a=ice-pwd:JOJwFcXOQgB/BjvWBYeoVf+o
a=ice-options:trickle
a=fingerprint:sha-256 26:61:B0:1D:FF:98:02:A7:80:5D:E9:93:2F:9A:3D:81:9D:5F:4F:53:F9:11:2E:07:55:56:E8:A8:3B:88:9E:C2
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 [docs/native-code/rtp-hdrext/abs-send-time - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time)
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:5 [docs/native-code/rtp-hdrext/playout-delay - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/playout-delay)
a=extmap:6 [docs/native-code/rtp-hdrext/video-content-type - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/video-content-type)
a=extmap:7 [docs/native-code/rtp-hdrext/video-timing - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/video-timing)
a=extmap:8 [docs/native-code/rtp-hdrext/color-space - src - Git at Google](http://www.webrtc.org/experiments/rtp-hdrext/color-space)
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:10 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:11 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendrecv
a=msid:f0cb88d3-b5f6-45ad-bf5e-2fc384cd5007 400a1efc-07aa-49e2-bd73-a607436762f0
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli
a=rtpmap:97 rtx/90000
a=fmtp:97 apt=96
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:122 rtx/90000
a=fmtp:122 apt=102
a=rtpmap:127 H264/90000
a=rtcp-fb:127 goog-remb
a=rtcp-fb:127 transport-cc
a=rtcp-fb:127 ccm fir
a=rtcp-fb:127 nack
a=rtcp-fb:127 nack pli
a=fmtp:127 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42001f
a=rtpmap:121 rtx/90000
a=fmtp:121 apt=127
a=rtpmap:125 H264/90000
a=rtcp-fb:125 goog-remb
a=rtcp-fb:125 transport-cc
a=rtcp-fb:125 ccm fir
a=rtcp-fb:125 nack
a=rtcp-fb:125 nack pli
a=fmtp:125 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:107 rtx/90000
a=fmtp:107 apt=125
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:109 rtx/90000
a=fmtp:109 apt=108
a=rtpmap:124 H264/90000
a=rtcp-fb:124 goog-remb
a=rtcp-fb:124 transport-cc
a=rtcp-fb:124 ccm fir
a=rtcp-fb:124 nack
a=rtcp-fb:124 nack pli
a=fmtp:124 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d001f
a=rtpmap:120 rtx/90000
a=fmtp:120 apt=124
a=rtpmap:39 H264/90000
<— Transmitting SIP response (478 bytes) to WSS:10.10.10.70:50758 —>
SIP/2.0 401 Unauthorized
Via: SIP/2.0/WSS 192.0.2.254;rport=50758;received=10.10.10.70;branch=z9hG4bK9756702
Call-ID: hs5dgk0n927dvgn1uaan
From: “prathibhab” sip:101001@bp1.erss.in;tag=jud8opvn3c
To: sip:101002@bp1.erss.in;tag=z9hG4bK9756702
CSeq: 1 INVITE
WWW-Authenticate: Digest realm=“asterisk”,nonce=“1676011526/d744eed67b737a66150d7633ee6e4351”,opaque=“4f7ddd973ad2ff35”,algorithm=md5,qop=“auth”
Server: Asterisk PBX certified/18.9-cert3
Content-Length: 0

m=video 63391 UDP/TLS/RTP/SAVPF 96 97 102 122 127 121 125 107 108 109 124 120 39 40 45 46 98 99 100 101 123 119 114 115 116
list all the codec options past 39, so 40 45 46 98 99 100 101 123 119 114 115 116
but there are no a=rtpmap: ... lines for all of these codecs from 40 onwards.
After a=rtpmap:39 H264/90000 it stops.

**Comment by fippo** [comment]
As the template you deleted should have told you this repository is about the samples at https://webrtc.github.io/samples/, not issues with Asterisk.
