### ISSUE TITLE
Scalable Video Coding example needs update

### ISSUE THREAD

**Issue by opusonline** [webrtc/samples#1594]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**
no specific version, but I have tested it with Chrome 111.0.5563.64

## Description

Thank you for having the [Scalable Video Codec](https://webrtc.github.io/samples/src/content/extensions/svc/) sample, but unfortunately it relies on using an outdated and non-working feature, so the sample can't be used.

https://github.com/webrtc/samples/blob/gh-pages/src/content/extensions/svc/js/main.js#L108

The sample uses the SVC extension of `.getCapabilities()`, but this has been removed. It should be replaced with the current working method `navigator.mediaCapabilities.encodingInfo` with video `scalabilityMode` parameter.

Here's the discussion about "getCapabilities() vs. MediaCapabilities":
- https://github.com/w3c/webrtc-svc/issues/49
- https://github.com/w3c/webrtc-svc/pull/76

## Steps to reproduce

Open https://webrtc.github.io/samples/src/content/extensions/svc/ in any browser that supports SVC (currently Chrome since v111, see https://chromestatus.com/feature/5769626174619648) and select any codec that should support scalability modes, like VP9 or AV1.

## Expected results

The "Scalability Mode" dropdown should act accordingly and contain supported scalability modes for each selected codec.

## Actual results

The "Scalability Mode" dropdown will always stay disabled and only contain the option "NONE".

**Comment by alvestrand** [comment]
Florent, can you take on the task to update this?

**Comment by alvestrand** [comment]
the fix shoujld be a fine example of how to use MediaCapabilities to work around the lack of an enumeration feature.

**Comment by Orphis** [comment]
Fixed by #1595.
