### ISSUE TITLE
No SRFLX ICE candidates?

### ISSUE THREAD

**Issue by rafalsk** [webrtc/samples#1604]
The issue is described in its fullness at:
https://stackoverflow.com/questions/75946023/should-a-client-which-is-not-behind-a-nat-receive-srflx-ice-candidates

when compared with https://icetest.info/ the results are not coherent. In particular, no SRFLX  is ever generated on a host which is publicly facing the Internet . Running Chrome 112.0.5615.50  on Windows 11.

**Comment by fippo** [comment]
see https://bugs.chromium.org/p/chromium/issues/detail?id=1431400
(and please, don't file in many places, I would prefer to explain once)
