### ISSUE TITLE
[Sample PeerConnection Channel] - The all sound turn off after enable navigator.mediaDevices.getUserMedia

### ISSUE THREAD

**Issue by tiennguyen1293** [webrtc/samples#1606]
Based on the sample: https://webrtc.github.io/samples/src/content/peerconnection/channel

I play the sound (play the audio file) and after that is get permission microphone from `navigator.mediaDevices.getUserMedia`
And then issues happened the sound from the audio file turned off and I just did not hear any more.

I research for many days to resolve this but can not see the answer. It just happens on some laptops (ASUS Laptop - Window 11 - Brower Chrome Version 112.0.5615.121 (latest))

Please help resolve this issue, Thanks

Code here: https://codesandbox.io/s/webrtc-n35bzf

- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x] I have provided steps to reproduce
- [x] I have provided the browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

## Browser affected

**Chrome 112.0.5615.121 (latest)**

## Steps to reproduce
- Click the "Start" button and wait a few seconds. The sound may stop playing.

## Expected results
- Can play sounds, including ringback tones, after obtaining permission to access the microphone using navigator.mediaDevices.getUserMedia.

## Actual results
- Didn't hearing any sound after obtaining permission to access the microphone using `navigator.mediaDevices.getUserMedia`

**Comment by tiennguyen1293** [comment]
screenshot OS from device
![image](https://user-images.githubusercontent.com/26110369/233557901-b299a2b9-1bf5-459b-95d2-ff18daa776b1.png)

**Comment by fippo** [comment]
This isn't an issue with the samples from this repository and you filed https://bugs.chromium.org/p/chromium/issues/detail?id=1435338& in addition.
