### ISSUE TITLE
navigator.mediaDevices.getUserMedia doesn't work on macos catalyst WKWebView

### ISSUE THREAD

**Issue by denmorgenshtern** [webrtc/samples#1627]
I've got the following error on Mac Catalyst WKWebView:

`TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')`

macOS 13.5 / 14.0
Safari 17.0

The same app works well on iOS.

I have added native checks for camera and microphone access. If they are not available, I make a request. After both are approved, checkboxes appear in the privacy settings of macOS. However, I still receive the same error. Interestingly, iOS does not have any access checks; the request is automatically initiated, presumably by Safari.

**Comment by fippo** [comment]
Not an issue with the samples, please file a webkit bug.
