### ISSUE TITLE
mp4 mimeType is downloaded with .webm extension, not a mp4.

### ISSUE THREAD

**Issue by sunggook** [webrtc/samples#1635]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [ x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [x ] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected
Chromium browsers.

**Browser name including version (e.g. Chrome 64.0.3282.119)**
Chrome (v120+). (The latest Chrome Canary).

## Description
Experimental Mp4 muixer is supported in the Chromium with disabled feature flag 
(see how to use, https://docs.google.com/document/d/1v0gTkKiH9j9ZXM65aNMpqnj7vp1AfuPp4wlqUu6Gi6o/edit#heading=h.v718fqi0xl4e).

When recorded with 'video/mp4,codecs=h264,aac', it is downloaded as a .webm file.

## Steps to reproduce
Download Chrome Canary if not in machine (v120+)
Launch the chrome with command line flag –enable-features=MediaRecorderEnableMp4Muxer
Go to WebRtc sample site.
Recording with mimeType of ‘video/mp4,codecs=h264,aac’.

## Expected results
Downloaded as .mp4 file.

## Actual results
Downloaded as .webm file.

**Comment by fippo** [comment]
https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/record/js/main.js#L49
i guess this needs to get a bit smarter and determine mimeType and file ending based on the input/recorded format
