### ISSUE TITLE
Can a shared surface select its derivative window？

### ISSUE THREAD

**Issue by trookie2000** [webrtc/samples#1639]
For example, after clicking the button with the red line shown in the picture, the pop-up window should also be shared

![image](https://github.com/webrtc/samples/assets/109945614/47700625-902a-4eb5-adfe-7e6211fe1add)
But now the pop-up is not shared (even though it belongs to the first shared process pop-up).

![image](https://github.com/webrtc/samples/assets/109945614/c89e0e4e-c4da-4d8e-ab9f-eac4b95bbd70)

**Comment by alvestrand** [comment]
This seems irrelevant to the WebRTC Samples.
