### ISSUE TITLE
On some of my machines I got the error "Error creating offer: SyntaxError: Failed to construct 'RTCPeerConnection': '' is not a valid URL."

### ISSUE THREAD

**Issue by qiulang** [webrtc/samples#1647]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [x] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [ ] I have provided steps to reproduce
- [x] I have provided browser name and version
- [x] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

```
  System:
    OS: macOS 14.1.2
    CPU: (8) arm64 Apple M2
    Memory: 82.39 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Browsers:
    Chrome: 120.0.6099.109
    Safari: 17.1.2
```

## Description

On some of my machines, when trying https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

I get "Error creating offer: SyntaxError: Failed to construct 'RTCPeerConnection': '' is not a valid URL."

<img width="956" alt="Failed to construct 'RTCPeerConnection" src="https://github.com/webrtc/samples/assets/516243/7cbd6c81-cae9-4b84-bce0-209bd94c1c8b">

The console log shows ,
```
Creating new PeerConnection with config={"iceServers":[{"urls":["stun:stun.l.google.com:19302"]},{"urls":[""],"username":"","credential":""},{"urls":[""],"username":"","credential":""},{"urls":[""],"username":"","credential":""}],"iceTransportPolicy":"all"}
```

## Steps to reproduce

I have restart the machines and Chrome, but I still get the error. But other browsers do not have it.

**Comment by alvestrand** [comment]
"" is not a legal URL, so the error message is quite correct.

I can reproduce the error by pressing "Add Server" a few times before hitting "Gather candidates" without filling in anything in the URI field of the form. Is this what's happening?

It might be good if the UI did not allow adding an empty URI.

**Comment by qiulang** [comment]
But I didn't know how I triggered the problem and it just happened and only happened in some of my machine.

**Comment by alvestrand** [comment]
Try it again and be careful to NOT touch the "Add Server" button, and see if you can reproduce.

**Comment by qiulang** [comment]
On one of my machine it  always happens now but it used to work so I had thought it may be because of some Chrome extensions I installed. I closed all these extension but it still happens. On my other machine I still can not trigger it.

**Comment by fippo** [comment]
The "Reset to defaults" button should clear the invisible elements. But we should not be adding them in the first place...

**Comment by qiulang** [comment]
@fippo yes "Reset to defaults" does fix my problem.  I just can't find out why it happened in the first place.

**Comment by qiulang** [comment]
Hi I am closing this issue as I don't want to "waste" my time on this minor issue.

**Comment by alvestrand** [comment]
See if PR #1648 fixes your issue.
