### ISSUE TITLE
ScriptProcessorNode deprecated in Chrome 121.

### ISSUE THREAD

**Issue by benbro** [webrtc/samples#1649]
- [ +] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [ +] I have provided steps to reproduce
- [ +] I have provided browser name and version
- [ +] I have provided a link to the sample here or a modified version thereof

## Browser affected
Chrome 121.0.6167.160

## Description
ScriptProcessorNode is deprecated in Chrome 121 but still works.
Console warning suggests to use AudioWorkletNode. Supported on all browsers and Safari 14.1:
https://developer.mozilla.org/en-US/docs/Web/API/AudioWorklet#browser_compatibility
https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/volume/js/soundmeter.js#L21

## Steps to reproduce
Open demo in Chrome 121:
https://webrtc.github.io/samples/src/content/getusermedia/volume/

## Expected results
No console warning.

## Actual results
Console warning.
```
soundmeter.js:21 [Deprecation] The ScriptProcessorNode is deprecated. Use AudioWorkletNode instead. (https://bit.ly/audio-worklet)
```

**Comment by fippo** [comment]
see #1509
