### ISSUE TITLE
Can not play video stream in my web app from remote phone. 

### ISSUE THREAD

**Issue by AdelGiniyatullin** [webrtc/samples#1661]
Hello! I have my web application with streaming from a remote phone to a browser. We exchange SPD and ICE candidates, the connection is established, but when I try to play the media stream in the <video></video> tag, I only hear sound but no video. I've already checked, the video stream is coming to me, its status is enabled and live. I've tried everything, but nothing helps. In the SDP, the stream is described as bundled, meaning both audio and video are transmitted over a single connection. Perhaps that's why the browser only specifies sdpmid 0 in the candidates; it reads everything as one stream. Please help me to solve my problem)

**Comment by fippo** [comment]
As noted in the template, this repository is not a place for general webrtc problems.
