### ISSUE TITLE
the video keeps not showing up

### ISSUE THREAD

**Issue by kun510** [webrtc/samples#1666]
my code:
peerConnection.ontrack = function(event) {
                console.log('Set up ontrack handler successfully');
                console.log('Received remote stream event:', event);
                console.log('Received remote stream:', event.streams[0]);
                console.log('MediaStream tracks:', event.streams[0].getTracks());
                event.streams[0].getVideoTracks().forEach(track => {
                    track.enabled = true;
                });
       
                try {
                    if(event.streams && event.streams[0]) {
                       video.srcObject = event.streams[0];
                      console.log('Video srcObject set to remote stream');
                      console.log('Video srcObject:', video.srcObject);
                    }else{
                        console.log('No stream found');
                    }
                } catch (error) {
                    console.error('Error setting srcObject:', error);
                }
            };
    Log:
    Set up ontrack handler successfully
(index):125 Received remote stream event: RTCTrackEvent {isTrusted: true, receiver: RTCRtpReceiver, track: MediaStreamTrack, streams: Array(1), transceiver: RTCRtpTransceiver, …}isTrusted: truebubbles: falsecancelBubble: falsecancelable: falsecomposed: falsecurrentTarget: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, onerror: ƒ, …}defaultPrevented: falseeventPhase: 0receiver: RTCRtpReceiver {track: MediaStreamTrack, transport: RTCDtlsTransport, rtcpTransport: null, playoutDelayHint: null, jitterBufferTarget: null}returnValue: truesrcElement: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, onerror: ƒ, …}streams: [MediaStream]target: RTCPeerConnection {localDescription: RTCSessionDescription, currentLocalDescription: RTCSessionDescription, pendingLocalDescription: null, remoteDescription: RTCSessionDescription, onerror: ƒ, …}timeStamp: 9550track: MediaStreamTrack {kind: 'video', id: '63f076da-8d01-4338-a574-8fbacb71f748', label: '63f076da-8d01-4338-a574-8fbacb71f748', enabled: true, muted: true, …}transceiver: RTCRtpTransceiver {mid: '0', sender: RTCRtpSender, receiver: RTCRtpReceiver, stopped: false, direction: 'recvonly', …}type: "track"[[Prototype]]: RTCTrackEvent
(index):126 Received remote stream: MediaStream {id: '1840e418-9a27-40d2-9c04-98db65d6b45e', active: true, onaddtrack: null, onremovetrack: null, onactive: null, …}active: trueid: "1840e418-9a27-40d2-9c04-98db65d6b45e"onactive: nullonaddtrack: nulloninactive: nullonremovetrack: null[[Prototype]]: MediaStream
(index):127 MediaStream tracks: [MediaStreamTrack]
(index):135 Video srcObject set to remote stream
*****
It clearly has data but it doesn't display the video
![image](https://github.com/webrtc/samples/assets/89560519/045ea299-f3e8-4487-9b1a-35c9671c8c35)

![Screenshot 2024-06-25 105152](https://github.com/webrtc/samples/assets/89560519/6f0b2c1e-c842-4994-84f5-5735da3df69d)

**Comment by fippo** [comment]
Not related to the samples, as noted in the deleted template this repository is not a general support place for WebRTC

**Comment by Yaqing2023** [comment]
Have you found a solution for your issue? I ran into something similar, a video sent from machine A to machine B, I ca see track added and media Stream  live, etc, but the video just not play on machine B.
