### ISSUE TITLE
Other streams like as Camera stream and put them in peer connections

### ISSUE THREAD

**Issue by mojtabaesfandiari** [webrtc/samples#1678]
HI there, 
Is it possible to use other streams (for example camera streams with RTSP) instead of getUserMedia() to capture streams and relay streams to a remote peer connection with the ability to change bandwidth on the fly?
Which sample code can help me to use it for development?
Thanks

**Comment by fippo** [comment]
as stated in the template you choose to ignore:
> Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
