### ISSUE TITLE
Android Gradle Dependency Not resolve

### ISSUE THREAD

**Issue by MohammadrezaAbbaszade** [webrtc/samples#1681]
# Please read first!
Please use [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) for general technical discussions and questions.
If you have found an issue/bug with the native `libwebrtc` SDK or a browser's behaviour around WebRTC please create an issue in the relevant bug tracker. You can find more information on how to submit a bug and do so in the right place [here](https://webrtc.googlesource.com/src/+/refs/heads/main/docs/bug-reporting.md)

- [ ] I understand that issues created here are _only_ relevant to the samples in this repo - not browser or SDK bugs 
- [ ] I have provided steps to reproduce
- [ ] I have provided browser name and version
- [ ] I have provided a link to the sample here or a modified version thereof

**Note: If the checkboxes above are not checked (which you do after the issue is posted), the issue will be closed.**

## Browser affected

**Browser name including version (e.g. Chrome 64.0.3282.119)**

**Comment by MohammadrezaAbbaszade** [comment]
I have been using the webRtc dependency in my android project based on webRtc document for several years: org.webrtc:google-webrtc:1.0.32006.

But recently, when I wanted to use this library again and sync the project, I encountered the error "Failed to resolve: org.webrtc:google-webrtc:1.0.32006".

Has there been a change or relocation in the library or repository?
Thank you for your guidance

**Comment by fippo** [comment]
This repository is, as the template you ignored points out, not the right place to ask.

See https://groups.google.com/g/discuss-webrtc/c/Ozvbd0p7Q1Y/m/M4WN2cRKCwAJ from 2019 for the latest on the outdated prebuilt library you use.

**Comment by MohammadrezaAbbaszade** [comment]
Sorry,Where is the right place to ask questions about my problem?
I thought I should ask my question in this repository because it is related to your library.
