### ISSUE TITLE
Remote Audio Data callback.

### ISSUE THREAD

**Issue by 48737304** [webrtc/samples#1685]
Dear WebRTC Team,

Could you please consider implementing a delegate callback for RTCAudioTrack to expose the remote audio data to the upper-layer applications through a delegate?

Thank you!

**Comment by alvestrand** [comment]
Have you looked at Breakout Box (mediacapture-transform)?
This doesn't seem directly relevant to samples, so closing here.

**Comment by 48737304** [comment]
I am based on the swift version of google Webrtc (GoogleWebRTC(1.1.32000)). I now need to record remote audio data, but I didn't find a similar proxy callback method to obtain remote audio data.
