### ISSUE TITLE
pr-answer sample is broken

### ISSUE THREAD

**Issue by smurugu** [webrtc/samples#178]
The sample does not seem to display video on Party B (callee) on both Canary and GA versions

40.0.2176.0 canary (64-bit)
38.0.2125.104

http://googlechrome.github.io/webrtc/samples/web/content/peerconnection/pr-answer/

**Comment by KaptenJansson** [comment]
webrtc bug: https://code.google.com/p/webrtc/issues/detail?id=3349.

**Comment by SteveCuiPanPan** [comment]
Issue - I still see this error in the js console:Failed to set local  sdp: Session error code: ERROR_TRANSPORT. Session error description: Couldn't set up DTLS-SRTP on RTP channel..

Who can tell me how to solve this problem? Thanks a lot.

**Comment by KaptenJansson** [comment]
This works in >= M48, please try it out.

**Comment by samdutton** [comment]
BTW: This is now at https://webrtc.github.io/samples/src/content/peerconnection/pr-answer. 

Also — can't remember why this was never ported to the new sample format. Raised issue #704.

**Comment by KaptenJansson** [comment]
Closing due to age.

**Comment by mustadev** [comment]
example in  https://webrtc.github.io/samples/src/content/peerconnection/pr-answer. does not work.
does not show remote stream.
