### ISSUE TITLE
Add more lint criteria/rules to CSS-, HTML-, JSHint- and JSCS lint files.

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#202]
There has been quite a lot of style nits lately which are annoying to fix afterwords, also it results in lots of work after the initial pull request.

We should go through the styleguides and add as many rules as we can, also go through some pull requests to make sure we pickup the nit's there as well (ideally they should be in the styleguide already).

Sam, let me know if you do not have the bandwidth for this.

**Comment by samdutton** [comment]
I've fixed the samples to validate with JSCS.

Strongly recommend installing the SublimeLinter-jscs plugin for Sublime
Text - note that you must install jscs and SublimeLinter first: good
article here:
https://yannick.cr/posts/enforcing-coding-rules-in-your-team-with-jscs/post.

In background mode the Sublime Text jscs linter highlights errors in the
page as you type and displays error explanations in the status bar. Select
debug mode from Tools > SublimeLinter if linting isn't working.

For me, running JSCS from grunt doesn't show error explanations, even with
--verbose (I've asked).

I've added a .jscsrc file which allows two things which JSCS complains
about but which (as far as I can tell - prove me wrong!) aren't actually
mentioned in the Google JavaScript style guide:
* multiple var declarations only allowed if undefined, e.g. var foo, bar;
but not var foo = 1, bar = {x: 1, y: 2};
* maximum line length - I've set this to 100 - I think the maximum line
length should be 80, but 100 allows some leeway for a few situations where
the slightly longer length seems neater.

I've added a note about JSCS checking to the Developer's Guide.

**Comment by samdutton** [comment]
After discussion with @andresusanopinto, I've removed the rule exclusions.

JavaScript must now validate against the Google preset rules: one var
declaration per line, max line length 80.

**Comment by KaptenJansson** [comment]
@samdutton what's the latest here?

**Comment by samdutton** [comment]
I think this can be closed: we changed the code to match the rules.
