### ISSUE TITLE
Improve timeout on stopCollectingAudio

### ISSUE THREAD

**Issue by andresusanopinto** [webrtc/samples#246]
It seems collecting audio from a microphone is reasonable flaky to the point one needs to wait 2 seconds to start getting some input from the stream.

Instead of an hard-code timeout of 2 seconds the test should maybe run for as much as 5 seconds terminating as soon as some audio is noticed.. also reporting how long it took to start gathering audio.

**Comment by juberti** [comment]
Please migrate this to testrtc tracker

**Comment by juberti** [comment]
Has this been migrated?

**Comment by KaptenJansson** [comment]
Moved here: https://github.com/webrtc/testrtc/issues/23
