### ISSUE TITLE
Add support for upcoming navigator.getMediaDevices()

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#256]
Original tracked in this [crbug](https://code.google.com/p/chromium/issues/detail?id=340606&q=reporter%3Ame&colspec=ID%20Pri%20M%20Iteration%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified#makechanges)

MediaStreamTrack.getSources() will soon be deprecated.

**Comment by juberti** [comment]
Please migrate this to testrtc tracker

**Comment by juberti** [comment]
migrate to adapter tracker, actually

**Comment by KaptenJansson** [comment]
Migrated to adapter https://github.com/webrtc/adapter/issues/14.
