### ISSUE TITLE
Record events for AppRTC and other demos

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#265]
For example, to record numbers for those who, having navigated to apprtc.appspot.com: 
• call gUM
• request a connection
• get a connection
• get errors
...

Could also add events for icon/button clicks on AppRTC and other demos.

**Comment by vr000m** [comment]
In addition to those listed above we have:

- iceDisconnected: if the interface disappears. If iceConnected again on the same or a different candidate pair, then we can pair disconnections and connections to calculate connectivity disruptions.
