### ISSUE TITLE
Make adapter.js a modern JS library (module systems aware)

### ISSUE THREAD

**Issue by ibc** [webrtc/samples#297]
No one in the world should define a **global** function called `trace()` (and so many other `window` globals defined in `adapter.js`).

`adapter.js` seems to ignore any new design pattern and JS module system (AMD, CommonJS, etc).

Would you accept a PR removing all the global stuff and providing a library suitable to be loaded by any existing JS module loader without polluting the `window` global namespace?

**Comment by ibc** [comment]
Hi, finally I've taken a different approach. It covers more than what adapter.js provides as it is a full wrapper over the RTCPeerConnection interface (along with all the other WebRTC interfaces and functions). It is loadable via Node+browserify, AMD, RequireJS, etc, and it does not pollute the global (window) namespace, even stuff like `RTCPeerConnection`, etc. Instead it provides a single entry module called "rtcninja":

https://github.com/ibc/rtcninja.js

The documentation is still missing however.

**Comment by juberti** [comment]
Thanks. 2KLOC seems kind of heavy though for this shim lib. I think we probably want to have something more like willscott's webrtc-adapter.

Perhaps the documentation will make the value more clear, but I was also somewhat wary of the various timers I saw in your implementation.

**Comment by juberti** [comment]
Migrated to other repo
