### ISSUE TITLE
element.mozSrcObject = stream; no longer works in FF >= 34.0.5

### ISSUE THREAD

**Issue by ibc** [webrtc/samples#302]
When Firefox is detected:

```
  // Attach a media stream to an element.
  attachMediaStream = function(element, stream) {
    console.log('Attaching media stream');
    element.mozSrcObject = stream;
  };
```

This no longer works in FF 34.0.5 (nor in the today's Nightly version). BTW the "old fashion?" `element.src = URL.createObjectURL(stream)` does work.

I know that this spec is changing and honestly I don't know how the standard will finally be.

Not sure how to "fix" adapter.js in order to apply one way or another depending on the version of FF.

**Comment by jan-ivar** [comment]
@ibc - I think there's some confusion here. We use element.mozSrcObject in all our tests e.g. http://jsfiddle.net/etj2kaax so it should work. The closest I can think of is we had a period of [timing issues with calling .play() too soon after](https://bugzilla.mozilla.org/show_bug.cgi?id=879717) on non-autoplaying elements, and another with [onloadedmetadata](https://bugzilla.mozilla.org/show_bug.cgi?id=926753) but these are fixed now. Not sure if any of these were specific to using the mozSrcObject form.

Also, adapter.js still seems to use it https://github.com/webrtc/adapter/blob/master/adapter.js#L131

**Comment by jan-ivar** [comment]
Moving comment to new issue

**Comment by ibc** [comment]
Thanks, will comment again if I detect similar problems.
