### ISSUE TITLE
Find a place to manually trigger "Wifi Periodic Scan" test.

### ISSUE THREAD

**Issue by andresusanopinto** [webrtc/samples#325]
Find a way to run the "Wifi Periodic Scan" test from testrtc. Due to its nature (multiple minutes) it cannot be run by default and one may need to have a UI to allow to trigger it.

For now the test is/will be implemented under the "?test_filter=Wifi Periodic Scan" flag.

**Comment by juberti** [comment]
Please migrate this to testrtc tracker

**Comment by juberti** [comment]
Has this been migrated?

**Comment by andresusanopinto** [comment]
Asked Jansson to do it... but now I don't understand what he did :| (will sync tomorrow)

**Comment by KaptenJansson** [comment]
My bad, it did not have the testrtc label hence I missed it. Filed here https://github.com/webrtc/testrtc/issues/22
