### ISSUE TITLE
Enable webrtc.org/samples to point to the WebRTC samples on GitHub

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#363]
For example: 
• webrtc.org/samples would point to [github.com/GoogleChrome/webrtc/index.html](https://github.com/GoogleChrome/webrtc/) 
• webrtc.org/samples/getusermedia/canvas would point to [googlechrome.github.io/webrtc/samples/web/content/getusermedia/canvas](http://googlechrome.github.io/webrtc/samples/web/content/getusermedia/canvas/)

There could also be some shortcuts. For example:
• [webrtc.org/gum](http://googlechrome.github.io/webrtc/samples/web/content/getusermedia/gum/)
• [webrtc.org/pc](http://googlechrome.github.io/webrtc/samples/web/content/peerconnection/pc1/)

**Comment by marwahvikas** [comment]
Sam, do you want me create a new page in webrtc.org named samples and have all the demos listed there pointing to their github links?

**Comment by samdutton** [comment]
Hi Vikas - in terms of maintenance, I think it's simpler just to add links
to the GitHub repo.

I've created webrtc.org/samples and added links to the sample repo, GitHub
Pages, and apprtc for good measure :).

**Comment by juberti** [comment]
Anything remaining, or should we close this?

**Comment by samdutton** [comment]
I think we can close.
