### ISSUE TITLE
The audio and video doesn't work on device pit using the link mentioned in the details

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#370]
when the below link is accessed in the device Pit and tried to click, on call after starting, the video doesn't show and the audio is also not heard in the build 41.0.2272.2/6680.1.0. 
http://googlechrome.github.io/webrtc/samples/web/content/peerconnection/pc1

**Comment by KaptenJansson** [comment]
Can you open the javascript console while the issue mentions occurs and type "pc1" and "pc2", then expand the session description object on both and copy all of the contents and attach it here? 

Thanks!

**Comment by selavazhagan** [comment]
adapter.js:30 15.124: Requesting local stream
adapter.js:30 16.738: Received local stream
adapter.js:30 16.770: Local video currentSrc: blob:http%3A//googlechrome.github.io/c4173c40-ae0d-41b7-addb-33019e4b6616, videoWidth: 2px,  videoHeight: 2px
adapter.js:30 18.316: Starting call
adapter.js:30 18.317: Using video device: 13e10000.gsc
adapter.js:30 18.317: Using audio device: Default
adapter.js:30 18.319: Created local peer connection object pc1
adapter.js:30 18.321: Created remote peer connection object pc2
adapter.js:30 18.325: Added local stream to pc1
adapter.js:30 18.326: pc1 createOffer start
adapter.js:30 18.346: Offer from pc1
v=0
o=- 3411705662451461234 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio video
a=msid-semantic: WMS H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
m=audio 9 RTP/SAVPF 111 103 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:cNiE/rqybwnKnCAK
a=ice-pwd:CqOb/rOpAfWs3dAjjnpIjPAY
a=ice-options:google-ice
a=fingerprint:sha-256 A8:B8:84:F6:45:5D:C8:06:38:33:94:77:DB:8C:30:D5:38:D4:5B:44:E0:07:5B:A4:2C:F1:5D:66:30:E3:FC:44
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:1927704964 cname:ucmvkN/plL6yQPL6
a=ssrc:1927704964 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo c11f4d5c-91e2-4323-9512-ba0cdd5c26fe
a=ssrc:1927704964 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
a=ssrc:1927704964 label:c11f4d5c-91e2-4323-9512-ba0cdd5c26fe
m=video 9 RTP/SAVPF 100 116 117 96
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:cNiE/rqybwnKnCAK
a=ice-pwd:CqOb/rOpAfWs3dAjjnpIjPAY
a=ice-options:google-ice
a=fingerprint:sha-256 A8:B8:84:F6:45:5D:C8:06:38:33:94:77:DB:8C:30:D5:38:D4:5B:44:E0:07:5B:A4:2C:F1:5D:66:30:E3:FC:44
a=setup:actpass
a=mid:video
a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:100 VP8/90000
a=rtcp-fb:100 ccm fir
a=rtcp-fb:100 nack
a=rtcp-fb:100 nack pli
a=rtcp-fb:100 goog-remb
a=rtpmap:116 red/90000
a=rtpmap:117 ulpfec/90000
a=rtpmap:96 rtx/90000
a=fmtp:96 apt=100
a=ssrc-group:FID 2748986645 2406480899
a=ssrc:2748986645 cname:ucmvkN/plL6yQPL6
a=ssrc:2748986645 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo e23834ee-8a98-4b08-8158-1c64c58af2ff
a=ssrc:2748986645 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
a=ssrc:2748986645 label:e23834ee-8a98-4b08-8158-1c64c58af2ff
a=ssrc:2406480899 cname:ucmvkN/plL6yQPL6
a=ssrc:2406480899 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo e23834ee-8a98-4b08-8158-1c64c58af2ff
a=ssrc:2406480899 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
a=ssrc:2406480899 label:e23834ee-8a98-4b08-8158-1c64c58af2ff
adapter.js:30 18.347: pc1 setLocalDescription start
adapter.js:30 18.351: pc2 setRemoteDescription start
adapter.js:30 18.356: pc2 createAnswer start
adapter.js:30 18.818: pc1 setLocalDescription complete
adapter.js:30 18.818: Failed to create session description: CreateAnswer can't be called before SetRemoteDescription.
adapter.js:30 18.924: pc1 ICE candidate: 
candidate:3454352297 1 udp 2122260223 192.168.1.218 59439 typ host generation 0
adapter.js:30 18.926: pc1 ICE candidate: 
candidate:3454352297 2 udp 2122260223 192.168.1.218 59439 typ host generation 0
adapter.js:30 18.927: pc1 ICE candidate: 
candidate:3454352297 1 udp 2122260223 192.168.1.218 59439 typ host generation 0
adapter.js:30 18.927: pc1 ICE candidate: 
candidate:3454352297 2 udp 2122260223 192.168.1.218 59439 typ host generation 0
2adapter.js:30 18.928: pc1 addIceCandidate success
adapter.js:30 18.929: pc1 addIceCandidate success
adapter.js:30 18.930: pc1 addIceCandidate success
adapter.js:30 18.934: pc1 ICE candidate: 
candidate:2204551001 1 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
adapter.js:30 18.939: pc1 ICE candidate: 
candidate:2204551001 2 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
adapter.js:30 18.941: pc1 ICE candidate: 
candidate:2204551001 1 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
adapter.js:30 18.943: pc1 addIceCandidate success
adapter.js:30 18.945: pc1 ICE candidate: 
candidate:2204551001 2 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
adapter.js:30 18.946: pc1 addIceCandidate success
adapter.js:30 18.947: pc1 addIceCandidate success
adapter.js:30 18.948: pc1 addIceCandidate success
pc1
RTCPeerConnection {ondatachannel: null, oniceconnectionstatechange: function, onremovestream: null, onaddstream: null, onsignalingstatechange: null…}iceConnectionState: "new"iceGatheringState: "complete"localDescription: RTCSessionDescriptionsdp: "v=0
↵o=- 3411705662451461234 2 IN IP4 127.0.0.1
↵s=-
↵t=0 0
↵a=group:BUNDLE audio video
↵a=msid-semantic: WMS H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
↵m=audio 59439 RTP/SAVPF 111 103 9 0 8 106 105 13 126
↵c=IN IP4 192.168.1.218
↵a=rtcp:59439 IN IP4 192.168.1.218
↵a=candidate:3454352297 1 udp 2122260223 192.168.1.218 59439 typ host generation 0
↵a=candidate:3454352297 2 udp 2122260223 192.168.1.218 59439 typ host generation 0
↵a=candidate:2204551001 1 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
↵a=candidate:2204551001 2 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
↵a=ice-ufrag:cNiE/rqybwnKnCAK
↵a=ice-pwd:CqOb/rOpAfWs3dAjjnpIjPAY
↵a=ice-options:google-ice
↵a=fingerprint:sha-256 A8:B8:84:F6:45:5D:C8:06:38:33:94:77:DB:8C:30:D5:38:D4:5B:44:E0:07:5B:A4:2C:F1:5D:66:30:E3:FC:44
↵a=setup:actpass
↵a=mid:audio
↵a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:111 opus/48000/2
↵a=fmtp:111 minptime=10; useinbandfec=1
↵a=rtpmap:103 ISAC/16000
↵a=rtpmap:9 G722/8000
↵a=rtpmap:0 PCMU/8000
↵a=rtpmap:8 PCMA/8000
↵a=rtpmap:106 CN/32000
↵a=rtpmap:105 CN/16000
↵a=rtpmap:13 CN/8000
↵a=rtpmap:126 telephone-event/8000
↵a=maxptime:60
↵a=ssrc:1927704964 cname:ucmvkN/plL6yQPL6
↵a=ssrc:1927704964 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo c11f4d5c-91e2-4323-9512-ba0cdd5c26fe
↵a=ssrc:1927704964 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
↵a=ssrc:1927704964 label:c11f4d5c-91e2-4323-9512-ba0cdd5c26fe
↵m=video 59439 RTP/SAVPF 100 116 117 96
↵c=IN IP4 192.168.1.218
↵a=rtcp:59439 IN IP4 192.168.1.218
↵a=candidate:3454352297 1 udp 2122260223 192.168.1.218 59439 typ host generation 0
↵a=candidate:3454352297 2 udp 2122260223 192.168.1.218 59439 typ host generation 0
↵a=candidate:2204551001 1 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
↵a=candidate:2204551001 2 tcp 1518280447 192.168.1.218 0 typ host tcptype active generation 0
↵a=ice-ufrag:cNiE/rqybwnKnCAK
↵a=ice-pwd:CqOb/rOpAfWs3dAjjnpIjPAY
↵a=ice-options:google-ice
↵a=fingerprint:sha-256 A8:B8:84:F6:45:5D:C8:06:38:33:94:77:DB:8C:30:D5:38:D4:5B:44:E0:07:5B:A4:2C:F1:5D:66:30:E3:FC:44
↵a=setup:actpass
↵a=mid:video
↵a=extmap:2 urn:ietf:params:rtp-hdrext:toffset
↵a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
↵a=sendrecv
↵a=rtcp-mux
↵a=rtpmap:100 VP8/90000
↵a=rtcp-fb:100 ccm fir
↵a=rtcp-fb:100 nack
↵a=rtcp-fb:100 nack pli
↵a=rtcp-fb:100 goog-remb
↵a=rtpmap:116 red/90000
↵a=rtpmap:117 ulpfec/90000
↵a=rtpmap:96 rtx/90000
↵a=fmtp:96 apt=100
↵a=ssrc-group:FID 2748986645 2406480899
↵a=ssrc:2748986645 cname:ucmvkN/plL6yQPL6
↵a=ssrc:2748986645 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo e23834ee-8a98-4b08-8158-1c64c58af2ff
↵a=ssrc:2748986645 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
↵a=ssrc:2748986645 label:e23834ee-8a98-4b08-8158-1c64c58af2ff
↵a=ssrc:2406480899 cname:ucmvkN/plL6yQPL6
↵a=ssrc:2406480899 msid:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo e23834ee-8a98-4b08-8158-1c64c58af2ff
↵a=ssrc:2406480899 mslabel:H3kbXFWil11sGioLummNDfC55oLlk6bJddoo
↵a=ssrc:2406480899 label:e23834ee-8a98-4b08-8158-1c64c58af2ff
↵"type: "offer"__proto__: RTCSessionDescriptionconstructor: function RTCSessionDescription() { [native code] }arguments: nullcaller: nulllength: 0name: "RTCSessionDescription"prototype: RTCSessionDescriptiontoString: function toString() { [native code] }__proto__: function Empty() {}<function scope>__proto__: Object__defineGetter__: function __defineGetter__() { [native code] }__defineSetter__: function __defineSetter__() { [native code] }__lookupGetter__: function __lookupGetter__() { [native code] }__lookupSetter__: function __lookupSetter__() { [native code] }constructor: function Object() { [native code] }hasOwnProperty: function hasOwnProperty() { [native code] }isPrototypeOf: function isPrototypeOf() { [native code] }propertyIsEnumerable: function propertyIsEnumerable() { [native code] }toLocaleString: function toLocaleString() { [native code] }toString: function toString() { [native code] }valueOf: function valueOf() { [native code] }get __proto__: function __proto__() { [native code] }set __proto__: function __proto__() { [native code] }onaddstream: nullondatachannel: nullonicecandidate: function (e) {oniceconnectionstatechange: function (e) {onnegotiationneeded: nullonremovestream: nullonsignalingstatechange: nullremoteDescription: RTCSessionDescriptionsignalingState: "have-local-offer"__proto__: RTCPeerConnection
pc2
RTCPeerConnection {ondatachannel: null, oniceconnectionstatechange: function, onremovestream: null, onaddstream: function, onsignalingstatechange: null…}iceConnectionState: "new"iceGatheringState: "new"localDescription: RTCSessionDescriptionsdp: ""type: ""__proto__: RTCSessionDescriptionconstructor: function RTCSessionDescription() { [native code] }__proto__: Objectonaddstream: function gotRemoteStream(e) {arguments: (...)get arguments: function ThrowTypeError() { [native code] }arguments: nullcaller: nulllength: 0name: "ThrowTypeError"prototype: ThrowTypeError__proto__: function Empty() {}<function scope>set arguments: function ThrowTypeError() { [native code] }caller: (...)get caller: function ThrowTypeError() { [native code] }set caller: function ThrowTypeError() { [native code] }length: 1name: "gotRemoteStream"prototype: gotRemoteStream__proto__: function Empty() {}<function scope>ondatachannel: nullonicecandidate: function (e) {oniceconnectionstatechange: function (e) {onnegotiationneeded: nullonremovestream: nullonsignalingstatechange: nullremoteDescription: RTCSessionDescriptionsignalingState: "have-remote-offer"__proto__: RTCPeerConnection

**Comment by selavazhagan** [comment]
Hi Chris,

I have attached the logs from the console on the device Pit when the issue
was seen.

Regards,
Shankari.

**Comment by tednakamura** [comment]
After further discussion, it seems like this error only occurs on a particular device. I think this bug can be closed, and let's move the discussion to https://code.google.com/p/chromium/issues/detail?id=448912
