### ISSUE TITLE
Pull request #13 introduces lots of JShint errors

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#385]
Please install grunt and friends and fix all the styleguide errors according to the [developers guide](https://docs.google.com/document/d/1tn1t6LW2ffzGuYTK3366w1fhTkkzsSvHsBnOHoDfRzY/edit). 

If you have strong feelings and a good reason for this not to be part of the lint/hint checks we can add an exception.

**Comment by alvestrand** [comment]
Wonderful to know that there is such a thing as a developer's guide for the project.
Do you have a pointer to how to run exactly the tests that Travis runs for the project?
(I've found the Travis doc to be largely incomprehensible on this subject)

**Comment by KaptenJansson** [comment]
When you have installed grunt, it will run the same tests as tavis.
Follow the [grunt guide](http://fcfeibel.com/blog/2013/07/28/grunt-quickstart-set-up-grunt-with-jshint/) in the developers guide to get started.

**Comment by samdutton** [comment]
>
> When you have installed grunt, it will run the same tests as tavis.


Yes - the project is configured on the Travis website
<https://travis-ci.org/>, then Travis listens via the GitHub API for pull
or push requests.

Each time there's a request to the repo, Travis fires up Node and runs the
command defined by the scripts.test property in /package.json
<https://github.com/GoogleChrome/webrtc/blob/master/package.json>, which
for this project is `grunt --verbose`. You can see the logs at
travis-ci.org/GoogleChrome/webrtc.

Travis can also be configured to run other build tasks, but we only use it
to report success or failure - which is signified by email and the build
pass/fail icon displayed on /README.md
<https://github.com/samdutton/webrtc/blob/demo-updates/README.md>.

We should probably set up additional notification recipients for
success/failure in travis.yml. (More information about ways to set
notification options here
<http://docs.travis-ci.com/user/notifications/#Notifications> - can use IRC
and webhooks, specify success and failure responses, etc.)

More information about Travis here
<https://docs.google.com/document/d/1tn1t6LW2ffzGuYTK3366w1fhTkkzsSvHsBnOHoDfRzY/edit#heading=h.ejd2dubhr7xa>
.

**Comment by juberti** [comment]
This new sample should go underneath the /getusermedia folder.

**Comment by KaptenJansson** [comment]
@alvestrand can we close this?

**Comment by alvestrand** [comment]
Yes, please close this. jan-ivar has supplied better functionality in adapter.js.
