### ISSUE TITLE
Grunt/JSCS is not running for samples

### ISSUE THREAD

**Issue by chuckhays** [webrtc/samples#402]
Grunt-JSCS can't find it's config file specified by 'google', and is silently failing. 

This change enables it, but there are a bunch of errors to fix, or rules to adjust, before we can merge it:
https://github.com/chuckhays/webrtc/commit/7fd09eea6746f120b982c6c6600280e27e6f17e2

@samdutton @jiayliu @juberti

**Comment by samdutton** [comment]
I set this up with the wrong key (or maybe it changed): it should be
preset: 'google' not config: 'google'.

See github.com/jscs-dev/grunt-jscs for more information.

As you say - this results in a number of errors in testrtc files.

I think we should change to preset: 'google' and fix the problems, and
maybe create a separate (additional) config file, or (better) use .jscsrc.

Sam

**Comment by chuckhays** [comment]
I'll try the preset key, I had to dig into the node module to figure out how to make it do anything at all with the config file. Hopefully preset will be simpler.

**Comment by chuckhays** [comment]
We should keep this open to track fixing the other sources. @samdutton do you have any suggestions who might be the right people for the other areas? I can take some of them too, just wasn't sure who typically does each area.

**Comment by juberti** [comment]
@KaptenJansson for testrtc
@samdutton for samples

**Comment by samdutton** [comment]
See #469 .

**Comment by samdutton** [comment]
Fixed in #469.
