### ISSUE TITLE
Show selfview on landing page

### ISSUE THREAD

**Issue by juberti** [webrtc/samples#425]
Something to try out and see if we like. We might want to apply a blur effect to reduce distraction.

**Comment by jiayliu** [comment]
I changed the media request to be made when Call is created in the greenroom PR, which is related to this issue.

**Comment by chuckhays** [comment]
Something to look at:
8d9d3d039e161f59587bd0f72ce71e2ce9e55b0d
This loads the video under the loading page. Right now it is very dim, and also blurred, to avoid having to add a background behind the room selection UI. We could make it brighter if we wanted, and add a frame around the room selection UI.

Screen shot below, but it is hard to get the experience from a screen shot.

![screen shot 2015-01-28 at 10 49 26 am](https://cloud.githubusercontent.com/assets/1405600/5944379/6295f838-a6db-11e4-8216-e37fa4ab158c.png)

**Comment by jiayliu** [comment]
We can get some designer input tomorrow. But I personally feel the dimmed self preview a bit strange. I'd move the room selection UI to the side or corner with the self preview in the background, or put self preview and room selection side by side.

**Comment by juberti** [comment]
I really like the transition from landing page to waiting state. Feels very natural.

I do see Jiayang's point about the overlay of the selection UI over the video; as it ends up over your face, it doesn't feel quite right.

I messed around with the filters a bit to try to make it less distracting. The screenshot below does grayscale and a 16px blur, which I think helps considerably.

![screen shot 2015-01-28 at 5 11 41 pm](https://cloud.githubusercontent.com/assets/1821693/5950637/b9e71a14-a711-11e4-83ea-ecb5b5e8517d.png)

**Comment by juberti** [comment]
I also tried messing around with making the room selection div more opaque, although I wasn't able to get anything I really liked. One such attempt:

![screen shot 2015-01-28 at 5 23 12 pm](https://cloud.githubusercontent.com/assets/1821693/5950698/606683fc-a712-11e4-8162-afb33264294b.png)

**Comment by chuckhays** [comment]
I was thinking about doing something like the dialog in the image below, but it required changing from dark->light so I didn't try it yet.

http://material-design.storage.googleapis.com/publish/v_2/material_ext_publish/0B8v7jImPsDi-Q3BQOERCOG5tNW8/components_dialogs_content1.png

![components_dialogs_content1](https://cloud.githubusercontent.com/assets/1405600/5959957/f20b1cea-a786-11e4-9160-41266fcd42fe.png)

**Comment by juberti** [comment]
Did you try doing something like that with a dark background? If the div in my example were a bit wider, I think that might work OK.
