### ISSUE TITLE
Chrome app doesn't send /bye on close.

### ISSUE THREAD

**Issue by chuckhays** [webrtc/samples#437]

**Comment by jiayliu** [comment]
Is this fixed in #424?

**Comment by chuckhays** [comment]
There are 2 issues.

1. If you close the app window, no bye message is sent, because onbeforeunload is not available in Chrome Apps
2. Sync xhr is not available in Chrome apps, so even when you hit hangup, the messages don't get sent.  

I started working on these but it isn't as simple as changing the xhr to async, because there is a specific ordering we need, and we need to finish the work before the window closes. I'll continue to work on a fix.

**Comment by jiayliu** [comment]
Is there a solution for the first issue?

On Thu, Jan 29, 2015 at 1:09 PM, Chuck Hays <notifications@github.com>
wrote:

> There are 2 issues.
>
>    1. If you close the app window, no bye message is sent, because
>    onbeforeunload is not available in Chrome Apps
>    2. Sync xhr is not available in Chrome apps, so even when you hit
>    hangup, the messages don't get sent.
>
> I started working on these but it isn't as simple as changing the xhr to
> async, because there is a specific ordering we need, and we need to finish
> the work before the window closes. I'll continue to work on a fix.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/GoogleChrome/webrtc/issues/437#issuecomment-72104433>.
>



-- 
Jiayang Liu

**Comment by chuckhays** [comment]
The background.js file can detect when the window closes, and can do the cleanup. This is how it can be hooked up:
https://github.com/chuckhays/webrtc/commit/e1a48f5ce5cd08b3addb18e6ac83e64bf784939f

The next step is to re-arrange things so the needed context is still available. Chrome starts disposing objects that we still need in order to make the ending calls.

**Comment by juberti** [comment]
Is there a bug for this in the apprtc repo?
