### ISSUE TITLE
Sample page showing a failing gUM A+V request falling back to gUM audio-only request

### ISSUE THREAD

**Issue by tednakamura** [webrtc/samples#447]
http://w3c.github.io/mediacapture-main/#dom-mediadevices-getusermedia indicates that if all requested media types aren't available, gUM should return an error. This means it's an application's responsibility, rather than browser's responsibility, to detect that error and appropriately handle it in the gUM error callback. Could a sample app be written that does the following to showcase this behavior? The general workflow I'm imagining is:

1) User with a microphone, but no camera, opens the page.
2) The user clicks a button and the page makes an audio and video gUM request.
3) That gUM request fails, and without any user intervention, the page then makes an audio-only gUM request.
4) That audio-only gUM request succeeds. I don't have a preference for what should go in the success callback, but it would be nice to have some sort of visible or audible indicator of success.

**Comment by juberti** [comment]
AppRTC should also do this - please file a bug in AppRTC for this functionality

**Comment by jiayliu** [comment]
Is it assigned to me to add this to apprtc only, or samples also?

**Comment by juberti** [comment]
apprtc, I think that should be sufficient for now

**Comment by jiayliu** [comment]
Opened issue in apprtc repo. Should this one be closed?
