### ISSUE TITLE
Failures in Python tests don't break Travis.

### ISSUE THREAD

**Issue by milkypostman** [webrtc/samples#451]
Consider: https://travis-ci.org/GoogleChrome/webrtc/builds/48841035

If you scroll down you can see the Python tests broke but the build says it passes.

**Comment by chuckhays** [comment]
Same thing happens with the jstdPhantom tests unfortunately. I know I'd feel a lot better if failures caused the grunt build to fail instead of having to look at the text closely.

**Comment by milkypostman** [comment]
There has to be a way to enable this.

**Comment by juberti** [comment]
Please migrate this to the apprtc repo

**Comment by KaptenJansson** [comment]
Migrated
