### ISSUE TITLE
Pull adapter.js as a dependency

### ISSUE THREAD

**Issue by juberti** [webrtc/samples#472]
Instead of including our own copy.

**Comment by KaptenJansson** [comment]
I'm looking into this, I spoke to @alvestrand and we came to the conclusion that we should use npm. WDYT? 

The downside is that we have to include the "node_modules" folder when we push to gh-pages branch. No manual step (other than npm install ofc) if we keep all plugins in the folder but if we want to clean it out prior pushing to gh-pages each npm plugin installed has to be removed.

**Comment by alvestrand** [comment]
Either npm or bower should work; npm seems a bit more popular. @flippo says we can call the npm module "webrtc" if we want to.
I'm not sure whether using npm requires use of browserify when installing JS to the server. I'll experiment.
(package publishing also needs tests. I'll add some to adapter.js.)

**Comment by KaptenJansson** [comment]
Assigning to @alvestrand for now.

**Comment by piranna** [comment]
The node_modules is not necesary for gh-pages at all... why do you think it's needed?

**Comment by piranna** [comment]
If you think about using them to publish de samples, I think is better to use bower, since it's focused for browsers Javascript.

**Comment by KaptenJansson** [comment]
It is needed if we install adapter.js via npm.

**Comment by alvestrand** [comment]
Check out PR #520 and see what you think. This makes the update manual (but scripted), which might be a Good Thing.

**Comment by alvestrand** [comment]
Marking as resolved - after PR #520 doing "npm install" will auto-update the adapter.js script.
