### ISSUE TITLE
adapter.js path has changed, apps using bower are broken

### ISSUE THREAD

**Issue by piranna** [webrtc/samples#475]
After moving adapter.js to its own repository, bower registry still point to this one. Problem is, that location of adapter.js on this repo [has changed](https://github.com/webrtc/samples/commit/90811ac692f3f1b7bc0ced814ec0cce5477467bb) from ```samples/web/js``` to ```src/js```, leading that all the webapps that were using bower and the old location now are broken because adapter.js can't be found. I know that moving the bower registry [is on process](https://github.com/bower/bower/issues/120#issuecomment-73019850), but we would need to have a solution until that occurs. Maybe a symlink is just enough, but if not, another one is just to put a copy of adapter.js on its old location until bower use the new repository.

**Comment by piranna** [comment]
Another option, that's also not incompatible, is to add another copy on the root of the project since it's the location on the new repo, so the transition can be easier.

**Comment by andresusanopinto** [comment]
Another solution would be to move this repo back to the old location.. do
bower unregister, then move it back... but I am afraid if that breaks any
github redirection things... so I am leaning towards wait for bower devs to
fix it.

**Comment by piranna** [comment]
Github redirections are not a problem, it's related to the location of the
files.

**Comment by andresusanopinto** [comment]
bower has been updated to point to the new github.com/webrtc/adapter.js

**Comment by piranna** [comment]
It's still pointing me to the old one...

```
[piranna@Mabuk:~/workspace/kurento-tutorial-node/kurento-platedetector]
 (develop) > bower cache clean

[piranna@Mabuk:~/workspace/kurento-tutorial-node/kurento-platedetector]
 (develop) > bower info adapter.js
bower adapter.js#*          not-cached git://github.com/webrtc/samples.git#*
bower adapter.js#*             resolve git://github.com/webrtc/samples.git#*
bower adapter.js#*            checkout master
bower adapter.js#*        invalid-meta adapter.js is missing "main" entry in bower.json
bower adapter.js#*        invalid-meta adapter.js is missing "ignore" entry in bower.json
bower adapter.js#*            resolved git://github.com/webrtc/samples.git#46e8844166

{
  name: 'adapter.js',
  homepage: 'https://github.com/webrtc/samples'
}

No versions available.
```
