### ISSUE TITLE
H1 title links point to https://googlechrome.github.io/webrtc/

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#477]
Example:
https://github.com/webrtc/samples/blob/master/src/content/peerconnection/audio/index.html#L32

This applies to all samples I believe.

**Comment by samdutton** [comment]
Good spot! Fix incorporated in #469, which I've merged.

**Comment by XH505** [comment]
> Example:
> https://github.com/webrtc/samples/blob/master/src/content/peerconnection/audio/index.html#L32
> 
> This applies to all samples I believe.
>
