### ISSUE TITLE
Favicon URL is wrong

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#490]
Seen on the following page but it most likely affects most sample pages with a favicon.
http://webrtc.github.io/samples/src/content/peerconnection/pc1/

http://webrtc.github.io/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by samdutton** [comment]
I can't see any files now using favicon, but I've done a pull request that updates the meta and link elements: #492.

**Comment by KaptenJansson** [comment]
Fixed in  #492.
