### ISSUE TITLE
Unmute video element by default on ../getusermedia/source demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#491]
https://webrtc.github.io/samples/src/content/getusermedia/source/

Currently the user has to unmute the video element in order to effectively verify that the microphone selection works.

I think it makes sense to have the video element in a non muted state by default.

**Comment by juberti** [comment]
I think a VU meter is a better idea that unmuting, since unmuting leads to feedback as you observe.

**Comment by KaptenJansson** [comment]
I only got feedback on my Linux machine, and that applied to other tests to so I think its related to my setup rather than the mute state of the video element.

**Comment by KaptenJansson** [comment]
Closing as per comments.
