### ISSUE TITLE
Links on https://webrtc.github.io/samples/ redirects to HTTP

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#494]

**Comment by samdutton** [comment]
More information about HTTPS and GitHub Pages [here](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it).

**Comment by KaptenJansson** [comment]
LGTM!

**Comment by samdutton** [comment]
Changed, but links on [webrtc.github.io/samples](https://webrtc.github.io/samples/) still redirect to HTTPS URLs :/. 

Just saw comments [here](https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it) – looks like GitHub Pages doesn't support HTTPS for pages other than index.html.

You can enter HTTPS URLs manually, however.

**Comment by KaptenJansson** [comment]
Closing as per last comment.
