### ISSUE TITLE
404 when changing devices on ../source sample page

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#500]
404 GET http://webrtc.github.io/samples/src/content/getusermedia/source/null /samples/src/content/getusermedia/source/null:1 

Steps to repro:
1. Browse to http://webrtc.github.io/samples/src/content/getusermedia/source/
2. Open the javascript console
3. Change the microphone from default to another device.

It looks like both the audio and video stream works fine after changing.

Not sure where the GET request is coming from.

**Comment by fippo** [comment]
caused by setting the src to null -- I think you need to removeAttr here. Or wait for srcObject which you can set to null :-)

**Comment by samdutton** [comment]
Yes: when constraints are changed, `attachMediaStream(video, null)` is called from `getMedia()`, which means that `URL.createObjectURL(stream)` is called with a null stream.

Removing `attachMediaStream(video, null)` from `getMedia()` doesn't cause a problem as far as I can tell.

**Comment by KaptenJansson** [comment]
Fixed part of #539
