### ISSUE TITLE
Seeing 500 Error while trying to negotiate a call when the other user is not established connection with the peerconnection server completely

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#503]
The logs from the console are as follows:

setLocalDescription success
main.js:1108 Sending message {"candidate":"candidate:855189020 1 udp 2122260223 192.168.1.229 37197 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 2 udp 2122260222 192.168.1.229 43887 typ host generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 1 udp 2122260223 192.168.1.229 56239 typ host generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:855189020 2 udp 2122260222 192.168.1.229 54695 typ host generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756setLocalAndSendMessage_ @ main.js:915
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:1108 Sending message {"candidate":"candidate:3014729896 1 udp 1686052607 104.135.6.108 60806 typ srflx raddr 192.168.1.229 rport 37197 generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 2 udp 1686052606 104.135.6.108 62307 typ srflx raddr 192.168.1.229 rport 54695 generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 1 udp 1686052607 104.135.6.108 54127 typ srflx raddr 192.168.1.229 rport 56239 generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:3014729896 2 udp 1686052606 104.135.6.108 50893 typ srflx raddr 192.168.1.229 rport 43887 generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 1 tcp 1518280447 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 2 tcp 1518280446 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"audio","sdpMLineIndex":0} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 1 tcp 1518280447 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:1108 Sending message {"candidate":"candidate:2088426220 2 tcp 1518280446 192.168.1.229 0 typ host tcptype active generation 0","sdpMid":"video","sdpMLineIndex":1} to peer null.
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904
main.js:756 POST http://192.168.1.110:8888/message?peer_id=20&to=null 500 (Error)sendToPeer @ main.js:756iceCallback_ @ main.js:904

**Comment by juberti** [comment]
Is this a AppRTC issue? Seems like it is in the wrong tracker.

**Comment by KaptenJansson** [comment]
This should be filed in the testrtc tracker where the manual test pages reside. Here is a link to file an issue directly: https://github.com/webrtc/testrtc/issues/new

**Comment by selavazhagan** [comment]
Have filed the bug in the new location provided by Christoffer.

The bug is now in https://github.com/webrtc/testrtc/issues/71

Regards,
Shankari.

**Comment by KaptenJansson** [comment]
Perfect, will take a look tomorrow, thanks for filing the issue.

/Chris
