### ISSUE TITLE
Importing video/images over video stream

### ISSUE THREAD

**Issue by joshuaterrill** [webrtc/samples#507]
Is there any way to take a video stream and cast an image or video over it?

**Comment by KaptenJansson** [comment]
Do you mean you want to inject it in the video stream or just overlaying it on top of a video element? Easiest way to do that is actually using some virtual camera software which can combine the input from cameras, video/image files, screen capture etc into one stream. E.g. xsplit broadcaster.

Another approach is that you could draw the video stream and any other image or video on top of a canvas and render that.

**Comment by samdutton** [comment]
simpl.info/alpha shows overlaying videos (more information here
<http://updates.html5rocks.com/2013/07/Alpha-transparency-in-Chrome-video>
).

**Comment by joshuaterrill** [comment]
Yes, this is exactly what I'm looking for thanks @samdutton
