### ISSUE TITLE
How to use different network interface for signaling & media in WebRTC app?

### ISSUE THREAD

**Issue by KrishPS** [webrtc/samples#529]
I would like to use different network interface for signaling and different network interface media (WebRTC programming). Suppose I have more that one network interface like one LAN & Other is WiFi or Usb Modem etc. 
1. signaling should be happened via LAN. 
2. Media (Video/audio) should use the network interface like Wi-Fi or Usb modem.

Could you please suggest how to achieve above scenario in WebRTC application?
More Info:
http://stackoverflow.com/q/30759848/4511149

**Comment by KaptenJansson** [comment]
When it comes to media you can filter out candidates based on their IP addresses, then you would ofc need to know which IP address belongs to each interface in order to selected the appropriate candidate, the problem is that you cannot access info about users network interfaces from javascript.

Also as mentioned in the stackoverflow post you cannot tell the browser to use a specific interface for signalling. The only way I can think of is perhaps to use some proxy setting in the browser, not sure if that will force all traffic though.

But this is not a real solution as it requires tinkering with the users browser and intimate knowledge of the users system which you cannot realistically get from them.

**Comment by KaptenJansson** [comment]
I did not realize you could not continue to comment (although it makes sense that you cannot once it's closed;)), please continue the discussion here. Sorry for blocking you off.

**Comment by KrishPS** [comment]
I am writing WebRTC application for windows. My scenario is like:

LAN is default network interface for all applications.
System has more than one network interfaces like LAN and Wifi or usb modem.
WebRTC Signaling should use LAN & media (peer-to-peer connection) should use Wifi network. So that application can get fast network access for media communication.
Question- How to replace the Wifi Ip Address from LAN IP Address for media communication (peer-to-peer connection)?

My observation is:

It is possible to print Private and Public ICE candidates as per blow code.

pc.onicecandidate = function(evt) {
  if (evt.target.iceGatheringState == "complete") {
    local.createOffer(function(offer) {
      console.log("Offer with ICE candidates: " + offer.sdp);
      signalingChannel.send(offer.sdp);
 });
This code prints below info in my case. Private ICE candidate (192.168.1.73:60834) for the peer Public ICE candidate (50.76.44.100:69834) returned by the STUN server.

Now how to replace the Private ICE conditate (IP Address) to Wifi (IP Address)? Could you please suggest any solution?

**Comment by KaptenJansson** [comment]
evt.candidate.candidate will give you the candidate string, if you know the IP you could use regexp to check the IP address and only add the candidate with the IP matching your Wifi card.

**Comment by KrishPS** [comment]
It is working.

Thanks a million.

**Comment by martinoshin** [comment]
Help me!
I can not resolve different network for peer-to-peer connection (media) in WebRtc app.

After receiving onicecandidate completed event, I choice wanted "candidate" and the other candidate remove in SDP.
origianl candidate is 
   candidate:1049242189 1 udp 2122129151 109.10.10.47 60063 typ host generation 0   --> wanted candicate
   candidate:815576321 1 udp 2122194687 192.168.30.133 60065 typ host generation 0  --> removed

But source IP of RTP is 192.168.30.133. Source IP is not changed.

Below is Offer SDP
v=0
o=- 2811982410950894626 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS 1uaKaSIKJcX5MGFSd3nSF8SvoX84pomsaEoa
m=audio 60063 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 109.10.10.47                              --> change IP
a=rtcp:60066 IN IP4 109.10.10.47               --> change IP
a=candidate:1049242189 1 udp 2122129151 109.10.10.47 60063 typ host generation 0
a=ice-ufrag:rTgigLD+hNeJHCII
a=ice-pwd:7hVOkvLVT+FgupGW7IceOTFo
a=fingerprint:sha-256 8E:51:7C:59:7E:46:5D:68:E8:D9:0A:50:41:D1:84:BC:B0:39:EE:2D:DF:51:6B:55:EF:16:9E:6F:3D:F7:75:F4
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3819145928 cname:oFgG4oXaRPtwYquK
a=ssrc:3819145928 msid:1uaKaSIKJcX5MGFSd3nSF8SvoX84pomsaEoa 8138f36b-464f-4d14-a09a-f23ad96a6736
a=ssrc:3819145928 mslabel:1uaKaSIKJcX5MGFSd3nSF8SvoX84pomsaEoa
a=ssrc:3819145928 label:8138f36b-464f-4d14-a09a-f23ad96a6736

What is problem?

**Comment by KaptenJansson** [comment]
I do not quite follow, you write that you want to use 109.10.10.47 and in the offer it is used,  what is the problem? ;)

**Comment by martinoshin** [comment]
Hello,

Thanks for your reply.

I have two IP address on my computer. 109.10.10.47 and 192.168.30.133.

I modified SDP in Offer Message by wanted Candidate (a=candidate:1049242189
1 udp 2122129151 109.10.10.47 60063 typ host generation 0).
I hope that source IP of RTP set to 109.10.10.47.
and then send Offer message to Server.

After connecting, I captured the RTP packet by Wireshark on client.
Although I removed "candidate:815576321 1 udp 2122194687 192.168.30.133
60065 typ host generation 0" in SDP message, still source IP and port of
WenRTC is "192.168.30.133:60065".

I can not change source IP and port for RTP.

I need to your advice.

Thanks,
Martino.

2016-02-29 16:26 GMT+09:00 Christoffer Jansson notifications@github.com:

**Comment by KaptenJansson** [comment]
I see, WebRTC/Chrome will use the default route out of your machine. PTAL at this extension https://chrome.google.com/webstore/detail/webrtc-network-limiter/npeicpdbkakmehahjeeohfdhnlpdklia?hl=en which allows you configure this somewhat.

**Comment by martinoshin** [comment]
Thank for your advise.

I will check and test using WebRTC Network Limiter

Best Regards,
Martino

2016-03-01 19:20 GMT+09:00 Christoffer Jansson notifications@github.com:

**Comment by ychen884** [comment]
Please help me! I met a quite similar issue to @martinoshin. 

@martinoshin Could you tell me how you eventually solved this?
I am using a simple webRTC application on my server-client testbed. 

Here is what the testbed topology looks like:
Server: NIC to external network with public ip 128.x.x.x, and another NIC connected only to the client with ip 192.168.100.1
Client: NIC to external network with public ip 128.x.x.x, and another NIC connected only to the server with ip 192.168.100.2

My issue:
I would like my server to send RTP traffic only through the link 192.168.100.1 - 192.168.100.2, as @KaptenJansson described,  maybe the default gateway setting causes the SDP offer message to show only use public IP addresses of my machines, and the default gateway for my server and client are all 128.x.x.x and I probably cannot fix this. 

I tried to take a look into the WebRTC Network Limiter, but I am not sure how to use it to solve my problem.

My questions are: 
1. Could someone give me some hints that how WebRTC Network Limiter can help here? 
2. Is it possible to actually modify SDP message to make sure the RTP traffic(media streaming packets) is through the user-defined network interfaces? 
3. Are there any other possible workaround here? 

Thanks in advance for any help!

**Comment by alvestrand** [comment]
This is a question, and so it belongs on discuss-webrtc@googlegroups.com - please join that mailing list!

If you want to make sure you use only the 192.168.100 addresses, you must discard all other candidates, and also filter the SDP exchanged between the endpoints to remove the references to such addresses.

If you don't see the addresses as candidates, you may be out of luck.
