### ISSUE TITLE
Make getUserMedia error visible on the page in the gUM resolution demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#535]
It would be great if we could surface the getUserMedia error for the https://webrtc.github.io/samples/src/content/getusermedia/resolution/ demo with a short explanation.

This is especially useful for the Full HD option, not a whole lot of cameras support 1080.

**Comment by KaptenJansson** [comment]
To be clear, I do not think the console error is clear enough, it's not thrown as an error either.

**Comment by samdutton** [comment]
Just noticed this again — agree. 

Maybe something like this in `errorCallback()`: 

    if (error.name === "ConstraintNotSatisfiedError") {
      error('The resolution ' + constraints.video.width.exact + 'x' + 
          constraints.video.width.exact + 'px is not supported by your device.'
    }

(This needs an `error()` method to display the error on the page and in the console, and for `constraints` to be global.)

**Comment by jan-ivar** [comment]
Hmm, this needs a shim for Firefox unfortunately. https://bugzil.la/1181896
