### ISSUE TITLE
Checking if camera/microphone is available

### ISSUE THREAD

**Issue by ignasbernotas** [webrtc/samples#537]
I was wondering whether there is a way to check if the camera/microphone is being used by another process (e.g. Skype).

It's possible to check whether the device exists, but can we check if it's in use?

**Comment by KaptenJansson** [comment]
No you cannot as that would be an invasion of privacy. I believe Chrome will just report back a permissionDeniedError in that case.

**Comment by alvestrand** [comment]
The spec actually doesn't require that devices are limited to one user only. Skype might have the camera open, and you might still get it.
You just don't know.
