### ISSUE TITLE
How to use different network for peer-to-peer connection (media) in WebRTC app?

### ISSUE THREAD

**Issue by KrishPS** [webrtc/samples#540]
I am writing a application for windows.
Scenario: 
If signaling is using the default network interface (e.g. LAN), is it possible to force local peer (for peer-to-peer connection to establish media session for communication) to use some specific network (e.g Wifi)?

I tried many methods to set specific IP Address to have peer-to-peer connection on that IP Addr only. But I could not force Private ICE candidate to use specific IP Address.
Could you please throw some light on this issue?

**Comment by KaptenJansson** [comment]
Answered in #529
