### ISSUE TITLE
Seeing '404 file not found' for the requested file in Glimmer on the link mentioned 

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#544]
Steps:
1. Go to the link  https://webrtc.github.io/samples/src/content/getusermedia/source and hit 'Enter'

Expected Result:
There should be the page with the source selection option for the media.

Actual Result: 
Instead seeing the '404 File not Found' Error.  Checked in the samples page of the github page and from there also i am seeing the same error.   The screenshot is atached.
![screenshot 2015-07-08 at 12 16 33 pm](https://cloud.githubusercontent.com/assets/9001606/8579752/47db0b3c-256b-11e5-8bf9-f83854eb3dd2.png)

**Comment by jan-ivar** [comment]
Caused by #542
