### ISSUE TITLE
AppRTC loopback should work with DTLS

### ISSUE THREAD

**Issue by marwahvikas** [webrtc/samples#55]
Moving issue from webrtc tracker to github. 
Quoth https://github.com/GoogleChrome/webrtc/blob/master/samples/web/content/apprtc/apprtc.py#L395

    debug = self.request.get('debug')
    if debug == 'loopback':
      # Set dtls to false as DTLS does not work for loopback.
      dtls = 'false'

Indeed, failing to disable DTLS causes errors like:
Error(transport.cc:101): Answerer must use either active or passive value for setup attribute.

Since SDES is eventually going to disappear in favor of DTLS we should make sure loopback calls work with DTLS as well.  The answer is probably to set up a second PeerConnection on the same page.
Once the JS version is updated the same should be done for the Android & iOS sample apps.

**Comment by jiayliu** [comment]
Should this be closed?

**Comment by marwahvikas** [comment]
Seems like we still need to fix this, the loopback call has dtls set to false so is using SDES. Any reasons we have dtls false for loopback? If its trivial change, i can just remove the line that sets it to false.

**Comment by juberti** [comment]
No, this is complex. We need multiple peer connections to handle DTLS in loopback, one for client, one for server.

**Comment by marwahvikas** [comment]
i see thanks Justin.

**Comment by juberti** [comment]
Please move this to apprtc issue tracker

**Comment by marwahvikas** [comment]
moved to apprtc tracker.. closing this one.
