### ISSUE TITLE
Disable connect button after successful a connection and add a hangup button to the constraints demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#552]
The [constraints demo](https://github.com/webrtc/samples/tree/master/src/content/peerconnection/constraints) allows the user to start arbitrary peerconnections by spamming the connect button. 

For a demo page I think we should somewhat prevent that by just disabling connect button after a successful connection. Then we also need a hangup button so that we can leave the connected state without reloading the page.

**Comment by fippo** [comment]
done in latest commit of #550 :-)
