### ISSUE TITLE
Move the extension folder to /extensions/

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#553]
I haven't looked at it closely enough before but I just realized having a folder named /samples in the samples repo feels a bit redundant.

Maybe delete samples/ and have extensions/ live in the root of the repo?

@samdutton @guoweis WDYT?

**Comment by samdutton** [comment]
Ah — hadn't noticed this.

The extensions folder should definitely be at the root of the samples repo, as you suggest.

**Comment by juberti** [comment]
agree with Sam
