### ISSUE TITLE
DTMF demo broken?

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#554]
http://webrtc.github.io/samples/src/content/peerconnection/dtmf/ complains about the lack of createDTMFSender()
I am pretty sure I used that demo recently... maybe before a chrome update?

**Comment by KaptenJansson** [comment]
Works for me in latest canary and dev channel. I believe I tested in FF and found that it does not support dtmf a while back.

**Comment by fippo** [comment]
hrm... seems to be a chromium issue. Works fine in google chrome indeed. Not sure what ubuntu does to make it not work, i've seen such issues several times in the past.

**Comment by KaptenJansson** [comment]
Can you file a crbug?

**Comment by fippo** [comment]
@KaptenJansson https://code.google.com/p/chromium/issues/detail?id=510073

**Comment by KaptenJansson** [comment]
thanks!

**Comment by jan-ivar** [comment]
yeah firefox does not support dtmf yet
