### ISSUE TITLE
Incorrect button state after gUM error callback/promise in constraints demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#561]
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/constraints/
2. Set Frame rate to 60 fps
3. Click OK in the gum error alert

Result:
All buttons greyed out.

Expected result:
All buttons greyed out except Get media.

@fippo do you want to fix this? ;) Otherwise I will take a look

**Comment by samdutton** [comment]
Had a go myself :).

Maybe the **Get media** button should be enabled after connecting, so you can have a go with different constraints without having to reload the page?

**Comment by KaptenJansson** [comment]
That can be achieved by using the hang up button. But if you want to test the scenario where we remove a stream and add a new stream to the peerconnection with different constraints your suggestion is the way to go I guess.

**Comment by samdutton** [comment]
> hang up button

You're right — don't need to reload.

**Comment by KaptenJansson** [comment]
Fixed in #562
