### ISSUE TITLE
PermissionDeniedError is seen for the peerconnection/constraints page

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#564]
1. Use the link https://webrtc.github.io/samples/src/content/peerconnection/constraints on the device Paine(45.0.2454.4/7262.3.0 dev) 
2. Click on 'Get Media'

Expected Result: 
The media should be seen in the window below

Actual Result:
The error message is seen as s
![screenshot 2015-07-16 at 2 29 57 pm](https://cloud.githubusercontent.com/assets/9001606/8735697/addfb7cc-2bc7-11e5-896a-d4f4f42634cf.png)
een in the screenshot attached

**Comment by fippo** [comment]
ah... 45 adds navigator.mediaDevices.getUserMedia so it's no longer shimmed in https://github.com/webrtc/adapter
However, the non-shimmed version doesn't accept the spec-constraints. @KaptenJansson will make a PR in adapter

**Comment by KaptenJansson** [comment]
To give background to why this slipped by my testing, I was testing using 45.0.2441.3 while this was introduced in 45.0.2453.0 it seems.

Note to self, always test on latest and greatest.
