### ISSUE TITLE
'404 file not found' is seen for the peerconnection multiple link 

### ISSUE THREAD

**Issue by selavazhagan** [webrtc/samples#565]
1. Go to the link https://webrtc.github.io/samples/src/content/peerconnection/multiple on Daisy(45.0.2454.4/7262.3.0 dev)

Expected Result:
The page should display the contents of the page

Actual Result:
Instead i do see the error as seen in the screenshot attached.  This is happening on this device and not on the desktop or the other chrome device.
![screenshot 2015-07-16 at 3 18 22 pm](https://cloud.githubusercontent.com/assets/9001606/8736566/802d07ba-2bce-11e5-9fcc-c59d61d0f726.png)

**Comment by KaptenJansson** [comment]
The link you provided is correct while the link in the screenshot is incorrect (mulitple should be multiple).
