### ISSUE TITLE
Unable to choose destination folder in example of devices/input-output/

### ISSUE THREAD

**Issue by flik** [webrtc/samples#570]
Unable to choose destination folder in example of devices/input-output/

**Comment by samdutton** [comment]
Do you mean you can't choose the audio output destination:?

Make sure you're using Chrome 45.0.2441.x or later and that you've enabled Experimental Web Platform Features from chrome://flags (see the notes on the page).

**Comment by KaptenJansson** [comment]
Closing this as I assume the conditions in the response above was not fulfilled. Please let us know if you did indeed follow the steps and it still did not work.
