### ISSUE TITLE
Investigate why firefox unstable stalls on the first test

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#583]
Running it locally results in the Firefox browser being started but stops at https://github.com/webrtc/samples/blob/master/src/content/getusermedia/gum/js/test.js#L24. Seems like the Promise callback is never triggered

**Comment by KaptenJansson** [comment]
@fippo FYI

**Comment by KaptenJansson** [comment]
Currently it fails before fetching the file, i.e. no URL navigation has taken place.

**Comment by KaptenJansson** [comment]
I see the following error after a while:
not ok 1 Error: Timed out waiting for the WebDriver server at http://127.0.0.1:51559/hub

**Comment by KaptenJansson** [comment]
Tried adding all the build() firefox logic in selenium-lib.js to the test file directly but I get the same result. That rules out some import issues.

**Comment by KaptenJansson** [comment]
Could it be related to a change in extension handling? The firefox driver is essentially a XPI file.  https://code.google.com/p/selenium/wiki/FirefoxDriver

**Comment by KaptenJansson** [comment]
This old [page](https://code.google.com/p/selenium/wiki/FirefoxDriverInternals) claims Firefox driver is an XPCOM extension and https://blog.mozilla.org/addons/2015/05/04/dropping-support-for-binary-components/ claims support for XPCOM is dropped in 41.

**Comment by KaptenJansson** [comment]
This [page](https://github.com/SeleniumHQ/selenium/wiki/FirefoxDriver-Internals) is fairly new and contains the same info.

**Comment by KaptenJansson** [comment]
Or it is a red herring, opened the Error console in firefox and can see:

Timestamp: 08/13/2015 03:04:55 PM
Error: Warning: unrecognized command line flag -CreateProfile

Source File: jar:file:///usr/local/google/home/jansson/src/github/samples/node_modules/travis-multirunner/browsers/firefox/41.0b1/browser/omni.ja!/components/nsBrowserContentHandler.js
Line: 805

**Comment by KaptenJansson** [comment]
Might be extension signing issue https://wiki.mozilla.org/Addons/Extension_Signing since I can see the firefox webdriver extension is disabled due to its unsigned.

**Comment by fippo** [comment]
this would be from travis-multirunner... do things unbreak if you remove this from node_modules/travis-multirunner/start-firefox.sh locally? Note: it might work locally since the profile already exists

**Comment by KaptenJansson** [comment]
https://github.com/SeleniumHQ/selenium/issues/901

**Comment by KaptenJansson** [comment]
Fixed it by doing profile.setPreference('xpinstall.signatures.required', false);
