### ISSUE TITLE
How do I link to HTTPS samples?

### ISSUE THREAD

**Issue by jan-ivar** [webrtc/samples#586]
Maybe I'm missing something fundamental, but I'm having trouble linking people to the HTTPS version of https://webrtc.github.io/samples/src/content/devices/input-output, e.g. from [here](http://stackoverflow.com/questions/31586889/how-to-detect-microphone-type/31601758#31601758), which is sad, because the HTTP version doesn't show labels, which is hard to explain.

Is there a way to fix or work around this from our end?

**Comment by samdutton** [comment]
Fixed this on stackoverflow.com/questions/31586889/how-to-detect-microphone-type/31601758#31601758 by adding a / to the URL.

(I tried several variations — hat tip to my esteemed colleague Paul Kinlan for noticing that the original redirect to add the trailing slash also meant the protocol changed to HTTP.)

A bit of a hack, but maybe we could force HTTPS via JavaScript, as per the suggestion at https://konklone.com/post/github-pages-now-sorta-supports-https-so-use-it?

    if ((window.location.host === 'webrtc.github.io') && (window.location.protocol !== 'https:')) {
        window.location.protocol = 'https';
    }

(Haven't tested if this actually works as intended.)

@juberti   @fippo

**Comment by KaptenJansson** [comment]
It now works ;)

**Comment by samdutton** [comment]
BTW: Because the links to the samples are relative, they'll (still) use
HTTP if they're from *http*://webrtc.github.io/samples
<http://webrtc.github.io/samples>.

In spite of that I'd probably rather they stayed relative.
