### ISSUE TITLE
Figure out if there is a way to test Edge through selenium

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#592]
http://blogs.windows.com/msedgedev/2015/07/23/bringing-automated-testing-to-microsoft-edge-through-webdriver/
-- Edge just got support for this. Possibly might make more sense to do this in the samples which are already using Selenium.

@alvestrand :-)

**Comment by KaptenJansson** [comment]
Travis-ci does not support Windows yet (it's being worked on but slowly), Linux and Mac only.

As an alternative maybe we could use http://www.appveyor.com/ for Windows?

**Comment by KaptenJansson** [comment]
I've created a milestone so that we can group PR's and issues together

**Comment by fippo** [comment]
the way I have in mind currently is to run test Edge by starting node on travis and then execute selenium as a remote webdriver. There are still some pieces missing (like hooking up the Edge webdriver with a selenium hub) and some are not yet public but it seems that we don't need to change our overall approach of using travis.

**Comment by KaptenJansson** [comment]
Closing due to age.
