### ISSUE TITLE
Set the sinkId per audio/video element in http://webrtc.github.io/samples/src/content/devices/multi/

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#597]
The statement on the page: 
> "tl;dr Only one output can be selected for all sources." 

is not entirely true, setting the output for media files directs all elements with a media file to the selected output, however getUserMedia streams do not, in fact they are controlled independently of video/audio elements with media or getUserMedia streams attached. 

Found in https://code.google.com/p/chromium/issues/detail?id=512798

**Comment by samdutton** [comment]
We could/should change this to have three audio output selectors: one each for `getUserMedia()` via audio and video elements, one single selector for the media elements with a file src.

Can we give a short explanation of why audio output selection is available for media elements that get a stream from `getUserMedia()`, but not for elements with a file src?

**Comment by KaptenJansson** [comment]
>Can we give a short explanation of why audio output selection is available for media elements that get a stream from getUserMedia(), but not for elements with a file src?

It is possible, it just seems once you set it for a video/audio element with a file src, all other video/audio elements will share the same destination. To why that is, yes, an explanation would be nice , but maybe this [bug](https://code.google.com/p/chromium/issues/detail?id=506507) covers it ?

**Comment by samdutton** [comment]
So — just to be clear: if you set the output for a video/audio element with a file src, all other video/audio elements with a file src share the same destination but not video/audio elements with a `getUserMedia()` src?

A brief explanation and link to the bug sounds sensible.

**Comment by KaptenJansson** [comment]
>So — just to be clear: if you set the output for a video/audio element with a file src, all other video/audio elements with a file src share the same destination but not video/audio elements with a getUserMedia() src?

That's what I noticed using the multi/ page and setting the sinkId manually on the video element with file src and setting the sinkId using the dropdown (which sets the sinkId on the left video element with getUserMedia() src).

**Comment by ouestaudition** [comment]
Hi Sam and Kapten, 
Do you know when this bug will be fixed.
I have to be sure that this new features works with no limitation to stream audio media to any audio output device on the fly.

Sorry for asking and thanks for your work, it seems that nobody except you give example for this feature.

**Comment by KaptenJansson** [comment]
I think this is the same as #649

**Comment by samdutton** [comment]
Yep — seems that way.

**Comment by KaptenJansson** [comment]
Closing per https://github.com/webrtc/samples/issues/597#issuecomment-149860507. Please create a new issue with a fresh repro case if this is still an issue.

I created a new issue for adding an output selector per video element #677.

**Comment by poojarfuturistic5** [comment]
does not fetch audio in iphone devices
