### ISSUE TITLE
Android webview permissions

### ISSUE THREAD

**Issue by dbroadhurst** [webrtc/samples#603]
The latest version of webview claims support for webrtc. However I get a permission error when I try to run any samples. Can anyone confirm if its possible to run the samples on an Android device in a webview?

**Comment by samdutton** [comment]
Could you give the text of the error you're getting?

**Comment by dbroadhurst** [comment]
I setup a cordova project as follows

  cordova create hello com.example.hello HelloWorld
    $ cd hello
    $ cordova platform add android
    $ cordova build

I then add the demo code making sure to prefix GetUserMedia with webkitGetUserMedia and receive the following error

navigator.getUserMedia error:  NavigatorUserMediaErrorconstraintName: ""message: ""name: "PermissionDeniedError"__proto__: NavigatorUserMediaError

**Comment by KaptenJansson** [comment]
What constraints do pass in ?

**Comment by dbroadhurst** [comment]
```

        // Put variables in global scope to make them available to the browser console.
        var video = document.querySelector('video');
        var constraints = window.constraints = {
          audio: false,
          video: true
        };

        function successCallback(stream) {
          // var videoTracks = stream.getVideoTracks();
          console.log('Got stream with constraints:', constraints);
          console.log('Using video device: ' + videoTracks[0].label);
          // stream.onended = function() {
          //   console.log('Stream ended');
          // };
          // window.stream = stream; // make variable available to browser console
          // attachMediaStream(video, stream);
        }

        function errorCallback(error) {
          console.log('navigator.getUserMedia error: ', error);
        }

        navigator.webkitGetUserMedia(constraints, successCallback, errorCallback);
```

**Comment by KaptenJansson** [comment]
Which android target are you using? Android M has a different permission model, not sure how that works with webview.

**Comment by dbroadhurst** [comment]
I'm targeting Api 22 and my device is running Lollipop with the latest webview

    <uses-sdk android:minSdkVersion="10" android:targetSdkVersion="22" />

**Comment by dbroadhurst** [comment]
Turns out I needed a modification to Cordova to ensure the permissions are setup correctly.

https://github.com/vbraun/cordova-android/commit/b60a1698fe0ba17fb379d87e7f523e433d106417?diff=split
