### ISSUE TITLE
Move to ESLint for JavaScript linting and code style checking

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#609]
I think we should probably move to ESLint for JavaScript linting: 

http://eslint.org
https://www.npmjs.com/package/grunt-eslint

Haven't used it myself, but it's quite popular among Chrome Dev Rel.

Pro and con:

http://blog.lauritz.me/linting-javascript-in-2015
http://www.sitepoint.com/comparison-javascript-linting-tools

Should be able to get rid of JSCS and JSHint if we opt for ESLint.

**Comment by KaptenJansson** [comment]
SGTM

**Comment by KaptenJansson** [comment]
@fippo WDYT?

**Comment by KaptenJansson** [comment]
@samdutton did you plan adding this yourself?

**Comment by samdutton** [comment]
>
> @samdutton <https://github.com/samdutton> did you plan adding this
> yourself?


Yes — though happy if anyone else wants to :).

**Comment by samdutton** [comment]
Working on this...
