### ISSUE TITLE
Is it possible to stream local media files?

### ISSUE THREAD

**Issue by AdamWorld** [webrtc/samples#616]
Now AppRTC streams media from camera by getUserMedia().
But I want to stream local media file and for that I looked into following link.
https://webrtc.github.io/samples/src/content/devices/multi/ 
Here are two media sources, one is getUserMedia(), the other is local media.
But i can't find the way how to stream local media from there.

Is it possible to stream local media files?

Thank you,
Regards,
Adam.

**Comment by KaptenJansson** [comment]
You can start chrome using command line flag --use-file-for-fake-video-capture="filename" which will use the specified file instead of a camera input for media streams.

**Comment by KaptenJansson** [comment]
Do note though that this is intended for development and testing, not production usage.

**Comment by AdamWorld** [comment]
Thank you very much, yes, i will check and leave a feedback right away.

**Comment by AdamWorld** [comment]
I tried with this in cmd.

1. Copied Test.avi in same folder of chrome.exe
2. run the following command in cmd.exe
> chrome.exe --use-file-for-fake-video-capture="Test.avi"
3. goes into https://apprtc.appspot.com 

But it still opens camera and stream it.

Did is do something wrong?

**Comment by KaptenJansson** [comment]
I think you have to provide a full path for the file, e.g. c:\tmp\file.avi for Windows and /tmp/file.avi for Posix OS's

**Comment by AdamWorld** [comment]
I tried that too but same result.

**Comment by AdamWorld** [comment]
![image](https://cloud.githubusercontent.com/assets/1290070/9251771/5fd3fb8c-4207-11e5-8ca7-2cdf923e7081.png)

**Comment by KaptenJansson** [comment]
Hmm you might need to add --allow-file-access and possibly  --use-fake-device-for-media-stream as well.

**Comment by AdamWorld** [comment]
chrome.exe --use-file-for-fake-video-capture="D:\Test\Video\Test.mp4" --allow-file-access --use-fake-device-for-media-stream

**Comment by KaptenJansson** [comment]
What happens if you omit the quotes for the file path? "D:\Test\Video\Test.mp4"  > D:\Test\Video\Test.mp4

**Comment by AdamWorld** [comment]
I tried that too but same problem.
You can see that case in the screenshot above ^-^.

**Comment by phoglund** [comment]
Read the documentation: https://code.google.com/p/chromium/codesearch#chromium/src/media/base/media_switches.cc&q=use-file-for-fake&sq=package:chromium&l=98

The only supported video format is .y4m.

**Comment by AdamWorld** [comment]
Thank you, i will try and leave the feedback the result soon.

**Comment by AdamWorld** [comment]
hmm, same problem.

I downloaded y4m here http://media.xiph.org/video/derf/y4m/

> chrome.exe --use-file-for-fake-video-capture="D:\Test\Video\y4m.y4m" --allow-file-access --use-fake-device-for-media-stream

**Comment by AdamWorld** [comment]
I tried this and it works well.. right now.

> chrome.exe --use-fake-device-for-media-stream --use-file-for-fake-video-capture="D:\Test\Video\y4m.y4m"

**Comment by AdamWorld** [comment]
Thank you very much for all your answers

**Comment by KaptenJansson** [comment]
No problem, glad it worked out.

@phoglund thanks for looking up the source of truth ;)

**Comment by tarun-iitd** [comment]
Hi,

I tried to run above steps. but i m not able to run the media from .y4m file.
Can you please tell the steps to play media from file on chrome browser.

I used below command from chrome browser:
C:\Program Files (x86)\Google\Chrome\Application>chrome.exe --use-fake-device-fo
r-media-stream --use-file-for-fake-video-capture="D:\Tarun\AssignedTasks\RTMP-pl
ayUsingKurento\Scaling_Stress_Testing\fakeBrowser\720p50_mobcal_ter.y4m"  --allo
w-file-access

but only chrome browser opens up and nothing is viewing and nothing is playing.

Then i tried to open https://apprtc.appspot.com

but no media is played from file.

I could not get how it  will play media from file to apprtc browser tab.
Please explain the steps.

Thanks,
Tarun

**Comment by tarun-iitd** [comment]
apprtc.debug.js:5317 2.392: Initializing; server= undefined.
apprtc.debug.js:5317 2.393: Initializing; room=undefined.
apprtc.debug.js:5317 22.464: Opening signaling channel.
apprtc.debug.js:5317 22.492: Error getting user media: 
apprtc.debug.js:5317 22.496: getUserMedia error: Failed to get access to local media. Error name was NotAllowedError. Continuing without sending a stream.

when i oen apprtc then it shows above error message.
How we can connect local file play to apprtc.

**Comment by tarun-iitd** [comment]
it is working now. i need to close all chrome.exe first then need to run test case.
thanks

**Comment by tscpereira** [comment]
Yes it works! In my case I had to kill all the chrome processes before initialize the new instance with fake-device enabled.

**Comment by azachar** [comment]
Hey Guys, is it possible to stream multiple files (so I can simulate a video chat)? Thanks!
