### ISSUE TITLE
To stublish P2P Con, WebRTC Signaling send via Citrix VDI & Media send via local machine

### ISSUE THREAD

**Issue by KrishPS** [webrtc/samples#623]
I have WebRTC App, APP Plug-in, Citrix server, VDI (Virtual desktop) and Citrix Receiver.

Scenario: WebRTC APP gets installed at VDI machine & one WebRTC VDI Plug-in gets installed at local machine with Citrix receiver.

WebRTC APP (VDI) should send the signaling to remove client.
But Media should be sent via Local WebRTC plug-in to remote client.
Questions:

How to achieve this scenario?

How to pass the message from VDI app to local machine app (Citrix receiver)?

How to send/accept the media request at local plug-in (Citix receiver)?

MS Lync has achieve this kind of but there is no enough information available? http://blogs.technet.com/b/nexthop/archive/2013/09/23/deployment-details-for-lync-vdi-plugin.aspx

Could you please anybody help for this??

**Comment by KaptenJansson** [comment]
Hi,

This question is better suited for https://groups.google.com/forum/#!forum/discuss-webrtc, but I see you have already posted it there as well. Closing.
