### ISSUE TITLE
Add data channels to munge-sdp demo

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#625]
It would be useful for testing data channels specifically.

**Comment by KaptenJansson** [comment]
@fippo @samdutton WDYT?

**Comment by KaptenJansson** [comment]
Came to mind when looking at https://code.google.com/p/chromium/issues/detail?id=280726

**Comment by fippo** [comment]
SGTM -- just a simple checkbox? There is not much you can manipulate for data channels though.
