### ISSUE TITLE
redirect to https

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#639]
mostly due to GUM breaking soon: https://twitter.com/stopsatgreen/status/639784534691737600
Easy way to do this: just change all the links on index.html
Hard way to do it: add https check on every demo that requires this. The datachannel demos still work without https

@samdutton: didn't you add a https redirect a while ago?

**Comment by samdutton** [comment]
@fippo PTAL before I merge.

**Comment by samdutton** [comment]
Pushed to gh-pages.
