### ISSUE TITLE
RTCDataChannel: Transmit Text demo works in Chrome, doesn't work in Chrome Canary

### ISSUE THREAD

**Issue by please-wait** [webrtc/samples#640]
Chrome Version: 45.0.2454.85 m
Chrome Canary Version: 47.0.2503.0 (64-bit)

**Comment by samdutton** [comment]
[Demo](https://webrtc.github.io/samples/src/content/datachannel/basic/) works for me in 47.0.2503.0 canary (64-bit) on Mac.

Are you on Mac — and, if so, is it still not working?

What happens?

**Comment by please-wait** [comment]
Thank you for your answer.
No, I'm on Windows 10. the link you have provided works perfectly. I found the page at simpl.info and I think [that page](http://simpl.info/rtcdatachannel/) is missing something.

**Comment by samdutton** [comment]
Ah — see what you mean. Thanks for the heads-up: will fix.

**Comment by samdutton** [comment]
Closing this, as is [simpl.info](http://simpl.info/dc) issue.
