### ISSUE TITLE
Simple many-to-many video chat application.What is wrong with this approach ? 

### ISSUE THREAD

**Issue by ahmed-taj** [webrtc/samples#644]
Hi,
I'm sorry if it's not the suitable place to ask such question but I need a help.
Well, recently I get started with webrtc, I made a simple one-to-one video chat, just like all tutorials, I created a `<video id="me" >` element for my stream, and another one, `<video id="him" >` for my partner.
Now I want to make a room chat, so - as expected from newbie - I wondered how can I differentiate between users, but I think this approach may work.
Here is my simple approach:
* Every peer will login by a unique username, to a unique room id.
* All rooms data(id,clients,...etc) are stored in the server side.
*  When a user is connected, he will send an offer to other partners in the same room. Actually he will send an offer to the server which will redirect it other partners.
* When a user received an offer he must  create a new (if not exists) `<video>` element with id equals the extracted stream label from the received offer.
* `onaddstream` user will set video element(which its id equals the  passed stream's label) to  stream.

Well, first, because I'm beginner I know there must be something wrong with my approach, any suggestions ?
Second, I saw many tutorials store room data in clients instead of server, why is that ?
At the end, my goal is to make efficient video chat serve up to 10 users in the same room

Thanks.

**Comment by samdutton** [comment]
Thanks for your question, but this is a forum for filing bugs and feature requests about this repo.

The best place for questions like yours is StackOverflow ([lots of WebRTC discussion](http://stackoverflow.com/questions/tagged/webrtc) there) or the [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) group.

More resources at [g.co/webrtc](https://g.co/webrtc).
