### ISSUE TITLE
Audio output sample only changes output

### ISSUE THREAD

**Issue by xdumaine** [webrtc/samples#649]
[This comment](https://github.com/webrtc/samples/blob/master/src/content/devices/multi/js/main.js#L70) isn't true for me (Chrome 45.0.2, Mac OS X 10.10):

> // Changing destination for one source changes destination for all.

When I change the audio output in this sample, it only affects the gumVideo media, not all the other media elements on the page. The rest all play through the default audio, not the selected audio.

**Comment by KaptenJansson** [comment]
Thanks for reporting.

Yes there were some misconceptions about what setSink actually did in the beginning (this was actually a caveat when it first landed but later change).

I plan to improve this demos in general which will cover this case as well as making sure each device selection sticks when selecting another type of device etc.
