### ISSUE TITLE
Master merge to gh-pages did not bring in all changes?

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#660]
@guoweis CC

By the looks of it the changes from https://github.com/webrtc/samples/pull/648#issuecomment-145919055 are not in gh-pages. Specifically commit https://github.com/webrtc/samples/commit/07536ca8d2505ef513155c66eaa385c3d5bc88ca.

@samdutton did you have latest master when merging to gh-pages?

**Comment by guoweis** [comment]
652 is also missing from the merge.

Thanks,
Guowei

**Comment by samdutton** [comment]
Looking into this.
