### ISSUE TITLE
Merge latest adapter.js release

### ISSUE THREAD

**Issue by tednakamura** [webrtc/samples#668]
Note that this is dependent on https://github.com/webrtc/adapter/issues/148

**Comment by KaptenJansson** [comment]
@fippo @alvestrand This is where we get punished from having two different adapter.js files. The one in this repo actually has removed trace() and has ORTC/edge shim in place.

@fippo how's your browserfication going? ;)

**Comment by fippo** [comment]
@KaptenJansson well, we didn't say "yay, samples support Edge". browserification is good but I want to merge it all in one step. Will send email re plan + timing.

**Comment by KaptenJansson** [comment]
Sorry, I did not mean to put down your efforts on the edge support. I can merge the changes in the meanwhile, should not be to hard.

**Comment by KaptenJansson** [comment]
@fippo Yay, samples support on MS EDGE :). That reminds me, we should probably spread the word, now or when your work is done as mentioned in your last comment?
