### ISSUE TITLE
Empty file transfer freezes data channel

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#670]
Repro steps:
1. Navigate to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Click on 'Choose file'  and upload an empty file (file with no contents). Please see the attached empty file.txt
3. Observe that 'Send progress' and 'Receive progress' are not shown and no data transfer happens
   https://screenshot.googleplex.com/1psw89qWuRk.png
4. Console(Javascript) logs shows that data channels are open

Expected result: 
File transfer should happen even when file does not have any contents and data channel should be closed after the transfer

Actual result:
File is not transferred when there are no contents and data channel is kept open indefinitely. 
'Choose file' button is frozen making users unable to upload another file.
https://screenshot.googleplex.com/1psw89qWuRk.png

Chrome version: 
46.0.2490.71 (Official Build) (64-bit)

OS:
Linux Desktop

Logs:
This appears to be Chrome
common.js:8 7.170: Created local peer connection object localConnection
common.js:8 7.171: Created send data channel
common.js:8 7.172: Created remote peer connection object remoteConnection
common.js:8 7.175: Offer from localConnection 
v=0
o=- 3047940909882059690 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:OqwkB8YTXHr/Ao2+
a=ice-pwd:5aitgQaLhWTdFoRVXcENVQ8Y
a=fingerprint:sha-256 DC:19:3B:3C:50:FB:6A:A9:E1:9B:FE:E0:D5:8B:B7:BD:5F:A6:19:EE:BE:95:B2:2A:F5:DC:FB:9B:51:E2:9D:E5
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 7.176: Answer from remoteConnection 
v=0
o=- 8820750149763377843 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:iy70e0O7g0+lCTGo
a=ice-pwd:3mgODL11WI94Qys9wWhUMuVQ
a=fingerprint:sha-256 DC:19:3B:3C:50:FB:6A:A9:E1:9B:FE:E0:D5:8B:B7:BD:5F:A6:19:EE:BE:95:B2:2A:F5:DC:FB:9B:51:E2:9D:E5
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 7.176: local ice callback
common.js:8 7.176: Local ICE candidate: 
candidate:2498979306 1 udp 2122262783 2620:0:1000:1502:788c:378:5d92:d93f 52232 typ host generation 0
common.js:8 7.176: local ice callback
common.js:8 7.177: Local ICE candidate: 
candidate:2614814290 1 udp 2122194687 172.22.104.141 44320 typ host generation 0
common.js:8 7.177: AddIceCandidate success.
common.js:8 7.178: AddIceCandidate success.
common.js:8 7.178: remote ice callback
common.js:8 7.178: Remote ICE candidate: 
 candidate:2498979306 1 udp 2122262783 2620:0:1000:1502:788c:378:5d92:d93f 58448 typ host generation 0
common.js:8 7.179: remote ice callback
common.js:8 7.179: Remote ICE candidate: 
 candidate:2614814290 1 udp 2122194687 172.22.104.141 34539 typ host generation 0
2common.js:8 7.180: AddIceCandidate success.
common.js:8 7.224: local ice callback
common.js:8 7.224: remote ice callback
common.js:8 7.227: Send channel state is: open
common.js:8 7.228: file is -emptyfile.txt 0 text/plain Thu Oct 22 2015 15:35:25 GMT-0700 (PDT)
common.js:8 7.228: Receive Channel Callback
common.js:8 7.229: Receive channel state is: open

**Comment by srnarayanan** [comment]
I see a similar Data Channel freeze while transferring 0 MB of data as well
https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
Screenshot:
![transfer_data](https://cloud.githubusercontent.com/assets/14947786/10681052/565ab0b4-78da-11e5-85d5-fcc2554918b7.png)

**Comment by fippo** [comment]
it's actually not the datachannel that is freezing (for the filetransfer sample).
The filereader's onload is simply never called (since there is no data).
I suspect the correct thing is to listen for the 'onloadend' event. @samdutton WDYT?
(alternatively handle the size-0 file, the metadata is available early enough)

For the datatransfer sample, onReceiveMessageCallback is never called so the receivedSize === bytesToSend code that evalutes whether the data has been received.

Good catch!
