### ISSUE TITLE
Tests for Network, Connectivity and Throughput are failing in WebRTC Troubleshooter page

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#679]
Repro steps:
1. Navigate to https://test.webrtc.org
2. Click on ' Start' button
3. Observe that Network, Connectivity and Throughput failed with 'Turn request failed' error
4. Observe that java script console logs show error " No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://test.webrtc.org' is therefore not allowed access. The response had HTTP status code 500

**Comment by cvranjani** [comment]
Expected result:
Test for Microphone, Camera, Network, Connectivity and Throughput on the device should pass successfully. 
Some failures may be expected, such as:
-if your camera can't support higher resolutions
-if you're currently on a network that doesn't supply an IPv6 address

Actual result:
Tests for Network, Connectivity and Throughput on device Butterfly are failing with error "TURN request failed".

**Comment by selavazhagan** [comment]
I did observe this error in the device Alex in the build 48.0.2555.0/7614.0.0.

**Comment by KaptenJansson** [comment]
This is the same as https://github.com/webrtc/apprtc/issues/216.

**Comment by KaptenJansson** [comment]
Jiayang fixed it by reverting a computeengineondemand push.
