### ISSUE TITLE
Create multiple mediastream per peerconnection demo page

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#682]

**Comment by samdutton** [comment]
Just noticed this (again). Could you elaborate a bit on the requirements?

**Comment by KaptenJansson** [comment]
Multiple audio and video streams > separate tracks > one peerconnection > multiple remote streams rendered in separate video tags with stats on the same page.

**Comment by fippo** [comment]
using what plan? _scnr_

**Comment by KaptenJansson** [comment]
Closing due to age.
