### ISSUE TITLE
Candidates(device) IP address not shown under "Type:host"  in ICE candidate gathering list

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#685]
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Click on 'Gather candidates'
3. Observe that candidates list is not showing entries for "Type:host" (Candidates IP address is not shown in Candidates list)
4. There are no errors in java script console logs.
5. Now add a new TURN server and click on 'Gather candidates'
6. Observe that candidates list is not showing entries for "host" (Candidates IP address is not shown in Candidates list)

Expected result:
Candidates(device) IP address should be shown as "Type:host" in ICE candidate gathering list for both stun and turn servers.

Actual result:
Candidates list is not showing entries for "Type: host" for both stun and turn servers.

Time  Component Type    Foundation   Protocol       Address            Port      Priority
0.084      2             srflx    842163049     udp              x.x.x.x             49966    100 | 30 | 254
0.087      1             srflx    842163049     udp              x.x.x.x             53051   100 | 30 | 255
0.157
Done

Note:
1) Observed the same issue after adding a new TURN server and clicking on 'Gather candidates'.
2) "Type:host" entry is not in candidates list

**Comment by srnarayanan** [comment]
I see this issue in Chrome canary 48.0.2560.0 in Mac 10.10.5, but not in Goobuntu 14.04

**Comment by cvranjani** [comment]
This issue was observed when multiple hangouts and apprtc calls were running on device swanky. I could not reproduce this issue after closing out all the other calls.

Closing this bug for now. I will reopen if this issue is seen again when device is in same state as mentioned in the initial bug report.
