### ISSUE TITLE
How to deploy Apprtc's collider into Google App Engine?

### ISSUE THREAD

**Issue by santhosh-kumar** [webrtc/samples#686]
I have deployed the apprtc's google app engine code on my own GAE server. I don't find instructions on how to deploy the Go based collider for websocket signaling. 

Any insights would help. Thank you.

**Comment by KaptenJansson** [comment]
Hi,

Could you file this in the correct repo? https://github.com/webrtc/apprtc.

Thanks!

**Comment by KaptenJansson** [comment]
Just looked into this, we just use a Google compute engine VM thus the instructions at https://github.com/webrtc/apprtc/tree/master/src/collider should be enough, you ofc have to setup the usual firewall rules etc to make it accessible to your clients but that's out of the scope here.
