### ISSUE TITLE
Session error description: Couldn't set up DTLS-SRTP on RTP channel

### ISSUE THREAD

**Issue by SteveCuiPanPan** [webrtc/samples#687]
Issue - I still see this error in the js console:Failed to set local sdp: Session error code: ERROR_TRANSPORT. Session error description: Couldn't set up DTLS-SRTP on RTP channel

What steps will reproduce the problem?
1.A send offer to B;
2.B receive offer，return pranswer
3.then,B return answer

When B setLocalDescription ,one error in the js console:Failed to set local sdp: Session error code: ERROR_TRANSPORT. Session error description: Couldn't set up DTLS-SRTP on RTP channel..

**Comment by KaptenJansson** [comment]
Dupe of #178, issue is in WebRTC.
