### ISSUE TITLE
Re-enable "Gather unbundled RTCP candidates" checkbox logic in Trickle ICE sample page

### ISSUE THREAD

**Issue by tednakamura** [webrtc/samples#690]
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ includes a "Gather unbundled RTCP candidates" checkbox. However, the state of the checkbox doesn't change the output of the gathered candidates at all.

On further inspection, it looks this is because the js logic related to the checkbox has been commented out. Here are what I believe are related snippets from src/content/peerconnection/trickle-ice/js/main.js:

`// var unbundleCheck = document.querySelector('input#unbundle');`
...
`// offerOptions.optional = [{'googUseRtpMUX': !unbundleCheck.checked}];`

There's no TODO near either of those commented out lines. Does anyone recall why they were commented out, and if that reason is no longer valid, can they be reinstated?

**Comment by fippo** [comment]
I think the new way to do it is to set the bundlePolicy. How about adding radio/dropdown buttons for that. Maybe also rtcp-mux policy but that won't make it into the spec.

**Comment by KaptenJansson** [comment]
Well spotted, did not even pay attention to the fact it was commented out ;). 

@fippo's suggestion SGTM.
