### ISSUE TITLE
Need a demo page for goog* options/constraints

### ISSUE THREAD

**Issue by marwahvikas** [webrtc/samples#70]
Fork constraints-and-stats.html to include googNoiseReduction, googNoiseSuppression,  googEchoCancellation and googHighpassFilter as well.

**Comment by KaptenJansson** [comment]
@samdutton do you think this is still a valuable addition?

**Comment by samdutton** [comment]
I tend to think the samples should only include what's in the spec(s).

https://github.com/webrtc/samples links to https://apprtc.appspot.com/params.html, which is probably enough. 

Also, the goog\* constraints will be barefuly usable in the  https://webrtc.github.io/samples/src/content/peerconnection/constraints demo.

**Comment by KaptenJansson** [comment]
Thanks for the response, I agree.
