### ISSUE TITLE
Grey tones and "Send tones" are not working as expected when duration is between 70 and 99

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#700]
Repro steps:
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/dtmf/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Press the "Call" button
4. Press any of the grey tone buttons and verify that you hear the corresponding tone.
5. Press the "Send tones" button
6. Verify that you hear the button tones as they're played out.
7. Observe that values in "Duration" and "Gap" are 500, 50 respectively
8. Now, try to change the values of "Duration" to any number less than 70 and press "Send tones" button
9. Observe that java script console shows error "Uncaught SyntaxError: Failed to execute 'insertDTMF' on 'RTCDTMFSender': The duration provided (69) is outside the range (70, 6000)."
10. Now, try to change the value of "Duration" to any number between 70 -99 and press "Send tones" button
11. Observe that no tones are sent and there are no errors shown in java script logs
12. Now, try to change the value of "Duration" to any number between 100 - 6000 and press "Send tones" button

Expected results:
When "Duration" value is between 70-99, pressing any grey button should play sound and pressing "Send tones" button should send tones.
(as java script console error indicates valid range for duration as 70-6000)

Actual results:
When "Duration" value is between 70-99, pressing any grey button is not playing any sound and pressing "Send tones" button is not sending corresponding tones.

Java script console logs:

"This appears to be Chrome
common.js:8 53.952: Starting call
common.js:8 54.058: Created local peer connection object pc1
common.js:8 54.062: Created remote peer connection object pc2
common.js:8 54.062: Requesting local stream
adapter.js:32 chrome: {"audio":true,"video":false}
common.js:8 56.172: Received local stream
common.js:8 56.173: Using Audio device: Default (pick up everything)
common.js:8 56.175: Adding Local Stream to peer connection
common.js:8 56.215: Offer from pc1 
v=0
o=- 6642370833130435042 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS 5JycXBC2HIJipFncDloucyOsNBNrO33gIkVn
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:MgDJOB/rRV69LqP9
a=ice-pwd:OJ9tkBjfVtpLL4+H98uDOwMH
a=fingerprint:sha-256 9D:0A:96:30:02:AF:E8:4F:34:C8:3E:E5:F3:50:D7:89:13:B2:70:BB:50:DA:59:D3:FB:7C:A0:CA:36:0C:33:D4
a=setup:actpass
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=sendrecv
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10; useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
a=ssrc:3133245449 cname:N81JPOmKwV9gtUEy
a=ssrc:3133245449 msid:5JycXBC2HIJipFncDloucyOsNBNrO33gIkVn 7d805825-3714-4aab-a7b5-c19772fd83e7
a=ssrc:3133245449 mslabel:5JycXBC2HIJipFncDloucyOsNBNrO33gIkVn
a=ssrc:3133245449 label:7d805825-3714-4aab-a7b5-c19772fd83e7
common.js:8 56.225: Answer from pc2: 
v=0
o=- 1928496966481560090 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE audio
a=msid-semantic: WMS
m=audio 1 RTP/SAVPF 0 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:L8ONfnQkE3RDzUGQ
a=ice-pwd:QZrxbGjaO4Ger1ob94blppXe
a=fingerprint:sha-256 9D:0A:96:30:02:AF:E8:4F:34:C8:3E:E5:F3:50:D7:89:13:B2:70:BB:50:DA:59:D3:FB:7C:A0:CA:36:0C:33:D4
a=setup:active
a=mid:audio
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:3 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:126 telephone-event/8000
a=maxptime:60
common.js:8 56.226: Local ICE candidate: 
candidate:186199869 1 udp 2122260223 192.168.1.101 48517 typ host generation 0
common.js:8 56.227: Local ICE candidate: 
candidate:186199869 2 udp 2122260222 192.168.1.101 34597 typ host generation 0
common.js:8 56.228: Received remote stream
common.js:8 56.229: Created DTMFSender:
2common.js:8 56.229: AddIceCandidate success
common.js:8 56.268: Remote ICE candidate: 
 candidate:186199869 1 udp 2122260223 192.168.1.101 47994 typ host generation 0
common.js:8 56.270: AddIceCandidate success
main.js:187 Tones, duration, gap:  4 500 50
common.js:8 58.545: Sent DTMF tone: 4
common.js:8 59.094: Sent DTMF tone: 
main.js:187 Tones, duration, gap:  C 500 50
common.js:8 61.418: Sent DTMF tone: C
common.js:8 61.967: Sent DTMF tone: 
main.js:187 Tones, duration, gap:  7 500 50
common.js:8 62.944: Sent DTMF tone: 7
common.js:8 63.493: Sent DTMF tone: 
main.js:187 Tones, duration, gap:  8 500 50
common.js:8 67.685: Sent DTMF tone: 8
common.js:8 68.235: Sent DTMF tone: 
main.js:187 Tones, duration, gap:  1199##9,6633221,9966332,9966332,1199##9,6633221 69 50
main.js:188 Uncaught SyntaxError: Failed to execute 'insertDTMF' on 'RTCDTMFSender': The duration provided (69) is outside the range (70, 6000).sendTones @ main.js:188handleSendTonesClick @ main.js:193
2main.js:187 Tones, duration, gap:  1199##9,6633221,9966332,9966332,1199##9,6633221 71 50"

**Comment by tednakamura** [comment]
cvranjani@ - if you skip step 8 (and by extension, step 9), do you still encounter this problem? It's unclear to me if the problem really is setting durations in the range of 70-99, or if the problem is the fact that once the js error noted in step 9 occurs, the page never fully recovers.

**Comment by KaptenJansson** [comment]
@tednakamura yes you are correct, it never recovers. However the page should not get into such a state, we should guard the API in the UI from this.

Good catch!

**Comment by cvranjani** [comment]
@tednakamura :

Observed this issue even after skipping steps 8 and 9.

**Comment by samdutton** [comment]
Thanks for reporting this — and especially for all the detail in the bug report.

#701 should fix it.

@tednakamura @KaptenJansson
