### ISSUE TITLE
Filetransfer page hangs up after canceling a selection of file 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#706]
Steps to reproduce:
1. Open https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Click on "Choose File" and select an empty/non-empty file to transfer
3. After the transfer is complete, click on "Choose File" again
4. This time, hit Cancel in the dialog box

Actual results:
The "Choose File" button gets disabled and there's a JS error in the console 
Uncaught TypeError: Cannot read property 'name' of undefined
The page needs to reloaded to enable filetransfer

Seen in Windows 7/Mac 10.11/Ubuntu 14.04

**Comment by srnarayanan** [comment]
Saw this issue today in M55 in Linux

Screenshot

![screenshot from 2016-10-06 12 56 56](https://cloud.githubusercontent.com/assets/14947786/19171101/f00910f8-8bcf-11e6-8dd5-5b3aea6556e9.png)

**Comment by samdutton** [comment]
Thanks for the heads-up. We'll take a look.
