### ISSUE TITLE
Getting timeout issue for ice candidate collection

### ISSUE THREAD

**Issue by KrishPS** [webrtc/samples#707]
During the call with WebRTC app in CEF3, I am getting below Errors. I have done a lot analysis but could not figure it out reason/solution of this issue.. Please suggest what is the problem & what is the solution.

1448447657717 - WebRtcAdaptorImpl - ICE candidate received: sdpMLineIndex = 1, candidate = candidate:1972606970 2 tcp 1518214910 10.12.1.104 0 typ host tcptype active generation 0 for call : undefined
1448447658619 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447659623 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447660625 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447661628 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447662630 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447663632 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447664635 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447665636 - WebRtcAdaptorImpl - Re-setting ice candidate collection timeout: 1000
1448447666638 - WebRtcAdaptorImpl - Ice candidate collection interrupted after given timeout, invoking successCallback.
1448447666639 - WebRtcAdaptorImpl - previous mute state of call: false

Error: WebRtcAdaptorImpl - Ice candidate collection interrupted after given timeout instead of "WebRtcAdaptorImpl - ice gathering complete"
Getting the delay of 9 seconds...

**Comment by samdutton** [comment]
Hi — this looks like a problem with a native implementation on CEF3, rather than a problem with the JavaScript for these samples.

You should post a bug at one of the forums linked to from [bitbucket.org/chromiumembedded/cef](https://bitbucket.org/chromiumembedded/cef) or on [crbug.com/new](https://crbug.com/new), or ask a question on [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc).

**Comment by KrishPS** [comment]
Thanks Sam, 
I have raised below issue for the same.
https://bitbucket.org/chromiumembedded/cef/issues/1777/getting-timeout-error-for-ice-candidate

**Comment by samdutton** [comment]
Thanks!
