### ISSUE TITLE
Uncaught error thrown on stopping screensharing using windows picker extension on device Kitty

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#708]
Device: Kitty
Chrome version:  48.0.2564.23 / 7647.18.0 beta

Repro steps:
1. Browse to https://test.webrtc.org/manual/peer2peer/
2. Click screen capture and if you get an error, follow the instructions and install the extension.
3. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
4. Follow the instructions on the page
5. Select any one of the windows to share
6. Observe that selected screen is shared/shown under 'Remote Video' 
7. Now stop the screenshare by clicking on 'Stop' in right hand side corner of the window on device Kitty
8. Observe that screensharing is stopped but javscript logs show "Uncaught Error: [object MediaStream] getUserMedia successful but MediaStreamTrack.onended event fired, no frames from camera."

Expected result:
Stopping screenshare should stop the screen sharing and should not result in any errors

Actual result:
Stopping screenshare stopped screen share but javscript logs show "Uncaught Error: [object MediaStream] getUserMedia successful but MediaStreamTrack.onended event fired, no frames from camera."

Feedback submitted:
https://feedback.corp.google.com/product/208/neutron?lView=rd&lRSort=1&lROrder=2&lRFilter=1&lReportSearch=user:srcv&lReport=6674826604

Javascript logs:
"This appears to be Chrome
main.js:1118 Requesting doGetUserMedia: constraints: {"audio":false,"video":{"mandatory":{"chromeMediaSource":"desktop","chromeMediaSourceId":"QtyD+v09GVZJqsTwrFOBAQ==","maxWidth":1920,"maxHeight":1080}}}
adapter.js:32 chrome: {"audio":false,"video":{"mandatory":{"chromeMediaSource":"desktop","chromeMediaSourceId":"QtyD+v09GVZJqsTwrFOBAQ==","maxWidth":1920,"maxHeight":1080}}}
main.js:1118 getUserMedia success
main.js:1116 Uncaught Error: [object MediaStream] getUserMedia successful but MediaStreamTrack.onended event fired, no frames from camera.printHandler_ @ main.js:1116error_ @ main.js:1103stream.getVideoTracks.onended @ main.js:984"

**Comment by KaptenJansson** [comment]
Good catch, we should ignore the event once the track has been stopped.

**Comment by KaptenJansson** [comment]
But this is filed in the wrong tracker, this belongs to the testrtc repo.

All pages on https://test.webrtc.org/manual/ (including WebRTC troubleshooter/testrtc) belong to https://github.com/webrtc/testrtc
All pages on https://webrtc.github.io/samples/ belong to https://github.com/webrtc/samples.

**Comment by cvranjani** [comment]
KaptenJansson@ : 
Thanks for the clarification.  Closing this issue  as it was filed under wrong repository.
Filed https://github.com/webrtc/testrtc/issues/165 under correct repository (https://github.com/webrtc/testrtc)
