### ISSUE TITLE
Firefox error with srcObject with MediaRecorder demo

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#711]
I get an error in Firefox with the [MediaRecorder demo](https://webrtc.github.io/samples/src/content/getusermedia/record/): 

```
TypeError: Value being assigned to HTMLMediaElement.srcObject does not implement interface MediaStream.
```

@fippo @KaptenJansson The pre-adapter.js version with `recordedVideo.src` works fine (I've still got that at [simpl.info/mr](https://simpl.info/mediarecorder/)).

**Comment by fippo** [comment]
my bad. I tested that and ran into the error but somehow changed things again in https://github.com/fippo/webrtc/commit/e28b4fa8c7344dd093b7868c7dc5c2c55f85ea43
