### ISSUE TITLE
Unable to download the recorded video

### ISSUE THREAD

**Issue by saulnoz** [webrtc/samples#712]
After recording the video, when I click on the download link I have an error in the console :
Uncaught TypeError: Cannot set property style of #<HTMLElement> which has only a getterdownload @ main.js:127

The video is recorded, i opened the webm in a new tab

My chrome version Version 47.0.2526.80 (64-bit)

**Comment by samdutton** [comment]
Do you also get this in Canary (i.e. 49)?

**Comment by saulnoz** [comment]
I tried with Canary, but I can't reproduce the error

**Comment by KaptenJansson** [comment]
@samdutton is this fixed?

**Comment by samdutton** [comment]
Yes — as per the merge. No further comments, so I'll close it now.
