### ISSUE TITLE
Recorded video on playback is badly pixelated

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#714]
Steps to reproduce:
1. Open https://webrtc.github.io/samples/src/content/getusermedia/record/
2. Click on "Start Recording" and after a few secs, click on "Stop Recording"
3. Click "Play" to view the recorded video 
4. Click on "Download" to download the recorded video

Expected results:
On playback, the video should be clear, and not pixelated/blurry

Actual results:
1. Recorded video on playback is badly pixelated (only seen in Linux)
2. After I hit "Stop Recording", intermittently I get a JS console error message "Assertion failed: State should be "recording" (seen in both Linux and Mac)
Screenshot attached.

Test env: Linux Ubuntu 14.04, Mac 10.11.2 - Canary 49.0.2588.0 
(not testable in Windows due to crash bug https://code.google.com/p/chromium/issues/detail?id=568334)

![screenshot from 2015-12-11 15 12 37](https://cloud.githubusercontent.com/assets/14947786/11758093/e3405476-a01b-11e5-9205-bac1f750a9b4.png)

**Comment by samdutton** [comment]
>  After I hit "Stop Recording", intermittently I get a JS console error message "Assertion failed: State should be "recording" (seen in both Linux and Mac)

@srnarayanan Thanks for the report! I've seen this too, but I don't think it's related to the pixelation you're seeing. 

@miguelao Should we just remove that assertion? I'm not clear what the state should be at that point. Can you reproduce this pixelation on Linux?

**Comment by cvranjani** [comment]
Observed this issue on Chrome OS device Pixel with M49 version 49.0.2600.0. / 7779.0.0 dev
![img_7716](https://cloud.githubusercontent.com/assets/15255941/12042585/28e8a780-ae31-11e5-845a-0042e4a933fd.JPG)

**Comment by KaptenJansson** [comment]
To me this looks like a mediaStream recorder issue in Chrome, not the demo page. Unless we store the data incorrectly ofc.

**Comment by samdutton** [comment]
@srnarayanan Apologies for the delay in responding — just got back from holidays. Are you still getting the pixellation problem in the latest Canary on Linux? I can't reproduce this on Mac. 

BTW: the assert statements have been removed — these were only meant for initial development.

@miguelao FYI

**Comment by srnarayanan** [comment]
Tested in Canary 49.0.2612.0 in Mac, Linux, and I'm not able to reproduce this. 
("Experimental Web Platform features" flag is enabled in chrome://flags)
I see the dialog box as in screenshot, and after I press OK, I see the following JS error on console

Exception while creating MediaRecorder: TypeError: Failed to construct 'MediaRecorder': parameter 2 ('options') is not an object.(…)

![screenshot from 2016-01-04 11 21 42](https://cloud.githubusercontent.com/assets/14947786/12098305/4e1ce594-b2d6-11e5-9217-38e510a3d2c4.png)

**Comment by samdutton** [comment]
Could you do a hard refresh (clear the cache) and try again? The parameter
2 ('options') error looks like something that's now been fixed.

If you look at main.js, options should be defined like this:

```
var options = {mimeType: 'video/vp9'};
```

**Comment by srnarayanan** [comment]
I cleared cache, relaunched canary and ran the test - I still see the same issue.

Note: I do not see this issue in stable Chrome 47.0.2526.106

**Comment by cvranjani** [comment]
Issue(mentioned in Comment #6 ) is observed in Chrome device Blaze MP with version M49 49.0.2611.0 / 7797.0.0 dev
![img_7853](https://cloud.githubusercontent.com/assets/15255941/12100483/14de82b6-b2e4-11e5-8e17-a917cd572b4e.JPG)

**Comment by samdutton** [comment]
I think what's happening is that for some reason the first try in `startRecording()` is throwing an exception, which means the String version of `options` is used, which leads to the error.

I've added a `console.log()` call to show the exception in the first try — could you have another go and tell me what error is shown?

Thanks.

**Comment by srnarayanan** [comment]
After I press "Start Recording", I see the error -
"Unable to create MediaRecorder with options Object:  DOMException: Failed to construct 'MediaRecorder': Failed to initialize native MediaRecorder, the type provided video/vp9is unsupported.(…)"

**Comment by samdutton** [comment]
Ah — that make sense. I'll add support for VP8.

Hold on...

**Comment by srnarayanan** [comment]
FYI - The above issue is seen in M48 Beta 48.0.2564.71 across all platforms (Win, Linux, Mac, CrOS)

**Comment by samdutton** [comment]
@srnarayanan @cvranjani #729 should fix this.

Please let us know if you're still experiencing problems.

**Comment by srnarayanan** [comment]
I still see the flag issue (as reported above) in today's Canary 49.0.2616.0 
Unable to create MediaRecorder with options Object:  DOMException: Failed to construct 'MediaRecorder': Failed to initialize native MediaRecorder, the type provided video/vp9is unsupported.(…)

Another (possibly) related bug where I cannot hear audio on playback - https://code.google.com/p/chromium/issues/detail?id=575748

**Comment by samdutton** [comment]
You might see the error message that VP9 isn't supported — but do you get the message that MediaRecorder was instantiated (using VP8)?

@miguelao Can you reproduce this (see thread — on Linux)?

**Comment by srnarayanan** [comment]
I see this error as well -
 Exception while creating MediaRecorder: TypeError: Failed to construct 'MediaRecorder': parameter 2 ('options') is not an object.(…)
startRecording @ main.js:102
toggleRecording @ main.js:74

**Comment by srnarayanan** [comment]
If you are looking for a message like this - "Created MediaRecorder MediaRecorder {} with options video/vp8", then no, I don't see it in today's canary

**Comment by samdutton** [comment]
OK — thanks.

**Comment by samdutton** [comment]
The mimeType property for `options` is changing. 

In #732 I've added `'video/webm'` which works for me (in Chrome 49 on Mac), though (as I understand it) this will eventually be something like `'video/webm,codecs=vp9'`.

@srnarayanan @cvranjani — could you confirm that https://webrtc.github.io/samples/src/content/getusermedia/record/ is working for your now? Thanks.

**Comment by srnarayanan** [comment]
https://webrtc.github.io/samples/src/content/getusermedia/record/ works as expected in Win, Mac & Linux - Chrome Canary 49.0.2618.0
I hear the audio on playback, and no JS errors while recording or after. 

JS logs -

This appears to be Chrome
spec:   {"audio":true,"video":true}
chrome: {"audio":true,"video":true}
getUserMedia() got stream:  MediaStream {id: "UqCPdkmBdxpsN7rWGiUXM1GJvFEfkpb0pzk0", active: true, onactive: null, oninactive: null, onended: null…}
Created MediaRecorder MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "inactive", onstart: null, onstop: null…} with options Object {mimeType: "video/webm"}
MediaRecorder started MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "recording", onstart: null, onpause: null…}
Recorded Blobs:  [Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob…]
Recorder stopped:  Event {isTrusted: true, type: "stop", target: MediaRecorder, currentTarget: MediaRecorder, eventPhase: 2…}

**Comment by samdutton** [comment]
Great news! Thanks for your patience :).

**Comment by cvranjani** [comment]
Tested https://webrtc.github.io/samples/src/content/getusermedia/record/ on Chrome OS with M49 version 49.0.2616.0 / 7818.0.0 dev.  Audio is clear on playback, and no JS errors while recording or after.

Java script logs:
"This appears to be Chrome
adapter.js:32 chrome: {"audio":true,"video":true}
main.js:49 getUserMedia() got stream:  MediaStream
main.js:107 Created MediaRecorder MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "inactive", onstart: null, onstop: null…} with options Object {mimeType: "video/webm"}
main.js:114 MediaRecorder started MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "recording", onstart: null, onpause: null…}
main.js:119 Recorded Blobs:  [Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob…]
main.js:69 Recorder stopped:  Event {isTrusted: true, type: "stop", target: MediaRecorder, currentTarget: MediaRecorder, eventPhase: 2…}"

**Comment by KaptenJansson** [comment]
Awesome, thanks for testing!

**Comment by cvranjani** [comment]
Device: Stumpy
OS: Chrome
Version : M49 dev ( 49.0.2618.0 / 7821.0.0 dev)

As mentioned in the initial bug report, https://webrtc.github.io/samples/src/content/getusermedia/record/  shows corrupted video on playback.
![record_playback_video_corrupted](https://cloud.githubusercontent.com/assets/15255941/12280659/9f8902ae-b944-11e5-9f9d-d6239fc80932.JPG)

There are errors in javascript logs

"This appears to be Chrome
adapter.js:32 chrome: {"audio":true,"video":true}
main.js:49 getUserMedia() got stream:  MediaStream
main.js:107 Created MediaRecorder MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "inactive", onstart: null, onstop: null…} with options Object {mimeType: "video/webm"}
main.js:114 MediaRecorder started MediaRecorder {stream: MediaStream, mimeType: "video/webm", state: "recording", onstart: null, onpause: null…}
main.js:119 Recorded Blobs:  [Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob, Blob…]
main.js:69 Recorder stopped:  Event {isTrusted: true, type: "stop", target: MediaRecorder, currentTarget: MediaRecorder, eventPhase: 2…}"

**Comment by cvranjani** [comment]
Sorry for small typo error in the recent comment. It should be "There are no errors in the javscript logs"

**Comment by cvranjani** [comment]
Device: Pixel
OS: Chrome
Chrome version :  49.0.2623.0 /7834.0.0 dev

Observed badly pixelated video on playback on device Pixel with M49 version 49.0.2623.0 /7834.0.0 dev.
![img_8083](https://cloud.githubusercontent.com/assets/15255941/12468009/ea07673e-bf94-11e5-8478-50a1557b667f.JPG)

**Comment by samdutton** [comment]
@miguelao fyi

**Comment by srnarayanan** [comment]
Saw the 'pixelated video on playback' issue in Linux 14.04 Chrome 49.0.2623.23

Screenshot - https://screenshot.googleplex.com/WdFCHaxx0xN.png
