### ISSUE TITLE
"Generate and send data" button can be enabled during data transfer

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#720]
Tested on device: Celes
Version: M49 (49.0.2577.0  / 7692.0.0 dev)
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click on "Generate and Send data" for the default size 128 MB
4. Observe that "Generate and Send data" button is disabled and data transfer is in progress 
5. Now change the data transfer size to any number > 0 (Example : 78)
6. Note that "Generate and send data" button is disabled as data transfer is in progress for previously selected data transfer size (128)
7. Now click anywhere around "Generate and send data" button and notice that the button gets enabled even though data transfer is in progress 
8. Click on "Generate and send data" button once it gets enabled
9. This results in following java script error : 
   "main.js:132 Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'" but data transfer completes (though I am not sure data transfer completed with old size or new size)
   ![data_channel_error](https://cloud.githubusercontent.com/assets/15255941/11964302/857e8ffe-a8a1-11e5-8139-678d624d33c8.JPG)

Expected results:
1. 'Generate and send data' button should be in disabled state as long as data transfer is in progress
2.  'Generate and send data' should be enabled after data transfer completes allowing the user to change the data size and send the data again.

Actual results:
1. 'Generate and send data' button is getting enabled if user clicks anywhere around that button while  data transfer is in progress 
2.  Data transfer completes (with old or new size) even though there are errors in javascript console
3. Data channels are not closed and "Generate and send data" button is in disabled state

Javscript logs:
"adapter.js:32 This appears to be Chrome
common.js:8 2.671: Created local peer connection object localConnection
common.js:8 2.679: Created send data channel
common.js:8 2.686: Created remote peer connection object remoteConnection
common.js:8 2.699: Offer from localConnection 
v=0
o=- 8379235379730154629 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:36QtyPdaNdVbLTOC
a=ice-pwd:jNkojIXfOihr1jZXCFWCraCh
a=fingerprint:sha-256 D3:30:A9:5B:31:C2:8D:C2:7A:E4:AE:1B:44:73:38:E1:71:6C:00:31:52:93:9C:62:5E:74:7B:8E:09:32:82:D5
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 2.711: Answer from remoteConnection 
v=0
o=- 8682207387353473832 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:SMVatWxwSbS2CRNL
a=ice-pwd:UVfnxlN/wbbLmmW4mzk4n347
a=fingerprint:sha-256 D3:30:A9:5B:31:C2:8D:C2:7A:E4:AE:1B:44:73:38:E1:71:6C:00:31:52:93:9C:62:5E:74:7B:8E:09:32:82:D5
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 2.714: local ice callback
common.js:8 2.717: Local ICE candidate: 
candidate:1021689336 1 udp 2113937151 192.168.1.160 34882 typ host generation 0
common.js:8 2.719: AddIceCandidate success.
common.js:8 2.720: remote ice callback
common.js:8 2.722: Remote ICE candidate: 
 candidate:1021689336 1 udp 2113937151 192.168.1.160 45260 typ host generation 0
common.js:8 2.723: AddIceCandidate success.
common.js:8 2.754: local ice callback
common.js:8 2.760: remote ice callback
common.js:8 2.769: Send channel state is: open
common.js:8 2.792: Using the bufferedamountlow event for flow control
common.js:8 2.795: Receive Channel Callback
common.js:8 13.558: Created local peer connection object localConnection
common.js:8 13.560: Created send data channel
common.js:8 13.569: Created remote peer connection object remoteConnection
common.js:8 13.587: Offer from localConnection 
v=0
o=- 8955282317808705151 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:FcFTAZhUUhLkToo+
a=ice-pwd:mAhVzK3YUgmWWK5u2kRdZLc+
a=fingerprint:sha-256 D3:30:A9:5B:31:C2:8D:C2:7A:E4:AE:1B:44:73:38:E1:71:6C:00:31:52:93:9C:62:5E:74:7B:8E:09:32:82:D5
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
common.js:8 13.673: Answer from remoteConnection 
v=0
o=- 4533321829994004332 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:bb4QE/qqmQGFpqmj
a=ice-pwd:gcw/pk6PSHn744R7l0MGVxID
a=fingerprint:sha-256 D3:30:A9:5B:31:C2:8D:C2:7A:E4:AE:1B:44:73:38:E1:71:6C:00:31:52:93:9C:62:5E:74:7B:8E:09:32:82:D5
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
main.js:132 Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'sendAllData @ main.js:132listener @ main.js:115
common.js:8 13.726: local ice callback
common.js:8 13.732: Local ICE candidate: 
candidate:1021689336 1 udp 2113937151 192.168.1.160 46705 typ host generation 0
common.js:8 13.739: AddIceCandidate success.
common.js:8 13.740: remote ice callback
common.js:8 13.743: Remote ICE candidate: 
 candidate:1021689336 1 udp 2113937151 192.168.1.160 35840 typ host generation 0
common.js:8 13.745: AddIceCandidate success.
common.js:8 13.756: remote ice callback
common.js:8 13.786: local ice callback
common.js:8 14.770: Send channel state is: open
common.js:8 14.787: Using the bufferedamountlow event for flow control
common.js:8 14.819: Receive Channel Callback"

**Comment by KaptenJansson** [comment]
I've not been able to reproduce this (did find #747 though). Is this only happening on CrOS?

**Comment by cvranjani** [comment]
This issue was observed on CrOS  for few days around the time when bug was initially filed (12/22/2015). Not sure what fixed this issue but I am unable to reproduce it now on M49 build 49.0. 2623.35 /7834.19.0 dev
