### ISSUE TITLE
Browser does not support output device selection. (Chrome 47 & 49)

### ISSUE THREAD

**Issue by jenyckee** [webrtc/samples#721]
I tried the samples from <a href="https://webrtc.github.io/samples/src/content/devices/multi/">here</a> on Chrome 47.0.2526.106 (64-bit) and 49.0.2603.0 canary (64-bit). Both give me 

```
"Browser does not support output device selection."
```

on the console. In what version of chrome is this supported?

**Comment by fippo** [comment]
You still need to enable "experimental Web Platform features" as described on https://webrtc.github.io/samples/src/content/devices/input-output/
