### ISSUE TITLE
Intermittent "Uncaught InvalidStateError" thrown in datachannel/datatransfer page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#734]
Steps to reproduce:
1. Open https://webrtc.github.io/samples/src/content/datachannel/datatransfer/ page
2. Leave the default size of data to be sent as is / Enter a big number (say 500 or 795 MB)
3. Let the Ordered mode option be selected as is
4. Click on "Generate and send data"

Expected results:
1. No JS console errors should be seen
2. Channel states should be opened and closed correctly, with data channels and peerconnections closed

Actual results:
JS error seen -
Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
sendAllData @ main.js:133
listener @ main.js:116 

JS logs and screenshot below

Notes - 
1. In the JS logs, the above JS error is seen before the message "Send channel state is: closed" 
2. There has been a few instances where the message "Send channel state is: closed" & the error do not appear. The last log entered would be "Closed peer connections"
3. So far, I've seen this issue in Mac & Linux, but it's not 100% reproducible though (happened 3/8 times or so)

My question here is - are we making an attempt to "send" after data channels/peerconnections are closed (as seen in the logs); hence we see this InvalidState error?

![screen shot 2016-01-12 at 11 10 38 am](https://cloud.githubusercontent.com/assets/14947786/12273918/3bfbf3ee-b91d-11e5-9957-3c063433afeb.png)

JS logs -

This appears to be Chrome
2.016: Created local peer connection object localConnection
2.017: Created send data channel
2.018: Created remote peer connection object remoteConnection
2.024: Offer from localConnection 
v=0
o=- 2097595999754420461 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
a=ice-ufrag:2CrKtt/S5ULaB4Vg
a=ice-pwd:Y9uI9xDsNT66640gP32zqgde
a=fingerprint:sha-256 1D:23:D5:3E:49:60:9B:63:E3:6F:FF:65:56:EA:08:F3:2E:33:86:C0:E4:1F:28:7D:DC:AB:24:D0:15:4A:83:D6
a=setup:actpass
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
2.026: local ice callback
2.027: Local ICE candidate: 
candidate:2960333419 1 udp 2122262783 2620::1000:137c:595:8716:95d5:5e36 64277 typ host generation 0 ufrag 2CrKtt/S5ULaB4Vg
2.027: local ice callback
2.028: Local ICE candidate: 
candidate:3684613574 1 udp 2122194687 172.19.2.101 55926 typ host generation 0 ufrag 2CrKtt/S5ULaB4Vg
2.029: Answer from remoteConnection 
v=0
o=- 6801389451626595108 2 IN IP4 127.0.0.1
s=-
t=0 0
a=msid-semantic: WMS
m=application 9 DTLS/SCTP 5000
c=IN IP4 0.0.0.0
b=AS:30
a=ice-ufrag:9jgt5jgs0kLeELQD
a=ice-pwd:FKVGvlBVyPATFdTTntstkIM7
a=fingerprint:sha-256 1D:23:D5:3E:49:60:9B:63:E3:6F:FF:65:56:EA:08:F3:2E:33:86:C0:E4:1F:28:7D:DC:AB:24:D0:15:4A:83:D6
a=setup:active
a=mid:data
a=sctpmap:5000 webrtc-datachannel 1024
22.031: AddIceCandidate success.
2.036: remote ice callback
2.037: Remote ICE candidate: 
 candidate:2960333419 1 udp 2122262783 2620::1000:137c:595:8716:95d5:5e36 55927 typ host generation 0 ufrag 9jgt5jgs0kLeELQD
2.037: remote ice callback
2.038: Remote ICE candidate: 
 candidate:3684613574 1 udp 2122194687 172.19.2.101 62122 typ host generation 0 ufrag 9jgt5jgs0kLeELQD
22.038: AddIceCandidate success.
2.038: remote ice callback
2.041: local ice callback
3.045: Send channel state is: open
3.055: Using the bufferedamountlow event for flow control
3.056: Receive Channel Callback
14.436: Closing data channels
14.436: Closed data channel with label: sendDataChannel
14.441: Closed data channel with label: sendDataChannel
14.447: Closed peer connections
main.js:133 Uncaught InvalidStateError: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
sendAllData @ main.js:133
listener @ main.js:116
14.453: Send channel state is: closed

**Comment by KaptenJansson** [comment]
Yes it looks like it's trying to send after the dataChannel is closed. Most like https://github.com/webrtc/samples/blob/gh-pages/src/content/datachannel/datatransfer/js/main.js#L126 firing after the dataChannel is closed, I think we should add a check so that the dataChannel exists/is in the right state before sending data.

**Comment by KaptenJansson** [comment]
Closing due to age.
