### ISSUE TITLE
Investigate why iceRestart test fails sometimes

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#743]
It looks like the event at https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/restart-ice/js/test.js#L82 is not firing.

Failed build on Chrome beta:
https://travis-ci.org/webrtc/samples/jobs/105573499#L1087

cc @fippo

**Comment by fippo** [comment]
https://bugs.chromium.org/p/webrtc/issues/detail?id=3021 -- even though that is pretty stable now in my experience. Going to completed is not a hard requirement for doing an ice restart so we can change the test.

cc @taylor-b

**Comment by KaptenJansson** [comment]
I see. Good to know.

**Comment by KaptenJansson** [comment]
#746 should fix this.
