### ISSUE TITLE
Intermittent "Uncaught TypeError" thrown in peerconnection/webaudio-input page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#745]
Steps to reproduce:
1. Go to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/ page
2. Click "Start", and observe the JS console

Actual results:
The following JS error is seen in the console
(Screenshot attached)

Uncaught TypeError: Failed to set the 'buffer' property on 'AudioBufferSourceMode': The provided value is not of type 'AudioBuffer'

Notes:
1. Saw this issue in Win 7, Win 8 - M50 Dev 50.0.2638.0
2. Happens ONLY when the webaudio-input sample page is opened for the first time, in a new browser session. Subsequent reloads of the same page doesn't show this error.

![typeerror](https://cloud.githubusercontent.com/assets/14947786/12767559/b7cf0ee6-c9be-11e5-83a3-2c71588d63b2.png)

**Comment by KaptenJansson** [comment]
Seems to be some race condtion when the page is not loaded from cache.

**Comment by KaptenJansson** [comment]
Closing due to age.
