### ISSUE TITLE
Datatransfer does not finish when triggered a 2nd time after changing value

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#747]
Steps to repro:
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
2. Click generate and send data
3. When finished, change the value to 44 (or any other number) and click generate and send date

Result:
Stuck on sending with the progress bar on 100%, last few events seen are:

```
9.560: AddIceCandidate success.
common.js:8 9.604: local ice callback
common.js:8 9.605: remote ice callback
common.js:8 9.611: Send channel state is: open
common.js:8 9.622: Using the bufferedamountlow event for flow control
common.js:8 9.651: Receive Channel Callback
```

Seems only to happen if the data size is changed between runs.

**Comment by KaptenJansson** [comment]
Chrome version 48.0.2564.82 (64-bit) on Kubuntu 14.04

**Comment by cvranjani** [comment]
Observed this issue on CroS with M49 build 49.0. 2623.35 /7834.19.0 dev (only when value is greater than 27MB). Please see the screenshots where it was working for value 27MB
![data_value_28mb](https://cloud.githubusercontent.com/assets/15255941/12792813/69743524-ca62-11e5-97a1-4ae090af81cc.JPG)
![data_value_27mb](https://cloud.githubusercontent.com/assets/15255941/12792819/6c5c6b80-ca62-11e5-9fd9-437f69e1c77f.JPG)

**Comment by KaptenJansson** [comment]
Closing due to age.
