### ISSUE TITLE
Web Audio Input sample page invokes createOffer and createAnswer without providing error callbacks

### ISSUE THREAD

**Issue by guidou** [webrtc/samples#751]
Not providing error callbacks to createOffer and createAnswer is deprecated in Chrome M49 and removed in Chrome M50.

See the following lines:
 https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/webaudio-input/js/main.js#L123
https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/webaudio-input/js/main.js#L82

**Comment by Hongbo-Miao** [comment]
Hi @guidou, my program actually has callback. But using Chrome 48.0.2564.109 (64-bit) still cannot run well. Last version runs well.

```
this.myConnection.createOffer((offer) => {
        this.send({type: "offer", offer: offer});
        this.myConnection.setLocalDescription(offer);
    }, (err) => {
        alert(`startPeerConnection: ${err}`);
    });
```

```
 this.myConnection.createAnswer((answer) => {
 this.myConnection.setLocalDescription(answer);
        this.send({type: "answer", answer: answer});
    }, (err) => {
        console.log("onOffer: ", err);
});
```

**Comment by hongbo-miao** [comment]
Hi, @guidou, I come from [here](https://code.google.com/p/chromium/issues/detail?can=2&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=&id=586007). My program actually has callback. But using Chrome 50.0.2645.4 dev (64-bit) still cannot run well. Last old dev version runs well.

This is part of my codes:

```
this.myConnection.createOffer((offer) => {
        this.send({type: "offer", offer: offer});
        this.myConnection.setLocalDescription(offer);
    }, (err) => {
        alert(`startPeerConnection: ${err}`);
});
```

```
this.myConnection.createAnswer((answer) => {
        this.myConnection.setLocalDescription(answer);
        this.send({type: "answer", answer: answer});
    }, (err) => {
        console.log("onOffer: ", err);
});
```

What do you mean callback here? Do you mean promise-based versions, not just normal callback? Thanks

**Comment by guidou** [comment]
Your problem is definitely not related to crbug.com/586007 since you are
providing error callbacks. crbug.com/586007 applies only to Chrome 50, and
you say you are having problems with 48.
Not having any other details, I cannot help you with your problem. However,
someone at https://groups.google.com/forum/#!forum/discuss-webrtc might be
able to help you if you provide more details there.

**Comment by hongbo-miao** [comment]
@guidou sorry, I typed wrong, not 48.
My program runs well on other **dev version** like 50.0.2644. I tested, only this 50.0.2645.4 dev version has problem. So I am thinking this 50.0.2645.4 dev Chrome may have other bugs. But thanks anyway!
