### ISSUE TITLE
Face tracking demo video is not shown in Chrome 50.0.2645.4 dev (64-bit)

### ISSUE THREAD

**Issue by hongbo-miao** [webrtc/samples#757]
[Face tracking](https://webrtc.github.io/samples/src/content/getusermedia/face/) demo video is not shown in Chrome 50.0.2645.4 dev (64-bit). The app actually already gets video, because you can see the rectangle of the detection of your face. But the video just does not show.
The demo works well in old version Chrome.

I am not sure this is because of Chrome bug or the demo has bug. Because other demos work well in Chrome 50.0.2645.4 dev (64-bit).

**Comment by KaptenJansson** [comment]
It works for me on 50.0.2652.0 but not all that well, not sure if it's
always been like that though.

**Comment by samdutton** [comment]
I get this error in Chrome 48 and 50 on Mac:

_Uncaught IndexSizeError: Failed to execute 'getImageData' on
'CanvasRenderingContext2D': The source width is 0.ccv.grayscale @
ccv.js:98poll @ (index):88_
Looks like ccv.js hasn't been updated in a long time — github.com/liuliu/ccv
.

We may have to remove this demo. Face detection is fun and useful, but it's
not really WebRTC!

**Comment by KaptenJansson** [comment]
Agreed.

**Comment by samdutton** [comment]
@juberti any objection if we remove the face tracking demo?
