### ISSUE TITLE
Firefox 45 can not play recorded video

### ISSUE THREAD

**Issue by pitrackster** [webrtc/samples#762]
**Browsers and versions affected**
Firefox 45

**Description**
After recording it is not possible to play the recorded blob in Firefox 45

**Steps to reproduce**
Record a video
Try to play it

**Expected results**
The video player shows the recorded video

**Actual results**
The video player display an error "The video can not be played because the file is corrupted"

In the dev console I have this message : 

```
The media resource blob:http://localhost/58eb7b9e-6f35-4433-acdc-7e9d6dc20b74 could not be decoded
```

**Comment by pitrackster** [comment]
Seems that there is a real problem with Firefox 45 and videos though... I even can't play Youtube videos !

**Comment by fippo** [comment]
can you file a bug in bugzilla please? Go to https://bugzilla.mozilla.org/enter_bug.cgi?product=Core, set the component to "WebRTC: audio/video" and ideally attach the corrupt file.
Might end up as a duplicate but better to file it than to miss something that is easy to fix.

**Comment by pitrackster** [comment]
done : 

https://bugzilla.mozilla.org/show_bug.cgi?id=1254914

**Comment by fippo** [comment]
paging @mreavy, thanks!

**Comment by pitrackster** [comment]
Ok this is solved !
It was because I ran an old FFmpeg version likely
buggy.

**Comment by mreavy** [comment]
Glad you and Jean-Yves (jya)  were able to figure it out.
