### ISSUE TITLE
Uncaught TypeError thrown during a 2 way apprtc call

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#763]
**Browsers and versions affected**
2 way apprtc call between Win 10, and CrOS device Kip 
M50 Dev 50.0.2661.18 in Win 10, and M50 dev build 50.0.2661.20 / 7978.10.0 dev in Kip

**Description**
Uncaught TypeError: Cannot read property 'receiveSignalingMessage' of null thrown during/just after a 2-way apprtc call

**Steps to reproduce**
1. Establish a 2 way apprtc call between 2 devices (in this instance, Win 10 and Kip)
2. Have the 2 participants doubletalk at the same time, and observe the JS console

**Expected results**
No JS errors should be seen, and no echo should be heard

**Actual results**
Uncaught TypeError: Cannot read property 'receiveSignalingMessage' of null thrown

Note:
While this error was seen in CrOS while double-talking, I saw this error just after disconnecting the apprtc call in Win 10. 

<img width="960" alt="js error" src="https://cloud.githubusercontent.com/assets/14947786/13652675/5e9fa85c-e602-11e5-99c8-7357a39cc402.png">

**Comment by KaptenJansson** [comment]
Thanks for reporting!
The log looks odd, the peerconnection is created after hanging up? Will take a look.

**Comment by KaptenJansson** [comment]
Closing due to age.
