### ISSUE TITLE
Can still enter <5 chars apprtc room names in browser url

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#764]
**Browsers and versions affected**
M49 Stable, M50 Dev 

**Description**
In the direct browser apprtc URL, if the "room name" in https://appr.tc/r/<<room_name>> is < 5 characters, I can still establish a 2 way apprtc call successfully 

**Steps to reproduce**
1. In either the stable/dev version of Chrome, go to https://appr.tc/r/ and type a name with lesser than 5 characters (for ex: https://appr.tc/r/abcd)
2. Click "Join"
3. Enter https://appr.tc/r/abcd in another machine and click "Join"

**Expected results**
In https://appr.tc/ and in the direct browser apprtc URL https://appr.tc/r/<<room name>>,  the apprtc room name must be 5 or more characters and include only letters, numbers, underscore and hyphen.

**Actual results**
Able to establish a 2 way apprtc call successfully even if the room name is <5 chars long

**Comment by KaptenJansson** [comment]
Thanks for reporting, this is indeed an issue but not a major one. Will fix one day ;).

**Comment by KaptenJansson** [comment]
Closing as this is reported in the wrong repo and it's not a of high priority right now.
