### ISSUE TITLE
Possible improvements to datachannel/basic sample

### ISSUE THREAD

**Issue by TikiTDO** [webrtc/samples#770]
I was recently interested in getting more familiar with DataChannels, so I decided to hit up the samples. Unfortunately the datachannel/basic sample was quite haphazard, making it difficult to see how things related to each other.

I did a quick refactor as a learning exercise, [located here](https://gist.github.com/TikiTDO/ccc2189813a11a8cc0472d977f28aaab) and I think the results are a bit clearer. I won't submit a pull request since I prefer underscores to camelCase for variable names, but I figured I'd submit it as reference for a possible refactor of the code in question.

**Comment by samdutton** [comment]
Thanks for making the effort to do this! I'll take a look.

**Comment by Globik** [comment]
But how to implement this basic with a signaler server? No need turn, stun and like? Only null?

**Comment by TikiTDO** [comment]
If you want to configure the stun servers then you can configure them in place of the nulls. Providing nulls skips that step.

**Comment by TikiTDO** [comment]
I was revisiting my WebRTC code, and decided to make some improvements to the example above. Now it documents optional parameters, and references the relevant places in the spec.

**Comment by KaptenJansson** [comment]
Closing due to age.
