### ISSUE TITLE
Webaudio input peerconnection call recording time is starting incorrectly

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#771]
Chrome version: 49.0.2623.112 / 7834.70.0 stable
Device: Celes

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Press Start
4. Start speaking, verify that you can hear yourself
5. Press Stop after few seconds (For example, stop after 4 seconds= 0:04)
6. Click on 'Start' again

**Expected results**
Call recording time should start from "0:00"

**Actual results**
Call recording time shows "0.04" and then shows "0:00". It continues recording correctly from there on.
Video for bug description: https://drive.google.com/file/d/0B_iIlDy84LyFOExnNlNHdm9pS1U/view?usp=sharing

Note:
1. This issue is seen even after refreshing the page and starting a new call.

**Comment by KaptenJansson** [comment]
Closing due to age.
