### ISSUE TITLE
FF46 getUserMedia error: SourceUnavailableError PermissionDeniedError may mean invalid constraints

### ISSUE THREAD

**Issue by arturparkhisenko** [webrtc/samples#777]
**Browsers and versions affected**
Firefox 46, 47a

**Description**
getUserMedia error: SourceUnavailableError PermissionDeniedError may mean invalid constraints.
I really ALLOWED cam and mic, i checked it!

**Steps to reproduce**
Open https://webrtc.github.io/samples/src/content/peerconnection/constraints/ in Firefox 46, 47a

**Expected results**
Should show constraints

**Actual results**
Not working

**Comment by KaptenJansson** [comment]
Could be the recent adapter.js update. Will check.

**Comment by arturparkhisenko** [comment]
@KaptenJansson tested today with Firefox 46 & 47, all is fine! Thanks)
ps. only one warning in console: `onaddstream is deprecated! Use peerConnection.ontrack instead.`
