### ISSUE TITLE
Investigate why Firefox Beta and nightly fails (46) on travis

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#780]
https://travis-ci.org/webrtc/samples/jobs/126834520

Now nightly and beta has the same error.

Cannot repro locally on Ubuntu 14.04.

@jan-ivar @fippo pointed out it might be an X11 crash, like [this](https://crash-stats.mozilla.com/report/index/5c8ce18a-0532-44f4-89cd-6aacb2160503)? WDYT?

**Comment by jan-ivar** [comment]
@KaptenJansson @fippo not sure where we see signs of crashing? The travis output doesn't look too different from what I get with both [Chrome](https://pastebin.mozilla.org/8869896) and [Firefox](https://pastebin.mozilla.org/8869897) when I try to test things locally (which isn't working for me at all as you can see). In contrast, testing adapter.js works just fine for me.

**Comment by KaptenJansson** [comment]
Closing this for now.
