### ISSUE TITLE
Aspect ratio is different between video and canvas element

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#786]
**Browsers and versions affected**
M51

**Description**

**Steps to reproduce**
Browse to https://webrtc.github.io/samples/src/content/capture/canvas-video/

**Expected results**
The dimensions of the WebGL object should be the same in both video elements.

**Actual results**
https://drive.google.com/file/d/0B71pLQBYIPv-akNFTU1JRkRkbDQ/view?usp=sharing

**Comment by samdutton** [comment]
Yes... Noticed that :/. 

In #787 added object-fit: cover to the canvas and video elements, which seems to do the trick. Checked in Canary and Firefox.
