### ISSUE TITLE
For all samples, update any out-of-date API or method usage

### ISSUE THREAD

**Issue by samdutton** [webrtc/samples#788]
**Browsers and versions affected**
All.

**Description**
Check all the samples for out-of-date API and method usage — for example, using callbacks where promises are now available. Pull requests with fixes can reference this issue.

**Comment by fippo** [comment]
I think #789 does it all :-)

**Comment by KaptenJansson** [comment]
Closing this since #789 has been merged. If any old/deprecated API's remain, file separate issues.
