### ISSUE TITLE
pc1 demo does not work on Mac, call is not setup properly

### ISSUE THREAD

**Issue by KaptenJansson** [webrtc/samples#795]
**Browsers and versions affected**
M50 and M52 Mac, works fine on linux.

**Description**
https://webrtc.github.io/samples/src/content/peerconnection/pc1/

**Steps to reproduce**
Browse to https://webrtc.github.io/samples/src/content/peerconnection/pc1/
Click start and call

**Expected results**
Call setup properly and remote video rendered.

**Actual results**
Looks like ICE is not setup properly, stuck in checking.

51.597: pc2 setLocalDescription start
common.js:8 51.599: pc1 setRemoteDescription start
common.js:8 51.601: pc2 received remote stream
common.js:8 51.617: pc2 setLocalDescription complete
common.js:8 51.617: pc1 setRemoteDescription complete
common.js:8 51.618: pc1 ICE state: checking
main.js:218 ICE state change event:  Event {isTrusted: true, type: "iceconnectionstatechange", target: RTCPeerConnection, currentTarget: RTCPeerConnection, eventPhase: 2…}

**Comment by KaptenJansson** [comment]
It seems to be general issue on my Mac, no demos work. Something is up with my network interfaces causing chrome not to generate candidates properly.

**Comment by fippo** [comment]
absolutely no candidates? I've heard some vague reports of that recently.

**Comment by samdutton** [comment]
Woah... FWIW WFM  50.0.2661.102 (64-bit) on Mac.

**Comment by donpark** [comment]
With Chrome version 51.0.2704.106 (64-bit) on OS X El Capitan, I'm seeing following symptoms:
1. candidates are generated
2. remote stream is received but not displayed
3. ICE state ends in 'failed' after timeout.

console log is attached.

[pc1.log.zip](https://github.com/webrtc/samples/files/332943/pc1.log.zip)

Note that other RTCPeerConnection demos also fail. Same demos work fine on Firefox.

**Comment by donpark** [comment]
More data points.
1. demos work with TURN server.
2. demos work with STUN on Firefox but fails on Chrome.
3. apprtc.appspot.com demo works on both browsers.

So it seems Chrome's STUN related code may have an issue when both peers are on same page.
This is a demo-condition only issue so I recommend clearly documenting possible issue in the demo pages.

**Comment by fippo** [comment]
@donpark I would say it is the ip leak prevention but you got candidates. Do you have a full chrome://webrtc-internals dump? (which is easier to read than the console)

**Comment by donpark** [comment]
here you go. dump from failed pc1 demo.

[webrtc_internals_dump.txt.zip](https://github.com/webrtc/samples/files/333869/webrtc_internals_dump.txt.zip)

> apprtc.appspot.com demo works on both browsers.

just realized this doesn't really indicate STUN worked. Is there a simple way to tell which ICE candidate was used to connect successfully?
