### ISSUE TITLE
Unable to start a new AppRTC call with letter 'i' in roomname after ending the current AppRTC call

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#805]
Version: 52.0.2743.32 / 8350.21.0 beta
Chrome device : Any

What steps will reproduce the problem?
1) Join an apprtc loopback call with any roomname from chrome device
https://appr.tc/?debug=loopback
2) Leave the call 
3) In the left side of the apprtc window, observe the message "You have left the call" followed by "REJOIN" and "NEW ROOM" buttons 
4) Now click on "NEW ROOM" button
5) When prompted for "Please enter a room name", try to enter any room name with letter "i" (For example, winky)

What is the expected output?
User should be allowed to enter any room name which has 5 or more characters and include only letters, numbers, undrerscore and hyphen

What do you see instead?
Entering letter "i" in room name displays an over-lay box which shows information about Version, gitHash, branch and time

Notes:
1) This issue is seen with both loopback and peer2peer calls
2) This issue is not seen when loopback and peer2peer calls are started with letter "i" in room name for the first time. Issue is seen only when user leaves the current call and joins a new room with letter "i" in room name.
3) This issue is not seen when new AppRTC call is started by directly typing the room name with letter "i" from the URL bar (https://appr.tc/r/roomwithletteri )

Feedback submitted for this issue:
https://feedback.corp.google.com/product/208/neutron?lView=rd&lRSort=1&lROrder=2&lRFilter=1&lReportSearch=user:srcv&lReport=9955116559

**Comment by cvranjani** [comment]
@KaptenJansson, @tednakamura

**Comment by KaptenJansson** [comment]
Thanks for filing. We need to reset the "state" so that the keyboard event listeners are not active on the new room page.

**Comment by KaptenJansson** [comment]
This should have been filed in the apprtc project: https://github.com/webrtc/apprtc.
