### ISSUE TITLE
Text overlap when device is in portrait orientation	

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#811]
**Browsers and versions affected**
M53 53.0.2785.44, M54 54.0.2816.4
Android Build Number: NPD35C
Device: Android N Nexus 5X

**Description**
Text overlap when device is in portrait orientation 

**Steps to reproduce**
1. Open https://webrtc.github.io/samples/src/content/peerconnection/constraints/ in Clank 
2. Adjust camera constraints values so we get a 1080x1080px video dimensions
3. Click 'GetMedia' and confirm that the local video dimensions on the left are 1080x1080px 
4. Now, click 'Connect'
5. Confirm that the remote video appears on the right

**Expected results**
No overlap of text should be seen, for best UI experience  

**Actual results**
The 1080x1080px video dimension text of the local video, overlaps with that on the right

Notes: There's no overlap of text when the device is turn to the landscape orientation

Screenshot:

![7bf4260d-75ec-4355-b1e5-9a27052d7ed7](https://cloud.githubusercontent.com/assets/14947786/17373750/7a6e550e-595e-11e6-8c48-95fe00008d31.png)

**Comment by KaptenJansson** [comment]
Closing due to age.
