### ISSUE TITLE
Uncaught ReferenceError: trace is not defined thrown in the captureStream() page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#812]
**Browsers and versions affected**
Chrome M53 53.0.2785.45, M54 54.0.2817.0 
Mac 10.11.6, Android N Nexus 5X

**Description**
Uncaught ReferenceError: trace is not defined thrown in the captureStream() page

**Steps to reproduce**
1. Open https://webrtc.github.io/samples/src/content/capture/video-video/ in Chrome
2. Inspect the JS console for any JS errors

**Expected results**
No JS errors should be seen

**Actual results**
Uncaught ReferenceError: trace is not defined
leftVideo.onplay @ main.js:28
JS error thrown. Screenshot attached. 

CC: @KaptenJansson @samdutton 

![screen shot 2016-08-03 at 1 50 12 pm](https://cloud.githubusercontent.com/assets/14947786/17382089/07af1fc8-5984-11e6-8f9d-cbce8bbb45a8.png)

**Comment by fippo** [comment]
missing include of common.js, good catch!

**Comment by samdutton** [comment]
Good catch! Fixed in #813.
