### ISSUE TITLE
getStats Promise API broken in Canary

### ISSUE THREAD

**Issue by xdumaine** [webrtc/samples#814]
**Browsers and versions affected**

Chrome Version 54.0.2815.0 canary (64-bit)

**Description**

Due to [an unadvertised chrome change](https://bugs.chromium.org/p/chromium/issues/detail?id=627816#c8), the promise based API for getStats no longer works with adapter.js. 

**Steps to reproduce**
1. Try to invoke getStats with no selector (or null selector), and no success handler

``` javascript
> pc1.getStats(null, (r) => console.log('callback result', r)).then((r) => console.log('promise result', r))
promise result undefined
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: undefined}
callback result Object {googTrack_741e3532-02c7-4c7b-84b5-fa30fed76953: Object, googTrack_0438c162-8c4f-4576-97e4-7c4772bd38d8: Object ... }

> pc1.getStats((r) => console.log('callback result', r)).then((r) => console.log('promise result', r))
promise result undefined
Promise {[[PromiseStatus]]: "resolved", [[PromiseValue]]: undefined}
callback result RTCStatsResponse {}

> pc1.getStats(null).then((r) => console.log('promise result', r))
Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}
adapter.js:238 Uncaught (in promise) TypeError: Failed to execute 'getStats' on 'RTCPeerConnection': parameter 2 is not of type 'MediaStreamTrack'.(…)
```

**Expected results**
1. getStats succeeds, and yields the result

**Actual results**
1. An error is thrown

**Other Notes**

Calling `getStats` with the legacy format should probably log a deprecation warning.

**Comment by xdumaine** [comment]
Welp, I guess this was an unintended. regression. Just got a canary update and it's working again

**Comment by KaptenJansson** [comment]
Yes, https://bugs.chromium.org/p/chromium/issues/detail?id=632457
