### ISSUE TITLE
Local canvas element appears shrunk in portrait mode 

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#823]
**Browsers and versions affected**
Clank M54 Dev, M53 Beta on any device

**Description**
Local canvas element appears shrunk in portrait mode in Clank 

**Steps to reproduce**
1. Hold the device in portrait mode
2. Open https://webrtc.github.io/samples/src/content/getusermedia/filter/ in Clank
3. With the default (none) filter / any filter, click 'Take snapshot'
4. Notice the captured snapshot below 

**Expected results**
The height/width of the snapshot image should be the same as the local preview above

**Actual results**
Local canvas element appears shrunk. Attached screenshot.

CC @KaptenJansson @samdutton 

![screenshot_20160823-170737](https://cloud.githubusercontent.com/assets/14947786/17914188/e50782ea-6954-11e6-91b6-f1dfbc103c39.png)

**Comment by KaptenJansson** [comment]
Closing due to age.
