### ISSUE TITLE
Unable to compile webrtc server in ubuntu 14.04

### ISSUE THREAD

**Issue by juanjosv** [webrtc/samples#824]
I downloaded the last version from repository in my server Ubuntu 14.04.2 LTS, following the instructions from https://webrtc.org/native-code/development/ to create a test server. 
I did the command: <i>gclient sync</i> without  problems, but the next step  <i>gn gen out/Default </i>, launches the error <i>gn.py: Could not find gn executable at: webrtc-checkout/buildtools/linux64/gn</i>
The system has the depot_tools in path, so i can find gn and gn.py, but there is no folder called buildtools in webrtc.

I tried the "Using GYP (deprecated)" <i>python webrtc/build/gyp_webrtc.py</i> and displays the error:
<i>Traceback (most recent call last):
  File "webrtc/build/gyp_webrtc.py", line 24, in <module>
    import gyp_chromium
ImportError: No module named gyp_chromium</i>
And i don't know where to get the "gyp_chromium" module 

Any possible solution for any method?

Thanks

**Comment by KaptenJansson** [comment]
This repo is for web samples, not the native webrtc code. Issues can be filed at bugs.webrtc.org but first take a look at the mailing list https://groups.google.com/forum/#!forum/discuss-webrtc and see if there is any info about the issues you are facing first. You can also post questions there.

I'll try to help this time though.

Have you done `git pull` then `gclient sync` and finally `gn gen out/Default`? I think you have forgotten to do `git pull` and depot tools expects GN (it updates itself when you run `gclient sync`) while you are using an older WebRTC checkout that uses GYP.

**Comment by juanjosv** [comment]
Thanks KatpenJansson, i'll do what you write and see in that forums.
