### ISSUE TITLE
Switch samples to use navigator.mediaDevices.getUserMedia() instead of navigator.gUM()?

### ISSUE THREAD

**Issue by dandv** [webrtc/samples#825]
Samples like [this one](https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/gum/js/main.js) use [navigator.getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/getUserMedia), which is marked as deprecated by MDN.

**Comment by KaptenJansson** [comment]
https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/gum/js/main.js#L50 uses navigator.mediaDevices.getUserMedia. Did you link to the wrong one?

**Comment by dandv** [comment]
The usage is actually in the error string,

> console.log('navigator.getUserMedia error: ', e);

<strike>Other than that, there's `navigator.mediaDevices.getUserMedia` instead of `MediaDevices.getUserMedia`. Probably not a problem.</strike>

**Comment by KaptenJansson** [comment]
Did not realize it lived under window. Is there spec for that?

**Comment by KaptenJansson** [comment]
MDN https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia lists it under navigator still. But it does live under window as well.

@alvestrand do you know?

**Comment by dandv** [comment]
Nevermind my previous comment, `navigator.mediaDevices` is correct. Checked in Firefox 48 and Chrome 53 too.

`window.MediaDevices` doesn't have a `getUserMedia()` method. Looks like a constructor, but I'm not sure what it does.

**Comment by KaptenJansson** [comment]
> window.MediaDevices doesn't have a getUserMedia() method. Looks like a constructor, but I'm not sure what it does.

Confusing is what it is......;)

**Comment by alvestrand** [comment]
MediaDevices (the type) has a getUserMedia (the function), and Navigator (the type, when it's extended with NavigatorUserMedia) has a mediaDevices attribute of type MediaDevices.  Window is a Navigator, and a global object, which means (I think) that it exposes constructors for all types not marked with [NoInterfaceObject], including MediaDevices. Why someone shold want to construct a MediaDevices is beyond me, but it's there.

Case matters.

Confused yet? :-)

**Comment by dontcallmedom** [comment]
to clarify @alvestrand 's description:
- window is the global object in browsers, defined in the `Window`interface
- it has a `navigator` attribute, of type `Navigator`
- that interface gets the `NavigatorUserMedia` as a mixed-in, which provides it with `mediaDevices` attribute, of type `MediaDevices`, which itself provides the Promise-based `getUserMedia` method

Any interface not marked with `[NoInterfaceObject]` (including `MediaDevices`) is exposed in the global space as a function, but only those marked with a `[Constructor]` or `[NamedConstructor]` extended attribute are exposed as a constructor per se - in particular, you cannot construct a `MediaDevices` object

**Comment by KaptenJansson** [comment]
I believe this is fixed.
