### ISSUE TITLE
Outdated captureStream demo

### ISSUE THREAD

**Issue by wpp** [webrtc/samples#827]
**Browsers and versions affected**

Chrome Version 53.0.2785.101 (64-bit)

**Description**

The [captureStream demo](https://webrtc.github.io/samples/src/content/capture/video-video/) logs `captureStream() not supported` in Chrome 53, despite the page noting:

> This demo requires Firefox 47, Chrome 53 (or later).

**Steps to reproduce**

Visit https://webrtc.github.io/samples/src/content/capture/video-video/ with Chrome 53.

**Expected results**

Either update the required browser version or a working captureStream demo.

**Actual results**

Page lists Chrome 53 as a required browser but logs `captureStream() not supported` console and the demo is not working.

**Comment by KaptenJansson** [comment]
@samdutton PTAL

**Comment by IvRRimum** [comment]
Any update on this?

**Comment by IvRRimum** [comment]
Has chrome removed support for captureStream in chrome 54?

**Comment by samdutton** [comment]
Thanks for reminding me to sort this out.

I've added a note about enabling Experimental Web Platform Features in chrome://flags.

**Comment by wpp** [comment]
Hi!

Good to know! Unfortunately there is still an issue even after enabling the flag. The demo only seems to work as intended when I drag the player slider on the left.

**Comment by wpp** [comment]
Just a quick update after enabling the flag this demo works now. I'll close this issue, hope everyone is ok with that.

**Comment by jhonny-villarroel** [comment]
Sorry, for the question:

In the future will there be any version that supports "chrome://flags/#enable-experimental-web-platform-features" by default, instead of enable manually ?

Thanks so much in advance.

**Comment by fippo** [comment]
@yellowdoge do you know (or know someone who knows)?

**Comment by jhonny-villarroel** [comment]
@samdutton, any comment about that ?

In the future will there be any version that supports "chrome://flags/#enable-experimental-web-platform-features" by default, instead of enable manually ?

Because currently I am using Chrome Versión 59.0.3071.104 (Build oficial) (64 bits) and the Flag is not supported by default.


Thanks in advance

**Comment by fippo** [comment]
there is an intent to ship on [blink-dev](https://groups.google.com/a/chromium.org/forum/?utm_medium=email&utm_source=footer#!msg/blink-dev/6Vai94SPoEQ/DLmSiLH3BAAJ) which means this could ship in 61.

go @yellowdoge ;-)

**Comment by cameronelliott** [comment]
I hope I can ask a basic question, this demo on ChromeOS v73.xxx doesn't show the right panel
until I start dragging the seek button.

Any ideas why that is?



Version info

> Google Chrome | 73.0.3683.88 (Official Build) (64-bit)
> Revision | 25c1840a8ffd1a641130f769dc755e418c8cf151-refs/branch-heads/3683@{#863}
> Platform | 11647.104.3 (Official Build) stable-channel eve
> Firmware Version | Google_Eve.9584.174.0
> Customization ID | GOOGLE-EVE
> ARC | 5376516
> JavaScript | V8 7.3.492.25
> Flash | 32.0.0.156 /opt/google/chrome/pepper/libpepflashplayer.so
> User Agent | Mozilla/5.0 (X11; CrOS x86_64 11647.104.3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.88 Safari/537.36
