### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'close' of null" seen in /trickle-ice/ page

### ISSUE THREAD

**Issue by srnarayanan** [webrtc/samples#830]
**Browsers and versions affected**
M55 Canary 55.0.2868.0 in Win 10

**Description**
"Uncaught TypeError: Cannot read property 'close' of null" thrown in /trickle-ice/ page

**Steps to reproduce**
1. Open https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ in Chrome
2. Keeping the ICE server as the default STUN, change the ICE options as
    - uncheck 'Gather IPv6 candidates' 
    - uncheck 'Gather RTCP candidates'
3. Click 'Gather candidates'
4. Now, check 'none' for IceTransports value and gather candidates again
5. Repeat steps 2, 3, 4 with various combinations of ICE options till you see the error in the JS console

**Expected results**
No JS errors should be seen 

**Actual results**
Uncaught TypeError: Cannot read property 'close' of null thrown 

CC: @KaptenJansson

**Comment by KaptenJansson** [comment]
Could you attach a screenshot of the error expanded? I need to see which line and what calls etc.

**Comment by fippo** [comment]
you can click "gather candidates" while the peerconnection is still open. Because onicecandidate still triggers on closed peerconnections (we have seen that before here, was there ever a bug filed?)

This might lead to situations where gathering takes a long time (until timeout, 10s), the user clicks again  and we get onicecandidate w/null twice.

**Comment by srnarayanan** [comment]
Screenshot

<img width="960" alt="untitled" src="https://cloud.githubusercontent.com/assets/14947786/18794425/4e4d13c8-8174-11e6-867d-735a33cfc07d.png">

**Comment by cvranjani** [comment]
This issue is also observed on Chrome OS with M54 54.0.2840.36 / 8743.38.0 beta

**Comment by fippo** [comment]
@KaptenJansson wdyt about disabling "gather candidates" until closing the peerconnection?

**Comment by KaptenJansson** [comment]
Yeah I think that makes sense.
