### ISSUE TITLE
No "Audio output destinations" are listed when using this in Firefox

### ISSUE THREAD

**Issue by ghost** [webrtc/samples#835]
Firefox 49.0.1 (running on Windows 10 OS).

Use demo page: https://webrtc.github.io/samples/src/content/devices/input-output/

Open the demo page in Firefox, no "Audio output destinations" are listed.
Open the demo page in Chrome and audio output destinations are listed (3 in my case).

**Comment by KaptenJansson** [comment]
*Enable experimental support in Chrome 45.0.2441.x or later by selecting Enable experimental Web Platform features in chrome://flags or by using command line flag "--enable-blink-features=EnumerateDevices,AudioOutputDevices". Use the setSinkID() method on the video element and provide a audio or video element and a sinkId (deviceId for where deviceInfo.kind === 'audiooutput') as arguments. Also the web page must be served over HTTPS.

**Comment by KaptenJansson** [comment]
Firefox does not have this implemented. File or search for a feature request at https://bugzilla.mozilla.org/.

**Comment by ghost** [comment]
Apparently it's a known bug in Firefox...
[https://bugzilla.mozilla.org/show_bug.cgi?id=1152401](url)

**Comment by Pehrsons** [comment]
It's not so much a bug as it is a feature request of output selection: https://bugzilla.mozilla.org/show_bug.cgi?id=1264375
