### ISSUE TITLE
Local address does not change on ICE restart for first time (on some chrome devices)

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#837]
Chrome version : 55.0.2883.20 / 8872.16.0 dev
Chrome Device: Swanky

**Steps to reproduce**

Precondition: Have the JS console open 
1. Go to https://webrtc.github.io/samples/src/content/peerconnection/restart-ice/
2. Confirm that both the local (PC1) and remote windows (PC2) do not show any video, and the message below says "Not connected" 
3. Click "Start" and wait till local video PC1 (in left window) appears
4. Click "Call" and confirm that the remote video PC2 appears
5. Note both the addresses of PC1 and PC2, are shown below the respective windows
6. Click "Restart ICE"
7. Now, note the addresses of PC1 and PC2

Expected results:
1. No JS console errors should be seen
2. The last 5 digits in the address of PC1 from step 5, before the ICE restart, should be different from the address of PC1 from step 7 
3. PC2 address should remain the same before/after ICE restart

Actual results:
Local address of PC1 does not change after clicking on 'Restart ICE' once. It changes only after subsequent clicks of 'Restart ICE'

[Swanky_js_logs_ice_Restart.txt](https://github.com/webrtc/samples/files/540436/Swanky_js_logs_ice_Restart.txt)

Notes:
This issue is seen only on some of the chrome devices and is not consistently reproducible.

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by alvestrand** [comment]
Please raise a bug on bugs.webrtc.org, and give specifics on which devices show the behavior. It does not appear with Chrome 55 on Linux.

Very nice "how to reproduce" description!

**Comment by fippo** [comment]
@alvestrand the test for that demo is actually flaky. The issue here is that we're doing an ice restart while being connected which might not be well-defined behaviour.

**Comment by alvestrand** [comment]
If it isn't well defined it should be. Roaming from 4g onto WiFi depends on being able to do this (or permanent trickle).

Den 21. desember 2016 15:45:39 CET, skrev Philipp Hancke <notifications@github.com>:
>@alvestrand that demo is actually flaky. The issue here is that we're
>doing an ice restart while being connected which might not be
>well-defined behaviour.
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/webrtc/samples/issues/837#issuecomment-268539744

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
