### ISSUE TITLE
Webrtc stream local video file

### ISSUE THREAD

**Issue by IvRRimum** [webrtc/samples#838]
How would one stream a local media file(video file) to peers?

For audio there is webAudio, but what about the video?

Thanks!

**Comment by samdutton** [comment]
Take a look at the peer connection examples here — and appr.tc.

**Comment by IvRRimum** [comment]
@samdutton 

Thanks for your response,

apprtc is basic p2p video call. I need to stream local media **file**. Like i select mp4 file and then other person sees the file(the video and audio) in real time.

**Comment by IvRRimum** [comment]
And the file is from the user's computer. Like he selects the file from File input and then it starts to stream to all peers.

**Comment by samdutton** [comment]
Take a look at the captureStream() examples, e.g.
webrtc.github.io/samples/src/content/capture/video-pc.

**Comment by IvRRimum** [comment]
@samdutton The browser compatibility is too bad. Is there any other way? Maybe chunking the video file and then sending the chunks trough peerconnection?

**Comment by samdutton** [comment]
You could try one of Muaz Khan's methods: webrtc-experiment.com
https://www.webrtc-experiment.com.

**Comment by IvRRimum** [comment]
@samdutton Went trough all of his examples/demos. None do what i need tho ;/

Of course there is possibility by just sending the video via datachannel(or RTCmultichanneling) to other peers and then send coordinates(12:34/53:21) and then play it. But the users would have to wait then. ;/

**Comment by samdutton** [comment]
You've got pretty good coverage with captureStream(): Firefox, and Chrome
on desktop, Android and Webview — pretty much the same as
RTCPeerConnection. Why not use that?

**Comment by fippo** [comment]
@IvRRimum media source extensions might be worth a look too. Not webrtc-related even though webrtc data channels can be used a a transport

**Comment by samdutton** [comment]
@fippo Good suggestion — though you don't get much more browser coverage :/.

**Comment by IvRRimum** [comment]
@samdutton @fippo video.captureStream doesnt seem to work with chrome 54(Linux mint). Does it work for others?

**Comment by samdutton** [comment]
Might still need flag in that 54.

**Comment by fippo** [comment]
M56 with chrome://flags/#enable-experimental-web-platform-features kind of works for me. Kind of... poked [the bug](https://bugs.chromium.org/p/chromium/issues/detail?id=569976)

**Comment by samdutton** [comment]
Closing this, since it's not about an issue with the samples code.

For discussion and questions about WebRTC development, try [discuss-webrtc](https://groups.google.com/forum/#!forum/discuss-webrtc) or [StackOverflow](https://stackoverflow.com).
