### ISSUE TITLE
streamCapture black box - masivly confusing

### ISSUE THREAD

**Issue by IvRRimum** [webrtc/samples#839]
So i want to test your example: https://github.com/webrtc/samples/tree/gh-pages/src/content/capture/video-video

On your live demo version it works perfectly: https://webrtc.github.io/samples/src/content/capture/video-video/

But when i clone the repo( or even copy/paste the code on my remote server ). The right video shows up as black box.

Code is 1:1. The only difference i found that your example host has SSL. Could this be a factor?

Thanks!

**Comment by fippo** [comment]
getUserMedia requires HTTPS in Chrome. See for example http://www.tokbox.com/blog/the-impact-of-googles-new-chrome-security-policy-on-webrtc/ -- I would not be surprised if the same was true for captureStream.

**Comment by IvRRimum** [comment]
I am using firefox and i am not using getUserMedia. Please read the issue.

**Comment by IvRRimum** [comment]
Nvm, it works on my local apache with firefox.

**Comment by IvRRimum** [comment]
But still... I can't run it with my angular2 app(starting using 

> npm start

)

**Comment by IvRRimum** [comment]
Update: The black box only shows when video src is not from local storage ://

**Comment by IvRRimum** [comment]
Update: It works if you select file from localstorage(via input type file). So it's pretty nice.

**Comment by IvRRimum** [comment]
I will close this, but others bevare, you can't do it from remote videos.
