### ISSUE TITLE
Webrtc question: Is it possible to stream multiple audioTracks within the same MediaStream

### ISSUE THREAD

**Issue by IvRRimum** [webrtc/samples#844]
I just had idea. Has anyone tried this? Is Volume control isolated between the tracks?

For example using multiple mp3 files and then stream them with different time offsets and volumes at the same time.

**Comment by KaptenJansson** [comment]
AFAIK the streams are mixed together, not sure if it can handle individual volume per track. @guidou do you know?

**Comment by IvRRimum** [comment]
They are not mixed. If you have a stream with 2 or more audiotrakcs, it will stream only the first one to peers.

**Comment by KaptenJansson** [comment]
Closing due to age.
