### ISSUE TITLE
I could not get the clear video with rear camera

### ISSUE THREAD

**Issue by huangbenhao** [webrtc/samples#846]
**Browsers and versions affected**
wechat

**Description**
I run the demo of the "Select camera, microphone and speaker",but when I change the rear camera,the video became not clear,but the front camera is very nice,I read the webRTC API and I found the default fitness distance is 0,but it not use for me to set the ideal to change it.So,can you give me a demo to use the rear camera default and the video is clear?thanks!

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=343894 for details. Also you can ask further questions in that bug.

**Comment by huangbenhao** [comment]
thanks!
