### ISSUE TITLE
webaudio-input: forceOpus probably broken

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#854]
https://github.com/webrtc/samples/blob/gh-pages/src/content/peerconnection/webaudio-input/js/main.js#L106
-- this tries to match RTP/SAVPF which has been gone from Chrome for quite a while.

And to make things worse, it tries to modify between createOffer and setLocalDescription which has been declared as illegal in the spec.

@KaptenJansson does apprtc have updated code for this?

**Comment by KaptenJansson** [comment]
I could only find a [test](https://github.com/webrtc/apprtc/blob/master/src/web_app/js/sdputils_test.js#L19) for this in AppRTC. It should too be updated but it's a unit test that just tests the code using the said static array of strings rather than grabbing it from the browser.

**Comment by ErikHellman** [comment]
What should be the action here? It seems that just removing the modification between `createOffer` and `setLocalDescription` would solve this? 

@fippo what do you think?

**Comment by fippo** [comment]
opus is preferred and used by default so i'd say lets just remove the forceOpus function and its usage
