### ISSUE TITLE
Media stream forwarding

### ISSUE THREAD

**Issue by davedoesdev** [webrtc/samples#860]
If I 'forward' a media stream from one peer connection to another, will any re-encoding occur or will it just copy the bytes?

**Comment by KaptenJansson** [comment]
I believe it will re-encode, try clicking insert relay on the follow page several times:  https://webrtc.github.io/samples/src/content/peerconnection/multiple-relay/

**Comment by davedoesdev** [comment]
30% CPU (i5) for each one.

**Comment by davedoesdev** [comment]
Also you can see the effects of the encoding as you add more relays.

@KaptenJansson thanks
