### ISSUE TITLE
"Gather candidates" button is disabled for 7-8 seconds in peerconnection/trickle-ice page

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#865]
**Browsers and versions affected**
Chrome : 57.0.2984.0 / 9199.0.0 dev
Chrome OS 

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click and observe the "Gather candidates" button 

**Expected results**
You should see candidates of type "host" and type "srflx"  and "Gather candidates" button should be enabled 

**Actual results**
Candidates of type "host" and type "srflx" are displayed but "Gather candidates" button is disabled for 7-8 seconds each time the button is clicked

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by fippo** [comment]
Depending on the network conditions you are in this might be perfectly normal. Typically this happens when you have a second interface that is not routable, the webrtc library is trying to gather a serverreflexive candidate and times out.

**Comment by cvranjani** [comment]
"Gather candidates" button is disabled for 7-8 seconds even with Ethernet connection and I did not observe this delay before. 

Please feel free to close this issue if this delay is expected.

**Comment by fippo** [comment]
depending on when you last tested [this](https://github.com/webrtc/samples/pull/834) was merged ~2 weeks ago to fix #830 which has changed the behaviour of the page slightly

**Comment by cvranjani** [comment]
Yes. I am seeing this change since a week or so (don't remember it exactly though). Thanks for pointing to   [this](https://github.com/webrtc/samples/pull/834) change. It might be the reason for "Gather candidates" button to be disabled for a little longer time
