### ISSUE TITLE
404 error in peerconnection/pr-answer sample page

### ISSUE THREAD

**Issue by cvranjani** [webrtc/samples#867]
**Browsers and versions affected**
Chrome : 57.0.2984.0 / 9202.0.0 dev
OS: Chrome and Linux

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Check if the local video is seen in the left pane
3. Click "Accept"
4. Click "Hangup"

**Expected results**
- Local video is displayed in the left pane
- Remote video is displayed after clicking "Accept"
- Remote video is blank after clicking "hangup"
- There should no errors in javascript console

**Actual results**
- Local video is displayed in the left pane
- Remote video is displayed after clicking "Accept"
- Remote video is blank after clicking "hangup"
-  javascript console shows " GET https://webrtc.github.io/favicon.ico 404 (Not Found)"

[pc_pranswer_js_logs.txt](https://github.com/webrtc/samples/files/720388/pc_pranswer_js_logs.txt)

**Comment by cvranjani** [comment]
@KaptenJansson

**Comment by kyomic** [comment]
the example is not work  in chrome browser
chrome version:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.7 Safari/537.36
Window7

but, Chrome/58.0.3029.110 Safari/537.36  is OK
