### ISSUE TITLE
Update getStats usage to support spec-compliant stats.

### ISSUE THREAD

**Issue by henbos** [webrtc/samples#869]
The latest adapter.js version invokes a spec-compliant version of RTCPeerConnection.getStats if it's available. It's available in M57 Canary behind experimental web platform features flag. We have several getStats calls that iterate the resulting report expecting old style stats, these need to be updated to support both old and new styles since we don't know which one will be used.

Examples:

https://github.com/webrtc/samples/blob/83f24e75187bec346b9ef4ad5654930708308e12/src/content/peerconnection/constraints/js/main.js#L220
The bytesReceived belongs to a report of type inbound-rtp and is of type RTCInboundRTPStreamStats.
The frameWidth and frameHeight belong to RTCMediaStreamTrackStats of the track stats pointed to by report's mediaTrackId, no "googFrameHeightReceived". Though this looks like an "is video" check, which can be tested with report.mediaType == 'video'.

https://github.com/webrtc/samples/blob/83f24e75187bec346b9ef4ad5654930708308e12/src/content/peerconnection/constraints/js/main.js#L246
If a connection is the activeConnection is not specified in candidate-pair but rather an RTCTransportStats pointing to the candidate-pair knows if it is the active connection. The transport had "activeConnection", but this is being replaced by "dtlsState" being "connected" (rawgit).

https://github.com/webrtc/samples/blob/83f24e75187bec346b9ef4ad5654930708308e12/src/content/peerconnection/constraints/js/main.js#L256
"ipAddress" and "portNumber" are now called "ip" and "port".

https://github.com/webrtc/samples/blob/d6e7e2501788848bbb20d16c7a586f3780d2bbfe/src/content/datachannel/filetransfer/js/main.js#L267
It's 'candidate-pair' not 'googCandidatePair', similar comment to above about active connection.

https://github.com/webrtc/samples/blob/d6e7e2501788848bbb20d16c7a586f3780d2bbfe/src/content/peerconnection/restart-ice/js/main.js#L239
Same comments as before.

**Comment by ErikHellman** [comment]
I'm looking at the comments above and comparing it with the current code. It seems all of this has been fixed already. @henbos can you check again and see if we can close this issue?

**Comment by henbos** [comment]
Yeah looks like it :)
