### ISSUE TITLE
Pc2 is not visible in basic peer connection demo

### ISSUE THREAD

**Issue by jichae** [webrtc/samples#871]
**Browsers and versions affected**
chrome M55 and android 5.0 samsung Glaxy alpha

**Description**
https://webrtc.github.io/samples/src/content/peerconnection/pc1/

**Steps to reproduce**
You need to initialize chrome in this application during execution.
In a mobile chrome browser to https://webrtc.github.io/samples/src/content/peerconnection/pc1/
Click start and call
If the call attempt is made more than once, it is well connected.

**Expected results**
The screen of pc2 should be shown.

**Actual results**
The screen of pc2 is not visible.

Statistics ssrc_1106410230_recv log
bytesReceived	0
codecImplementationName	unknown
framesDecoded	0
mediaType	video
packetsLost	0
packetsReceived	0
ssrc	3974091997
transportId	Channel-audio-1
googCaptureStartNtpTimeMs	0
googCodecName	
googCurrentDelayMs	0
googDecodeMs	0
googFirsSent	0
googFrameHeightReceived	0
googFrameRateDecoded	0
googFrameRateOutput	0
googFrameRateReceived	0
googFrameWidthReceived	0
googJitterBufferMs	0
googMaxDecodeMs	0
googMinPlayoutDelayMs	0
googNacksSent	0
googPlisSent	0
googRenderDelayMs	10
googTargetDelayMs	10
googTrackId	66d7a29c-63ae-4d5a-a7c1-e0a8162f2849

**Comment by KaptenJansson** [comment]
I've also seen this intermittently on desktop, i.e. the pc2 is not available in the global scope, window.pc2. Not sure what's going on...

**Comment by simkesd** [comment]
I'm still seeing problem with [Basic peer connection](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) on Chrome (Version 64.0.3282.167 (Official Build) (64-bit)). No errors in the console. Tried both from Chrome in OsX and Ubuntu.

Any info on when will the samples be fixed? I'll be glad to help if needed.

**Comment by KaptenJansson** [comment]
It must be a race condition in the browser somehow, I mean it does assign pc2 to the window object, always. Not sure if any change in JS will fix this.
