### ISSUE TITLE
filetransfer sample doesn't use bufferedAmountLow

### ISSUE THREAD

**Issue by fippo** [webrtc/samples#872]
https://github.com/webrtc/samples/blob/gh-pages/src/content/datachannel/filetransfer/js/main.js
doesn't use the bufferedAmountLow callback. It should, like the datatransfer one does.

cc @taylor-b :-)

**Comment by ErikHellman** [comment]
Since we're using a `FileReader` and the `load` event from that, it becomes tricky to also use `bufferedamountlow` event. 

I'm closing this since the sample works well at the moment and there is no need to use this event. Also ,there seems to be some problems with that event at the moment.
