### ISSUE TITLE
WebAudio Input Demo - Why Windows Only? 

### ISSUE THREAD

**Issue by NTShop** [webrtc/samples#877]
In the WebAudio Output demo linked below it says _Please note that: Linux is currently not supported._

I'm wondering why is Linux not supported? Is it because of the JS coding or is it because some features of loading an audio and connecting it to a RTC stream (addStream) may not be supported? Or some other reason?

I ask because when I test it from Linux using Firefox 51.0.1 for one client and Chrome Version 56.0.2924.87 for another client the two of them connect via RTC but no voice audio flows between them. And per the demo if I press a key to generate the sound effect (i.e. play the loaded WAV file) I do hear the WAV audio on the either system but that audio doesn't flow to the remote side. So no audio of any kinds flow works between clients (no voice, no WAV). 

I'm trying to figure out why and what to do about it,  if anything can done. 

Any answers/explanations/advice would be greatly appreciated. Thanks in advance!

https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/

**Comment by samdutton** [comment]
@cwilso: is Web Audio supported on Linux? Don't have a Linux box handy.

Hi @NTShop — does audio work for you with the [single-page peer connection demo](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) and [appr.tc](https://appr.tc)?

> Why Windows Only?

Just to clarify — the demo also works on [other platforms](http://caniuse.com/#search=webrtc).

**Comment by cwilso** [comment]
Web Audio does work on Linux (it tends to have higher latencies, but still works the same).

**Comment by NTShop** [comment]
Yes Web Audio works. I'm using Ubuntu 16.04 and I have no problems with Web Audio and no latency on the local network.

**Comment by samdutton** [comment]
@NTShop: does audio work for you with the [single-page peer connection demo](https://webrtc.github.io/samples/src/content/peerconnection/pc1/) and [appr.tc](https://appr.tc)?

**Comment by KaptenJansson** [comment]
Ping

**Comment by KaptenJansson** [comment]
Page needs to be updated I guess.

**Comment by samdutton** [comment]
@KaptenJansson Updated page in #1026.
