### ISSUE TITLE
 WebRTC samplesSelect sources & outputs shows incorrect camera id for 'Video Source'

### ISSUE THREAD

**Issue by JaspalK** [webrtc/samples#878]
**Browsers and versions affected**
Google Chrome: 58.0.3018.3 / Dev 
OS: Windows 10, MacOS 10.12.3

**Steps to reproduce**
1. Connect to two external cameras on Windows 10 eg Logitech c930e and Microsoft LifeCan HD-3000

2. In chrome settings, choose a camera and microphone:
	chrome://settings/content/camera   [ Logitech c930e ]
        chrome://settings/content/microphone [ Microphone (2 - Logitech Webcam C930e) ]

1. Browse to https://webrtc.github.io/samples/src/content/getusermedia/source/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Select each audio input source
4. Select each video source

**Expected results**
step 3: verify that you can hear audio from that source (e.g. scratch that specific microphone)
step 4: verify that you see video from each source

**Actual results**
step 3: 'Audio source' shows 'Default'   Is this correct ? i.e should it not show 'Microphone (2 - Logitech Webcam C930e)' ? 

step 4: 'Video source' shows: Microsoft LifeCan HD-3000 (instead of Logitech c930e) although the actual video stream is correctly shown from the Logitech c930e webcam

Info bubble camera icon in URL bar shows:
		Microphone:  Microphone (2 - Logitech Webcam C930e)
		Camera: Logitech c930e

Other info:
The wrong behavior i.e that 'Video source' shows wrong camera id, is also seen on MacOS when using the in built camera and and an external camera eg LifeCan HD-5000

The fault is also observed on Windows 10 Chrome Dev 57.0.2986.0

![screenshot-1](https://cloud.githubusercontent.com/assets/22443950/23456090/5118bf5a-fe72-11e6-858f-089fb68fca6f.PNG)

**Comment by fippo** [comment]
step 3: during the initial call the default device you chose will be used -- getUserMedia is not called with any constraints (check on chrome://webrtc-internals in the getUserMedia tab)

The VideoSource dropdown is not updated to reflect choice of the default device (there could be some correlation using the track label in the getUserMedia result)

The easiest workaround here is probably to not start the cam + mic here by default and only when the user clicks a button.
