### ISSUE TITLE
“gUM Record” on MacOS (10.12.3) gives green/pink artifacts for playback media

### ISSUE THREAD

**Issue by JaspalK** [webrtc/samples#879]
**Browsers and versions affected**
Google Chrome: 58.0.3018.3 / Dev
OS: MacOS 10.12.3

**Steps to reproduce**

0. Browse to https://webrtc.github.io/samples/src/content/getusermedia/record/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors 
2. Enable "Enable experimental Web Platform features" flag in chrome://flags (will require browser re-launch)
3. Click on "Start Recording" and record audio/video for around 5 -10 seconds
4. Click on "Stop Recording"  
5. Click on "Play" to playback the media stream recorded
 6. Click on "Download" to download the recorded media stream  

**Expected results**
Expected result: 

1. No javascript errors
 2. The media stream that is played back should be clearly visible/audible without any pixelations 
3. the user should be able to playback the downloaded media stream by opening a new browser tab and dragging and dropping the .webm file 
4. The browser should not crash while/after recording or during playback/download 

**Actual results**
Step 5:  Green/Pink artifacts are seen on the played back video (see screenshot), However the download video plays without any artifacts

Other info:
This bug is NOT seen on Windows 10 (using Google Chrome: 58.0.3018.3 / Dev)

This bug is NOT seen on Mac OS 10.12.3 (58.0.3013.3 / Dev)

This bug was observed with the following cameras:

- FaceTime HD Camera
- Logitech 930e
- Microsoft LifeCam HD-5000

I see the line in the log file (attached):

" Histogram: Accessibility.InvertedColors recorded 1 samples, mean = 0.0 (flags = 0x41)"

I don't know if this is helpful.

Another bug (https://bugs.chromium.org/p/chromium/issues/detail?id=692558) may or may not have some relevance this bug 

![screen shot 2017-03-01 at 15 04 18](https://cloud.githubusercontent.com/assets/22443950/23464108/149d7616-fe94-11e6-8fbd-081b42b59303.png)

![screen shot 2017-03-01 at 15 05 26]
(https://cloud.githubusercontent.com/assets/22443950/23464123/1c6f6142-fe94-11e6-9648-f2d807b6f663.png)

Chrome logs (with --vmodule=*/webrtc/*=1) can be seen at:

https://drive.google.com/a/google.com/file/d/0BzevCB72sdnCT3pYLTNpeGZwdWs/view?usp=sharing

**Comment by KaptenJansson** [comment]
Great report, I do not think this is sample page issue though, most likely something with the video tag.

**Comment by JaspalK** [comment]
This bug is not found on 59.0.3043.0 / Dev /  MacOS 10.12.3. Thus it is closed.
