### ISSUE TITLE
[ask] How to ?

### ISSUE THREAD

**Issue by nopalhilmy** [webrtc/samples#880]
Hi, 
How to automatically set to rear camera ?

Thanks. )

**Comment by KaptenJansson** [comment]
You need to perform a getUserMedia request with the facingMode constraint set to `environment`. Take a look here: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia.

Not sure if Chrome properly supports this yet though but give it a try. Firefox does at least.
