### ISSUE TITLE
TURN auth fails without credentialType attribute on trickle-ice example

### ISSUE THREAD

**Issue by muellni** [webrtc/samples#882]
**Browsers and versions affected**
- Fails in Chromium 56.0.2924.87 (64-bit) on Linux
- Works in Firefox 52.0 (64-bit) on Linux

I experienced the same behaviour on Windows, but don't know the versions.

**Description**
If you set up a coturn server to use the [TURN REST API](https://github.com/coturn/coturn/wiki/turnserver#turn-rest-api), no relay candidate will be allocated in the [Trickle ICE example](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/) with recent webrtc library.

**Steps to reproduce**
Set up Coturn STUN/TURN server with "lt-cred-mech", "use-auth-secret", "static-auth-secret=shared_secret" options. Use temporary credentials as described [here](https://github.com/coturn/coturn/wiki/turnserver#turn-rest-api).

**Solution**
Specifying the [credentialType](https://developer.mozilla.org/en-US/docs/Web/API/RTCIceServer/credentialType) attribute with `"token"` for the entered ICE server fixes this problem (and would have saved me many hours).

**Comment by fippo** [comment]
@taylor-b does chrome support token even?

**Comment by muellni** [comment]
I tested it with the webrtc "library", which will announce relay candidates if you specify `"credentialType" : "token"`. Don't know if chrome itself supports this.

**Comment by muellni** [comment]
While trying to test the `credentialType` attribute in the trickle-ice-example I can't reproduce this error anymore.

**Comment by taylor-b** [comment]
@fippo No; we're still working on standardizing how OAuth credentials work actually, and it's called "oauth" in the latest version rather than "token": https://github.com/w3c/webrtc-pc/pull/1033

I'm confused about why Chrome would complain about the lack of a "credentialType" though. Currently it looks like it completely ignores the "credentialType" member: https://cs.chromium.org/chromium/src/third_party/WebKit/Source/modules/peerconnection/RTCIceServer.idl?l=14

@muellni, what error do you get when you leave out "credentialType"? And if "token" works, does "password"? I'd hope so, since that's what you're actually using.

**Comment by muellni** [comment]
I made a screenshot of the error on Windows. Chrome on the left doesn't announce relay candidates, while firefox does.
![screenshot_from_2017-03-08_21-33-35](https://cloud.githubusercontent.com/assets/569476/23788177/ac538f9e-0575-11e7-9022-4bf008d1c982.png)

**Comment by taylor-b** [comment]
@muellni What about my other question; does a "credentialType" of "password" work?

Also, if there are still circumstances where you can reproduce this, can you file a bug here: https://bugs.chromium.org/p/webrtc/issues/list

And preferably include a packet capture and/or chrome debug log, to figure out what went wrong?

**Comment by muellni** [comment]
I can't reproduce this issue anymore. Just tested in Windows and I also got the relay candidates in Chrome. This is really odd, since it's still the same Coturn config, maybe some race condition.

Since "credentialType": "password" is the default and you can't specify this at the trickle-ice-example, it seems to work.
