### ISSUE TITLE
who can use it with video chat with Wowza

### ISSUE THREAD

**Issue by MGA-Coder** [webrtc/samples#886]
who can use it with video chat with Wowza ?
like this 
https://www.wowza.com/resources/3.6.0/examples/VideoChat/FlashRTMPPlayer/player.html

**Comment by KaptenJansson** [comment]
Could you elaborate what this has to do with this repository?

**Comment by MGA-Coder** [comment]
can i use it with wowza live stream ? 
with RTMP

**Comment by MirkoBonadei** [comment]
Hi, I think this question is not related to this repository. Here we have a list of examples of how to use WebRTC. If you have specific questions on video streaming you should try to ask [here](https://groups.google.com/forum/#!forum/discuss-webrtc).
