### ISSUE TITLE
WebRTC extension doesn't work with current version of the Chrome browser

### ISSUE THREAD

**Issue by rgordeev** [webrtc/samples#890]
**Browsers and versions affected**
Google Chrome 57.0.2987.133 (64-bit)

**Description**
After Chrome extension installed it doesn't work.
ScreenSharing Extension is disabled in Chrome extensions panel.

**Steps to reproduce**
Walk through all steps from this README
https://github.com/webrtc/samples/tree/gh-pages/src/content/extensions/desktopcapture

**Expected results**
Extension work properly

**Actual results**
Extension doesn't work

**Comment by KaptenJansson** [comment]
Have you updated the manifest for your URL? https://github.com/webrtc/samples/blob/gh-pages/src/content/extensions/desktopcapture/extension/manifest.json#L14
