### ISSUE TITLE
Some PeerConnection WebRTC samples use deprecated APIs

### ISSUE THREAD

**Issue by youennf** [webrtc/samples#893]
Some of the samples use addStream/onaddstream.
It might be good to move to addTrack/ontrack to strengthen adoption to track-based processing.

**Comment by youennf** [comment]
See also https://github.com/w3c/webrtc-pc/issues/1125

**Comment by fippo** [comment]
👍
addTrack is basically blocked on https://github.com/webrtc/adapter/pull/503 unless we want the conditional addTrack-or-addStream approach from #888 which would be better than nothing at least

**Comment by youennf** [comment]
Seems good to wait for webrtc/adapter#503

**Comment by fippo** [comment]
#901 and #902 should fix quite some of this :-)
