### ISSUE TITLE
Chrom(e/ium) 58: "ICE candidate gathering from STUN/TURN servers" fails

### ISSUE THREAD

**Issue by Eusebius1920** [webrtc/samples#897]
**Browsers and versions affected**
chrome 58 (i will edit in the exact version shortly) 64bit
chromium 58.0.3029.96 64bit

**Description**
Running the "ICE candidate gathering from STUN/TURN servers" gives back no candidates.
Running it on the same machine in Firefox works.

**Steps to reproduce**
Run the "ICE candidate gathering from STUN/TURN servers" gives back no candidates.

**Expected results**
See suitable ICE candidates from stun / turn servers

**Actual results**
No ICE candidates are received

**Comment by Eusebius1920** [comment]
Cromium 58 log attached:
[webrtc_internals_dump.txt](https://github.com/webrtc/samples/files/999317/webrtc_internals_dump.txt)

**Comment by Eusebius1920** [comment]
I solved this by disabling uBlock-extension. Seems that the chromium / chrome update came the same time where uBlock started blocking "leakage of local IP-address"

Sry I bothered you.

**Comment by fippo** [comment]
better safe than sorry 👍
