### ISSUE TITLE
Failed to set remote offer sdp in the second time I renegotiate.

### ISSUE THREAD

**Issue by linqiangsheng** [webrtc/samples#899]
**Browsers and versions affected**
chrome 58

**Description**
In the second time I renegotiate(resolution), than the console to report errors like that.

Failed to set remote offer sdp: Session error code: ERROR_CONTENT. Session error description: Failed to set remote video description streams.

**Steps to reproduce**

**Expected results**
how can i renegotiate(resolution) time and time again without any errors.

**Actual results**

**Comment by KaptenJansson** [comment]
Are you using a samples demo or your own code? If the latter please add a link to a working demo as jsfiddle or something similar.

**Comment by linqiangsheng** [comment]
@KaptenJansson, I was using my own code. But I did use a samples demo to test this, and got the same error after my second time to resolution.
This is the url of that demo, https://rtcmulticonnection.herokuapp.com/demos/change-resolutions.html

**Comment by artmatsak** [comment]
Could it be this Chrome issue? https://bugs.chromium.org/p/webrtc/issues/detail?id=7567

**Comment by KaptenJansson** [comment]
Well this has nothing to do with the samples, closing.
