### ISSUE TITLE
WebRTC Sample - Transfer a file does not work, no answer from remote connection seein JS log

### ISSUE THREAD

**Issue by JaspalK** [webrtc/samples#903]
**Browsers and versions affected**
Chrome 60.0.3100.0 / Dev

OS: MacOS: 10.12.4, Windows 10

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click the "Choose File" button
4. Select a file of any size 

**Expected results**
Step 4: Verify that the Average Bitrate is > 0

**Actual results**
Step 4: 
- The chosen file is not send over the data channel
- No progress is seen in "Send progress" or "Receive progress" bars
- No JS Errors
- This is seen even if the chosen file is of length is 
<img width="1440" alt="screenshotdatachannel" src="https://cloud.githubusercontent.com/assets/22443950/26250257/bf37fb02-3ca9-11e7-8ff0-be2c0c53bc12.png">
zero bytes

** Other information **
The JS log seems not get "Answer from remoteConnection"

See attached screenshot

As a quick try and do NOT get this bug on MacOS: 10.12.4, Windows 10 using on both Chrome Stable (57.0.2987.133)

I update if find the same bug on Linux Ubuntu 14.04 or Windows 7

**Comment by fippo** [comment]
anything on chrome://webrtc-internals? (remember to open it before running the test, M60 has a change in behaviour here)

**Comment by JaspalK** [comment]
I noticed a similar issue when running the test case

https://webrtc.github.io/samples/src/content/datachannel/datatransfer/

**Comment by JaspalK** [comment]
Ok, some more info.

I don't get the bug if I do one extra step (i.e step 0 below) first to open a new browser tab:

Steps to reproduce:

0. Open a new Chrome browser tab
1. Browse to https://webrtc.github.io/samples/src/content/datachannel/filetransfer/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click the "Choose File" button
4. Select a file of any size

However,  the bug is seen again if you reload the page (https://webrtc.github.io/samples/src/content/datachannel/filetransfer/) after step 4

**Comment by JaspalK** [comment]
@fippo:
With regards to your question, webrtc-internals shows 'iceconnectionstateChange: checking' when running the sample page: https://webrtc.github.io/samples/src/content/datachannel/filetransfer/

I notice other webrc sample pages also give simialar problems (eg https://webrtc.github.io/samples/src/content/peerconnection/multiple/) 

I.e you have to run the sample page in a new Chrome browser tab and reloading afterwards the page doesn't work (well in this case the https://webrtc.github.io/samples/src/content/peerconnection/multiple/)  doesn't show the camera)

Looking the JS logs, I think I see a common theme here for all webrtc sample pages that don't work where ice candidate stuff is missing.

I heard some adapter changes were recently made, could that have an impact?

**Comment by fippo** [comment]
no, this sounds like an issue with missing candidates that @taylor-b might know about

**Comment by JaspalK** [comment]
FYI: I've also written a bug in crbug.com which has similar symptoms to this bug.  Some one is looking at into this bug.  The bug URL is: www.crbug.com/725038

**Comment by fippo** [comment]
yes, that looks like the right person is looking at it. Lets close here?

**Comment by JaspalK** [comment]
Ok, closing this bug since http://www.crbug.com/725038 is relevant now.
