### ISSUE TITLE
Displaying mirrored image on android mobile chrome.

### ISSUE THREAD

**Issue by nishant0131** [webrtc/samples#904]
**Browsers and versions affected**

**Description**

**Steps to reproduce**
https://webrtc.github.io/samples/src/content/getusermedia/filter/
Open above link on mobile chrome browser.

**Expected results**
Image should be aligned as streaming through webcam on mobile as well.

**Actual results**
Getting an mirrored image with inverted text.

**Comment by KaptenJansson** [comment]
Closing due to age and lack of value.
