### ISSUE TITLE
In the electron and edge ,the vedio stream is black,chrome and firebox has no problem.why?

### ISSUE THREAD

**Issue by Hazlank** [webrtc/samples#913]
Hi
**Browsers and versions affected**
Microsoft Edge 40.15063.0.0
electron 1.6.10

**Description**
In edge or electron,when i open two new pages,the first one is work,the vedio stream at the last one is black,and i open the other browser like chrome and firefox ,it become black to ,if i trun off the first one ,and refresh the other page ,there can work and show the image,why?

**Comment by fippo** [comment]
Typically cameras can only be used by a single process. The easiest fix might be to use multiple cameras.

**Comment by Hazlank** [comment]
@fippo  thanks for reply，but why the chorme can run two pages？can the electron do like that？

**Comment by KaptenJansson** [comment]
Chrome is a multiprocess browser however the brower process opens the camera once and shares it with child render processes. Not sure it is possible to start several render processes in Electron. Anyhow has nothing to do with these samples.
