### ISSUE TITLE
Samples not working on edge browser

### ISSUE THREAD

**Issue by whimsicaldreamer** [webrtc/samples#915]
**Browsers and versions affected**
Microsoft Edge 38.14393.1358.0

**Description**
None of the webRTC samples are working on Edge browser(mobile).
I keep getting error for `getUserMedia` as `getUserMedia error: SourceUnavailableError`

**Comment by fippo** [comment]
works fine here, that error sounds like your webcam is either not attached or (for some reason) not supported. What model is is?

cc @shijuns

**Comment by whimsicaldreamer** [comment]
@fippo I am using Microsoft Lumia 540 Dual SIM as my phone (EDGE 38.14393.1358.0)
The cam works just fine as I am being able to use skype perfectly fine and also take pictures clearly.

I even restarted my phone and tried but the same issue persists.

**Comment by ShijunS** [comment]
Edge doesn't have support to WebRTC on mobile platform at this point.  The team's focus is still on desktop/tablet devices.  GetUserMedia is expected to work though.  I don't have 540 handy here, but the first couple getUserMedia samples seem to work fine on a 640 device.  The OS on the device is newer (version 15063), so you might want to upgrade the OS and give another try.

**Comment by whimsicaldreamer** [comment]
@ShijunS I don't think I can upgrade anymore on my device as my device seems to have been listed officially unsupported for creators update. I am currently running OS version 1607 build 10.0.14393.1358 and would like to stay in this version.

**NOTE:** `Let apps use my camera` and `Let apps use my microphone` are turned on.
Any other workarounds? :(

cc @fippo

**Comment by whimsicaldreamer** [comment]
I am not sure but just asking out of curiosity. Since I get that webRTC is not supported in my version of mobile Edge browser so would it help if I use modernizr and adapter.js hand in hand?

**Comment by ShijunS** [comment]
There is no RTC support on mobile Edge browser, so it won't help with the JS libraries.

**Comment by whimsicaldreamer** [comment]
So that means even with this shims I can't get it to work on Edge mobile browser unless the OS is updated.

**Comment by ShijunS** [comment]
Correct.  At this point, we haven't scheduled the work yet to add RTC stack to Edge mobile browser.  This is still something on our backlog.

**Comment by whimsicaldreamer** [comment]
Ok. That's bad for now. When can we expect to see the addition?
Out of curiosity RTC stack means the getUserMedia, peerConnection etc?

**Comment by ShijunS** [comment]
RTC stack means the WebRTC/ORTC APIs and the corresponding networking protocols.  

The basic functionality of getUserMedia is expected to work on the OS you have on your Lumia 540.  Not sure what is the issue there.  Please feel free to open a bug to us using the Edge issue tracker - https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/.

**Comment by whimsicaldreamer** [comment]
Well I tried opening a new issue on the link you provided but it seems they are not allowing to create a new issue at this moment.

**Comment by KaptenJansson** [comment]
Closing due to age.
