### ISSUE TITLE
Samples - Record Stream no longer working in chrome Macbook 

### ISSUE THREAD

**Issue by trevordowdle** [webrtc/samples#916]
**Browsers and versions affected**
Version 59.0.3071.115

**Description**
When recording there is some stalling and then when you try to play back the recording it errors out

**Steps to reproduce**
Try the recording sample using Chrome (I'm on a macbook pro)

**Expected results**
It produces a recording that you can playback

**Actual results**
Errors out

**In Addition**
In past versions of Chrome my recordings contained an h264 track.

Per spec, webm is to contain only opus, vorbis, vp8, vp9 (and now av1)
http://www.webmproject.org/docs/container/

Can you give me any insight into this issue, can you confirm that chrome is indeed not producing valid webm files?  Or am I doing something wrong?

**Comment by KaptenJansson** [comment]
Closing due to age.
