### ISSUE TITLE
close camera

### ISSUE THREAD

**Issue by samkhan1** [webrtc/samples#924]
@samdutton How does one close the camera after stop recording? 

The camera stays on after stop recording is click in this example: https://github.com/webrtc/samples/blob/gh-pages/src/content/getusermedia/record/js/main.js

**Comment by fippo** [comment]
see the hangup button in https://webrtc.github.io/samples/src/content/peerconnection/pc1/ -- essentially you call track.stop() on the video track (not the stream!)
