### ISSUE TITLE
Webrtc video examples throw error getUserMedia error Failed to get access to local media

### ISSUE THREAD

**Issue by sampleref** [webrtc/samples#927]
**Browsers and versions affected**
Chrome Version 60.0.3112.113 (Official Build) (64-bit) 

**Description**
When trying to loaf WebRTC examples  like h**ttps://appr.tc/ or Kurento Examples or any WebRTC examples with code navigator.mediaDevices.getUserMedia, Error is thrown as below in browser console**

_**getUserMedia error: Failed to get access to local media. Error name was NotFoundError. Continuing without sending a stream.**_

**Steps to reproduce**
Open Chrome or Firefox in Ubuntu 16.04 or 16.10 LTS and load any WebRTC example showing video/audio chat

**Expected results**
Video webcam has to be detected and video captured from same

**Actual results**
_**Throws error -  getUserMedia error: Failed to get access to local media. Error name was NotFoundError. Continuing without sending a stream.**_

The webcam actually work well with command 
_vlc v4l2:///dev/video0
vlc v4l2:///dev/video1_ 
 just to ensure video is loading from VLC Player and camera is working. 

But loading in chrome or firefox in ubuntu this is the issue. Windows 7 its fine

Is there any stable version for Chrome/Firefox to get it working this in Ubuntu OS?

**On ubuntu chrome the webcam is listed at :Settings -> Advanced -> Content Settings -> Camera - list of cameras are shown fine. But still on webrtc example this error is thrown**

**Comment by AsyraniAzni** [comment]
Browsers and versions affected
Chrome Version 60.0.3112.116 (Android)

**Comment by KaptenJansson** [comment]
Does any of the apps on https://webrtc.github.io/test-pages/ work?

**Comment by 9joshua** [comment]
Same problem as OP with Chrome 63.0 and FireFox 57.0 on Ubuntu 16.04.
In addition, most of the apps on https://webrtc.github.io/test-pages/ return:
 `User media request denied with error code undefined`

Error on https://webrtc.github.io/test-pages/src/peer2peer/
```
Requesting doGetUserMedia: constraints: {
 "audio": true,
 "video": {
  "height": 720,
  "width": 1280
 }
}
GetUserMedia failed with error: NotFoundError
```

**Comment by AkshayDwarakanath** [comment]
Is there any stable version for this fix. all browsers are returning this error.

**Comment by AkshayDwarakanath** [comment]
i found the solution. check this link https://stackoverflow.com/questions/48378750/getusermedia-devicesnotfounderror-thrown-in-latest-browsers/48396578#48396578

**Comment by RamyaAshika** [comment]
Facing the same issue. Any updates?

**Comment by ghost** [comment]
Me too! I tested this on other computers running the same version of Chrome and the error does not happen! I think it has to do with a setting specifically for our computers Chrome

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/12274550/58060821-398ad000-7b41-11e9-8e3b-5199cece8de9.png)

**Comment by vaibhavkanmeriya** [comment]
> 

> 

> 

> 

> 

- [ ] 

- [ ] 

- [ ] 

- [ ] fgfgfgfgff
![access-mysql-remote-server-01](https://user-images.githubusercontent.com/22982991/60381281-b9c12100-9a6f-11e9-89e7-8e41810fa82a.png)

**Comment by msaber2015** [comment]
> 
> 
> **Browsers and versions affected**
> Chrome Version 60.0.3112.113 (Official Build) (64-bit)
> 
> **Description**
> When trying to loaf WebRTC examples like h**ttps://appr.tc/ or Kurento Examples or any WebRTC examples with code navigator.mediaDevices.getUserMedia, Error is thrown as below in browser console**
> 
> _**getUserMedia error: Failed to get access to local media. Error name was NotFoundError. Continuing without sending a stream.**_
> 
> **Steps to reproduce**
> Open Chrome or Firefox in Ubuntu 16.04 or 16.10 LTS and load any WebRTC example showing video/audio chat
> 
> **Expected results**
> Video webcam has to be detected and video captured from same
> 
> **Actual results**
> _**Throws error - getUserMedia error: Failed to get access to local media. Error name was NotFoundError. Continuing without sending a stream.**_
> 
> The webcam actually work well with command
> _vlc v4l2:///dev/video0 vlc v4l2:///dev/video1_
> just to ensure video is loading from VLC Player and camera is working.
> 
> But loading in chrome or firefox in ubuntu this is the issue. Windows 7 its fine
> 
> Is there any stable version for Chrome/Firefox to get it working this in Ubuntu OS?
> 
>can you please help me
https://github.com/cloudwebrtc/flutter-webrtc/issues/239**
