### ISSUE TITLE
Volume example on iOS Safari 11

### ISSUE THREAD

**Issue by benbro** [webrtc/samples#931]
**Browsers and versions affected**
Safari 11, iOS

**Description**
There is no volume indication in Safari.
Also reported to webkit:
https://bugs.webkit.org/show_bug.cgi?id=177292

**Steps to reproduce**
Load the sample in iOS Safari:
https://webrtc.github.io/samples/src/content/getusermedia/volume/

**Expected results**
Volume indicators should respond to the mic.

**Actual results**
No volume indication.

**Comment by fquirin** [comment]
+1
None of the "audio-only" examples is working on my iPhone 6, tried iOS 11.0.0 - 11.0.2.

**Comment by marcelrouw** [comment]
+1 
I run into the same issue with my mac 
Safari Version 11.0 (13604.1.38.1.6)

**Comment by marcelrouw** [comment]
My issue seem to be caused by the update of my mac
"macOS High Sierra 10.13 Supplemental Update"
Released October 5, 2017

**Comment by benbro** [comment]
https://bugs.webkit.org/show_bug.cgi?id=177292#c3
> An AudioContext can only be started from within a touchend handler on iOS. Add something like audioContext.startRendering() in a touchend event handler makes the attached test case work.

**Comment by wpp** [comment]
Some additional information from me (#950): The example works fine on the Desktop Version of Safari (11.0.1).

**Comment by KaptenJansson** [comment]
Please provide a PR with the changes required.

**Comment by benbro** [comment]
The webkit issue says it should be fixed.
Still doesn't work in iOS 11.2.6.
I'll test again in iOS 11.3.
