### ISSUE TITLE
tried to setup datachannel following the example

### ISSUE THREAD

**Issue by ghost** [webrtc/samples#932]
I tried to follow the example of sending text, i have compared the codes, and on my side it's simply not working.

It's going to UDP, fallback to TCP, and i think going to STUN after that, as Firefox says. Chrome does not say anything just stuck.

Any idea on this?

On the example itself with UDP is working.

**Comment by KaptenJansson** [comment]
Please provide a jsfiddle with your code.

**Comment by ErikHellman** [comment]
Closing this since there have been no updates. If you can reproduce the problem using one of the samples, please file a new bug with complete details.
