### ISSUE TITLE
Travis CI failed on Firefox since version 55

### ISSUE THREAD

**Issue by alvestrand** [webrtc/samples#936]
**Browsers and versions affected**
Last successful run on Firefox stable: https://travis-ci.org/webrtc/samples/jobs/262281750
First unsuccessful run on Firefox stable: https://travis-ci.org/webrtc/samples/jobs/262698326

Nothing seems to have succeeded since, but the errors might vary.

Tagging @jan-ivar  - feel free to reassign.

**Comment by fippo** [comment]
mostly because geckodriver is pinned to 1.4.0 in https://github.com/webrtc/utilities
I'll update there but it requires fixing more bugs...

**Comment by fippo** [comment]
https://github.com/webrtc/utilities/pull/30 should fix stuff. I wonder if we should get rid of that package as we  never managed to use it for more than the samples even.

**Comment by alvestrand** [comment]
Seems to still be failing, so reopening. Not propagated to samples repo?

**Comment by ErikHellman** [comment]
Closing this as it is no longer failing.
