### ISSUE TITLE
MediaRecording.recordmedia.error() - 416 Requested Range not satisfiable 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#944]
**Browsers and versions affected**
ChromeBooks

**Description**
When trying to Record and play the media with the subjected test page (in the steps), this error shows up multiple times (1 out of 2 times). 

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/getusermedia/record/
Open JS Console in the Chromebook (Shift + Ctrl + J)
Tap on Start recording
Tap on Stop recording after a while (1 min)
Tap on Play

**Expected results**
It should be played without any issues in the JS Console 

**Actual results**
(1/2) times, getting 416 - Requested range Not saisfiable, MediaRecording.recordMedia.error() - Main.js Line 71

**Comment by fippo** [comment]
@yellowdoge ^^

**Comment by KaptenJansson** [comment]
Does it still happen and if so, what version of Chrome?

**Comment by KaptenJansson** [comment]
Ping

**Comment by senthazalravi** [comment]
M63 issue, not reproducible anymore, closing.

**Comment by rantonysamy** [comment]
Verified in M66 Dev. Closing.
