### ISSUE TITLE
Flags or Experimental Features no longer needed

### ISSUE THREAD

**Issue by slpn1** [webrtc/samples#947]
**Browsers and versions affected**
Version 62.0.3202.75 Mac and Windows

**Description**
It seems Enable experimental Web Platform features or setting flag --enable-blink-features=EnumerateDevices,AudioOutputDevices is no longer needed for this to work correctly. Although this is good, it picks my headset as default now. I am using Tokbox which doesn't provide any api to change output.

**Steps to reproduce**
Don't Enable experimental Web Platform or set flag and run demo

**Expected results**
Audio output would be same as system default

**Actual results**
Headset is picked as default and ability to change output works

**Comment by fippo** [comment]
which demo? Also I am fairly sure Tokbox provides an API for that. @aullman will know.

**Comment by slpn1** [comment]
This demo: https://webrtc.github.io/samples/src/content/devices/multi/ 
I was led here from the link at the bottom of that page. I'm pretty sure Tokbox do not provide a js API for output devices, only input devices.

My question really is when enabling the flag or setting experimental features was no longer needed as I can't find any release notes about it, and it no longer seems the case. If it was recent, it explains the problem I am having. Thanks.

**Comment by fippo** [comment]
@guidou you might know

**Comment by slpn1** [comment]
I think you answered my query on StackOverflow. Seems flags are no longer needed, but since version 62 of Chrome, the system default audio output isn't picked.

**Comment by ErikHellman** [comment]
Closing this as the mention of the command line flag is no longer in the samples.
