### ISSUE TITLE
Uncaught DOMException: Failed to execute "send" on "RTCDataChannel"

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#948]
**Browsers and versions affected**
Chrome

**Description**
While trying to generate and transfer data, greeted with Javascript Exception.

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
Click on Generate and send data
Open the Javascript console and watch for errors (happens in the end of the transfer)

**Expected results**
No Javascript exceptions 

**Actual results**
DOMException : Failed to execute "send" on "RTCDataChannel" on main.js/140:19

Log1: DOMException in Ordered mode
[Data_transfer_ordered_mode_webrtc.github.io-1510318564659.log](https://github.com/webrtc/samples/files/1461383/Data_transfer_ordered_mode_webrtc.github.io-1510318564659.log)

Log2: DOMException in Normal mode
[ordered_webrtc.github.io-1510318765546.log](https://github.com/webrtc/samples/files/1461384/ordered_webrtc.github.io-1510318765546.log)

**Comment by cvranjani** [comment]
This issue is same as : https://github.com/webrtc/samples/issues/894

**Comment by KaptenJansson** [comment]
Closed as dupe
