### ISSUE TITLE
webrtc/samples throws 'Failed to allocate audiosource' error in Firefox

### ISSUE THREAD

**Issue by sshadmand** [webrtc/samples#949]
**Browsers and versions affected**
FF 56.0.2 (64-bit) on Mac OS 10.13.1

**Description**

When running the basic script below (and having restart my computer, browsers, and made sure nothing else is using Audio) I get this error:

> navigator.getUserMedia error:  MediaStreamError { name: "NotReadableError", message: "Failed to allocate audiosource", constraint: "", stack: "" }

For sanity I have tried https://webrtc.github.io/samples/src/content/getusermedia/record/ on Firefox and get the same error. 

Is there a way to see (and kill) what ever is causing the audio problem? 

Note: The same code and webrtc url work on Chrome.

**Steps to reproduce**
Run this code snippet in Firefox web console

```
navigator.mediaDevices.getUserMedia({
    audio: true
}).then(function (stream) {
    console.log(stream)
}).catch(console.log)
```

**Expected results**

Anything but that blocking error would be nice. 
**Actual results**

I get an error that generates a blocking error

> navigator.getUserMedia error:  MediaStreamError { name: "NotReadableError", message: "Failed to allocate audiosource", constraint: "", stack: "" }

**Comment by Pehrsons** [comment]
I don't know anything that could cause this from the top of my head. But if you file a bug on bugzilla.mozilla.org we can take a deeper look. The product and component would be "Core :: WebRTC: Audio/Video".

Some more data like testing other versions (57,58) and with a clean profile (no extensions and all default prefs in about:config) would help also.

**Comment by sshadmand** [comment]
Thanks @Pehrsons, using 57 fixed the issue! What a lucky break :-)
