### ISSUE TITLE
Connection Status has not affected after connection

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#951]
**Browsers and versions affected**
Chrome OS

**Description**
Test Page for Ice restart, has connection status field and Its always static as "Not connected"

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/peerconnection/restart-ice/
Click on "Start"
Click on "Call"
Click on "Restart Ice"
Click on "Hangup"

**Expected results**
The Connection status should be changed when there is a connection and when its disconnected. 

**Actual results**
"Not connected" is static all the time.

**Comment by fippo** [comment]
@henbos this looks like it doesn't work with the new stats. There is code in the constraints sample which can probably be copied.

**Comment by cvranjani** [comment]
Existing issue for "Not connected" status in restart-ice page : 
https://github.com/webrtc/samples/issues/863

**Comment by KaptenJansson** [comment]
closed as dupe
