### ISSUE TITLE
Spam link at webaudio-input sample page

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#953]
**Browsers and versions affected**
All

**Description**
Sample has a "Live audio input" link, that redirects to html5audio.org domain which was expired or unattended, and spammy ad-content had been linked with that.

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
Check the "Live audio input" and click on it
**Expected results**
Goes to the correct link or working link

**Actual results**
Goes to a spam link.

**Comment by KaptenJansson** [comment]
Moved to https://developers.google.com/web/updates/2012/09/Live-Web-Audio-Input-Enabled

**Comment by fippo** [comment]
@samdutton if you remember similar stuff on that domain from the ancient past you might want to change those links too

**Comment by samdutton** [comment]
Thanks @rantonysamy !

Hi @fippo — which page do you mean :)?

**Comment by fippo** [comment]
@samdutton: html5audio.org -- assuming that you added the link and not someone else ;-)

**Comment by samdutton** [comment]
Sorry to be dim @fippo — which page has the link to html5audio.org?
