### ISSUE TITLE
Failed to load resource: the server responded with a status of 404 (Not Found)

### ISSUE THREAD

**Issue by BrandoZhang** [webrtc/samples#957]
**Browsers and versions affected**
System: MacOS 10.13.1
Browser: Chrome 62.0.3202.94

**Description**
When I do the tutorial in codelab step-04: https://codelabs.developers.google.com/codelabs/webrtc-web/#6
I install dependencies, run `npm install` from the command line terminal in my work directory, it shows that:
`step-04 brando$ npm install
npm WARN webrtc-codelab@0.0.1 No repository field.
npm WARN webrtc-codelab@0.0.1 No license field.`

But I still run `node index.js`, and it seems to be OK, I can create a room with a name "brando".
However, nothing happen, there is no videos or audios. I create a new tab, enter "brando" again, from the Console I think I join the same room with the first tab:

```
main.js:10 Message from client: Asking to join room Brando
main.js:31 Message from server: Received request to create or join room Brando
main.js:31 Message from server: Room Brando now has 2 client(s)
main.js:31 Message from server: Client ID gXZQsZypBOLHpMQ4AAAB joined room Brando
```
But in the first tab's Console:
```
main.js:10 Message from client: Asking to join room Brando
main.js:31 Message from server: Received request to create or join room Brando
main.js:31 Message from server: Room Brando now has 1 client(s)
main.js:31 Message from server: Client ID ZC84y0dek-rc9WwbAAAA created room Brando
:8080/favicon.ico Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Expected results**
In the first tab I can create a room by giving a name while I can join this room with the same name in the second tab. In addition, there should be a video in the first tab since it is a local object.

**Comment by KaptenJansson** [comment]
Wrong project, https://bitbucket.org/webrtc/codelab.
