### ISSUE TITLE
Adding Local Cache to Store the Data

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#959]
**Browsers and versions affected**
All

**Description**
Adding Local Cache to Store the Data, So while connecting again, I do not need to enter the data  (Even better, make a AppRTC Call and find out the Credentials and list that down) 

https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/

**Comment by KaptenJansson** [comment]
We should not do automatic fetching but using local storage is fine for storing submitted servers. Feel free to create a PR.
