### ISSUE TITLE
Status message Once the Receive Progress / Send Progress Completed 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#960]
**Browsers and versions affected**
All

**Description**
Little Status message Once the Receive Progress / Send Progress Completed 

https://webrtc.github.io/samples/src/content/datachannel/datatransfer/

**Comment by rantonysamy** [comment]
Query sendChannel.readyStage and Display that below. (Sometimes the Send progress bar is visually seen as not fully completed)

**Comment by KaptenJansson** [comment]
Please provide a fix in a PR.

**Comment by ErikHellman** [comment]
The changes in #1110 fixes this issue. Please reopen this in case you feel it isn't sufficient.
