### ISSUE TITLE
Improve the UI with the objective of the test

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#961]
**Browsers and versions affected**
All

**Description**
The PR Answer test, does not have any details / Descriptions like other tests. It will be nice to have the Objective of the test added in the page

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/

**Expected results**
Test Objective and description added in the Page

**Actual results**
No test objective or description.

**Comment by KaptenJansson** [comment]
As stated in the PR, please add all the CSS style that's missing and make it look like other demos. Just make sure the code is formatted correctly with indents etc.

**Comment by ErikHellman** [comment]
Closing this as the sample now has a description.
