### ISSUE TITLE
In the constraints sample, allow 4K sample to be tested

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#964]
**Browsers and versions affected**
All

**Description**
Allow Max width upto 4K in https://webrtc.github.io/samples/src/content/peerconnection/constraints/

**Steps to reproduce**
All the User to setup 4K Res for the Sliders Max Width and Max Height. 

**Expected results**
Users able to test 4K resolution in the test page.

**Comment by rantonysamy** [comment]
Merged !

**Comment by KaptenJansson** [comment]
FYI you can add fixes #"issue number" in the PR to automatically close the bug.
