### ISSUE TITLE
webrtc each step success but no video share

### ISSUE THREAD

**Issue by axe-axe** [webrtc/samples#969]
**chrome version: 62.0.3202.94 **
**firefox version: 57.0.1**

I'm sorry there is no description, i've already asked a question at [stackoverflow](https://stackoverflow.com/questions/47688581/webrtc-each-step-success-but-no-video-share) and shown all the code.Up to now there is no answer.
Please help me.

**Comment by fippo** [comment]
answered on stackoverflow.

**Comment by axe-axe** [comment]
thanks a lot, but i'm sorry it didn't work. Now i repalce `createOffer` after `addStream` and it still no use.
```
.then(function (stream) {
        v.src = window.URL.createObjectURL(stream);
        pc.addStream(stream);
        console.log('addStream success ===========')
    })
    .then(function () {
        // create offer
        pc.createOffer({offerToReceiveVideo: 1}).then(function (e) {
            // pc setLocalDescription
            console.log('createOffer ================')
            pc.setLocalDescription(e).then(
                function () {
                    socket.emit('send_phone_sdp', {desc: e})
                },
                function () {
                    console.log('pc setLocalDescription error')
                }
            )
        });
    })
```

**Comment by axe-axe** [comment]
excuse me ？

**Comment by KaptenJansson** [comment]
PTAL at https://www.html5rocks.com/en/tutorials/webrtc/basics/#toc-signaling

**Comment by KaptenJansson** [comment]
Also closing this since its not related to samples.
