### ISSUE TITLE
Add Ideal values (Bitrate / BitsPerSecond) to be checked in different codecs

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#970]
**Browsers and versions affected**
All

**Description**
In the Sample https://webrtc.github.io/samples/src/content/peerconnection/audio/ Bit Rates and Bits Per second has been displayed in the Graph. But It will be great to add What is the Ideal bit rate / bits per second for each codecs.

**Comment by fippo** [comment]
this is not trivial to define. For example opus has a different target bitrate in Chrome (~35-40kbps) and Firefox (50kbps)

But adding a table to document those bitrates sounds like a good idea

**Comment by rantonysamy** [comment]
Thanks. Nice to have the expected bitrate / BPS in a table view will be helpful. Please take a look below.

Expected results:
Opus:
Bitrate range: ~40 kbps, mute: same
Packets sent per second range: ~50 packets, muted: same

iSAC 16k
Bitrate range: ~30 kbps, muted: same
Packets sent per second range: ~35 packets, muted: same

G722
Bitrate range: ~70 kbps, muted: same
Packets sent per second range: ~50 packets, muted: same

PCMU
Bitrate range: ~70 kbps, muted: same
Packets sent per second range: ~50 packets, muted: same

**Comment by rantonysamy** [comment]
I can send a PR with this table added in the test page if you think the above table is good.

**Comment by fippo** [comment]
opus and isac should drop bitrate when muted (unless cbr is used for opus which might be an interesting extension)

ISAC has 30ms frames so should be ~33pps. Other values look good but you might want to get one of the folks with "magic ears" give a courtsy nod :-)

**Comment by rantonysamy** [comment]
Okey good. I will add all these Information and create a PR, lets see how it goes.

**Comment by rantonysamy** [comment]
Yes XCode messed up my Indent I fixed that too.
