### ISSUE TITLE
Pause button is not working while playing a recorded video.

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#973]
**Browsers and versions affected**
M64 Dev ToT
10172.0.0 / 64.0.3282.11
(Chrome)

**Description**
Pause button is not working. 

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/getusermedia/record/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Enable "Enable experimental Web Platform features" flag in chrome://flags.
3. Click on "Start Recording" and record audio/video for a min or so
4. Click on "Stop Recording" 
5. Click on "Play" to playback the media stream recorded
6. Pause the video by clicking puase button

**Expected results**
Video needs to be paused. 

**Actual results**
Video cannot be paused.

**Tip**
Seems like an html issue. Under Video tag, Instead of "loop controls", "controls loop" needs to be added for looping the video. Probably this is blocking the feature of pausing.

**Comment by KaptenJansson** [comment]
Please submit a fix in a PR if you think this is important.

**Comment by RpCoding** [comment]
Any updates on this? I can't get the pause button to work and could need some help.

**Comment by vkkkumar** [comment]
Hi RpCoding, Haven't started the work on it. Soon will update on this issue. Thanks!
