### ISSUE TITLE
Boundary values can be provided for this example (Usability feedback)

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#974]
**Browsers and versions affected**
All

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/datachannel/datatransfer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Click on "Generate and Send data" for the default size 128 MB
3. Enter a very large number for example (15000)

**Expected results**
Provide the supported boundary values. It takes so much time if given very large time. or Provide a text it will take more time beyond a limit.

**Actual results**
no warning that this value is very large value and no clue how long it will take.

**Comment by KaptenJansson** [comment]
Feel free to add some text in a PR warning the user about high values.

**Comment by ErikHellman** [comment]
I added a warning about large values. Since the limit depends on many different factors, it is difficult to provide an upper limit.
