### ISSUE TITLE
DevicesNotFoundError 

### ISSUE THREAD

**Issue by lumen82** [webrtc/samples#977]
**Browsers and versions affected**
chrome
Version 63.0.3239.84 (Official Build) (64-bit)

**Description**
视频通话时显示提示错误信息 DevicesNotFoundError 

**Steps to reproduce**

**Expected results**

**Actual results**

**Comment by KaptenJansson** [comment]
This indicates your devices are not found, have you connected a camera and a mic to your computer? Also what page is this from?

**Comment by lumen82** [comment]
Sorry, I use this in a http website. When I change to https, it's all right now!
