### ISSUE TITLE
Failed to load resource: status 403

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#978]
**Browsers and versions affected**
chrome 64.0.3282.22 

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click the "Gather candidates" button
4. java script error should come if not
5. open appr.tc and join a new room in another tab. 

**Expected results**
no error should be thrown

**Actual results**
Failed to load resource: status 403 is thrown

[webrtc_internals_dump (1).txt](https://github.com/webrtc/samples/files/1558817/webrtc_internals_dump.1.txt)
[javascriptlog.log](https://github.com/webrtc/samples/files/1558818/javascriptlog.log)

![screenshot 2017-12-14 at 11 27 49 am](https://user-images.githubusercontent.com/34342420/33988072-6dbf47d0-e0c3-11e7-913c-e941f67e14b1.png)

**Comment by rantonysamy** [comment]
Its a problem with the Extension associated with the browser. So "Won't Fix".
