### ISSUE TITLE
Update the test page with the latest methods [deprecation]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#979]
**Browsers and versions affected**
chrome OS  64.0.3282.22

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Press Start
4. Start speaking, verify that you can hear yourself
5. While focus is still on the page, press any key on your keyboard. Verify that you hear a "twang" sound.

**Expected results**
no warning should be thrown if using the correct parameters.

**Actual results**
showing warning that soon to be removed. 
[webrtc_internals_dump (2).txt](https://github.com/webrtc/samples/files/1558897/webrtc_internals_dump.2.txt)
![screenshot 2017-12-14 at 11 51 19 am](https://user-images.githubusercontent.com/34342420/33988894-1db1a0f0-e0c6-11e7-92e7-a1e84a745c59.png)
[deprecatejavascriptlog.log](https://github.com/webrtc/samples/files/1558899/deprecatejavascriptlog.log)

**Comment by fippo** [comment]
works for me
