### ISSUE TITLE
Gather candidates button disabled upon following the steps

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#980]
**Browsers and versions affected**
chrome OS M64 Dev ToT 10176.11.0 / 64.0.3282.22 

**Steps to reproduce**
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. **Click the "Gather candidates" button** **(Note at this point button is active)
4. Verify that you see candidates of type "host" and type "srflx" 
5. In the ICE servers section, click the default STUN server, then click the "Remove server" button.
6. Click the "Gather candidates" button again, verify that you only see "host" candidates.
7. In the ICE servers section, enter TURN server credentials(*see below), then click the "Add Server" button
8. Click the "Gather candidates" button again, verify that you see "host," "srflx," and "relay" candidates.
9. In the IceTransports value section, fill in the "relay" radio button, then gather candidates. 

(*)One way to get TURN server credentials is to start an apprtc call (by yourself is fine), open the js console, and search for "turn." You should find a debug line like:
Creating RTCPeerConnnection with:
config: '{"iceServers":[{"urls":["turn:104.196.16.66:3478?transport=udp","turn:104.196.16.66:3478?transport=tcp","turn:104.196.16.66:3479?transport=udp","turn:104.196.16.66:3479?transport=tcp"],"username":"1447369900:121027630","credential":"E6IhmNYIdTQ35LmwAKEif7Cf0g0="}]}';
constraints: '{"optional":[]}'.
Note:: The TURN server credentials are only valid for 23 hours

TURN URI: enter the full IP address and port (e.g. turn:104.196.16.66:3478)
TURN username: enter the username listed in that debug line without quotes (e.g. 1447369900:121027630)
TURN password: enter the password listed in that debug line without quotes (e.g. E6IhmNYIdTQ35LmwAKEif7Cf0g0=)

Additional verification:
1. "host" candidates should match the IP address of your network interfaces.
2. "srflx" candidates should match your public IP address (e.g. what you see if you google "What is my ip address" or external pages like http://ip4.me and http://ip6.me)
3. "relay" candidates should show the IP address of the TURN server
4. Invalid username / password - 
e.g: username = 1447369900:1210276 / password = E6IhmNYIdTQ35LmwAKEif7Cf0g0 (remove a few characters in the credentials)
Expected: "Authentication failed?" message should appear in the Candidates section
5. While adding a TURN server, enter an invalid TURN server URI (e.g. remove the "turn:" and add only the IP address and port)
Expected: A dialog with message "URI scheme <ip address=""> is not valid" appears

**Expected results**
Verify that only "relay" candidates are returned.

**Actual results**
Gather candidates button is disabled

[icebugdec14num2.log](https://github.com/webrtc/samples/files/1559116/icebugdec14num2.log)
[webrtc_internals_dump (3).txt](https://github.com/webrtc/samples/files/1559117/webrtc_internals_dump.3.txt)
![screenshot 2017-12-14 at 1 18 23 pm](https://user-images.githubusercontent.com/34342420/33995684-038ee5ca-e0df-11e7-8221-70d318b0a131.png)
![Uploading Screenshot 2017-12-14 at 1.18.23 PM.png…]()

**Comment by KaptenJansson** [comment]
The screenshot link added is broken.

I guess the turn server is not returning in this case. How long do you wait?

Maybe we should add a timeout? Does it make sense to make it user configurable?

**Comment by fippo** [comment]
candidate gathering is timing out. We changed the behaviour of the gather button to wait a while ago.
Now why it times out...

**Comment by vkkkumar** [comment]
I waited for long time. No much reaction. It happens for many devices. 

Please let me know if you need more details.

**Comment by KaptenJansson** [comment]
Does it only on a specific device? Or a specific Chrome version?

**Comment by vkkkumar** [comment]
It happens in all devices and all versions of chrome. Currently testing on 
M64 Dev ToT 10176.11.0 / 64.0.3282.22 : Samus
M64 Dev ToT 10176.11.0 / 64.0.3282.22 : Tricky

**Comment by fippo** [comment]
if you look on the network tab while making the apprtc call (on which url), is there a request to networktraversal.googleapis.com or similar? It looks like you're hitting instance that gives you turn servers which no longer exist

**Comment by vkkkumar** [comment]
![screen shot 2017-12-14 at 3 23 09 pm](https://user-images.githubusercontent.com/34342420/33996861-c7a91626-e0e2-11e7-9750-629141415fb6.png)


I use something active call and add the server with user name and password. 
After that I gather candidates,
modify any of the 
a. IceTransports value:   all   relay
b. Gather IPv6 candidates:  
c. ICE Candidate Pool:

Then try to click gather candidates. 

It seem to work in the old chrome version. (63) and macbook pro (corporate machine)

**Comment by vkkkumar** [comment]
![screen shot 2017-12-14 at 3 28 10 pm](https://user-images.githubusercontent.com/34342420/33997055-7149da44-e0e3-11e7-9d96-c192babbb0b5.png)
![screen shot 2017-12-14 at 3 27 47 pm](https://user-images.githubusercontent.com/34342420/33997056-71612096-e0e3-11e7-9b32-2c2fc6842fe7.png)

**Comment by rantonysamy** [comment]
If you click on gather candidates when IceTransports value combo button is "All" - Candidates Gathered immediately. 

If you try to get only Relay candidates (By changing the combo button) to Relay, the Gather candidate button (below) is seen as in disabled state. 

It would be nice to have the gather candidates immediately enabled when the IceTransports value combo button is changed and we could gather candidates again (without refreshing the page).

**Comment by fippo** [comment]
see #830 / #834 -- we wanted to avoid getting into a limbo state by disabling the gather button while there was a request in flight. Now whether one should disable the other buttons as well... is a good question.

**Comment by KaptenJansson** [comment]
I think we can close this, not a big deal and lots of demos have this design, i.e. refresh rather than knowing lots of states which adds complexity.
