### ISSUE TITLE
Deprecated methods at WebAudioInput sample (BitQuad / AudioParam)

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#982]
![screenshot 2017-12-15 at 5 07 31 pm](https://user-images.githubusercontent.com/32895099/34050650-e6347b88-e1bb-11e7-96b5-6fd84881f7ac.png)
**Browsers and versions affected**
Chrome

**Description**
Deprecated methods been used for  BiquadFilterNode.frequency.value and AudioParam value setter in file webaudioextended.js

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
Click on Start
Ctrl + Shift + J or Inspect->Console Log (Javascript Log)\

**Expected results**
Use new methods

Please take a look at the logs. 
[webrtc.github.io-1513353162886.log](https://github.com/webrtc/samples/files/1563281/webrtc.github.io-1513353162886.log)

**Comment by nitobuendia** [comment]
Changing
`this.filter.frequency = 1500;`

For:
`this.filter.frequency.setValueAtTime(1500, this.context.currentTime + 1);`

Seems to solve the issue. Sending PR.

--

Interestingly, [the spec](https://webaudio.github.io/web-audio-api/#dom-audioparam-defaultvalue) seems to claim that setValueAtTime is being called underneath:

> value of type float
> The parameter's floating-point value. This attribute is initialized to the defaultValue.
>
> Setting this attribute has the effect of assigning the requested value to the [[current value]] slot, and calling the setValueAtTime() method with the current AudioContext's currentTime and [[current value]]. Any exceptions that would be thrown by setValueAtTime() will also be thrown by setting this attribute.

Hence, not too sure why Chrome does not like it, but let's follow the instruction here.
