### ISSUE TITLE
Cross Origin iframe warning at WebAudioExtended.js (WebAudioInput Sample)

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#983]
**Browsers and versions affected**
Chrome

**Description**
Warning at WebAudioExtended.js for using cross origin iframes.

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/
Press Start
Look at the Console logs (Js)

**Expected results**
No warning about using cross origin iframe
![screenshot 2017-12-15 at 5 07 31 pm](https://user-images.githubusercontent.com/32895099/34050771-57c7654e-e1bc-11e7-9b82-6a9d477ad51b.png)

**Comment by nitobuendia** [comment]
Hello @rantonysamy 

Thanks a lot for reporting.



I tried to reproduce the error, but I have not been able to.

Steps taken:
1) Go to https://webrtc.github.io/samples/src/content/peerconnection/webaudio-input/

This is what I see on the JS Console:
<img width="1389" alt="screen shot 2018-01-17 at 22 16 47" src="https://user-images.githubusercontent.com/16522489/35047195-2796ece6-fbd4-11e7-8fb0-4701e8ef8889.png">

Can you still reproduce this error?

Settings:
Chrome 63.0.3239.84; macOs High Sierra 10.13.2

**Comment by rantonysamy** [comment]
No I can't reproduce either. Closing. Thanks.
