### ISSUE TITLE
live stream not working

### ISSUE THREAD

**Issue by lakshman2891** [webrtc/samples#984]
**Browsers and versions affected**
safari - ios 11

**Description**
not starting the live stream on either camera

**Steps to reproduce**
in iphone 6s(updated to ios 11). navigate to your sample site where we can switch camera source

**Expected results**
live stream is no displayed. instead getting blank screen.

**Actual results**
![whatsapp image 2017-12-21 at 12 44 01 pm](https://user-images.githubusercontent.com/32470202/34274333-f2c21b9a-e64c-11e7-8ca3-1f273159f8c0.jpeg)

**Comment by KaptenJansson** [comment]
@youennf does this work on Safari? Device enumeration and getUserMedia with sourceId?

**Comment by youennf** [comment]
It should work, video element should have playsInline to work correctly though.

**Comment by youennf** [comment]
Filed https://github.com/webrtc/samples/pull/1008
