### ISSUE TITLE
Packets sent per second graph: Y axis of the graph is not adapting to the new range

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#985]
**Browsers and versions affected**
Chrome 64.0.3282.39 
OS: windows 7, windows 10, Macbook air Mac OS (EI Caption), Mackbook 12 inch MacOS (High Sierra)

**Steps to reproduce**
This is tested in 4 devices: Macbook(12 inch), Macbook Air, Lenovo win 7, Asus win 10

Scenario 1:
1. Browse to https://webrtc.github.io/samples/src/content/peerconnection/audio/
2. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. select opus codec in the dropdown menu
a. Press Call (wait ~3-4 mins)

check the observation below in Actual results section before following the second scenario.

Scenario 2:
1. Press mute button
2. Press call button and observe. (wait ~3-4 mins)

**Expected results**
Graph should be adapted to the new Y axis range and should not display as shown in the attachments.

**Actual results**
Scenario 1 observation :
Y axis of the graph in Windows 7, Macbook air and Macbook 12 inch goes beyond the limit. It is 100% reproducible. For windows 10 it is reproducible 1 out of 3 times.

Scenario 2 observation:
All the devices have the issue of displaying the graph beyond the limit. Graph is not adapted if the value is beyond the current range.

![scenario1 win10](https://user-images.githubusercontent.com/34342420/34384390-37f7d064-eb1c-11e7-967b-426a02acd1bc.png)
![scenario 2 win 10](https://user-images.githubusercontent.com/34342420/34384391-381285ee-eb1c-11e7-9be5-59d4d2fec172.png)
![graph is wrong win 10](https://user-images.githubusercontent.com/34342420/34384392-382a87de-eb1c-11e7-8375-f49ab382640f.png)
<img width="1280" alt="scenario 2 win 7" src="https://user-images.githubusercontent.com/34342420/34384393-3841494c-eb1c-11e7-90f6-101fb7ffde12.png">
<img width="1280" alt="scenario 1 win 7" src="https://user-images.githubusercontent.com/34342420/34384394-385802f4-eb1c-11e7-8a90-c7329670b3af.png">
<img width="1197" alt="scenario 2 macbook 12 inch" src="https://user-images.githubusercontent.com/34342420/34384395-386f4f2c-eb1c-11e7-9683-e583068b9351.png">
<img width="1193" alt="scenario 1 macbook 12inch" src="https://user-images.githubusercontent.com/34342420/34384396-3885cf7c-eb1c-11e7-9674-daa6f9db7c1b.png">
![scenario1 macbookair](https://user-images.githubusercontent.com/34342420/34384397-389df3e0-eb1c-11e7-9fc4-278f3d1ed871.png)
![scenario 2 macbook air](https://user-images.githubusercontent.com/34342420/34384398-38b75d6c-eb1c-11e7-8720-e740e83982cb.png)

**Comment by KaptenJansson** [comment]
How do you know it's beyond the limit? Have you verified that the actual values are higher than what's being rendered in the graphs?

**Comment by vkkkumar** [comment]
Yes, If you see the graph from top to bottom, first two graph accommodates the value clearly. We can make a clear understanding the trend of the graph.

Third, fourth, fifth and sixth shows it goes beyond the 50. Or else we could have got the graph alike first and two. Due to this we just see a straight line and not the original trend. (Top right we can see 50 not sure if thats above 50 or between 50 and 60).

**Comment by KaptenJansson** [comment]
After talkin with Vasan offline, we came to the conclusion it still does its job although its not as sensitive as webrtc-internals.
