### ISSUE TITLE
Use case of Call and Accept button needs a review. [causing javascript errors]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#986]
**Browsers and versions affected**
64.0.3282.39 / Macbook High sierra, Macbook Air El Caption, Lenovo win 7, Asus win 10 (Possible in all other OS and devices.)

**Steps to reproduce**
0. Browse to https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
1. Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
2. Check if the local video is seen in the left pane
3. Press "Call"
4. Press "Accept" 
keep repeating step 3 and 4. 

**Expected results**
Solution 1: 
Disable call button if Accept button is clicked. Thus we can avoid the javascript error.
Solution 2:
If there is a reason like checking the relay (adding more calls) then inform the user say for example 5 calls is the maximum we support.  

**Actual results**
It is possible to call so many calls and accept it. Thus at one some point no video is seen in the right box. Also there are so many javascript exceptions thrown. 

**100% reproducible**
[webrtc.github.io-1514535525036.log](https://github.com/webrtc/samples/files/1592818/webrtc.github.io-1514535525036.log)
[webrtc.github.io-1514535283679.log](https://github.com/webrtc/samples/files/1592819/webrtc.github.io-1514535283679.log)

**Comment by nitobuendia** [comment]
Hello @vkkkumar,

Thanks a lot for reporting.

I am unable to reproduce the error. This is what I did:
1) Went to:  https://webrtc.github.io/samples/src/content/peerconnection/pr-answer/
2) I pressed "Call > Accept" > "Call > Accept" about 10 times and I did not get any errors on the console.
3) Every time I press call, the call is restarted and when I press 'Accept, the connection is initialised successfully.

Is this still reproducible? Maybe a video would help :)

If we disable 'Call' when pressing 'Accept', the call cannot be restarted.
I understand this is done this way on purpose so you can play with that.

Settings:
Chrome 63.0.3239.84; macOs High Sierra 10.13.2

**Comment by KaptenJansson** [comment]
This is an edge case but do agree that the call button should be disabled after accept has been clicked, that's an easy fix, feel free to create a PR to fix. The demo needs an overhaul to make it look like the rest of the demos but that can be done in a separate PR.
