### ISSUE TITLE
Video Quality (of Motion/detail) is very bad and not working as described. 

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#988]
**Browsers and versions affected**
Chrome: 64.0.3282.39 
OS: OSx, Android, chromeOS and possible in other OS too

**Steps to reproduce**
Open the webpage in chrome (https://webrtc.github.io/samples/src/content/capture/video-contenthint/ )
and observe the motion and detail videos 

**Expected results**
Verify that In the motion video, fighting scene is better
Verify that in the detail video, text part is better. 
Read the test case description in the weblink for more verification. 

**Actual results**
Video Quality of Motion or detail is very bad. Rendering the video itself very slow on Android. (LG Flex 2)

![screenshot_2018-01-04-17-51-52](https://user-images.githubusercontent.com/34342420/34574726-952240a0-f178-11e7-9e3c-a3b50008e3dd.png)
![screenshot_2018-01-04-17-51-43](https://user-images.githubusercontent.com/34342420/34574727-9542aba6-f178-11e7-8001-0dc8ff03447f.png)
![screenshot_2018-01-04-17-51-47](https://user-images.githubusercontent.com/34342420/34574728-955a411c-f178-11e7-8f9e-9a6ba7fc6691.png)

**Comment by KaptenJansson** [comment]
This is slow on my workstation as well which I think is the point, it sacrifices FPS for higher quality per frame. Mind you 50kbps for video is nothing.
