### ISSUE TITLE
Drop down button for Select Audio output does not have all devices connected in Android.

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#989]
**Browsers and versions affected**
Chrome: 64.0.3282.39 / Samsung Galaxy S6 possible in all android devices. 

**Description**
Pre-Condition:
Android device with 6x OS or above available 
Install the latest (or test build) Google Chrome in the test device.
Connect a Audio headset in the Device 

Procedure:
Goto https://webrtc.github.io/samples/src/content/devices/multi/
Try to change the Audio devices and listen

**Expected results**
All possible audio out devices should be available. When changing each source audio should be heard and pleasant. 

**Actual results**
Default is the only one available in the list (headphones). Naturally default means the built in speaker but the working state is on headphones. This is bit confusing. 
If I want to change to device inbuilt device of the device it is not possible. 

Kindly check the screenshot attached.

Note:
Same test is working fine on Mac with 3-4 devices connected. It works as expected upon changing the devices. 

Android observation (bug): 
![screenshot_20180105-100924](https://user-images.githubusercontent.com/34342420/34606256-006ef376-f20f-11e7-9503-6b85e748c517.png)
![screenshot_20180105-100915](https://user-images.githubusercontent.com/34342420/34606257-0086020a-f20f-11e7-8f0c-505e9f49b654.png)
![screenshot_20180105-100905](https://user-images.githubusercontent.com/34342420/34606258-009c06fe-f20f-11e7-80ba-2c4e053af2f8.png)
![screenshot_20180105-101021](https://user-images.githubusercontent.com/34342420/34606259-00b2bf84-f20f-11e7-8c5a-8782407936b3.png)

Macbook observation:
![screen shot 2018-01-05 at 10 13 41 am](https://user-images.githubusercontent.com/34342420/34605463-025541b6-f20c-11e7-8901-f636d1b0236c.png)
![screen shot 2018-01-05 at 10 13 33 am](https://user-images.githubusercontent.com/34342420/34605464-026c50f4-f20c-11e7-9095-e7503914a9f8.png)
![screen shot 2018-01-05 at 10 13 25 am](https://user-images.githubusercontent.com/34342420/34605465-02839a5c-f20c-11e7-9d7b-8c3ced2ed560.png)
![screen shot 2018-01-05 at 10 13 13 am](https://user-images.githubusercontent.com/34342420/34605466-029d6dec-f20c-11e7-93f3-d06772443ab2.png)

**Comment by KaptenJansson** [comment]
I do not think Chrome on Android can enumerate audio devices. Please check crbug.com if there is a feature request for this or file one.
