### ISSUE TITLE
RTCDataChannel - broken after reconnection

### ISSUE THREAD

**Issue by MaciejWWojcik** [webrtc/samples#991]
**Browsers and versions affected**
I tested on newest chrome, on mac os sierra

**Description**
RTCDataChannel is working correctly, until one of the peer disconnects. If he recconect, all features from webrtc is working, except rtcDataChannel. So if peer recoennected he has streams, audio, video, but no chat. 

**Steps to reproduce**
Establish webrtc connection between two peers, on two chrome-tabs, on two apps.
Create RTCDataChannel, and connect correctly.
Test that everything is working.
Then refresh tab with some peer, and reconnect. Check if connection is correct and now test chat. 
See that chat is broken now.

**Expected results**
I expected that when peer reconnect, and renegotiate connection, that the whole connection will work correctly, of course rtcDataChannel too.

**Actual results**
RTCDataChannel is broken after peer reconnection.

**What I try to do?**

I try to close existing connection, and start another one. When I do this the datachannel is't opening. The onOpen() event wasn't call.

**Comment by KaptenJansson** [comment]
Which sample are you referring to?

**Comment by dheera** [comment]
I notice this behavior too in 2020 .. any solution?

**Comment by vria** [comment]
Same thing in 2021. Cannot add datachannel after reconnection.

**Comment by iamcsharper** [comment]
Story stays the same on 3/08/2021 Can we restart it somehow? The ice events appear to be connected & completed, but the data channel is not opened, still.

**Comment by AniketSK** [comment]
@vria @dheera @MaciejWWojcik @iamcsharper have you'll worked around this or found that it has gone away?

**Comment by iamcsharper** [comment]
> @vria @dheera @MaciejWWojcik @iamcsharper have you'll worked around this or found that it has gone away?

It turned out to be my local mobile operator who blocked the requests, fixed with a TURN server. Be aware that not every browser/device/operator supports webrtc, it still is an experimental API.

**Comment by dheera** [comment]
> @vria @dheera @MaciejWWojcik @iamcsharper have you'll worked around this or found that it has gone away?

Since nobody responded I used websockets for data instead of the data channel in the application I was developing at the time. But I can retry and see if I can get it working.

**Comment by AniketSK** [comment]
It seems that a fix in m93 dealt with this problem.
