### ISSUE TITLE
Streamed canvas video jitters when compared to the original canvas object. [use to be smooth]

### ISSUE THREAD

**Issue by vkkkumar** [webrtc/samples#995]
**Browsers and versions affected**
10176.41.0 / 64.0.3282.79 Enguarde, Blaze, Stout
Available in 63 on Mac also. 63.0.3239.132
(Maybe possible in all chrome devices)

**Steps to reproduce**
Procedure:
1. Open https://webrtc.github.io/samples/src/content/capture/canvas-video/
2..Open the javascript console (alt+cmd+j or ctr+shift+j) and watch for any errors
3. Click and drag on the canvas (on the left) to move the teapot.

**Expected results**
1. Verify that the video element on the right moves in the same pattern as the canvas element
2. Ensure that there are no JS errors in the console

**Actual results**
Video element on the right is slightly slow than the one on the left. It use to be very smooth.

**Comment by KaptenJansson** [comment]
This has not changed in years hence if it used to be smooth, the issue is probably on the device or the browser.
