### ISSUE TITLE
Support 8K to test the overConstraintError with 4K 

### ISSUE THREAD

**Issue by rantonysamy** [webrtc/samples#999]
**Browsers and versions affected**
All

**Description**
Have 8K resolution supported, so that when connected with a 4K camera, we can check overConstraint Error.

**Steps to reproduce**
Go to https://webrtc.github.io/samples/src/content/getusermedia/resolution/ 
Check we have 8K button and supporting (7680×4320)

**Expected results**
Add 8K button that requests (7680×4320) resolution

**Comment by KaptenJansson** [comment]
SGTM, please make a PR.

**Comment by rantonysamy** [comment]
Sure. will do it today.
